# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/arpa/inet.h
# Generated: 2026-08-17 15:28:51
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("in_addr")
class PyiInAddr:
  sAddr: uint @native_name("s_addr")

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("inet_addr")
def pyiInetAddr(cp: CStr) -> uint:
  ...

@native
@native_name("inet_ntoa")
def pyiInetNtoa(in_: PyiInAddr) -> CStr:
  ...

@native
@native_name("inet_ntop")
def pyiInetNtop(af: int, src: uintptr, dst: CStr, size: uint) -> CStr:
  ...

@native
@native_name("inet_pton")
def pyiInetPton(af: int, src: CStr, dst: uintptr) -> int:
  ...

# stats: structs=1 enums=0 aliases=0 consts=0 funcs=4
