"""序列化协议：``EncoderType`` / ``DecoderType``（``@protocol``，供 ``@serializable`` 泛型约束）。"""
from ..builtins import *
from __future__ import annotations

from ..core.protocols import protocol
from ..numeric.long import long


@protocol
class EncoderType:
  """格式无关写出端；具体格式由 ``JsonEncoder`` 等实现。"""

  def beginObject(self) -> None: ...

  def endObject(self) -> None: ...

  def beginArray(self) -> None: ...

  def endArray(self) -> None: ...

  def dumpKey(self, name: str) -> None: ...

  def dumpInt(self, value: int) -> None: ...

  def dumpLong(self, value: long) -> None: ...

  def dumpFloat(self, value: float) -> None: ...

  def dumpBool(self, value: bool) -> None: ...

  def dumpStr(self, value: str) -> None: ...

  def dumpListInt(self, value: list[int]) -> None: ...

  def dumpListLong(self, value: list[long]) -> None: ...

  def dumpListStr(self, value: list[str]) -> None: ...

  def dumpListFloat(self, value: list[float]) -> None: ...

  def dumpDictStrInt(self, value: dict[str, int]) -> None: ...

  def dumpDictStrLong(self, value: dict[str, long]) -> None: ...

  def dumpDictStrStr(self, value: dict[str, str]) -> None: ...

  def dumpDictStrFloat(self, value: dict[str, float]) -> None: ...

  def beginVariant(self, tag: str) -> None: ...

  def endVariant(self) -> None: ...


@protocol
class DecoderType:
  """格式无关读入端；与 ``EncoderType`` 对称。"""

  def beginRootObject(self) -> None: ...

  def loadKey(self) -> str: ...

  def skipValue(self) -> None: ...

  def loadInt(self) -> int: ...

  def loadLong(self) -> long: ...

  def loadFloat(self) -> float: ...

  def loadStr(self) -> str: ...

  def loadBool(self) -> bool: ...

  def loadListInt(self) -> list[int]: ...

  def loadListLong(self) -> list[long]: ...

  def loadListStr(self) -> list[str]: ...

  def loadListFloat(self) -> list[float]: ...

  def loadDictStrInt(self) -> dict[str, int]: ...

  def loadDictStrLong(self) -> dict[str, long]: ...

  def loadDictStrStr(self) -> dict[str, str]: ...

  def loadDictStrFloat(self) -> dict[str, float]: ...

  def atObjectEnd(self) -> bool: ...

  def loadTagField(self) -> str: ...

  def beginPayloadObject(self) -> None: ...

  def endPayloadObject(self) -> None: ...

  def fail(self, msg: str) -> int: ...


@protocol
class DocumentType:
  """持久化文档的部分访问；具体实现如 ``JsonDocument``。"""

  @staticmethod
  @virtual
  def open(path: str, mode: str = "r") -> Self: ...

  def load[T](self) -> T:
    """全量读入并解析为 ``T``（等价 ``Json.loads[T](全文)``）。"""
    ...

  def dump(self) -> str:
    """当前文档快照序列化为 ``str``。"""
    ...

  def commit(self) -> None:
    """将 dirty 变更写回存储（原子替换）。"""
    ...

  def discard(self) -> None:
    """放弃未 ``commit`` 的内存变更。"""
    ...

  def __enter__(self) -> Self: ...

  def __exit__(self): ...
