"""序列化协议：``Encoder`` / ``Decoder``（``@protocol``，供 ``@serializable`` 泛型约束）。"""
from ..builtins import *
from __future__ import annotations

from ..core.protocols import protocol
from ..numeric.varint import varint


@protocol
class Encoder:
  """格式无关写出端；具体格式由 ``JsonEncoder`` 等实现。"""

  def begin_object(self) -> None: ...

  def end_object(self) -> None: ...

  def begin_array(self) -> None: ...

  def end_array(self) -> None: ...

  def dump_key(self, name: str) -> None: ...

  def dump_int(self, value: int) -> None: ...

  def dump_varint(self, value: varint) -> None: ...

  def dump_float(self, value: float) -> None: ...

  def dump_bool(self, value: bool) -> None: ...

  def dump_str(self, value: str) -> None: ...

  def dump_list_int(self, value: list[int]) -> None: ...

  def dump_list_varint(self, value: list[varint]) -> None: ...

  def dump_list_str(self, value: list[str]) -> None: ...

  def dump_list_float(self, value: list[float]) -> None: ...

  def dump_dict_str_int(self, value: dict[str, int]) -> None: ...

  def dump_dict_str_varint(self, value: dict[str, varint]) -> None: ...

  def dump_dict_str_str(self, value: dict[str, str]) -> None: ...

  def dump_dict_str_float(self, value: dict[str, float]) -> None: ...

  def begin_variant(self, tag: str) -> None: ...

  def end_variant(self) -> None: ...


@protocol
class Decoder:
  """格式无关读入端；与 ``Encoder`` 对称。"""

  def begin_root_object(self) -> None: ...

  def load_key(self) -> str: ...

  def skip_value(self) -> None: ...

  def load_int(self) -> int: ...

  def load_varint(self) -> varint: ...

  def load_float(self) -> float: ...

  def load_str(self) -> str: ...

  def load_bool(self) -> bool: ...

  def load_list_int(self) -> list[int]: ...

  def load_list_varint(self) -> list[varint]: ...

  def load_list_str(self) -> list[str]: ...

  def load_list_float(self) -> list[float]: ...

  def load_dict_str_int(self) -> dict[str, int]: ...

  def load_dict_str_varint(self) -> dict[str, varint]: ...

  def load_dict_str_str(self) -> dict[str, str]: ...

  def load_dict_str_float(self) -> dict[str, float]: ...

  def at_object_end(self) -> bool: ...

  def load_tag_field(self) -> str: ...

  def begin_payload_object(self) -> None: ...

  def end_payload_object(self) -> None: ...

  def fail(self, msg: str) -> int: ...


@protocol
class Document:
  """持久化文档的部分访问；具体实现如 ``JsonDocument``。"""

  @staticmethod
  @virtual
  def open(path: str, mode: str = "r") -> Self: ...

  def load[T](self) -> T:
    """全量读入并解析为 ``T``（等价 ``Json.loads[T](全文)``）。"""
    ...

  def dump(self) -> str:
    """当前文档快照序列化为 ``str``。"""
    ...

  def commit(self) -> None:
    """将 dirty 变更写回存储（原子替换）。"""
    ...

  def discard(self) -> None:
    """放弃未 ``commit`` 的内存变更。"""
    ...

  def __enter__(self) -> Self: ...

  def __exit__(self): ...
