# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/sys/select.h
# Generated: 2026-08-20 20:18:37
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("fd_set")
class PyiFdSet:
  fdsBits: Pointer[uint] @native_name("fds_bits")  # array

@native
@native_name("timeval")
class PyiTimeval:
  tvSec: int @native_name("tv_sec")
  tvUsec: int @native_name("tv_usec")

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("FD_ISSET")
def pyiFdIsset(fd: int, set: Pointer[PyiFdSet]) -> int:
  ...

@native
@native_name("FD_SET")
def pyiFdSet(fd: int, set: Pointer[PyiFdSet]) -> None:
  ...

@native
@native_name("FD_ZERO")
def pyiFdZero(set: Pointer[PyiFdSet]) -> None:
  ...

@native
@native_name("select")
def pyiSelect(nfds: int, readfds: Pointer[PyiFdSet], writefds: Pointer[PyiFdSet], exceptfds: Pointer[PyiFdSet], timeout: Pointer[PyiTimeval]) -> int:
  ...

# stats: structs=2 enums=0 aliases=0 consts=0 funcs=4
