# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/sys/socket.h
# Generated: 2026-08-20 20:18:38
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("accept")
def pyiAccept(sockfd: int, addr: uintptr, addrlen: Pointer[uint64]) -> int:
  ...

@native
@native_name("bind")
def pyiBind(sockfd: int, addr: uintptr, addrlen: uint64) -> int:
  ...

@native
@native_name("connect")
def pyiConnect(sockfd: int, addr: uintptr, addrlen: uint64) -> int:
  ...

@native
@native_name("getsockopt")
def pyiGetsockopt(sockfd: int, level: int, optname: int, optval: uintptr, optlen: Pointer[uint64]) -> int:
  ...

@native
@native_name("listen")
def pyiListen(sockfd: int, backlog: int) -> int:
  ...

@native
@native_name("setsockopt")
def pyiSetsockopt(sockfd: int, level: int, optname: int, optval: uintptr, optlen: uint64) -> int:
  ...

@native
@native_name("socket")
def pyiSocket(domain: int, type: int, protocol: int) -> int:
  ...

# stats: structs=0 enums=0 aliases=0 consts=0 funcs=7
