# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/sqlite/sqlite3.h
# Generated: 2026-08-05 20:56:07
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi_*；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("Fts5Context")
class Pyi_Fts5Context:
  ...  # C incomplete struct

@native
@native_name("Fts5ExtensionApi")
class Pyi_Fts5ExtensionApi:
  iVersion: int
  xUserData: Function[[Pointer[Pyi_Fts5Context]], uintptr]  # fn ptr
  xColumnCount: Function[[Pointer[Pyi_Fts5Context]], int]  # fn ptr
  xRowCount: Function[[Pointer[Pyi_Fts5Context], Pointer[int64]], int]  # fn ptr
  xColumnTotalSize: Function[[Pointer[Pyi_Fts5Context], int, Pointer[int64]], int]  # fn ptr
  xTokenize: Function[[Pointer[Pyi_Fts5Context], c_str, int, uintptr, Function[[uintptr, int, c_str, int, int, int], int]], int]  # fn ptr
  xPhraseCount: Function[[Pointer[Pyi_Fts5Context]], int]  # fn ptr
  xPhraseSize: Function[[Pointer[Pyi_Fts5Context], int], int]  # fn ptr
  xInstCount: Function[[Pointer[Pyi_Fts5Context], Pointer[int]], int]  # fn ptr
  xInst: Function[[Pointer[Pyi_Fts5Context], int, Pointer[int], Pointer[int], Pointer[int]], int]  # fn ptr
  xRowid: Function[[Pointer[Pyi_Fts5Context]], int64]  # fn ptr
  xColumnText: Function[[Pointer[Pyi_Fts5Context], int, Pointer[c_str], Pointer[int]], int]  # fn ptr
  xColumnSize: Function[[Pointer[Pyi_Fts5Context], int, Pointer[int]], int]  # fn ptr
  xQueryPhrase: Function[[Pointer[Pyi_Fts5Context], int, uintptr, Function[[Pointer[Self], Pointer[Pyi_Fts5Context], uintptr], int]], int]  # fn ptr
  xSetAuxdata: Function[[Pointer[Pyi_Fts5Context], uintptr, Function[[uintptr], None]], int]  # fn ptr
  xGetAuxdata: Function[[Pointer[Pyi_Fts5Context], int], uintptr]  # fn ptr
  xPhraseFirst: Function[[Pointer[Pyi_Fts5Context], int, Pointer[Pyi_Fts5PhraseIter], Pointer[int], Pointer[int]], int]  # fn ptr
  xPhraseNext: Function[[Pointer[Pyi_Fts5Context], Pointer[Pyi_Fts5PhraseIter], Pointer[int], Pointer[int]], None]  # fn ptr
  xPhraseFirstColumn: Function[[Pointer[Pyi_Fts5Context], int, Pointer[Pyi_Fts5PhraseIter], Pointer[int]], int]  # fn ptr
  xPhraseNextColumn: Function[[Pointer[Pyi_Fts5Context], Pointer[Pyi_Fts5PhraseIter], Pointer[int]], None]  # fn ptr
  xQueryToken: Function[[Pointer[Pyi_Fts5Context], int, int, Pointer[c_str], Pointer[int]], int]  # fn ptr
  xInstToken: Function[[Pointer[Pyi_Fts5Context], int, int, Pointer[c_str], Pointer[int]], int]  # fn ptr
  xColumnLocale: Function[[Pointer[Pyi_Fts5Context], int, Pointer[c_str], Pointer[int]], int]  # fn ptr
  xTokenize_v2: Function[[Pointer[Pyi_Fts5Context], c_str, int, c_str, int, uintptr, Function[[uintptr, int, c_str, int, int, int], int]], int]  # fn ptr

@native
@native_name("Fts5PhraseIter")
class Pyi_Fts5PhraseIter:
  a: c_str
  b: c_str

@native
@native_name("Fts5Tokenizer")
class Pyi_Fts5Tokenizer:
  ...  # C incomplete struct

@native
@native_name("fts5_api")
class Pyi_fts5_api:
  iVersion: int
  xCreateTokenizer: Function[[Pointer[Self], c_str, uintptr, Pointer[Pyi_fts5_tokenizer], Function[[uintptr], None]], int]  # fn ptr
  xFindTokenizer: Function[[Pointer[Self], c_str, Pointer[uintptr], Pointer[Pyi_fts5_tokenizer]], int]  # fn ptr
  xCreateFunction: Function[[Pointer[Self], c_str, uintptr, Function[[Pointer[Pyi_Fts5ExtensionApi], Pointer[Pyi_Fts5Context], Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], Function[[uintptr], None]], int]  # fn ptr
  xCreateTokenizer_v2: Function[[Pointer[Self], c_str, uintptr, Pointer[Pyi_fts5_tokenizer_v2], Function[[uintptr], None]], int]  # fn ptr
  xFindTokenizer_v2: Function[[Pointer[Self], c_str, Pointer[uintptr], Pointer[Pointer[Pyi_fts5_tokenizer_v2]]], int]  # fn ptr

@native
@native_name("fts5_tokenizer")
class Pyi_fts5_tokenizer:
  xCreate: Function[[uintptr, Pointer[c_str], int, Pointer[Pointer[Pyi_Fts5Tokenizer]]], int]  # fn ptr
  xDelete: Function[[Pointer[Pyi_Fts5Tokenizer]], None]  # fn ptr
  xTokenize: Function[[Pointer[Pyi_Fts5Tokenizer], uintptr, int, c_str, int, Function[[uintptr, int, c_str, int, int, int], int]], int]  # fn ptr

@native
@native_name("fts5_tokenizer_v2")
class Pyi_fts5_tokenizer_v2:
  iVersion: int
  xCreate: Function[[uintptr, Pointer[c_str], int, Pointer[Pointer[Pyi_Fts5Tokenizer]]], int]  # fn ptr
  xDelete: Function[[Pointer[Pyi_Fts5Tokenizer]], None]  # fn ptr
  xTokenize: Function[[Pointer[Pyi_Fts5Tokenizer], uintptr, int, c_str, int, c_str, int, Function[[uintptr, int, c_str, int, int, int], int]], int]  # fn ptr

@native
@native_name("sqlite3")
class Pyi_sqlite3:
  ...  # C incomplete struct

@native
@native_name("sqlite3_api_routines")
class Pyi_sqlite3_api_routines:
  ...  # C incomplete struct

@native
@native_name("sqlite3_backup")
class Pyi_sqlite3_backup:
  ...  # C incomplete struct

@native
@native_name("sqlite3_blob")
class Pyi_sqlite3_blob:
  ...  # C incomplete struct

@native
@native_name("sqlite3_context")
class Pyi_sqlite3_context:
  ...  # C incomplete struct

@native
@native_name("sqlite3_file")
class Pyi_sqlite3_file:
  pMethods: Pointer[Pyi_sqlite3_io_methods]

@native
@native_name("sqlite3_index_info::sqlite3_index_constraint")
class Pyi_sqlite3_index_constraint:
  iColumn: int
  op: int
  usable: int
  iTermOffset: int

@native
@native_name("sqlite3_index_info::sqlite3_index_constraint_usage")
class Pyi_sqlite3_index_constraint_usage:
  argvIndex: int
  omit: int

@native
@native_name("sqlite3_index_info")
class Pyi_sqlite3_index_info:
  nConstraint: int
  aConstraint: Pointer[Pyi_sqlite3_index_constraint]
  nOrderBy: int
  aOrderBy: Pointer[Pyi_sqlite3_index_orderby]
  aConstraintUsage: Pointer[Pyi_sqlite3_index_constraint_usage]
  idxNum: int
  idxStr: c_str
  needToFreeIdxStr: int
  orderByConsumed: int
  estimatedCost: float64
  estimatedRows: int64
  idxFlags: int
  colUsed: uint64

@native
@native_name("sqlite3_index_info::sqlite3_index_orderby")
class Pyi_sqlite3_index_orderby:
  iColumn: int
  desc: int

@native
@native_name("sqlite3_io_methods")
class Pyi_sqlite3_io_methods:
  iVersion: int
  xClose: Function[[Pointer[Pyi_sqlite3_file]], int]  # fn ptr
  xRead: Function[[Pointer[Pyi_sqlite3_file], uintptr, int, int64], int]  # fn ptr
  xWrite: Function[[Pointer[Pyi_sqlite3_file], uintptr, int, int64], int]  # fn ptr
  xTruncate: Function[[Pointer[Pyi_sqlite3_file], int64], int]  # fn ptr
  xSync: Function[[Pointer[Pyi_sqlite3_file], int], int]  # fn ptr
  xFileSize: Function[[Pointer[Pyi_sqlite3_file], Pointer[int64]], int]  # fn ptr
  xLock: Function[[Pointer[Pyi_sqlite3_file], int], int]  # fn ptr
  xUnlock: Function[[Pointer[Pyi_sqlite3_file], int], int]  # fn ptr
  xCheckReservedLock: Function[[Pointer[Pyi_sqlite3_file], Pointer[int]], int]  # fn ptr
  xFileControl: Function[[Pointer[Pyi_sqlite3_file], int, uintptr], int]  # fn ptr
  xSectorSize: Function[[Pointer[Pyi_sqlite3_file]], int]  # fn ptr
  xDeviceCharacteristics: Function[[Pointer[Pyi_sqlite3_file]], int]  # fn ptr
  xShmMap: Function[[Pointer[Pyi_sqlite3_file], int, int, int, Pointer[uintptr]], int]  # fn ptr
  xShmLock: Function[[Pointer[Pyi_sqlite3_file], int, int, int], int]  # fn ptr
  xShmBarrier: Function[[Pointer[Pyi_sqlite3_file]], None]  # fn ptr
  xShmUnmap: Function[[Pointer[Pyi_sqlite3_file], int], int]  # fn ptr
  xFetch: Function[[Pointer[Pyi_sqlite3_file], int64, int, Pointer[uintptr]], int]  # fn ptr
  xUnfetch: Function[[Pointer[Pyi_sqlite3_file], int64, uintptr], int]  # fn ptr

@native
@native_name("sqlite3_mem_methods")
class Pyi_sqlite3_mem_methods:
  xMalloc: Function[[int], uintptr]  # fn ptr
  xFree: Function[[uintptr], None]  # fn ptr
  xRealloc: Function[[uintptr, int], uintptr]  # fn ptr
  xSize: Function[[uintptr], int]  # fn ptr
  xRoundup: Function[[int], int]  # fn ptr
  xInit: Function[[uintptr], int]  # fn ptr
  xShutdown: Function[[uintptr], None]  # fn ptr
  pAppData: uintptr

@native
@native_name("sqlite3_module")
class Pyi_sqlite3_module:
  iVersion: int
  xCreate: Function[[Pointer[Pyi_sqlite3], uintptr, int, Pointer[c_str], Pointer[Pointer[Pyi_sqlite3_vtab]], Pointer[c_str]], int]  # fn ptr
  xConnect: Function[[Pointer[Pyi_sqlite3], uintptr, int, Pointer[c_str], Pointer[Pointer[Pyi_sqlite3_vtab]], Pointer[c_str]], int]  # fn ptr
  xBestIndex: Function[[Pointer[Pyi_sqlite3_vtab], Pointer[Pyi_sqlite3_index_info]], int]  # fn ptr
  xDisconnect: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xDestroy: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xOpen: Function[[Pointer[Pyi_sqlite3_vtab], Pointer[Pointer[Pyi_sqlite3_vtab_cursor]]], int]  # fn ptr
  xClose: Function[[Pointer[Pyi_sqlite3_vtab_cursor]], int]  # fn ptr
  xFilter: Function[[Pointer[Pyi_sqlite3_vtab_cursor], int, c_str, int, Pointer[Pointer[Pyi_sqlite3_value]]], int]  # fn ptr
  xNext: Function[[Pointer[Pyi_sqlite3_vtab_cursor]], int]  # fn ptr
  xEof: Function[[Pointer[Pyi_sqlite3_vtab_cursor]], int]  # fn ptr
  xColumn: Function[[Pointer[Pyi_sqlite3_vtab_cursor], Pointer[Pyi_sqlite3_context], int], int]  # fn ptr
  xRowid: Function[[Pointer[Pyi_sqlite3_vtab_cursor], Pointer[int64]], int]  # fn ptr
  xUpdate: Function[[Pointer[Pyi_sqlite3_vtab], int, Pointer[Pointer[Pyi_sqlite3_value]], Pointer[int64]], int]  # fn ptr
  xBegin: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xSync: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xCommit: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xRollback: Function[[Pointer[Pyi_sqlite3_vtab]], int]  # fn ptr
  xFindFunction: Function[[Pointer[Pyi_sqlite3_vtab], int, c_str, Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], Pointer[uintptr]], int]  # fn ptr
  xRename: Function[[Pointer[Pyi_sqlite3_vtab], c_str], int]  # fn ptr
  xSavepoint: Function[[Pointer[Pyi_sqlite3_vtab], int], int]  # fn ptr
  xRelease: Function[[Pointer[Pyi_sqlite3_vtab], int], int]  # fn ptr
  xRollbackTo: Function[[Pointer[Pyi_sqlite3_vtab], int], int]  # fn ptr
  xShadowName: Function[[c_str], int]  # fn ptr
  xIntegrity: Function[[Pointer[Pyi_sqlite3_vtab], c_str, c_str, int, Pointer[c_str]], int]  # fn ptr

@native
@native_name("sqlite3_mutex")
class Pyi_sqlite3_mutex:
  ...  # C incomplete struct

@native
@native_name("sqlite3_mutex_methods")
class Pyi_sqlite3_mutex_methods:
  xMutexInit: Function[[], int]  # fn ptr
  xMutexEnd: Function[[], int]  # fn ptr
  xMutexAlloc: Function[[int], Pointer[Pyi_sqlite3_mutex]]  # fn ptr
  xMutexFree: Function[[Pointer[Pyi_sqlite3_mutex]], None]  # fn ptr
  xMutexEnter: Function[[Pointer[Pyi_sqlite3_mutex]], None]  # fn ptr
  xMutexTry: Function[[Pointer[Pyi_sqlite3_mutex]], int]  # fn ptr
  xMutexLeave: Function[[Pointer[Pyi_sqlite3_mutex]], None]  # fn ptr
  xMutexHeld: Function[[Pointer[Pyi_sqlite3_mutex]], int]  # fn ptr
  xMutexNotheld: Function[[Pointer[Pyi_sqlite3_mutex]], int]  # fn ptr

@native
@native_name("sqlite3_pcache")
class Pyi_sqlite3_pcache:
  ...  # C incomplete struct

@native
@native_name("sqlite3_pcache_methods")
class Pyi_sqlite3_pcache_methods:
  pArg: uintptr
  xInit: Function[[uintptr], int]  # fn ptr
  xShutdown: Function[[uintptr], None]  # fn ptr
  xCreate: Function[[int, int], Pointer[Pyi_sqlite3_pcache]]  # fn ptr
  xCachesize: Function[[Pointer[Pyi_sqlite3_pcache], int], None]  # fn ptr
  xPagecount: Function[[Pointer[Pyi_sqlite3_pcache]], int]  # fn ptr
  xFetch: Function[[Pointer[Pyi_sqlite3_pcache], uint, int], uintptr]  # fn ptr
  xUnpin: Function[[Pointer[Pyi_sqlite3_pcache], uintptr, int], None]  # fn ptr
  xRekey: Function[[Pointer[Pyi_sqlite3_pcache], uintptr, uint, uint], None]  # fn ptr
  xTruncate: Function[[Pointer[Pyi_sqlite3_pcache], uint], None]  # fn ptr
  xDestroy: Function[[Pointer[Pyi_sqlite3_pcache]], None]  # fn ptr

@native
@native_name("sqlite3_pcache_methods2")
class Pyi_sqlite3_pcache_methods2:
  iVersion: int
  pArg: uintptr
  xInit: Function[[uintptr], int]  # fn ptr
  xShutdown: Function[[uintptr], None]  # fn ptr
  xCreate: Function[[int, int, int], Pointer[Pyi_sqlite3_pcache]]  # fn ptr
  xCachesize: Function[[Pointer[Pyi_sqlite3_pcache], int], None]  # fn ptr
  xPagecount: Function[[Pointer[Pyi_sqlite3_pcache]], int]  # fn ptr
  xFetch: Function[[Pointer[Pyi_sqlite3_pcache], uint, int], Pointer[Pyi_sqlite3_pcache_page]]  # fn ptr
  xUnpin: Function[[Pointer[Pyi_sqlite3_pcache], Pointer[Pyi_sqlite3_pcache_page], int], None]  # fn ptr
  xRekey: Function[[Pointer[Pyi_sqlite3_pcache], Pointer[Pyi_sqlite3_pcache_page], uint, uint], None]  # fn ptr
  xTruncate: Function[[Pointer[Pyi_sqlite3_pcache], uint], None]  # fn ptr
  xDestroy: Function[[Pointer[Pyi_sqlite3_pcache]], None]  # fn ptr
  xShrink: Function[[Pointer[Pyi_sqlite3_pcache]], None]  # fn ptr

@native
@native_name("sqlite3_pcache_page")
class Pyi_sqlite3_pcache_page:
  pBuf: uintptr
  pExtra: uintptr

@native
@native_name("sqlite3_rtree_geometry")
class Pyi_sqlite3_rtree_geometry:
  pContext: uintptr
  nParam: int
  aParam: Pointer[float64]
  pUser: uintptr
  xDelUser: Function[[uintptr], None]  # fn ptr

@native
@native_name("sqlite3_rtree_query_info")
class Pyi_sqlite3_rtree_query_info:
  pContext: uintptr
  nParam: int
  aParam: Pointer[float64]
  pUser: uintptr
  xDelUser: Function[[uintptr], None]  # fn ptr
  aCoord: Pointer[float64]
  anQueue: Pointer[uint]
  nCoord: int
  iLevel: int
  mxLevel: int
  iRowid: int64
  rParentScore: float64
  eParentWithin: int
  eWithin: int
  rScore: float64
  apSqlParam: Pointer[Pointer[Pyi_sqlite3_value]]

@native
@native_name("sqlite3_snapshot")
class Pyi_sqlite3_snapshot:
  hidden: Pointer[int]  # array

@native
@native_name("sqlite3_stmt")
class Pyi_sqlite3_stmt:
  ...  # C incomplete struct

@native
@native_name("sqlite3_str")
class Pyi_sqlite3_str:
  ...  # C incomplete struct

@native
@native_name("sqlite3_value")
class Pyi_sqlite3_value:
  ...  # C incomplete struct

@native
@native_name("sqlite3_vfs")
class Pyi_sqlite3_vfs:
  iVersion: int
  szOsFile: int
  mxPathname: int
  pNext: Pointer[Self]
  zName: c_str
  pAppData: uintptr
  xOpen: Function[[Pointer[Self], c_str, Pointer[Pyi_sqlite3_file], int, Pointer[int]], int]  # fn ptr
  xDelete: Function[[Pointer[Self], c_str, int], int]  # fn ptr
  xAccess: Function[[Pointer[Self], c_str, int, Pointer[int]], int]  # fn ptr
  xFullPathname: Function[[Pointer[Self], c_str, int, c_str], int]  # fn ptr
  xDlOpen: Function[[Pointer[Self], c_str], uintptr]  # fn ptr
  xDlError: Function[[Pointer[Self], int, c_str], None]  # fn ptr
  xDlSym: Function[[Pointer[Self], uintptr, c_str], Function[[], None]]  # fn ptr
  xDlClose: Function[[Pointer[Self], uintptr], None]  # fn ptr
  xRandomness: Function[[Pointer[Self], int, c_str], int]  # fn ptr
  xSleep: Function[[Pointer[Self], int], int]  # fn ptr
  xCurrentTime: Function[[Pointer[Self], Pointer[float64]], int]  # fn ptr
  xGetLastError: Function[[Pointer[Self], int, c_str], int]  # fn ptr
  xCurrentTimeInt64: Function[[Pointer[Self], Pointer[int64]], int]  # fn ptr
  xSetSystemCall: Function[[Pointer[Self], c_str, Function[[], None]], int]  # fn ptr
  xGetSystemCall: Function[[Pointer[Self], c_str], Function[[], None]]  # fn ptr
  xNextSystemCall: Function[[Pointer[Self], c_str], c_str]  # fn ptr

@native
@native_name("sqlite3_vtab")
class Pyi_sqlite3_vtab:
  pModule: Pointer[Pyi_sqlite3_module]
  nRef: int
  zErrMsg: c_str

@native
@native_name("sqlite3_vtab_cursor")
class Pyi_sqlite3_vtab_cursor:
  pVtab: Pointer[Pyi_sqlite3_vtab]

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员）
# ---------------------------------------------------------------------------

# C: SQLITE_ABORT
Pyi_SQLITE_ABORT: int = 4
# C: SQLITE_ACCESS_EXISTS
Pyi_SQLITE_ACCESS_EXISTS: int = 0
# C: SQLITE_ACCESS_READ
Pyi_SQLITE_ACCESS_READ: int = 2
# C: SQLITE_ACCESS_READWRITE
Pyi_SQLITE_ACCESS_READWRITE: int = 1
# C: SQLITE_ALTER_TABLE
Pyi_SQLITE_ALTER_TABLE: int = 26
# C: SQLITE_ANALYZE
Pyi_SQLITE_ANALYZE: int = 28
# C: SQLITE_ANY
Pyi_SQLITE_ANY: int = 5
# C: SQLITE_ATTACH
Pyi_SQLITE_ATTACH: int = 24
# C: SQLITE_AUTH
Pyi_SQLITE_AUTH: int = 23
# C: SQLITE_BLOB
Pyi_SQLITE_BLOB: int = 4
# C: SQLITE_BUSY
Pyi_SQLITE_BUSY: int = 5
# C: SQLITE_CANTOPEN
Pyi_SQLITE_CANTOPEN: int = 14
# C: SQLITE_CARRAY_BLOB
Pyi_SQLITE_CARRAY_BLOB: int = 4
# C: SQLITE_CARRAY_DOUBLE
Pyi_SQLITE_CARRAY_DOUBLE: int = 2
# C: SQLITE_CARRAY_INT32
Pyi_SQLITE_CARRAY_INT32: int = 0
# C: SQLITE_CARRAY_INT64
Pyi_SQLITE_CARRAY_INT64: int = 1
# C: SQLITE_CARRAY_TEXT
Pyi_SQLITE_CARRAY_TEXT: int = 3
# C: SQLITE_CHECKPOINT_FULL
Pyi_SQLITE_CHECKPOINT_FULL: int = 1
# C: SQLITE_CHECKPOINT_NOOP
Pyi_SQLITE_CHECKPOINT_NOOP: int = -1
# C: SQLITE_CHECKPOINT_PASSIVE
Pyi_SQLITE_CHECKPOINT_PASSIVE: int = 0
# C: SQLITE_CHECKPOINT_RESTART
Pyi_SQLITE_CHECKPOINT_RESTART: int = 2
# C: SQLITE_CHECKPOINT_TRUNCATE
Pyi_SQLITE_CHECKPOINT_TRUNCATE: int = 3
# C: SQLITE_CONFIG_COVERING_INDEX_SCAN
Pyi_SQLITE_CONFIG_COVERING_INDEX_SCAN: int = 20
# C: SQLITE_CONFIG_GETMALLOC
Pyi_SQLITE_CONFIG_GETMALLOC: int = 5
# C: SQLITE_CONFIG_GETMUTEX
Pyi_SQLITE_CONFIG_GETMUTEX: int = 11
# C: SQLITE_CONFIG_GETPCACHE
Pyi_SQLITE_CONFIG_GETPCACHE: int = 15
# C: SQLITE_CONFIG_GETPCACHE2
Pyi_SQLITE_CONFIG_GETPCACHE2: int = 19
# C: SQLITE_CONFIG_HEAP
Pyi_SQLITE_CONFIG_HEAP: int = 8
# C: SQLITE_CONFIG_LOG
Pyi_SQLITE_CONFIG_LOG: int = 16
# C: SQLITE_CONFIG_LOOKASIDE
Pyi_SQLITE_CONFIG_LOOKASIDE: int = 13
# C: SQLITE_CONFIG_MALLOC
Pyi_SQLITE_CONFIG_MALLOC: int = 4
# C: SQLITE_CONFIG_MEMDB_MAXSIZE
Pyi_SQLITE_CONFIG_MEMDB_MAXSIZE: int = 29
# C: SQLITE_CONFIG_MEMSTATUS
Pyi_SQLITE_CONFIG_MEMSTATUS: int = 9
# C: SQLITE_CONFIG_MMAP_SIZE
Pyi_SQLITE_CONFIG_MMAP_SIZE: int = 22
# C: SQLITE_CONFIG_MULTITHREAD
Pyi_SQLITE_CONFIG_MULTITHREAD: int = 2
# C: SQLITE_CONFIG_MUTEX
Pyi_SQLITE_CONFIG_MUTEX: int = 10
# C: SQLITE_CONFIG_PAGECACHE
Pyi_SQLITE_CONFIG_PAGECACHE: int = 7
# C: SQLITE_CONFIG_PCACHE
Pyi_SQLITE_CONFIG_PCACHE: int = 14
# C: SQLITE_CONFIG_PCACHE2
Pyi_SQLITE_CONFIG_PCACHE2: int = 18
# C: SQLITE_CONFIG_PCACHE_HDRSZ
Pyi_SQLITE_CONFIG_PCACHE_HDRSZ: int = 24
# C: SQLITE_CONFIG_PMASZ
Pyi_SQLITE_CONFIG_PMASZ: int = 25
# C: SQLITE_CONFIG_ROWID_IN_VIEW
Pyi_SQLITE_CONFIG_ROWID_IN_VIEW: int = 30
# C: SQLITE_CONFIG_SCRATCH
Pyi_SQLITE_CONFIG_SCRATCH: int = 6
# C: SQLITE_CONFIG_SERIALIZED
Pyi_SQLITE_CONFIG_SERIALIZED: int = 3
# C: SQLITE_CONFIG_SINGLETHREAD
Pyi_SQLITE_CONFIG_SINGLETHREAD: int = 1
# C: SQLITE_CONFIG_SMALL_MALLOC
Pyi_SQLITE_CONFIG_SMALL_MALLOC: int = 27
# C: SQLITE_CONFIG_SORTERREF_SIZE
Pyi_SQLITE_CONFIG_SORTERREF_SIZE: int = 28
# C: SQLITE_CONFIG_SQLLOG
Pyi_SQLITE_CONFIG_SQLLOG: int = 21
# C: SQLITE_CONFIG_STMTJRNL_SPILL
Pyi_SQLITE_CONFIG_STMTJRNL_SPILL: int = 26
# C: SQLITE_CONFIG_URI
Pyi_SQLITE_CONFIG_URI: int = 17
# C: SQLITE_CONFIG_WIN32_HEAPSIZE
Pyi_SQLITE_CONFIG_WIN32_HEAPSIZE: int = 23
# C: SQLITE_CONSTRAINT
Pyi_SQLITE_CONSTRAINT: int = 19
# C: SQLITE_COPY
Pyi_SQLITE_COPY: int = 0
# C: SQLITE_CORRUPT
Pyi_SQLITE_CORRUPT: int = 11
# C: SQLITE_CREATE_INDEX
Pyi_SQLITE_CREATE_INDEX: int = 1
# C: SQLITE_CREATE_TABLE
Pyi_SQLITE_CREATE_TABLE: int = 2
# C: SQLITE_CREATE_TEMP_INDEX
Pyi_SQLITE_CREATE_TEMP_INDEX: int = 3
# C: SQLITE_CREATE_TEMP_TABLE
Pyi_SQLITE_CREATE_TEMP_TABLE: int = 4
# C: SQLITE_CREATE_TEMP_TRIGGER
Pyi_SQLITE_CREATE_TEMP_TRIGGER: int = 5
# C: SQLITE_CREATE_TEMP_VIEW
Pyi_SQLITE_CREATE_TEMP_VIEW: int = 6
# C: SQLITE_CREATE_TRIGGER
Pyi_SQLITE_CREATE_TRIGGER: int = 7
# C: SQLITE_CREATE_VIEW
Pyi_SQLITE_CREATE_VIEW: int = 8
# C: SQLITE_CREATE_VTABLE
Pyi_SQLITE_CREATE_VTABLE: int = 29
# C: SQLITE_DBCONFIG_DEFENSIVE
Pyi_SQLITE_DBCONFIG_DEFENSIVE: int = 1010
# C: SQLITE_DBCONFIG_DQS_DDL
Pyi_SQLITE_DBCONFIG_DQS_DDL: int = 1014
# C: SQLITE_DBCONFIG_DQS_DML
Pyi_SQLITE_DBCONFIG_DQS_DML: int = 1013
# C: SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE
Pyi_SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE: int = 1020
# C: SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE
Pyi_SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE: int = 1021
# C: SQLITE_DBCONFIG_ENABLE_COMMENTS
Pyi_SQLITE_DBCONFIG_ENABLE_COMMENTS: int = 1022
# C: SQLITE_DBCONFIG_ENABLE_FKEY
Pyi_SQLITE_DBCONFIG_ENABLE_FKEY: int = 1002
# C: SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER
Pyi_SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER: int = 1004
# C: SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION
Pyi_SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION: int = 1005
# C: SQLITE_DBCONFIG_ENABLE_QPSG
Pyi_SQLITE_DBCONFIG_ENABLE_QPSG: int = 1007
# C: SQLITE_DBCONFIG_ENABLE_TRIGGER
Pyi_SQLITE_DBCONFIG_ENABLE_TRIGGER: int = 1003
# C: SQLITE_DBCONFIG_ENABLE_VIEW
Pyi_SQLITE_DBCONFIG_ENABLE_VIEW: int = 1015
# C: SQLITE_DBCONFIG_FP_DIGITS
Pyi_SQLITE_DBCONFIG_FP_DIGITS: int = 1023
# C: SQLITE_DBCONFIG_LEGACY_ALTER_TABLE
Pyi_SQLITE_DBCONFIG_LEGACY_ALTER_TABLE: int = 1012
# C: SQLITE_DBCONFIG_LEGACY_FILE_FORMAT
Pyi_SQLITE_DBCONFIG_LEGACY_FILE_FORMAT: int = 1016
# C: SQLITE_DBCONFIG_LOOKASIDE
Pyi_SQLITE_DBCONFIG_LOOKASIDE: int = 1001
# C: SQLITE_DBCONFIG_MAINDBNAME
Pyi_SQLITE_DBCONFIG_MAINDBNAME: int = 1000
# C: SQLITE_DBCONFIG_MAX
Pyi_SQLITE_DBCONFIG_MAX: int = 1023
# C: SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE
Pyi_SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE: int = 1006
# C: SQLITE_DBCONFIG_RESET_DATABASE
Pyi_SQLITE_DBCONFIG_RESET_DATABASE: int = 1009
# C: SQLITE_DBCONFIG_REVERSE_SCANORDER
Pyi_SQLITE_DBCONFIG_REVERSE_SCANORDER: int = 1019
# C: SQLITE_DBCONFIG_STMT_SCANSTATUS
Pyi_SQLITE_DBCONFIG_STMT_SCANSTATUS: int = 1018
# C: SQLITE_DBCONFIG_TRIGGER_EQP
Pyi_SQLITE_DBCONFIG_TRIGGER_EQP: int = 1008
# C: SQLITE_DBCONFIG_TRUSTED_SCHEMA
Pyi_SQLITE_DBCONFIG_TRUSTED_SCHEMA: int = 1017
# C: SQLITE_DBCONFIG_WRITABLE_SCHEMA
Pyi_SQLITE_DBCONFIG_WRITABLE_SCHEMA: int = 1011
# C: SQLITE_DBSTATUS_CACHE_HIT
Pyi_SQLITE_DBSTATUS_CACHE_HIT: int = 7
# C: SQLITE_DBSTATUS_CACHE_MISS
Pyi_SQLITE_DBSTATUS_CACHE_MISS: int = 8
# C: SQLITE_DBSTATUS_CACHE_SPILL
Pyi_SQLITE_DBSTATUS_CACHE_SPILL: int = 12
# C: SQLITE_DBSTATUS_CACHE_USED
Pyi_SQLITE_DBSTATUS_CACHE_USED: int = 1
# C: SQLITE_DBSTATUS_CACHE_USED_SHARED
Pyi_SQLITE_DBSTATUS_CACHE_USED_SHARED: int = 11
# C: SQLITE_DBSTATUS_CACHE_WRITE
Pyi_SQLITE_DBSTATUS_CACHE_WRITE: int = 9
# C: SQLITE_DBSTATUS_DEFERRED_FKS
Pyi_SQLITE_DBSTATUS_DEFERRED_FKS: int = 10
# C: SQLITE_DBSTATUS_LOOKASIDE_HIT
Pyi_SQLITE_DBSTATUS_LOOKASIDE_HIT: int = 4
# C: SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL
Pyi_SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL: int = 6
# C: SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE
Pyi_SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE: int = 5
# C: SQLITE_DBSTATUS_LOOKASIDE_USED
Pyi_SQLITE_DBSTATUS_LOOKASIDE_USED: int = 0
# C: SQLITE_DBSTATUS_MAX
Pyi_SQLITE_DBSTATUS_MAX: int = 13
# C: SQLITE_DBSTATUS_SCHEMA_USED
Pyi_SQLITE_DBSTATUS_SCHEMA_USED: int = 2
# C: SQLITE_DBSTATUS_STMT_USED
Pyi_SQLITE_DBSTATUS_STMT_USED: int = 3
# C: SQLITE_DBSTATUS_TEMPBUF_SPILL
Pyi_SQLITE_DBSTATUS_TEMPBUF_SPILL: int = 13
# C: SQLITE_DELETE
Pyi_SQLITE_DELETE: int = 9
# C: SQLITE_DENY
Pyi_SQLITE_DENY: int = 1
# C: SQLITE_DESERIALIZE_FREEONCLOSE
Pyi_SQLITE_DESERIALIZE_FREEONCLOSE: int = 1
# C: SQLITE_DESERIALIZE_READONLY
Pyi_SQLITE_DESERIALIZE_READONLY: int = 4
# C: SQLITE_DESERIALIZE_RESIZEABLE
Pyi_SQLITE_DESERIALIZE_RESIZEABLE: int = 2
# C: SQLITE_DETACH
Pyi_SQLITE_DETACH: int = 25
# C: SQLITE_DETERMINISTIC
Pyi_SQLITE_DETERMINISTIC: int = 0x000000800
# C: SQLITE_DIRECTONLY
Pyi_SQLITE_DIRECTONLY: int = 0x000080000
# C: SQLITE_DONE
Pyi_SQLITE_DONE: int = 101
# C: SQLITE_DROP_INDEX
Pyi_SQLITE_DROP_INDEX: int = 10
# C: SQLITE_DROP_TABLE
Pyi_SQLITE_DROP_TABLE: int = 11
# C: SQLITE_DROP_TEMP_INDEX
Pyi_SQLITE_DROP_TEMP_INDEX: int = 12
# C: SQLITE_DROP_TEMP_TABLE
Pyi_SQLITE_DROP_TEMP_TABLE: int = 13
# C: SQLITE_DROP_TEMP_TRIGGER
Pyi_SQLITE_DROP_TEMP_TRIGGER: int = 14
# C: SQLITE_DROP_TEMP_VIEW
Pyi_SQLITE_DROP_TEMP_VIEW: int = 15
# C: SQLITE_DROP_TRIGGER
Pyi_SQLITE_DROP_TRIGGER: int = 16
# C: SQLITE_DROP_VIEW
Pyi_SQLITE_DROP_VIEW: int = 17
# C: SQLITE_DROP_VTABLE
Pyi_SQLITE_DROP_VTABLE: int = 30
# C: SQLITE_EMPTY
Pyi_SQLITE_EMPTY: int = 16
# C: SQLITE_ERROR
Pyi_SQLITE_ERROR: int = 1
# C: SQLITE_FAIL
Pyi_SQLITE_FAIL: int = 3
# C: SQLITE_FCNTL_BEGIN_ATOMIC_WRITE
Pyi_SQLITE_FCNTL_BEGIN_ATOMIC_WRITE: int = 31
# C: SQLITE_FCNTL_BLOCK_ON_CONNECT
Pyi_SQLITE_FCNTL_BLOCK_ON_CONNECT: int = 44
# C: SQLITE_FCNTL_BUSYHANDLER
Pyi_SQLITE_FCNTL_BUSYHANDLER: int = 15
# C: SQLITE_FCNTL_CHUNK_SIZE
Pyi_SQLITE_FCNTL_CHUNK_SIZE: int = 6
# C: SQLITE_FCNTL_CKPT_DONE
Pyi_SQLITE_FCNTL_CKPT_DONE: int = 37
# C: SQLITE_FCNTL_CKPT_START
Pyi_SQLITE_FCNTL_CKPT_START: int = 39
# C: SQLITE_FCNTL_CKSM_FILE
Pyi_SQLITE_FCNTL_CKSM_FILE: int = 41
# C: SQLITE_FCNTL_COMMIT_ATOMIC_WRITE
Pyi_SQLITE_FCNTL_COMMIT_ATOMIC_WRITE: int = 32
# C: SQLITE_FCNTL_COMMIT_PHASETWO
Pyi_SQLITE_FCNTL_COMMIT_PHASETWO: int = 22
# C: SQLITE_FCNTL_DATA_VERSION
Pyi_SQLITE_FCNTL_DATA_VERSION: int = 35
# C: SQLITE_FCNTL_EXTERNAL_READER
Pyi_SQLITE_FCNTL_EXTERNAL_READER: int = 40
# C: SQLITE_FCNTL_FILESTAT
Pyi_SQLITE_FCNTL_FILESTAT: int = 45
# C: SQLITE_FCNTL_FILE_POINTER
Pyi_SQLITE_FCNTL_FILE_POINTER: int = 7
# C: SQLITE_FCNTL_GET_LOCKPROXYFILE
Pyi_SQLITE_FCNTL_GET_LOCKPROXYFILE: int = 2
# C: SQLITE_FCNTL_HAS_MOVED
Pyi_SQLITE_FCNTL_HAS_MOVED: int = 20
# C: SQLITE_FCNTL_JOURNAL_POINTER
Pyi_SQLITE_FCNTL_JOURNAL_POINTER: int = 28
# C: SQLITE_FCNTL_LAST_ERRNO
Pyi_SQLITE_FCNTL_LAST_ERRNO: int = 4
# C: SQLITE_FCNTL_LOCKSTATE
Pyi_SQLITE_FCNTL_LOCKSTATE: int = 1
# C: SQLITE_FCNTL_LOCK_TIMEOUT
Pyi_SQLITE_FCNTL_LOCK_TIMEOUT: int = 34
# C: SQLITE_FCNTL_MMAP_SIZE
Pyi_SQLITE_FCNTL_MMAP_SIZE: int = 18
# C: SQLITE_FCNTL_NULL_IO
Pyi_SQLITE_FCNTL_NULL_IO: int = 43
# C: SQLITE_FCNTL_OVERWRITE
Pyi_SQLITE_FCNTL_OVERWRITE: int = 11
# C: SQLITE_FCNTL_PDB
Pyi_SQLITE_FCNTL_PDB: int = 30
# C: SQLITE_FCNTL_PERSIST_WAL
Pyi_SQLITE_FCNTL_PERSIST_WAL: int = 10
# C: SQLITE_FCNTL_POWERSAFE_OVERWRITE
Pyi_SQLITE_FCNTL_POWERSAFE_OVERWRITE: int = 13
# C: SQLITE_FCNTL_PRAGMA
Pyi_SQLITE_FCNTL_PRAGMA: int = 14
# C: SQLITE_FCNTL_RBU
Pyi_SQLITE_FCNTL_RBU: int = 26
# C: SQLITE_FCNTL_RESERVE_BYTES
Pyi_SQLITE_FCNTL_RESERVE_BYTES: int = 38
# C: SQLITE_FCNTL_RESET_CACHE
Pyi_SQLITE_FCNTL_RESET_CACHE: int = 42
# C: SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE
Pyi_SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE: int = 33
# C: SQLITE_FCNTL_SET_LOCKPROXYFILE
Pyi_SQLITE_FCNTL_SET_LOCKPROXYFILE: int = 3
# C: SQLITE_FCNTL_SIZE_HINT
Pyi_SQLITE_FCNTL_SIZE_HINT: int = 5
# C: SQLITE_FCNTL_SIZE_LIMIT
Pyi_SQLITE_FCNTL_SIZE_LIMIT: int = 36
# C: SQLITE_FCNTL_SYNC
Pyi_SQLITE_FCNTL_SYNC: int = 21
# C: SQLITE_FCNTL_SYNC_OMITTED
Pyi_SQLITE_FCNTL_SYNC_OMITTED: int = 8
# C: SQLITE_FCNTL_TEMPFILENAME
Pyi_SQLITE_FCNTL_TEMPFILENAME: int = 16
# C: SQLITE_FCNTL_TRACE
Pyi_SQLITE_FCNTL_TRACE: int = 19
# C: SQLITE_FCNTL_VFSNAME
Pyi_SQLITE_FCNTL_VFSNAME: int = 12
# C: SQLITE_FCNTL_VFS_POINTER
Pyi_SQLITE_FCNTL_VFS_POINTER: int = 27
# C: SQLITE_FCNTL_WAL_BLOCK
Pyi_SQLITE_FCNTL_WAL_BLOCK: int = 24
# C: SQLITE_FCNTL_WIN32_AV_RETRY
Pyi_SQLITE_FCNTL_WIN32_AV_RETRY: int = 9
# C: SQLITE_FCNTL_WIN32_GET_HANDLE
Pyi_SQLITE_FCNTL_WIN32_GET_HANDLE: int = 29
# C: SQLITE_FCNTL_WIN32_SET_HANDLE
Pyi_SQLITE_FCNTL_WIN32_SET_HANDLE: int = 23
# C: SQLITE_FCNTL_ZIPVFS
Pyi_SQLITE_FCNTL_ZIPVFS: int = 25
# C: SQLITE_FLOAT
Pyi_SQLITE_FLOAT: int = 2
# C: SQLITE_FORMAT
Pyi_SQLITE_FORMAT: int = 24
# C: SQLITE_FULL
Pyi_SQLITE_FULL: int = 13
# C: SQLITE_FUNCTION
Pyi_SQLITE_FUNCTION: int = 31
# C: SQLITE_GET_LOCKPROXYFILE
Pyi_SQLITE_GET_LOCKPROXYFILE: int = 2
# C: SQLITE_IGNORE
Pyi_SQLITE_IGNORE: int = 2
# C: SQLITE_INDEX_CONSTRAINT_EQ
Pyi_SQLITE_INDEX_CONSTRAINT_EQ: int = 2
# C: SQLITE_INDEX_CONSTRAINT_FUNCTION
Pyi_SQLITE_INDEX_CONSTRAINT_FUNCTION: int = 150
# C: SQLITE_INDEX_CONSTRAINT_GE
Pyi_SQLITE_INDEX_CONSTRAINT_GE: int = 32
# C: SQLITE_INDEX_CONSTRAINT_GLOB
Pyi_SQLITE_INDEX_CONSTRAINT_GLOB: int = 66
# C: SQLITE_INDEX_CONSTRAINT_GT
Pyi_SQLITE_INDEX_CONSTRAINT_GT: int = 4
# C: SQLITE_INDEX_CONSTRAINT_IS
Pyi_SQLITE_INDEX_CONSTRAINT_IS: int = 72
# C: SQLITE_INDEX_CONSTRAINT_ISNOT
Pyi_SQLITE_INDEX_CONSTRAINT_ISNOT: int = 69
# C: SQLITE_INDEX_CONSTRAINT_ISNOTNULL
Pyi_SQLITE_INDEX_CONSTRAINT_ISNOTNULL: int = 70
# C: SQLITE_INDEX_CONSTRAINT_ISNULL
Pyi_SQLITE_INDEX_CONSTRAINT_ISNULL: int = 71
# C: SQLITE_INDEX_CONSTRAINT_LE
Pyi_SQLITE_INDEX_CONSTRAINT_LE: int = 8
# C: SQLITE_INDEX_CONSTRAINT_LIKE
Pyi_SQLITE_INDEX_CONSTRAINT_LIKE: int = 65
# C: SQLITE_INDEX_CONSTRAINT_LIMIT
Pyi_SQLITE_INDEX_CONSTRAINT_LIMIT: int = 73
# C: SQLITE_INDEX_CONSTRAINT_LT
Pyi_SQLITE_INDEX_CONSTRAINT_LT: int = 16
# C: SQLITE_INDEX_CONSTRAINT_MATCH
Pyi_SQLITE_INDEX_CONSTRAINT_MATCH: int = 64
# C: SQLITE_INDEX_CONSTRAINT_NE
Pyi_SQLITE_INDEX_CONSTRAINT_NE: int = 68
# C: SQLITE_INDEX_CONSTRAINT_OFFSET
Pyi_SQLITE_INDEX_CONSTRAINT_OFFSET: int = 74
# C: SQLITE_INDEX_CONSTRAINT_REGEXP
Pyi_SQLITE_INDEX_CONSTRAINT_REGEXP: int = 67
# C: SQLITE_INDEX_SCAN_HEX
Pyi_SQLITE_INDEX_SCAN_HEX: int = 0x00000002
# C: SQLITE_INDEX_SCAN_UNIQUE
Pyi_SQLITE_INDEX_SCAN_UNIQUE: int = 0x00000001
# C: SQLITE_INNOCUOUS
Pyi_SQLITE_INNOCUOUS: int = 0x000200000
# C: SQLITE_INSERT
Pyi_SQLITE_INSERT: int = 18
# C: SQLITE_INTEGER
Pyi_SQLITE_INTEGER: int = 1
# C: SQLITE_INTERNAL
Pyi_SQLITE_INTERNAL: int = 2
# C: SQLITE_INTERRUPT
Pyi_SQLITE_INTERRUPT: int = 9
# C: SQLITE_IOCAP_ATOMIC
Pyi_SQLITE_IOCAP_ATOMIC: int = 0x00000001
# C: SQLITE_IOCAP_ATOMIC16K
Pyi_SQLITE_IOCAP_ATOMIC16K: int = 0x00000040
# C: SQLITE_IOCAP_ATOMIC1K
Pyi_SQLITE_IOCAP_ATOMIC1K: int = 0x00000004
# C: SQLITE_IOCAP_ATOMIC2K
Pyi_SQLITE_IOCAP_ATOMIC2K: int = 0x00000008
# C: SQLITE_IOCAP_ATOMIC32K
Pyi_SQLITE_IOCAP_ATOMIC32K: int = 0x00000080
# C: SQLITE_IOCAP_ATOMIC4K
Pyi_SQLITE_IOCAP_ATOMIC4K: int = 0x00000010
# C: SQLITE_IOCAP_ATOMIC512
Pyi_SQLITE_IOCAP_ATOMIC512: int = 0x00000002
# C: SQLITE_IOCAP_ATOMIC64K
Pyi_SQLITE_IOCAP_ATOMIC64K: int = 0x00000100
# C: SQLITE_IOCAP_ATOMIC8K
Pyi_SQLITE_IOCAP_ATOMIC8K: int = 0x00000020
# C: SQLITE_IOCAP_BATCH_ATOMIC
Pyi_SQLITE_IOCAP_BATCH_ATOMIC: int = 0x00004000
# C: SQLITE_IOCAP_IMMUTABLE
Pyi_SQLITE_IOCAP_IMMUTABLE: int = 0x00002000
# C: SQLITE_IOCAP_POWERSAFE_OVERWRITE
Pyi_SQLITE_IOCAP_POWERSAFE_OVERWRITE: int = 0x00001000
# C: SQLITE_IOCAP_SAFE_APPEND
Pyi_SQLITE_IOCAP_SAFE_APPEND: int = 0x00000200
# C: SQLITE_IOCAP_SEQUENTIAL
Pyi_SQLITE_IOCAP_SEQUENTIAL: int = 0x00000400
# C: SQLITE_IOCAP_SUBPAGE_READ
Pyi_SQLITE_IOCAP_SUBPAGE_READ: int = 0x00008000
# C: SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN
Pyi_SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN: int = 0x00000800
# C: SQLITE_IOERR
Pyi_SQLITE_IOERR: int = 10
# C: SQLITE_LAST_ERRNO
Pyi_SQLITE_LAST_ERRNO: int = 4
# C: SQLITE_LIMIT_ATTACHED
Pyi_SQLITE_LIMIT_ATTACHED: int = 7
# C: SQLITE_LIMIT_COLUMN
Pyi_SQLITE_LIMIT_COLUMN: int = 2
# C: SQLITE_LIMIT_COMPOUND_SELECT
Pyi_SQLITE_LIMIT_COMPOUND_SELECT: int = 4
# C: SQLITE_LIMIT_EXPR_DEPTH
Pyi_SQLITE_LIMIT_EXPR_DEPTH: int = 3
# C: SQLITE_LIMIT_FUNCTION_ARG
Pyi_SQLITE_LIMIT_FUNCTION_ARG: int = 6
# C: SQLITE_LIMIT_LENGTH
Pyi_SQLITE_LIMIT_LENGTH: int = 0
# C: SQLITE_LIMIT_LIKE_PATTERN_LENGTH
Pyi_SQLITE_LIMIT_LIKE_PATTERN_LENGTH: int = 8
# C: SQLITE_LIMIT_PARSER_DEPTH
Pyi_SQLITE_LIMIT_PARSER_DEPTH: int = 12
# C: SQLITE_LIMIT_SQL_LENGTH
Pyi_SQLITE_LIMIT_SQL_LENGTH: int = 1
# C: SQLITE_LIMIT_TRIGGER_DEPTH
Pyi_SQLITE_LIMIT_TRIGGER_DEPTH: int = 10
# C: SQLITE_LIMIT_VARIABLE_NUMBER
Pyi_SQLITE_LIMIT_VARIABLE_NUMBER: int = 9
# C: SQLITE_LIMIT_VDBE_OP
Pyi_SQLITE_LIMIT_VDBE_OP: int = 5
# C: SQLITE_LIMIT_WORKER_THREADS
Pyi_SQLITE_LIMIT_WORKER_THREADS: int = 11
# C: SQLITE_LOCKED
Pyi_SQLITE_LOCKED: int = 6
# C: SQLITE_LOCK_EXCLUSIVE
Pyi_SQLITE_LOCK_EXCLUSIVE: int = 4
# C: SQLITE_LOCK_NONE
Pyi_SQLITE_LOCK_NONE: int = 0
# C: SQLITE_LOCK_PENDING
Pyi_SQLITE_LOCK_PENDING: int = 3
# C: SQLITE_LOCK_RESERVED
Pyi_SQLITE_LOCK_RESERVED: int = 2
# C: SQLITE_LOCK_SHARED
Pyi_SQLITE_LOCK_SHARED: int = 1
# C: SQLITE_MISMATCH
Pyi_SQLITE_MISMATCH: int = 20
# C: SQLITE_MISUSE
Pyi_SQLITE_MISUSE: int = 21
# C: SQLITE_MUTEX_FAST
Pyi_SQLITE_MUTEX_FAST: int = 0
# C: SQLITE_MUTEX_RECURSIVE
Pyi_SQLITE_MUTEX_RECURSIVE: int = 1
# C: SQLITE_MUTEX_STATIC_APP1
Pyi_SQLITE_MUTEX_STATIC_APP1: int = 8
# C: SQLITE_MUTEX_STATIC_APP2
Pyi_SQLITE_MUTEX_STATIC_APP2: int = 9
# C: SQLITE_MUTEX_STATIC_APP3
Pyi_SQLITE_MUTEX_STATIC_APP3: int = 10
# C: SQLITE_MUTEX_STATIC_LRU
Pyi_SQLITE_MUTEX_STATIC_LRU: int = 6
# C: SQLITE_MUTEX_STATIC_LRU2
Pyi_SQLITE_MUTEX_STATIC_LRU2: int = 7
# C: SQLITE_MUTEX_STATIC_MAIN
Pyi_SQLITE_MUTEX_STATIC_MAIN: int = 2
# C: SQLITE_MUTEX_STATIC_MASTER
Pyi_SQLITE_MUTEX_STATIC_MASTER: int = 2
# C: SQLITE_MUTEX_STATIC_MEM
Pyi_SQLITE_MUTEX_STATIC_MEM: int = 3
# C: SQLITE_MUTEX_STATIC_MEM2
Pyi_SQLITE_MUTEX_STATIC_MEM2: int = 4
# C: SQLITE_MUTEX_STATIC_OPEN
Pyi_SQLITE_MUTEX_STATIC_OPEN: int = 4
# C: SQLITE_MUTEX_STATIC_PMEM
Pyi_SQLITE_MUTEX_STATIC_PMEM: int = 7
# C: SQLITE_MUTEX_STATIC_PRNG
Pyi_SQLITE_MUTEX_STATIC_PRNG: int = 5
# C: SQLITE_MUTEX_STATIC_VFS1
Pyi_SQLITE_MUTEX_STATIC_VFS1: int = 11
# C: SQLITE_MUTEX_STATIC_VFS2
Pyi_SQLITE_MUTEX_STATIC_VFS2: int = 12
# C: SQLITE_MUTEX_STATIC_VFS3
Pyi_SQLITE_MUTEX_STATIC_VFS3: int = 13
# C: SQLITE_NOLFS
Pyi_SQLITE_NOLFS: int = 22
# C: SQLITE_NOMEM
Pyi_SQLITE_NOMEM: int = 7
# C: SQLITE_NOTADB
Pyi_SQLITE_NOTADB: int = 26
# C: SQLITE_NOTFOUND
Pyi_SQLITE_NOTFOUND: int = 12
# C: SQLITE_NOTICE
Pyi_SQLITE_NOTICE: int = 27
# C: SQLITE_NULL
Pyi_SQLITE_NULL: int = 5
# C: SQLITE_OK
Pyi_SQLITE_OK: int = 0
# C: SQLITE_OPEN_AUTOPROXY
Pyi_SQLITE_OPEN_AUTOPROXY: int = 0x00000020
# C: SQLITE_OPEN_CREATE
Pyi_SQLITE_OPEN_CREATE: int = 0x00000004
# C: SQLITE_OPEN_DELETEONCLOSE
Pyi_SQLITE_OPEN_DELETEONCLOSE: int = 0x00000008
# C: SQLITE_OPEN_EXCLUSIVE
Pyi_SQLITE_OPEN_EXCLUSIVE: int = 0x00000010
# C: SQLITE_OPEN_EXRESCODE
Pyi_SQLITE_OPEN_EXRESCODE: int = 0x02000000
# C: SQLITE_OPEN_FULLMUTEX
Pyi_SQLITE_OPEN_FULLMUTEX: int = 0x00010000
# C: SQLITE_OPEN_MAIN_DB
Pyi_SQLITE_OPEN_MAIN_DB: int = 0x00000100
# C: SQLITE_OPEN_MAIN_JOURNAL
Pyi_SQLITE_OPEN_MAIN_JOURNAL: int = 0x00000800
# C: SQLITE_OPEN_MASTER_JOURNAL
Pyi_SQLITE_OPEN_MASTER_JOURNAL: int = 0x00004000
# C: SQLITE_OPEN_MEMORY
Pyi_SQLITE_OPEN_MEMORY: int = 0x00000080
# C: SQLITE_OPEN_NOFOLLOW
Pyi_SQLITE_OPEN_NOFOLLOW: int = 0x01000000
# C: SQLITE_OPEN_NOMUTEX
Pyi_SQLITE_OPEN_NOMUTEX: int = 0x00008000
# C: SQLITE_OPEN_PRIVATECACHE
Pyi_SQLITE_OPEN_PRIVATECACHE: int = 0x00040000
# C: SQLITE_OPEN_READONLY
Pyi_SQLITE_OPEN_READONLY: int = 0x00000001
# C: SQLITE_OPEN_READWRITE
Pyi_SQLITE_OPEN_READWRITE: int = 0x00000002
# C: SQLITE_OPEN_SHAREDCACHE
Pyi_SQLITE_OPEN_SHAREDCACHE: int = 0x00020000
# C: SQLITE_OPEN_SUBJOURNAL
Pyi_SQLITE_OPEN_SUBJOURNAL: int = 0x00002000
# C: SQLITE_OPEN_SUPER_JOURNAL
Pyi_SQLITE_OPEN_SUPER_JOURNAL: int = 0x00004000
# C: SQLITE_OPEN_TEMP_DB
Pyi_SQLITE_OPEN_TEMP_DB: int = 0x00000200
# C: SQLITE_OPEN_TEMP_JOURNAL
Pyi_SQLITE_OPEN_TEMP_JOURNAL: int = 0x00001000
# C: SQLITE_OPEN_TRANSIENT_DB
Pyi_SQLITE_OPEN_TRANSIENT_DB: int = 0x00000400
# C: SQLITE_OPEN_URI
Pyi_SQLITE_OPEN_URI: int = 0x00000040
# C: SQLITE_OPEN_WAL
Pyi_SQLITE_OPEN_WAL: int = 0x00080000
# C: SQLITE_PERM
Pyi_SQLITE_PERM: int = 3
# C: SQLITE_PRAGMA
Pyi_SQLITE_PRAGMA: int = 19
# C: SQLITE_PREPARE_DONT_LOG
Pyi_SQLITE_PREPARE_DONT_LOG: int = 0x10
# C: SQLITE_PREPARE_FROM_DDL
Pyi_SQLITE_PREPARE_FROM_DDL: int = 0x20
# C: SQLITE_PREPARE_NORMALIZE
Pyi_SQLITE_PREPARE_NORMALIZE: int = 0x02
# C: SQLITE_PREPARE_NO_VTAB
Pyi_SQLITE_PREPARE_NO_VTAB: int = 0x04
# C: SQLITE_PREPARE_PERSISTENT
Pyi_SQLITE_PREPARE_PERSISTENT: int = 0x01
# C: SQLITE_PROTOCOL
Pyi_SQLITE_PROTOCOL: int = 15
# C: SQLITE_RANGE
Pyi_SQLITE_RANGE: int = 25
# C: SQLITE_READ
Pyi_SQLITE_READ: int = 20
# C: SQLITE_READONLY
Pyi_SQLITE_READONLY: int = 8
# C: SQLITE_RECURSIVE
Pyi_SQLITE_RECURSIVE: int = 33
# C: SQLITE_REINDEX
Pyi_SQLITE_REINDEX: int = 27
# C: SQLITE_REPLACE
Pyi_SQLITE_REPLACE: int = 5
# C: SQLITE_RESULT_SUBTYPE
Pyi_SQLITE_RESULT_SUBTYPE: int = 0x001000000
# C: SQLITE_ROLLBACK
Pyi_SQLITE_ROLLBACK: int = 1
# C: SQLITE_ROW
Pyi_SQLITE_ROW: int = 100
# C: SQLITE_SAVEPOINT
Pyi_SQLITE_SAVEPOINT: int = 32
# C: SQLITE_SCANSTAT_COMPLEX
Pyi_SQLITE_SCANSTAT_COMPLEX: int = 0x0001
# C: SQLITE_SCANSTAT_EST
Pyi_SQLITE_SCANSTAT_EST: int = 2
# C: SQLITE_SCANSTAT_EXPLAIN
Pyi_SQLITE_SCANSTAT_EXPLAIN: int = 4
# C: SQLITE_SCANSTAT_NAME
Pyi_SQLITE_SCANSTAT_NAME: int = 3
# C: SQLITE_SCANSTAT_NCYCLE
Pyi_SQLITE_SCANSTAT_NCYCLE: int = 7
# C: SQLITE_SCANSTAT_NLOOP
Pyi_SQLITE_SCANSTAT_NLOOP: int = 0
# C: SQLITE_SCANSTAT_NVISIT
Pyi_SQLITE_SCANSTAT_NVISIT: int = 1
# C: SQLITE_SCANSTAT_PARENTID
Pyi_SQLITE_SCANSTAT_PARENTID: int = 6
# C: SQLITE_SCANSTAT_SELECTID
Pyi_SQLITE_SCANSTAT_SELECTID: int = 5
# C: SQLITE_SCHEMA
Pyi_SQLITE_SCHEMA: int = 17
# C: SQLITE_SCM_BRANCH
Pyi_SQLITE_SCM_BRANCH: str = "branch-3.53"
# C: SQLITE_SCM_DATETIME
Pyi_SQLITE_SCM_DATETIME: str = "2026-06-03T19:12:13.350Z"
# C: SQLITE_SCM_TAGS
Pyi_SQLITE_SCM_TAGS: str = "release version-3.53.2"
# C: SQLITE_SELECT
Pyi_SQLITE_SELECT: int = 21
# C: SQLITE_SELFORDER1
Pyi_SQLITE_SELFORDER1: int = 0x002000000
# C: SQLITE_SERIALIZE_NOCOPY
Pyi_SQLITE_SERIALIZE_NOCOPY: int = 0x001
# C: SQLITE_SETLK_BLOCK_ON_CONNECT
Pyi_SQLITE_SETLK_BLOCK_ON_CONNECT: int = 0x01
# C: SQLITE_SET_LOCKPROXYFILE
Pyi_SQLITE_SET_LOCKPROXYFILE: int = 3
# C: SQLITE_SHM_EXCLUSIVE
Pyi_SQLITE_SHM_EXCLUSIVE: int = 8
# C: SQLITE_SHM_LOCK
Pyi_SQLITE_SHM_LOCK: int = 2
# C: SQLITE_SHM_NLOCK
Pyi_SQLITE_SHM_NLOCK: int = 8
# C: SQLITE_SHM_SHARED
Pyi_SQLITE_SHM_SHARED: int = 4
# C: SQLITE_SHM_UNLOCK
Pyi_SQLITE_SHM_UNLOCK: int = 1
# C: SQLITE_SOURCE_ID
Pyi_SQLITE_SOURCE_ID: str = "2026-06-03 19:12:13 d6e03d8c777cfa2d35e3b60d8ec3e0187f3e9f99d8e2ee9cac695fd6fcdf1a24"
# C: SQLITE_STATUS_MALLOC_COUNT
Pyi_SQLITE_STATUS_MALLOC_COUNT: int = 9
# C: SQLITE_STATUS_MALLOC_SIZE
Pyi_SQLITE_STATUS_MALLOC_SIZE: int = 5
# C: SQLITE_STATUS_MEMORY_USED
Pyi_SQLITE_STATUS_MEMORY_USED: int = 0
# C: SQLITE_STATUS_PAGECACHE_OVERFLOW
Pyi_SQLITE_STATUS_PAGECACHE_OVERFLOW: int = 2
# C: SQLITE_STATUS_PAGECACHE_SIZE
Pyi_SQLITE_STATUS_PAGECACHE_SIZE: int = 7
# C: SQLITE_STATUS_PAGECACHE_USED
Pyi_SQLITE_STATUS_PAGECACHE_USED: int = 1
# C: SQLITE_STATUS_PARSER_STACK
Pyi_SQLITE_STATUS_PARSER_STACK: int = 6
# C: SQLITE_STATUS_SCRATCH_OVERFLOW
Pyi_SQLITE_STATUS_SCRATCH_OVERFLOW: int = 4
# C: SQLITE_STATUS_SCRATCH_SIZE
Pyi_SQLITE_STATUS_SCRATCH_SIZE: int = 8
# C: SQLITE_STATUS_SCRATCH_USED
Pyi_SQLITE_STATUS_SCRATCH_USED: int = 3
# C: SQLITE_STMTSTATUS_AUTOINDEX
Pyi_SQLITE_STMTSTATUS_AUTOINDEX: int = 3
# C: SQLITE_STMTSTATUS_FILTER_HIT
Pyi_SQLITE_STMTSTATUS_FILTER_HIT: int = 8
# C: SQLITE_STMTSTATUS_FILTER_MISS
Pyi_SQLITE_STMTSTATUS_FILTER_MISS: int = 7
# C: SQLITE_STMTSTATUS_FULLSCAN_STEP
Pyi_SQLITE_STMTSTATUS_FULLSCAN_STEP: int = 1
# C: SQLITE_STMTSTATUS_MEMUSED
Pyi_SQLITE_STMTSTATUS_MEMUSED: int = 99
# C: SQLITE_STMTSTATUS_REPREPARE
Pyi_SQLITE_STMTSTATUS_REPREPARE: int = 5
# C: SQLITE_STMTSTATUS_RUN
Pyi_SQLITE_STMTSTATUS_RUN: int = 6
# C: SQLITE_STMTSTATUS_SORT
Pyi_SQLITE_STMTSTATUS_SORT: int = 2
# C: SQLITE_STMTSTATUS_VM_STEP
Pyi_SQLITE_STMTSTATUS_VM_STEP: int = 4
# C: SQLITE_SUBTYPE
Pyi_SQLITE_SUBTYPE: int = 0x000100000
# C: SQLITE_SYNC_DATAONLY
Pyi_SQLITE_SYNC_DATAONLY: int = 0x00010
# C: SQLITE_SYNC_FULL
Pyi_SQLITE_SYNC_FULL: int = 0x00003
# C: SQLITE_SYNC_NORMAL
Pyi_SQLITE_SYNC_NORMAL: int = 0x00002
# C: SQLITE_TESTCTRL_ALWAYS
Pyi_SQLITE_TESTCTRL_ALWAYS: int = 13
# C: SQLITE_TESTCTRL_ASSERT
Pyi_SQLITE_TESTCTRL_ASSERT: int = 12
# C: SQLITE_TESTCTRL_ATOF
Pyi_SQLITE_TESTCTRL_ATOF: int = 34
# C: SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS
Pyi_SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS: int = 10
# C: SQLITE_TESTCTRL_BITVEC_TEST
Pyi_SQLITE_TESTCTRL_BITVEC_TEST: int = 8
# C: SQLITE_TESTCTRL_BYTEORDER
Pyi_SQLITE_TESTCTRL_BYTEORDER: int = 22
# C: SQLITE_TESTCTRL_EXPLAIN_STMT
Pyi_SQLITE_TESTCTRL_EXPLAIN_STMT: int = 19
# C: SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS
Pyi_SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS: int = 29
# C: SQLITE_TESTCTRL_FAULT_INSTALL
Pyi_SQLITE_TESTCTRL_FAULT_INSTALL: int = 9
# C: SQLITE_TESTCTRL_FIRST
Pyi_SQLITE_TESTCTRL_FIRST: int = 5
# C: SQLITE_TESTCTRL_FK_NO_ACTION
Pyi_SQLITE_TESTCTRL_FK_NO_ACTION: int = 7
# C: SQLITE_TESTCTRL_GETOPT
Pyi_SQLITE_TESTCTRL_GETOPT: int = 16
# C: SQLITE_TESTCTRL_IMPOSTER
Pyi_SQLITE_TESTCTRL_IMPOSTER: int = 25
# C: SQLITE_TESTCTRL_INTERNAL_FUNCTIONS
Pyi_SQLITE_TESTCTRL_INTERNAL_FUNCTIONS: int = 17
# C: SQLITE_TESTCTRL_ISINIT
Pyi_SQLITE_TESTCTRL_ISINIT: int = 23
# C: SQLITE_TESTCTRL_ISKEYWORD
Pyi_SQLITE_TESTCTRL_ISKEYWORD: int = 16
# C: SQLITE_TESTCTRL_JSON_SELFCHECK
Pyi_SQLITE_TESTCTRL_JSON_SELFCHECK: int = 14
# C: SQLITE_TESTCTRL_LAST
Pyi_SQLITE_TESTCTRL_LAST: int = 34
# C: SQLITE_TESTCTRL_LOCALTIME_FAULT
Pyi_SQLITE_TESTCTRL_LOCALTIME_FAULT: int = 18
# C: SQLITE_TESTCTRL_LOGEST
Pyi_SQLITE_TESTCTRL_LOGEST: int = 33
# C: SQLITE_TESTCTRL_NEVER_CORRUPT
Pyi_SQLITE_TESTCTRL_NEVER_CORRUPT: int = 20
# C: SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD
Pyi_SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD: int = 19
# C: SQLITE_TESTCTRL_OPTIMIZATIONS
Pyi_SQLITE_TESTCTRL_OPTIMIZATIONS: int = 15
# C: SQLITE_TESTCTRL_PARSER_COVERAGE
Pyi_SQLITE_TESTCTRL_PARSER_COVERAGE: int = 26
# C: SQLITE_TESTCTRL_PENDING_BYTE
Pyi_SQLITE_TESTCTRL_PENDING_BYTE: int = 11
# C: SQLITE_TESTCTRL_PRNG_RESET
Pyi_SQLITE_TESTCTRL_PRNG_RESET: int = 7
# C: SQLITE_TESTCTRL_PRNG_RESTORE
Pyi_SQLITE_TESTCTRL_PRNG_RESTORE: int = 6
# C: SQLITE_TESTCTRL_PRNG_SAVE
Pyi_SQLITE_TESTCTRL_PRNG_SAVE: int = 5
# C: SQLITE_TESTCTRL_PRNG_SEED
Pyi_SQLITE_TESTCTRL_PRNG_SEED: int = 28
# C: SQLITE_TESTCTRL_RESERVE
Pyi_SQLITE_TESTCTRL_RESERVE: int = 14
# C: SQLITE_TESTCTRL_RESULT_INTREAL
Pyi_SQLITE_TESTCTRL_RESULT_INTREAL: int = 27
# C: SQLITE_TESTCTRL_SCRATCHMALLOC
Pyi_SQLITE_TESTCTRL_SCRATCHMALLOC: int = 17
# C: SQLITE_TESTCTRL_SEEK_COUNT
Pyi_SQLITE_TESTCTRL_SEEK_COUNT: int = 30
# C: SQLITE_TESTCTRL_SORTER_MMAP
Pyi_SQLITE_TESTCTRL_SORTER_MMAP: int = 24
# C: SQLITE_TESTCTRL_TRACEFLAGS
Pyi_SQLITE_TESTCTRL_TRACEFLAGS: int = 31
# C: SQLITE_TESTCTRL_TUNE
Pyi_SQLITE_TESTCTRL_TUNE: int = 32
# C: SQLITE_TESTCTRL_USELONGDOUBLE
Pyi_SQLITE_TESTCTRL_USELONGDOUBLE: int = 34
# C: SQLITE_TESTCTRL_VDBE_COVERAGE
Pyi_SQLITE_TESTCTRL_VDBE_COVERAGE: int = 21
# C: SQLITE_TEXT
Pyi_SQLITE_TEXT: int = 3
# C: SQLITE_TOOBIG
Pyi_SQLITE_TOOBIG: int = 18
# C: SQLITE_TRACE_CLOSE
Pyi_SQLITE_TRACE_CLOSE: int = 0x08
# C: SQLITE_TRACE_PROFILE
Pyi_SQLITE_TRACE_PROFILE: int = 0x02
# C: SQLITE_TRACE_ROW
Pyi_SQLITE_TRACE_ROW: int = 0x04
# C: SQLITE_TRACE_STMT
Pyi_SQLITE_TRACE_STMT: int = 0x01
# C: SQLITE_TRANSACTION
Pyi_SQLITE_TRANSACTION: int = 22
# C: SQLITE_TXN_NONE
Pyi_SQLITE_TXN_NONE: int = 0
# C: SQLITE_TXN_READ
Pyi_SQLITE_TXN_READ: int = 1
# C: SQLITE_TXN_WRITE
Pyi_SQLITE_TXN_WRITE: int = 2
# C: SQLITE_UPDATE
Pyi_SQLITE_UPDATE: int = 23
# C: SQLITE_UTF16
Pyi_SQLITE_UTF16: int = 4
# C: SQLITE_UTF16BE
Pyi_SQLITE_UTF16BE: int = 3
# C: SQLITE_UTF16LE
Pyi_SQLITE_UTF16LE: int = 2
# C: SQLITE_UTF16_ALIGNED
Pyi_SQLITE_UTF16_ALIGNED: int = 8
# C: SQLITE_UTF8
Pyi_SQLITE_UTF8: int = 1
# C: SQLITE_UTF8_ZT
Pyi_SQLITE_UTF8_ZT: int = 16
# C: SQLITE_VERSION
Pyi_SQLITE_VERSION: str = "3.53.2"
# C: SQLITE_VERSION_NUMBER
Pyi_SQLITE_VERSION_NUMBER: int = 3053002
# C: SQLITE_VTAB_CONSTRAINT_SUPPORT
Pyi_SQLITE_VTAB_CONSTRAINT_SUPPORT: int = 1
# C: SQLITE_VTAB_DIRECTONLY
Pyi_SQLITE_VTAB_DIRECTONLY: int = 3
# C: SQLITE_VTAB_INNOCUOUS
Pyi_SQLITE_VTAB_INNOCUOUS: int = 2
# C: SQLITE_VTAB_USES_ALL_SCHEMAS
Pyi_SQLITE_VTAB_USES_ALL_SCHEMAS: int = 4
# C: SQLITE_WARNING
Pyi_SQLITE_WARNING: int = 28
# C: SQLITE_WIN32_DATA_DIRECTORY_TYPE
Pyi_SQLITE_WIN32_DATA_DIRECTORY_TYPE: int = 1
# C: SQLITE_WIN32_TEMP_DIRECTORY_TYPE
Pyi_SQLITE_WIN32_TEMP_DIRECTORY_TYPE: int = 2

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("sqlite3_aggregate_context")
def Pyi_sqlite3_aggregate_context(arg0: Pointer[Pyi_sqlite3_context], nBytes: int) -> uintptr:
  ...

@native
@native_name("sqlite3_aggregate_count")
def Pyi_sqlite3_aggregate_count(arg0: Pointer[Pyi_sqlite3_context]) -> int:
  ...

@native
@native_name("sqlite3_auto_extension")
def Pyi_sqlite3_auto_extension(xEntryPoint: Function[[], None]) -> int:
  ...

@native
@native_name("sqlite3_autovacuum_pages")
def Pyi_sqlite3_autovacuum_pages(db: Pointer[Pyi_sqlite3], arg1: Function[[uintptr, c_str, uint, uint, uint], uint], arg2: uintptr, arg3: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_backup_finish")
def Pyi_sqlite3_backup_finish(p: Pointer[Pyi_sqlite3_backup]) -> int:
  ...

@native
@native_name("sqlite3_backup_init")
def Pyi_sqlite3_backup_init(pDest: Pointer[Pyi_sqlite3], zDestName: c_str, pSource: Pointer[Pyi_sqlite3], zSourceName: c_str) -> Pointer[Pyi_sqlite3_backup]:
  ...

@native
@native_name("sqlite3_backup_pagecount")
def Pyi_sqlite3_backup_pagecount(p: Pointer[Pyi_sqlite3_backup]) -> int:
  ...

@native
@native_name("sqlite3_backup_remaining")
def Pyi_sqlite3_backup_remaining(p: Pointer[Pyi_sqlite3_backup]) -> int:
  ...

@native
@native_name("sqlite3_backup_step")
def Pyi_sqlite3_backup_step(p: Pointer[Pyi_sqlite3_backup], nPage: int) -> int:
  ...

@native
@native_name("sqlite3_bind_blob")
def Pyi_sqlite3_bind_blob(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: uintptr, n: int, arg4: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_bind_blob64")
def Pyi_sqlite3_bind_blob64(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: uintptr, arg3: uint64, arg4: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_bind_double")
def Pyi_sqlite3_bind_double(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: float64) -> int:
  ...

@native
@native_name("sqlite3_bind_int")
def Pyi_sqlite3_bind_int(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: int) -> int:
  ...

@native
@native_name("sqlite3_bind_int64")
def Pyi_sqlite3_bind_int64(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: int64) -> int:
  ...

@native
@native_name("sqlite3_bind_null")
def Pyi_sqlite3_bind_null(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_count")
def Pyi_sqlite3_bind_parameter_count(arg0: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_index")
def Pyi_sqlite3_bind_parameter_index(arg0: Pointer[Pyi_sqlite3_stmt], zName: c_str) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_name")
def Pyi_sqlite3_bind_parameter_name(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_bind_pointer")
def Pyi_sqlite3_bind_pointer(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: uintptr, arg3: c_str, arg4: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_bind_text")
def Pyi_sqlite3_bind_text(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: c_str, arg3: int, arg4: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_bind_text16")
def Pyi_sqlite3_bind_text16(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: uintptr, arg3: int, arg4: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_bind_text64")
def Pyi_sqlite3_bind_text64(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: c_str, arg3: uint64, arg4: Function[[uintptr], None], encoding: int) -> int:
  ...

@native
@native_name("sqlite3_bind_value")
def Pyi_sqlite3_bind_value(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_bind_zeroblob")
def Pyi_sqlite3_bind_zeroblob(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, n: int) -> int:
  ...

@native
@native_name("sqlite3_bind_zeroblob64")
def Pyi_sqlite3_bind_zeroblob64(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int, arg2: uint64) -> int:
  ...

@native
@native_name("sqlite3_blob_bytes")
def Pyi_sqlite3_blob_bytes(arg0: Pointer[Pyi_sqlite3_blob]) -> int:
  ...

@native
@native_name("sqlite3_blob_close")
def Pyi_sqlite3_blob_close(arg0: Pointer[Pyi_sqlite3_blob]) -> int:
  ...

@native
@native_name("sqlite3_blob_open")
def Pyi_sqlite3_blob_open(arg0: Pointer[Pyi_sqlite3], zDb: c_str, zTable: c_str, zColumn: c_str, iRow: int64, flags: int, ppBlob: Pointer[Pointer[Pyi_sqlite3_blob]]) -> int:
  ...

@native
@native_name("sqlite3_blob_read")
def Pyi_sqlite3_blob_read(arg0: Pointer[Pyi_sqlite3_blob], Z: uintptr, N: int, iOffset: int) -> int:
  ...

@native
@native_name("sqlite3_blob_reopen")
def Pyi_sqlite3_blob_reopen(arg0: Pointer[Pyi_sqlite3_blob], arg1: int64) -> int:
  ...

@native
@native_name("sqlite3_blob_write")
def Pyi_sqlite3_blob_write(arg0: Pointer[Pyi_sqlite3_blob], z: uintptr, n: int, iOffset: int) -> int:
  ...

@native
@native_name("sqlite3_busy_handler")
def Pyi_sqlite3_busy_handler(arg0: Pointer[Pyi_sqlite3], arg1: Function[[uintptr, int], int], arg2: uintptr) -> int:
  ...

@native
@native_name("sqlite3_busy_timeout")
def Pyi_sqlite3_busy_timeout(arg0: Pointer[Pyi_sqlite3], ms: int) -> int:
  ...

@native
@native_name("sqlite3_cancel_auto_extension")
def Pyi_sqlite3_cancel_auto_extension(xEntryPoint: Function[[], None]) -> int:
  ...

@native
@native_name("sqlite3_carray_bind")
def Pyi_sqlite3_carray_bind(pStmt: Pointer[Pyi_sqlite3_stmt], i: int, aData: uintptr, nData: int, mFlags: int, xDel: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_carray_bind_v2")
def Pyi_sqlite3_carray_bind_v2(pStmt: Pointer[Pyi_sqlite3_stmt], i: int, aData: uintptr, nData: int, mFlags: int, xDel: Function[[uintptr], None], pDel: uintptr) -> int:
  ...

@native
@native_name("sqlite3_changes")
def Pyi_sqlite3_changes(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_changes64")
def Pyi_sqlite3_changes64(arg0: Pointer[Pyi_sqlite3]) -> int64:
  ...

@native
@native_name("sqlite3_clear_bindings")
def Pyi_sqlite3_clear_bindings(arg0: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_close")
def Pyi_sqlite3_close(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_close_v2")
def Pyi_sqlite3_close_v2(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_collation_needed")
def Pyi_sqlite3_collation_needed(arg0: Pointer[Pyi_sqlite3], arg1: uintptr, arg2: Function[[uintptr, Pointer[Pyi_sqlite3], int, c_str], None]) -> int:
  ...

@native
@native_name("sqlite3_collation_needed16")
def Pyi_sqlite3_collation_needed16(arg0: Pointer[Pyi_sqlite3], arg1: uintptr, arg2: Function[[uintptr, Pointer[Pyi_sqlite3], int, uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_column_blob")
def Pyi_sqlite3_column_blob(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_bytes")
def Pyi_sqlite3_column_bytes(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_bytes16")
def Pyi_sqlite3_column_bytes16(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_count")
def Pyi_sqlite3_column_count(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_column_database_name")
def Pyi_sqlite3_column_database_name(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_database_name16")
def Pyi_sqlite3_column_database_name16(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_decltype")
def Pyi_sqlite3_column_decltype(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_decltype16")
def Pyi_sqlite3_column_decltype16(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_double")
def Pyi_sqlite3_column_double(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> float64:
  ...

@native
@native_name("sqlite3_column_int")
def Pyi_sqlite3_column_int(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_int64")
def Pyi_sqlite3_column_int64(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> int64:
  ...

@native
@native_name("sqlite3_column_name")
def Pyi_sqlite3_column_name(arg0: Pointer[Pyi_sqlite3_stmt], N: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_name16")
def Pyi_sqlite3_column_name16(arg0: Pointer[Pyi_sqlite3_stmt], N: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_origin_name")
def Pyi_sqlite3_column_origin_name(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_origin_name16")
def Pyi_sqlite3_column_origin_name16(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_table_name")
def Pyi_sqlite3_column_table_name(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_table_name16")
def Pyi_sqlite3_column_table_name16(arg0: Pointer[Pyi_sqlite3_stmt], arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_text")
def Pyi_sqlite3_column_text(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_text16")
def Pyi_sqlite3_column_text16(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_type")
def Pyi_sqlite3_column_type(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_value")
def Pyi_sqlite3_column_value(arg0: Pointer[Pyi_sqlite3_stmt], iCol: int) -> Pointer[Pyi_sqlite3_value]:
  ...

@native
@native_name("sqlite3_commit_hook")
def Pyi_sqlite3_commit_hook(arg0: Pointer[Pyi_sqlite3], arg1: Function[[uintptr], int], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_compileoption_get")
def Pyi_sqlite3_compileoption_get(N: int) -> c_str:
  ...

@native
@native_name("sqlite3_compileoption_used")
def Pyi_sqlite3_compileoption_used(zOptName: c_str) -> int:
  ...

@native
@native_name("sqlite3_complete")
def Pyi_sqlite3_complete(sql: c_str) -> int:
  ...

@native
@native_name("sqlite3_complete16")
def Pyi_sqlite3_complete16(sql: uintptr) -> int:
  ...

@native
@native_name("sqlite3_config")
def Pyi_sqlite3_config(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_context_db_handle")
def Pyi_sqlite3_context_db_handle(arg0: Pointer[Pyi_sqlite3_context]) -> Pointer[Pyi_sqlite3]:
  ...

@native
@native_name("sqlite3_create_collation")
def Pyi_sqlite3_create_collation(arg0: Pointer[Pyi_sqlite3], zName: c_str, eTextRep: int, pArg: uintptr, xCompare: Function[[uintptr, int, uintptr, int, uintptr], int]) -> int:
  ...

@native
@native_name("sqlite3_create_collation16")
def Pyi_sqlite3_create_collation16(arg0: Pointer[Pyi_sqlite3], zName: uintptr, eTextRep: int, pArg: uintptr, xCompare: Function[[uintptr, int, uintptr, int, uintptr], int]) -> int:
  ...

@native
@native_name("sqlite3_create_collation_v2")
def Pyi_sqlite3_create_collation_v2(arg0: Pointer[Pyi_sqlite3], zName: c_str, eTextRep: int, pArg: uintptr, xCompare: Function[[uintptr, int, uintptr, int, uintptr], int], xDestroy: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_create_filename")
def Pyi_sqlite3_create_filename(zDatabase: c_str, zJournal: c_str, zWal: c_str, nParam: int, azParam: Pointer[c_str]) -> c_str:
  ...

@native
@native_name("sqlite3_create_function")
def Pyi_sqlite3_create_function(db: Pointer[Pyi_sqlite3], zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xFunc: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xStep: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xFinal: Function[[Pointer[Pyi_sqlite3_context]], None]) -> int:
  ...

@native
@native_name("sqlite3_create_function16")
def Pyi_sqlite3_create_function16(db: Pointer[Pyi_sqlite3], zFunctionName: uintptr, nArg: int, eTextRep: int, pApp: uintptr, xFunc: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xStep: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xFinal: Function[[Pointer[Pyi_sqlite3_context]], None]) -> int:
  ...

@native
@native_name("sqlite3_create_function_v2")
def Pyi_sqlite3_create_function_v2(db: Pointer[Pyi_sqlite3], zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xFunc: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xStep: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xFinal: Function[[Pointer[Pyi_sqlite3_context]], None], xDestroy: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_create_module")
def Pyi_sqlite3_create_module(db: Pointer[Pyi_sqlite3], zName: c_str, p: Pointer[Pyi_sqlite3_module], pClientData: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_module_v2")
def Pyi_sqlite3_create_module_v2(db: Pointer[Pyi_sqlite3], zName: c_str, p: Pointer[Pyi_sqlite3_module], pClientData: uintptr, xDestroy: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_create_window_function")
def Pyi_sqlite3_create_window_function(db: Pointer[Pyi_sqlite3], zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xStep: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xFinal: Function[[Pointer[Pyi_sqlite3_context]], None], xValue: Function[[Pointer[Pyi_sqlite3_context]], None], xInverse: Function[[Pointer[Pyi_sqlite3_context], int, Pointer[Pointer[Pyi_sqlite3_value]]], None], xDestroy: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_data_count")
def Pyi_sqlite3_data_count(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_database_file_object")
def Pyi_sqlite3_database_file_object(arg0: c_str) -> Pointer[Pyi_sqlite3_file]:
  ...

@native
@native_name("sqlite3_db_cacheflush")
def Pyi_sqlite3_db_cacheflush(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_db_config")
def Pyi_sqlite3_db_config(arg0: Pointer[Pyi_sqlite3], op: int) -> int:
  ...

@native
@native_name("sqlite3_db_filename")
def Pyi_sqlite3_db_filename(db: Pointer[Pyi_sqlite3], zDbName: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_db_handle")
def Pyi_sqlite3_db_handle(arg0: Pointer[Pyi_sqlite3_stmt]) -> Pointer[Pyi_sqlite3]:
  ...

@native
@native_name("sqlite3_db_mutex")
def Pyi_sqlite3_db_mutex(arg0: Pointer[Pyi_sqlite3]) -> Pointer[Pyi_sqlite3_mutex]:
  ...

@native
@native_name("sqlite3_db_name")
def Pyi_sqlite3_db_name(db: Pointer[Pyi_sqlite3], N: int) -> c_str:
  ...

@native
@native_name("sqlite3_db_readonly")
def Pyi_sqlite3_db_readonly(db: Pointer[Pyi_sqlite3], zDbName: c_str) -> int:
  ...

@native
@native_name("sqlite3_db_release_memory")
def Pyi_sqlite3_db_release_memory(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_db_status")
def Pyi_sqlite3_db_status(arg0: Pointer[Pyi_sqlite3], op: int, pCur: Pointer[int], pHiwtr: Pointer[int], resetFlg: int) -> int:
  ...

@native
@native_name("sqlite3_db_status64")
def Pyi_sqlite3_db_status64(arg0: Pointer[Pyi_sqlite3], arg1: int, arg2: Pointer[int64], arg3: Pointer[int64], arg4: int) -> int:
  ...

@native
@native_name("sqlite3_declare_vtab")
def Pyi_sqlite3_declare_vtab(arg0: Pointer[Pyi_sqlite3], zSQL: c_str) -> int:
  ...

@native
@native_name("sqlite3_deserialize")
def Pyi_sqlite3_deserialize(db: Pointer[Pyi_sqlite3], zSchema: c_str, pData: c_str, szDb: int64, szBuf: int64, mFlags: uint) -> int:
  ...

@native
@native_name("sqlite3_drop_modules")
def Pyi_sqlite3_drop_modules(db: Pointer[Pyi_sqlite3], azKeep: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_enable_load_extension")
def Pyi_sqlite3_enable_load_extension(db: Pointer[Pyi_sqlite3], onoff: int) -> int:
  ...

@native
@native_name("sqlite3_enable_shared_cache")
def Pyi_sqlite3_enable_shared_cache(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_errcode")
def Pyi_sqlite3_errcode(db: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_errmsg")
def Pyi_sqlite3_errmsg(arg0: Pointer[Pyi_sqlite3]) -> c_str:
  ...

@native
@native_name("sqlite3_errmsg16")
def Pyi_sqlite3_errmsg16(arg0: Pointer[Pyi_sqlite3]) -> uintptr:
  ...

@native
@native_name("sqlite3_error_offset")
def Pyi_sqlite3_error_offset(db: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_errstr")
def Pyi_sqlite3_errstr(arg0: int) -> c_str:
  ...

@native
@native_name("sqlite3_exec")
def Pyi_sqlite3_exec(arg0: Pointer[Pyi_sqlite3], sql: c_str, callback: Function[[uintptr, int, Pointer[c_str], Pointer[c_str]], int], arg3: uintptr, errmsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_expanded_sql")
def Pyi_sqlite3_expanded_sql(pStmt: Pointer[Pyi_sqlite3_stmt]) -> c_str:
  ...

@native
@native_name("sqlite3_expired")
def Pyi_sqlite3_expired(arg0: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_extended_errcode")
def Pyi_sqlite3_extended_errcode(db: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_extended_result_codes")
def Pyi_sqlite3_extended_result_codes(arg0: Pointer[Pyi_sqlite3], onoff: int) -> int:
  ...

@native
@native_name("sqlite3_file_control")
def Pyi_sqlite3_file_control(arg0: Pointer[Pyi_sqlite3], zDbName: c_str, op: int, arg3: uintptr) -> int:
  ...

@native
@native_name("sqlite3_filename_database")
def Pyi_sqlite3_filename_database(arg0: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_filename_journal")
def Pyi_sqlite3_filename_journal(arg0: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_filename_wal")
def Pyi_sqlite3_filename_wal(arg0: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_finalize")
def Pyi_sqlite3_finalize(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_free")
def Pyi_sqlite3_free(arg0: uintptr) -> None:
  ...

@native
@native_name("sqlite3_free_filename")
def Pyi_sqlite3_free_filename(arg0: c_str) -> None:
  ...

@native
@native_name("sqlite3_free_table")
def Pyi_sqlite3_free_table(result: Pointer[c_str]) -> None:
  ...

@native
@native_name("sqlite3_get_autocommit")
def Pyi_sqlite3_get_autocommit(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_get_auxdata")
def Pyi_sqlite3_get_auxdata(arg0: Pointer[Pyi_sqlite3_context], N: int) -> uintptr:
  ...

@native
@native_name("sqlite3_get_clientdata")
def Pyi_sqlite3_get_clientdata(arg0: Pointer[Pyi_sqlite3], arg1: c_str) -> uintptr:
  ...

@native
@native_name("sqlite3_get_table")
def Pyi_sqlite3_get_table(db: Pointer[Pyi_sqlite3], zSql: c_str, pazResult: Pointer[Pointer[c_str]], pnRow: Pointer[int], pnColumn: Pointer[int], pzErrmsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_global_recover")
def Pyi_sqlite3_global_recover() -> int:
  ...

@native
@native_name("sqlite3_hard_heap_limit64")
def Pyi_sqlite3_hard_heap_limit64(N: int64) -> int64:
  ...

@native
@native_name("sqlite3_initialize")
def Pyi_sqlite3_initialize() -> int:
  ...

@native
@native_name("sqlite3_interrupt")
def Pyi_sqlite3_interrupt(arg0: Pointer[Pyi_sqlite3]) -> None:
  ...

@native
@native_name("sqlite3_is_interrupted")
def Pyi_sqlite3_is_interrupted(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_keyword_check")
def Pyi_sqlite3_keyword_check(arg0: c_str, arg1: int) -> int:
  ...

@native
@native_name("sqlite3_keyword_count")
def Pyi_sqlite3_keyword_count() -> int:
  ...

@native
@native_name("sqlite3_keyword_name")
def Pyi_sqlite3_keyword_name(arg0: int, arg1: Pointer[c_str], arg2: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_last_insert_rowid")
def Pyi_sqlite3_last_insert_rowid(arg0: Pointer[Pyi_sqlite3]) -> int64:
  ...

@native
@native_name("sqlite3_libversion")
def Pyi_sqlite3_libversion() -> c_str:
  ...

@native
@native_name("sqlite3_libversion_number")
def Pyi_sqlite3_libversion_number() -> int:
  ...

@native
@native_name("sqlite3_limit")
def Pyi_sqlite3_limit(arg0: Pointer[Pyi_sqlite3], id: int, newVal: int) -> int:
  ...

@native
@native_name("sqlite3_load_extension")
def Pyi_sqlite3_load_extension(db: Pointer[Pyi_sqlite3], zFile: c_str, zProc: c_str, pzErrMsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_log")
def Pyi_sqlite3_log(iErrCode: int, zFormat: c_str) -> None:
  ...

@native
@native_name("sqlite3_malloc")
def Pyi_sqlite3_malloc(arg0: int) -> uintptr:
  ...

@native
@native_name("sqlite3_malloc64")
def Pyi_sqlite3_malloc64(arg0: uint64) -> uintptr:
  ...

@native
@native_name("sqlite3_memory_alarm")
def Pyi_sqlite3_memory_alarm(arg0: Function[[uintptr, int64, int], None], arg1: uintptr, arg2: int64) -> int:
  ...

@native
@native_name("sqlite3_memory_highwater")
def Pyi_sqlite3_memory_highwater(resetFlag: int) -> int64:
  ...

@native
@native_name("sqlite3_memory_used")
def Pyi_sqlite3_memory_used() -> int64:
  ...

@native
@native_name("sqlite3_mprintf")
def Pyi_sqlite3_mprintf(arg0: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_msize")
def Pyi_sqlite3_msize(arg0: uintptr) -> uint64:
  ...

@native
@native_name("sqlite3_mutex_alloc")
def Pyi_sqlite3_mutex_alloc(arg0: int) -> Pointer[Pyi_sqlite3_mutex]:
  ...

@native
@native_name("sqlite3_mutex_enter")
def Pyi_sqlite3_mutex_enter(arg0: Pointer[Pyi_sqlite3_mutex]) -> None:
  ...

@native
@native_name("sqlite3_mutex_free")
def Pyi_sqlite3_mutex_free(arg0: Pointer[Pyi_sqlite3_mutex]) -> None:
  ...

@native
@native_name("sqlite3_mutex_held")
def Pyi_sqlite3_mutex_held(arg0: Pointer[Pyi_sqlite3_mutex]) -> int:
  ...

@native
@native_name("sqlite3_mutex_leave")
def Pyi_sqlite3_mutex_leave(arg0: Pointer[Pyi_sqlite3_mutex]) -> None:
  ...

@native
@native_name("sqlite3_mutex_notheld")
def Pyi_sqlite3_mutex_notheld(arg0: Pointer[Pyi_sqlite3_mutex]) -> int:
  ...

@native
@native_name("sqlite3_mutex_try")
def Pyi_sqlite3_mutex_try(arg0: Pointer[Pyi_sqlite3_mutex]) -> int:
  ...

@native
@native_name("sqlite3_next_stmt")
def Pyi_sqlite3_next_stmt(pDb: Pointer[Pyi_sqlite3], pStmt: Pointer[Pyi_sqlite3_stmt]) -> Pointer[Pyi_sqlite3_stmt]:
  ...

@native
@native_name("sqlite3_open")
def Pyi_sqlite3_open(filename: c_str, ppDb: Pointer[Pointer[Pyi_sqlite3]]) -> int:
  ...

@native
@native_name("sqlite3_open16")
def Pyi_sqlite3_open16(filename: uintptr, ppDb: Pointer[Pointer[Pyi_sqlite3]]) -> int:
  ...

@native
@native_name("sqlite3_open_v2")
def Pyi_sqlite3_open_v2(filename: c_str, ppDb: Pointer[Pointer[Pyi_sqlite3]], flags: int, zVfs: c_str) -> int:
  ...

@native
@native_name("sqlite3_os_end")
def Pyi_sqlite3_os_end() -> int:
  ...

@native
@native_name("sqlite3_os_init")
def Pyi_sqlite3_os_init() -> int:
  ...

@native
@native_name("sqlite3_overload_function")
def Pyi_sqlite3_overload_function(arg0: Pointer[Pyi_sqlite3], zFuncName: c_str, nArg: int) -> int:
  ...

@native
@native_name("sqlite3_prepare")
def Pyi_sqlite3_prepare(db: Pointer[Pyi_sqlite3], zSql: c_str, nByte: int, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_prepare16")
def Pyi_sqlite3_prepare16(db: Pointer[Pyi_sqlite3], zSql: uintptr, nByte: int, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare16_v2")
def Pyi_sqlite3_prepare16_v2(db: Pointer[Pyi_sqlite3], zSql: uintptr, nByte: int, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare16_v3")
def Pyi_sqlite3_prepare16_v3(db: Pointer[Pyi_sqlite3], zSql: uintptr, nByte: int, prepFlags: uint, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare_v2")
def Pyi_sqlite3_prepare_v2(db: Pointer[Pyi_sqlite3], zSql: c_str, nByte: int, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_prepare_v3")
def Pyi_sqlite3_prepare_v3(db: Pointer[Pyi_sqlite3], zSql: c_str, nByte: int, prepFlags: uint, ppStmt: Pointer[Pointer[Pyi_sqlite3_stmt]], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_profile")
def Pyi_sqlite3_profile(arg0: Pointer[Pyi_sqlite3], xProfile: Function[[uintptr, c_str, uint64], None], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_progress_handler")
def Pyi_sqlite3_progress_handler(arg0: Pointer[Pyi_sqlite3], arg1: int, arg2: Function[[uintptr], int], arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_randomness")
def Pyi_sqlite3_randomness(N: int, P: uintptr) -> None:
  ...

@native
@native_name("sqlite3_realloc")
def Pyi_sqlite3_realloc(arg0: uintptr, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_realloc64")
def Pyi_sqlite3_realloc64(arg0: uintptr, arg1: uint64) -> uintptr:
  ...

@native
@native_name("sqlite3_release_memory")
def Pyi_sqlite3_release_memory(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_reset")
def Pyi_sqlite3_reset(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_reset_auto_extension")
def Pyi_sqlite3_reset_auto_extension() -> None:
  ...

@native
@native_name("sqlite3_result_blob")
def Pyi_sqlite3_result_blob(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: int, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_blob64")
def Pyi_sqlite3_result_blob64(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: uint64, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_double")
def Pyi_sqlite3_result_double(arg0: Pointer[Pyi_sqlite3_context], arg1: float64) -> None:
  ...

@native
@native_name("sqlite3_result_error")
def Pyi_sqlite3_result_error(arg0: Pointer[Pyi_sqlite3_context], arg1: c_str, arg2: int) -> None:
  ...

@native
@native_name("sqlite3_result_error16")
def Pyi_sqlite3_result_error16(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: int) -> None:
  ...

@native
@native_name("sqlite3_result_error_code")
def Pyi_sqlite3_result_error_code(arg0: Pointer[Pyi_sqlite3_context], arg1: int) -> None:
  ...

@native
@native_name("sqlite3_result_error_nomem")
def Pyi_sqlite3_result_error_nomem(arg0: Pointer[Pyi_sqlite3_context]) -> None:
  ...

@native
@native_name("sqlite3_result_error_toobig")
def Pyi_sqlite3_result_error_toobig(arg0: Pointer[Pyi_sqlite3_context]) -> None:
  ...

@native
@native_name("sqlite3_result_int")
def Pyi_sqlite3_result_int(arg0: Pointer[Pyi_sqlite3_context], arg1: int) -> None:
  ...

@native
@native_name("sqlite3_result_int64")
def Pyi_sqlite3_result_int64(arg0: Pointer[Pyi_sqlite3_context], arg1: int64) -> None:
  ...

@native
@native_name("sqlite3_result_null")
def Pyi_sqlite3_result_null(arg0: Pointer[Pyi_sqlite3_context]) -> None:
  ...

@native
@native_name("sqlite3_result_pointer")
def Pyi_sqlite3_result_pointer(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: c_str, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_subtype")
def Pyi_sqlite3_result_subtype(arg0: Pointer[Pyi_sqlite3_context], arg1: uint) -> None:
  ...

@native
@native_name("sqlite3_result_text")
def Pyi_sqlite3_result_text(arg0: Pointer[Pyi_sqlite3_context], arg1: c_str, arg2: int, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_text16")
def Pyi_sqlite3_result_text16(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: int, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_text16be")
def Pyi_sqlite3_result_text16be(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: int, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_text16le")
def Pyi_sqlite3_result_text16le(arg0: Pointer[Pyi_sqlite3_context], arg1: uintptr, arg2: int, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_result_text64")
def Pyi_sqlite3_result_text64(arg0: Pointer[Pyi_sqlite3_context], z: c_str, n: uint64, arg3: Function[[uintptr], None], encoding: int) -> None:
  ...

@native
@native_name("sqlite3_result_value")
def Pyi_sqlite3_result_value(arg0: Pointer[Pyi_sqlite3_context], arg1: Pointer[Pyi_sqlite3_value]) -> None:
  ...

@native
@native_name("sqlite3_result_zeroblob")
def Pyi_sqlite3_result_zeroblob(arg0: Pointer[Pyi_sqlite3_context], n: int) -> None:
  ...

@native
@native_name("sqlite3_result_zeroblob64")
def Pyi_sqlite3_result_zeroblob64(arg0: Pointer[Pyi_sqlite3_context], n: uint64) -> int:
  ...

@native
@native_name("sqlite3_rollback_hook")
def Pyi_sqlite3_rollback_hook(arg0: Pointer[Pyi_sqlite3], arg1: Function[[uintptr], None], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_rtree_geometry_callback")
def Pyi_sqlite3_rtree_geometry_callback(db: Pointer[Pyi_sqlite3], zGeom: c_str, xGeom: Function[[Pointer[Pyi_sqlite3_rtree_geometry], int, Pointer[float64], Pointer[int]], int], pContext: uintptr) -> int:
  ...

@native
@native_name("sqlite3_rtree_query_callback")
def Pyi_sqlite3_rtree_query_callback(db: Pointer[Pyi_sqlite3], zQueryFunc: c_str, xQueryFunc: Function[[Pointer[Pyi_sqlite3_rtree_query_info]], int], pContext: uintptr, xDestructor: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_serialize")
def Pyi_sqlite3_serialize(db: Pointer[Pyi_sqlite3], zSchema: c_str, piSize: Pointer[int64], mFlags: uint) -> c_str:
  ...

@native
@native_name("sqlite3_set_authorizer")
def Pyi_sqlite3_set_authorizer(arg0: Pointer[Pyi_sqlite3], xAuth: Function[[uintptr, int, c_str, c_str, c_str, c_str], int], pUserData: uintptr) -> int:
  ...

@native
@native_name("sqlite3_set_auxdata")
def Pyi_sqlite3_set_auxdata(arg0: Pointer[Pyi_sqlite3_context], N: int, arg2: uintptr, arg3: Function[[uintptr], None]) -> None:
  ...

@native
@native_name("sqlite3_set_clientdata")
def Pyi_sqlite3_set_clientdata(arg0: Pointer[Pyi_sqlite3], arg1: c_str, arg2: uintptr, arg3: Function[[uintptr], None]) -> int:
  ...

@native
@native_name("sqlite3_set_errmsg")
def Pyi_sqlite3_set_errmsg(db: Pointer[Pyi_sqlite3], errcode: int, zErrMsg: c_str) -> int:
  ...

@native
@native_name("sqlite3_set_last_insert_rowid")
def Pyi_sqlite3_set_last_insert_rowid(arg0: Pointer[Pyi_sqlite3], arg1: int64) -> None:
  ...

@native
@native_name("sqlite3_setlk_timeout")
def Pyi_sqlite3_setlk_timeout(arg0: Pointer[Pyi_sqlite3], ms: int, flags: int) -> int:
  ...

@native
@native_name("sqlite3_shutdown")
def Pyi_sqlite3_shutdown() -> int:
  ...

@native
@native_name("sqlite3_sleep")
def Pyi_sqlite3_sleep(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_snapshot_cmp")
def Pyi_sqlite3_snapshot_cmp(p1: Pointer[Pyi_sqlite3_snapshot], p2: Pointer[Pyi_sqlite3_snapshot]) -> int:
  ...

@native
@native_name("sqlite3_snapshot_free")
def Pyi_sqlite3_snapshot_free(arg0: Pointer[Pyi_sqlite3_snapshot]) -> None:
  ...

@native
@native_name("sqlite3_snapshot_get")
def Pyi_sqlite3_snapshot_get(db: Pointer[Pyi_sqlite3], zSchema: c_str, ppSnapshot: Pointer[Pointer[Pyi_sqlite3_snapshot]]) -> int:
  ...

@native
@native_name("sqlite3_snapshot_open")
def Pyi_sqlite3_snapshot_open(db: Pointer[Pyi_sqlite3], zSchema: c_str, pSnapshot: Pointer[Pyi_sqlite3_snapshot]) -> int:
  ...

@native
@native_name("sqlite3_snapshot_recover")
def Pyi_sqlite3_snapshot_recover(db: Pointer[Pyi_sqlite3], zDb: c_str) -> int:
  ...

@native
@native_name("sqlite3_snprintf")
def Pyi_sqlite3_snprintf(arg0: int, arg1: c_str, arg2: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_soft_heap_limit")
def Pyi_sqlite3_soft_heap_limit(N: int) -> None:
  ...

@native
@native_name("sqlite3_soft_heap_limit64")
def Pyi_sqlite3_soft_heap_limit64(N: int64) -> int64:
  ...

@native
@native_name("sqlite3_sourceid")
def Pyi_sqlite3_sourceid() -> c_str:
  ...

@native
@native_name("sqlite3_sql")
def Pyi_sqlite3_sql(pStmt: Pointer[Pyi_sqlite3_stmt]) -> c_str:
  ...

@native
@native_name("sqlite3_status")
def Pyi_sqlite3_status(op: int, pCurrent: Pointer[int], pHighwater: Pointer[int], resetFlag: int) -> int:
  ...

@native
@native_name("sqlite3_status64")
def Pyi_sqlite3_status64(op: int, pCurrent: Pointer[int64], pHighwater: Pointer[int64], resetFlag: int) -> int:
  ...

@native
@native_name("sqlite3_step")
def Pyi_sqlite3_step(arg0: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_stmt_busy")
def Pyi_sqlite3_stmt_busy(arg0: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_stmt_explain")
def Pyi_sqlite3_stmt_explain(pStmt: Pointer[Pyi_sqlite3_stmt], eMode: int) -> int:
  ...

@native
@native_name("sqlite3_stmt_isexplain")
def Pyi_sqlite3_stmt_isexplain(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_stmt_readonly")
def Pyi_sqlite3_stmt_readonly(pStmt: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_stmt_scanstatus")
def Pyi_sqlite3_stmt_scanstatus(pStmt: Pointer[Pyi_sqlite3_stmt], idx: int, iScanStatusOp: int, pOut: uintptr) -> int:
  ...

@native
@native_name("sqlite3_stmt_scanstatus_reset")
def Pyi_sqlite3_stmt_scanstatus_reset(arg0: Pointer[Pyi_sqlite3_stmt]) -> None:
  ...

@native
@native_name("sqlite3_stmt_scanstatus_v2")
def Pyi_sqlite3_stmt_scanstatus_v2(pStmt: Pointer[Pyi_sqlite3_stmt], idx: int, iScanStatusOp: int, flags: int, pOut: uintptr) -> int:
  ...

@native
@native_name("sqlite3_stmt_status")
def Pyi_sqlite3_stmt_status(arg0: Pointer[Pyi_sqlite3_stmt], op: int, resetFlg: int) -> int:
  ...

@native
@native_name("sqlite3_str_append")
def Pyi_sqlite3_str_append(arg0: Pointer[Pyi_sqlite3_str], zIn: c_str, N: int) -> None:
  ...

@native
@native_name("sqlite3_str_appendall")
def Pyi_sqlite3_str_appendall(arg0: Pointer[Pyi_sqlite3_str], zIn: c_str) -> None:
  ...

@native
@native_name("sqlite3_str_appendchar")
def Pyi_sqlite3_str_appendchar(arg0: Pointer[Pyi_sqlite3_str], N: int, C: int) -> None:
  ...

@native
@native_name("sqlite3_str_appendf")
def Pyi_sqlite3_str_appendf(arg0: Pointer[Pyi_sqlite3_str], zFormat: c_str) -> None:
  ...

@native
@native_name("sqlite3_str_errcode")
def Pyi_sqlite3_str_errcode(arg0: Pointer[Pyi_sqlite3_str]) -> int:
  ...

@native
@native_name("sqlite3_str_finish")
def Pyi_sqlite3_str_finish(arg0: Pointer[Pyi_sqlite3_str]) -> c_str:
  ...

@native
@native_name("sqlite3_str_free")
def Pyi_sqlite3_str_free(arg0: Pointer[Pyi_sqlite3_str]) -> None:
  ...

@native
@native_name("sqlite3_str_length")
def Pyi_sqlite3_str_length(arg0: Pointer[Pyi_sqlite3_str]) -> int:
  ...

@native
@native_name("sqlite3_str_new")
def Pyi_sqlite3_str_new(arg0: Pointer[Pyi_sqlite3]) -> Pointer[Pyi_sqlite3_str]:
  ...

@native
@native_name("sqlite3_str_reset")
def Pyi_sqlite3_str_reset(arg0: Pointer[Pyi_sqlite3_str]) -> None:
  ...

@native
@native_name("sqlite3_str_truncate")
def Pyi_sqlite3_str_truncate(arg0: Pointer[Pyi_sqlite3_str], N: int) -> None:
  ...

@native
@native_name("sqlite3_str_value")
def Pyi_sqlite3_str_value(arg0: Pointer[Pyi_sqlite3_str]) -> c_str:
  ...

@native
@native_name("sqlite3_str_vappendf")
def Pyi_sqlite3_str_vappendf(arg0: Pointer[Pyi_sqlite3_str], zFormat: c_str, arg2: c_str) -> None:
  ...

@native
@native_name("sqlite3_strglob")
def Pyi_sqlite3_strglob(zGlob: c_str, zStr: c_str) -> int:
  ...

@native
@native_name("sqlite3_stricmp")
def Pyi_sqlite3_stricmp(arg0: c_str, arg1: c_str) -> int:
  ...

@native
@native_name("sqlite3_strlike")
def Pyi_sqlite3_strlike(zGlob: c_str, zStr: c_str, cEsc: uint) -> int:
  ...

@native
@native_name("sqlite3_strnicmp")
def Pyi_sqlite3_strnicmp(arg0: c_str, arg1: c_str, arg2: int) -> int:
  ...

@native
@native_name("sqlite3_system_errno")
def Pyi_sqlite3_system_errno(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_table_column_metadata")
def Pyi_sqlite3_table_column_metadata(db: Pointer[Pyi_sqlite3], zDbName: c_str, zTableName: c_str, zColumnName: c_str, pzDataType: Pointer[c_str], pzCollSeq: Pointer[c_str], pNotNull: Pointer[int], pPrimaryKey: Pointer[int], pAutoinc: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_test_control")
def Pyi_sqlite3_test_control(op: int) -> int:
  ...

@native
@native_name("sqlite3_thread_cleanup")
def Pyi_sqlite3_thread_cleanup() -> None:
  ...

@native
@native_name("sqlite3_threadsafe")
def Pyi_sqlite3_threadsafe() -> int:
  ...

@native
@native_name("sqlite3_total_changes")
def Pyi_sqlite3_total_changes(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_total_changes64")
def Pyi_sqlite3_total_changes64(arg0: Pointer[Pyi_sqlite3]) -> int64:
  ...

@native
@native_name("sqlite3_trace")
def Pyi_sqlite3_trace(arg0: Pointer[Pyi_sqlite3], xTrace: Function[[uintptr, c_str], None], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_trace_v2")
def Pyi_sqlite3_trace_v2(arg0: Pointer[Pyi_sqlite3], uMask: uint, xCallback: Function[[uint, uintptr, uintptr, uintptr], int], pCtx: uintptr) -> int:
  ...

@native
@native_name("sqlite3_transfer_bindings")
def Pyi_sqlite3_transfer_bindings(arg0: Pointer[Pyi_sqlite3_stmt], arg1: Pointer[Pyi_sqlite3_stmt]) -> int:
  ...

@native
@native_name("sqlite3_txn_state")
def Pyi_sqlite3_txn_state(arg0: Pointer[Pyi_sqlite3], zSchema: c_str) -> int:
  ...

@native
@native_name("sqlite3_unlock_notify")
def Pyi_sqlite3_unlock_notify(pBlocked: Pointer[Pyi_sqlite3], xNotify: Function[[Pointer[uintptr], int], None], pNotifyArg: uintptr) -> int:
  ...

@native
@native_name("sqlite3_update_hook")
def Pyi_sqlite3_update_hook(arg0: Pointer[Pyi_sqlite3], arg1: Function[[uintptr, int, c_str, c_str, int64], None], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_uri_boolean")
def Pyi_sqlite3_uri_boolean(z: c_str, zParam: c_str, bDefault: int) -> int:
  ...

@native
@native_name("sqlite3_uri_int64")
def Pyi_sqlite3_uri_int64(arg0: c_str, arg1: c_str, arg2: int64) -> int64:
  ...

@native
@native_name("sqlite3_uri_key")
def Pyi_sqlite3_uri_key(z: c_str, N: int) -> c_str:
  ...

@native
@native_name("sqlite3_uri_parameter")
def Pyi_sqlite3_uri_parameter(z: c_str, zParam: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_user_data")
def Pyi_sqlite3_user_data(arg0: Pointer[Pyi_sqlite3_context]) -> uintptr:
  ...

@native
@native_name("sqlite3_value_blob")
def Pyi_sqlite3_value_blob(arg0: Pointer[Pyi_sqlite3_value]) -> uintptr:
  ...

@native
@native_name("sqlite3_value_bytes")
def Pyi_sqlite3_value_bytes(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_bytes16")
def Pyi_sqlite3_value_bytes16(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_double")
def Pyi_sqlite3_value_double(arg0: Pointer[Pyi_sqlite3_value]) -> float64:
  ...

@native
@native_name("sqlite3_value_dup")
def Pyi_sqlite3_value_dup(arg0: Pointer[Pyi_sqlite3_value]) -> Pointer[Pyi_sqlite3_value]:
  ...

@native
@native_name("sqlite3_value_encoding")
def Pyi_sqlite3_value_encoding(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_free")
def Pyi_sqlite3_value_free(arg0: Pointer[Pyi_sqlite3_value]) -> None:
  ...

@native
@native_name("sqlite3_value_frombind")
def Pyi_sqlite3_value_frombind(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_int")
def Pyi_sqlite3_value_int(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_int64")
def Pyi_sqlite3_value_int64(arg0: Pointer[Pyi_sqlite3_value]) -> int64:
  ...

@native
@native_name("sqlite3_value_nochange")
def Pyi_sqlite3_value_nochange(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_numeric_type")
def Pyi_sqlite3_value_numeric_type(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_value_pointer")
def Pyi_sqlite3_value_pointer(arg0: Pointer[Pyi_sqlite3_value], arg1: c_str) -> uintptr:
  ...

@native
@native_name("sqlite3_value_subtype")
def Pyi_sqlite3_value_subtype(arg0: Pointer[Pyi_sqlite3_value]) -> uint:
  ...

@native
@native_name("sqlite3_value_text")
def Pyi_sqlite3_value_text(arg0: Pointer[Pyi_sqlite3_value]) -> c_str:
  ...

@native
@native_name("sqlite3_value_text16")
def Pyi_sqlite3_value_text16(arg0: Pointer[Pyi_sqlite3_value]) -> uintptr:
  ...

@native
@native_name("sqlite3_value_text16be")
def Pyi_sqlite3_value_text16be(arg0: Pointer[Pyi_sqlite3_value]) -> uintptr:
  ...

@native
@native_name("sqlite3_value_text16le")
def Pyi_sqlite3_value_text16le(arg0: Pointer[Pyi_sqlite3_value]) -> uintptr:
  ...

@native
@native_name("sqlite3_value_type")
def Pyi_sqlite3_value_type(arg0: Pointer[Pyi_sqlite3_value]) -> int:
  ...

@native
@native_name("sqlite3_vfs_find")
def Pyi_sqlite3_vfs_find(zVfsName: c_str) -> Pointer[Pyi_sqlite3_vfs]:
  ...

@native
@native_name("sqlite3_vfs_register")
def Pyi_sqlite3_vfs_register(arg0: Pointer[Pyi_sqlite3_vfs], makeDflt: int) -> int:
  ...

@native
@native_name("sqlite3_vfs_unregister")
def Pyi_sqlite3_vfs_unregister(arg0: Pointer[Pyi_sqlite3_vfs]) -> int:
  ...

@native
@native_name("sqlite3_vmprintf")
def Pyi_sqlite3_vmprintf(arg0: c_str, arg1: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_vsnprintf")
def Pyi_sqlite3_vsnprintf(arg0: int, arg1: c_str, arg2: c_str, arg3: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_vtab_collation")
def Pyi_sqlite3_vtab_collation(arg0: Pointer[Pyi_sqlite3_index_info], arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_vtab_config")
def Pyi_sqlite3_vtab_config(arg0: Pointer[Pyi_sqlite3], op: int) -> int:
  ...

@native
@native_name("sqlite3_vtab_distinct")
def Pyi_sqlite3_vtab_distinct(arg0: Pointer[Pyi_sqlite3_index_info]) -> int:
  ...

@native
@native_name("sqlite3_vtab_in")
def Pyi_sqlite3_vtab_in(arg0: Pointer[Pyi_sqlite3_index_info], iCons: int, bHandle: int) -> int:
  ...

@native
@native_name("sqlite3_vtab_in_first")
def Pyi_sqlite3_vtab_in_first(pVal: Pointer[Pyi_sqlite3_value], ppOut: Pointer[Pointer[Pyi_sqlite3_value]]) -> int:
  ...

@native
@native_name("sqlite3_vtab_in_next")
def Pyi_sqlite3_vtab_in_next(pVal: Pointer[Pyi_sqlite3_value], ppOut: Pointer[Pointer[Pyi_sqlite3_value]]) -> int:
  ...

@native
@native_name("sqlite3_vtab_nochange")
def Pyi_sqlite3_vtab_nochange(arg0: Pointer[Pyi_sqlite3_context]) -> int:
  ...

@native
@native_name("sqlite3_vtab_on_conflict")
def Pyi_sqlite3_vtab_on_conflict(arg0: Pointer[Pyi_sqlite3]) -> int:
  ...

@native
@native_name("sqlite3_vtab_rhs_value")
def Pyi_sqlite3_vtab_rhs_value(arg0: Pointer[Pyi_sqlite3_index_info], arg1: int, ppVal: Pointer[Pointer[Pyi_sqlite3_value]]) -> int:
  ...

@native
@native_name("sqlite3_wal_autocheckpoint")
def Pyi_sqlite3_wal_autocheckpoint(db: Pointer[Pyi_sqlite3], N: int) -> int:
  ...

@native
@native_name("sqlite3_wal_checkpoint")
def Pyi_sqlite3_wal_checkpoint(db: Pointer[Pyi_sqlite3], zDb: c_str) -> int:
  ...

@native
@native_name("sqlite3_wal_checkpoint_v2")
def Pyi_sqlite3_wal_checkpoint_v2(db: Pointer[Pyi_sqlite3], zDb: c_str, eMode: int, pnLog: Pointer[int], pnCkpt: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_wal_hook")
def Pyi_sqlite3_wal_hook(arg0: Pointer[Pyi_sqlite3], arg1: Function[[uintptr, Pointer[Pyi_sqlite3], c_str, int], int], arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_win32_set_directory")
def Pyi_sqlite3_win32_set_directory(type: uint, zValue: uintptr) -> int:
  ...

@native
@native_name("sqlite3_win32_set_directory16")
def Pyi_sqlite3_win32_set_directory16(type: uint, zValue: uintptr) -> int:
  ...

@native
@native_name("sqlite3_win32_set_directory8")
def Pyi_sqlite3_win32_set_directory8(type: uint, zValue: c_str) -> int:
  ...

# stats: structs=35 enums=0 aliases=0 consts=413 funcs=298
