# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/sqlite/sqlite3.h
# Generated: 2026-07-20 01:37:39
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Opaque handles (incomplete struct → *_h alias = uint64; C tag in comment)
# ---------------------------------------------------------------------------

type Fts5Context_h = uint64  # C: Fts5Context
type Fts5Tokenizer_h = uint64  # C: Fts5Tokenizer
type sqlite3_h = uint64  # C: sqlite3
type sqlite3_api_routines_h = uint64  # C: sqlite3_api_routines
type sqlite3_backup_h = uint64  # C: sqlite3_backup
type sqlite3_blob_h = uint64  # C: sqlite3_blob
type sqlite3_context_h = uint64  # C: sqlite3_context
type sqlite3_file_h = uint64  # C: sqlite3_file
type sqlite3_index_info_h = uint64  # C: sqlite3_index_info
type sqlite3_module_h = uint64  # C: sqlite3_module
type sqlite3_mutex_h = uint64  # C: sqlite3_mutex
type sqlite3_pcache_h = uint64  # C: sqlite3_pcache
type sqlite3_snapshot_h = uint64  # C: sqlite3_snapshot
type sqlite3_stmt_h = uint64  # C: sqlite3_stmt
type sqlite3_str_h = uint64  # C: sqlite3_str
type sqlite3_value_h = uint64  # C: sqlite3_value
type sqlite3_vfs_h = uint64  # C: sqlite3_vfs

# ---------------------------------------------------------------------------
# Constants (#define)
# ---------------------------------------------------------------------------

SQLITE_ABORT: int = 4
SQLITE_ACCESS_EXISTS: int = 0
SQLITE_ACCESS_READ: int = 2
SQLITE_ACCESS_READWRITE: int = 1
SQLITE_ALTER_TABLE: int = 26
SQLITE_ANALYZE: int = 28
SQLITE_ANY: int = 5
SQLITE_ATTACH: int = 24
SQLITE_AUTH: int = 23
SQLITE_BLOB: int = 4
SQLITE_BUSY: int = 5
SQLITE_CANTOPEN: int = 14
SQLITE_CARRAY_BLOB: int = 4
SQLITE_CARRAY_DOUBLE: int = 2
SQLITE_CARRAY_INT32: int = 0
SQLITE_CARRAY_INT64: int = 1
SQLITE_CARRAY_TEXT: int = 3
SQLITE_CHECKPOINT_FULL: int = 1
SQLITE_CHECKPOINT_NOOP: int = -1
SQLITE_CHECKPOINT_PASSIVE: int = 0
SQLITE_CHECKPOINT_RESTART: int = 2
SQLITE_CHECKPOINT_TRUNCATE: int = 3
SQLITE_CONFIG_COVERING_INDEX_SCAN: int = 20
SQLITE_CONFIG_GETMALLOC: int = 5
SQLITE_CONFIG_GETMUTEX: int = 11
SQLITE_CONFIG_GETPCACHE: int = 15
SQLITE_CONFIG_GETPCACHE2: int = 19
SQLITE_CONFIG_HEAP: int = 8
SQLITE_CONFIG_LOG: int = 16
SQLITE_CONFIG_LOOKASIDE: int = 13
SQLITE_CONFIG_MALLOC: int = 4
SQLITE_CONFIG_MEMDB_MAXSIZE: int = 29
SQLITE_CONFIG_MEMSTATUS: int = 9
SQLITE_CONFIG_MMAP_SIZE: int = 22
SQLITE_CONFIG_MULTITHREAD: int = 2
SQLITE_CONFIG_MUTEX: int = 10
SQLITE_CONFIG_PAGECACHE: int = 7
SQLITE_CONFIG_PCACHE: int = 14
SQLITE_CONFIG_PCACHE2: int = 18
SQLITE_CONFIG_PCACHE_HDRSZ: int = 24
SQLITE_CONFIG_PMASZ: int = 25
SQLITE_CONFIG_ROWID_IN_VIEW: int = 30
SQLITE_CONFIG_SCRATCH: int = 6
SQLITE_CONFIG_SERIALIZED: int = 3
SQLITE_CONFIG_SINGLETHREAD: int = 1
SQLITE_CONFIG_SMALL_MALLOC: int = 27
SQLITE_CONFIG_SORTERREF_SIZE: int = 28
SQLITE_CONFIG_SQLLOG: int = 21
SQLITE_CONFIG_STMTJRNL_SPILL: int = 26
SQLITE_CONFIG_URI: int = 17
SQLITE_CONFIG_WIN32_HEAPSIZE: int = 23
SQLITE_CONSTRAINT: int = 19
SQLITE_COPY: int = 0
SQLITE_CORRUPT: int = 11
SQLITE_CREATE_INDEX: int = 1
SQLITE_CREATE_TABLE: int = 2
SQLITE_CREATE_TEMP_INDEX: int = 3
SQLITE_CREATE_TEMP_TABLE: int = 4
SQLITE_CREATE_TEMP_TRIGGER: int = 5
SQLITE_CREATE_TEMP_VIEW: int = 6
SQLITE_CREATE_TRIGGER: int = 7
SQLITE_CREATE_VIEW: int = 8
SQLITE_CREATE_VTABLE: int = 29
SQLITE_DBCONFIG_DEFENSIVE: int = 1010
SQLITE_DBCONFIG_DQS_DDL: int = 1014
SQLITE_DBCONFIG_DQS_DML: int = 1013
SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE: int = 1020
SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE: int = 1021
SQLITE_DBCONFIG_ENABLE_COMMENTS: int = 1022
SQLITE_DBCONFIG_ENABLE_FKEY: int = 1002
SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER: int = 1004
SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION: int = 1005
SQLITE_DBCONFIG_ENABLE_QPSG: int = 1007
SQLITE_DBCONFIG_ENABLE_TRIGGER: int = 1003
SQLITE_DBCONFIG_ENABLE_VIEW: int = 1015
SQLITE_DBCONFIG_FP_DIGITS: int = 1023
SQLITE_DBCONFIG_LEGACY_ALTER_TABLE: int = 1012
SQLITE_DBCONFIG_LEGACY_FILE_FORMAT: int = 1016
SQLITE_DBCONFIG_LOOKASIDE: int = 1001
SQLITE_DBCONFIG_MAINDBNAME: int = 1000
SQLITE_DBCONFIG_MAX: int = 1023
SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE: int = 1006
SQLITE_DBCONFIG_RESET_DATABASE: int = 1009
SQLITE_DBCONFIG_REVERSE_SCANORDER: int = 1019
SQLITE_DBCONFIG_STMT_SCANSTATUS: int = 1018
SQLITE_DBCONFIG_TRIGGER_EQP: int = 1008
SQLITE_DBCONFIG_TRUSTED_SCHEMA: int = 1017
SQLITE_DBCONFIG_WRITABLE_SCHEMA: int = 1011
SQLITE_DBSTATUS_CACHE_HIT: int = 7
SQLITE_DBSTATUS_CACHE_MISS: int = 8
SQLITE_DBSTATUS_CACHE_SPILL: int = 12
SQLITE_DBSTATUS_CACHE_USED: int = 1
SQLITE_DBSTATUS_CACHE_USED_SHARED: int = 11
SQLITE_DBSTATUS_CACHE_WRITE: int = 9
SQLITE_DBSTATUS_DEFERRED_FKS: int = 10
SQLITE_DBSTATUS_LOOKASIDE_HIT: int = 4
SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL: int = 6
SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE: int = 5
SQLITE_DBSTATUS_LOOKASIDE_USED: int = 0
SQLITE_DBSTATUS_MAX: int = 13
SQLITE_DBSTATUS_SCHEMA_USED: int = 2
SQLITE_DBSTATUS_STMT_USED: int = 3
SQLITE_DBSTATUS_TEMPBUF_SPILL: int = 13
SQLITE_DELETE: int = 9
SQLITE_DENY: int = 1
SQLITE_DESERIALIZE_FREEONCLOSE: int = 1
SQLITE_DESERIALIZE_READONLY: int = 4
SQLITE_DESERIALIZE_RESIZEABLE: int = 2
SQLITE_DETACH: int = 25
SQLITE_DETERMINISTIC: int = 0x000000800
SQLITE_DIRECTONLY: int = 0x000080000
SQLITE_DONE: int = 101
SQLITE_DROP_INDEX: int = 10
SQLITE_DROP_TABLE: int = 11
SQLITE_DROP_TEMP_INDEX: int = 12
SQLITE_DROP_TEMP_TABLE: int = 13
SQLITE_DROP_TEMP_TRIGGER: int = 14
SQLITE_DROP_TEMP_VIEW: int = 15
SQLITE_DROP_TRIGGER: int = 16
SQLITE_DROP_VIEW: int = 17
SQLITE_DROP_VTABLE: int = 30
SQLITE_EMPTY: int = 16
SQLITE_ERROR: int = 1
SQLITE_FAIL: int = 3
SQLITE_FCNTL_BEGIN_ATOMIC_WRITE: int = 31
SQLITE_FCNTL_BLOCK_ON_CONNECT: int = 44
SQLITE_FCNTL_BUSYHANDLER: int = 15
SQLITE_FCNTL_CHUNK_SIZE: int = 6
SQLITE_FCNTL_CKPT_DONE: int = 37
SQLITE_FCNTL_CKPT_START: int = 39
SQLITE_FCNTL_CKSM_FILE: int = 41
SQLITE_FCNTL_COMMIT_ATOMIC_WRITE: int = 32
SQLITE_FCNTL_COMMIT_PHASETWO: int = 22
SQLITE_FCNTL_DATA_VERSION: int = 35
SQLITE_FCNTL_EXTERNAL_READER: int = 40
SQLITE_FCNTL_FILESTAT: int = 45
SQLITE_FCNTL_FILE_POINTER: int = 7
SQLITE_FCNTL_GET_LOCKPROXYFILE: int = 2
SQLITE_FCNTL_HAS_MOVED: int = 20
SQLITE_FCNTL_JOURNAL_POINTER: int = 28
SQLITE_FCNTL_LAST_ERRNO: int = 4
SQLITE_FCNTL_LOCKSTATE: int = 1
SQLITE_FCNTL_LOCK_TIMEOUT: int = 34
SQLITE_FCNTL_MMAP_SIZE: int = 18
SQLITE_FCNTL_NULL_IO: int = 43
SQLITE_FCNTL_OVERWRITE: int = 11
SQLITE_FCNTL_PDB: int = 30
SQLITE_FCNTL_PERSIST_WAL: int = 10
SQLITE_FCNTL_POWERSAFE_OVERWRITE: int = 13
SQLITE_FCNTL_PRAGMA: int = 14
SQLITE_FCNTL_RBU: int = 26
SQLITE_FCNTL_RESERVE_BYTES: int = 38
SQLITE_FCNTL_RESET_CACHE: int = 42
SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE: int = 33
SQLITE_FCNTL_SET_LOCKPROXYFILE: int = 3
SQLITE_FCNTL_SIZE_HINT: int = 5
SQLITE_FCNTL_SIZE_LIMIT: int = 36
SQLITE_FCNTL_SYNC: int = 21
SQLITE_FCNTL_SYNC_OMITTED: int = 8
SQLITE_FCNTL_TEMPFILENAME: int = 16
SQLITE_FCNTL_TRACE: int = 19
SQLITE_FCNTL_VFSNAME: int = 12
SQLITE_FCNTL_VFS_POINTER: int = 27
SQLITE_FCNTL_WAL_BLOCK: int = 24
SQLITE_FCNTL_WIN32_AV_RETRY: int = 9
SQLITE_FCNTL_WIN32_GET_HANDLE: int = 29
SQLITE_FCNTL_WIN32_SET_HANDLE: int = 23
SQLITE_FCNTL_ZIPVFS: int = 25
SQLITE_FLOAT: int = 2
SQLITE_FORMAT: int = 24
SQLITE_FULL: int = 13
SQLITE_FUNCTION: int = 31
SQLITE_IGNORE: int = 2
SQLITE_INDEX_CONSTRAINT_EQ: int = 2
SQLITE_INDEX_CONSTRAINT_FUNCTION: int = 150
SQLITE_INDEX_CONSTRAINT_GE: int = 32
SQLITE_INDEX_CONSTRAINT_GLOB: int = 66
SQLITE_INDEX_CONSTRAINT_GT: int = 4
SQLITE_INDEX_CONSTRAINT_IS: int = 72
SQLITE_INDEX_CONSTRAINT_ISNOT: int = 69
SQLITE_INDEX_CONSTRAINT_ISNOTNULL: int = 70
SQLITE_INDEX_CONSTRAINT_ISNULL: int = 71
SQLITE_INDEX_CONSTRAINT_LE: int = 8
SQLITE_INDEX_CONSTRAINT_LIKE: int = 65
SQLITE_INDEX_CONSTRAINT_LIMIT: int = 73
SQLITE_INDEX_CONSTRAINT_LT: int = 16
SQLITE_INDEX_CONSTRAINT_MATCH: int = 64
SQLITE_INDEX_CONSTRAINT_NE: int = 68
SQLITE_INDEX_CONSTRAINT_OFFSET: int = 74
SQLITE_INDEX_CONSTRAINT_REGEXP: int = 67
SQLITE_INDEX_SCAN_HEX: int = 0x00000002
SQLITE_INDEX_SCAN_UNIQUE: int = 0x00000001
SQLITE_INNOCUOUS: int = 0x000200000
SQLITE_INSERT: int = 18
SQLITE_INTEGER: int = 1
SQLITE_INTERNAL: int = 2
SQLITE_INTERRUPT: int = 9
SQLITE_IOCAP_ATOMIC: int = 0x00000001
SQLITE_IOCAP_ATOMIC16K: int = 0x00000040
SQLITE_IOCAP_ATOMIC1K: int = 0x00000004
SQLITE_IOCAP_ATOMIC2K: int = 0x00000008
SQLITE_IOCAP_ATOMIC32K: int = 0x00000080
SQLITE_IOCAP_ATOMIC4K: int = 0x00000010
SQLITE_IOCAP_ATOMIC512: int = 0x00000002
SQLITE_IOCAP_ATOMIC64K: int = 0x00000100
SQLITE_IOCAP_ATOMIC8K: int = 0x00000020
SQLITE_IOCAP_BATCH_ATOMIC: int = 0x00004000
SQLITE_IOCAP_IMMUTABLE: int = 0x00002000
SQLITE_IOCAP_POWERSAFE_OVERWRITE: int = 0x00001000
SQLITE_IOCAP_SAFE_APPEND: int = 0x00000200
SQLITE_IOCAP_SEQUENTIAL: int = 0x00000400
SQLITE_IOCAP_SUBPAGE_READ: int = 0x00008000
SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN: int = 0x00000800
SQLITE_IOERR: int = 10
SQLITE_LIMIT_ATTACHED: int = 7
SQLITE_LIMIT_COLUMN: int = 2
SQLITE_LIMIT_COMPOUND_SELECT: int = 4
SQLITE_LIMIT_EXPR_DEPTH: int = 3
SQLITE_LIMIT_FUNCTION_ARG: int = 6
SQLITE_LIMIT_LENGTH: int = 0
SQLITE_LIMIT_LIKE_PATTERN_LENGTH: int = 8
SQLITE_LIMIT_PARSER_DEPTH: int = 12
SQLITE_LIMIT_SQL_LENGTH: int = 1
SQLITE_LIMIT_TRIGGER_DEPTH: int = 10
SQLITE_LIMIT_VARIABLE_NUMBER: int = 9
SQLITE_LIMIT_VDBE_OP: int = 5
SQLITE_LIMIT_WORKER_THREADS: int = 11
SQLITE_LOCKED: int = 6
SQLITE_LOCK_EXCLUSIVE: int = 4
SQLITE_LOCK_NONE: int = 0
SQLITE_LOCK_PENDING: int = 3
SQLITE_LOCK_RESERVED: int = 2
SQLITE_LOCK_SHARED: int = 1
SQLITE_MISMATCH: int = 20
SQLITE_MISUSE: int = 21
SQLITE_MUTEX_FAST: int = 0
SQLITE_MUTEX_RECURSIVE: int = 1
SQLITE_MUTEX_STATIC_APP1: int = 8
SQLITE_MUTEX_STATIC_APP2: int = 9
SQLITE_MUTEX_STATIC_APP3: int = 10
SQLITE_MUTEX_STATIC_LRU: int = 6
SQLITE_MUTEX_STATIC_LRU2: int = 7
SQLITE_MUTEX_STATIC_MAIN: int = 2
SQLITE_MUTEX_STATIC_MASTER: int = 2
SQLITE_MUTEX_STATIC_MEM: int = 3
SQLITE_MUTEX_STATIC_MEM2: int = 4
SQLITE_MUTEX_STATIC_OPEN: int = 4
SQLITE_MUTEX_STATIC_PMEM: int = 7
SQLITE_MUTEX_STATIC_PRNG: int = 5
SQLITE_MUTEX_STATIC_VFS1: int = 11
SQLITE_MUTEX_STATIC_VFS2: int = 12
SQLITE_MUTEX_STATIC_VFS3: int = 13
SQLITE_NOLFS: int = 22
SQLITE_NOMEM: int = 7
SQLITE_NOTADB: int = 26
SQLITE_NOTFOUND: int = 12
SQLITE_NOTICE: int = 27
SQLITE_NULL: int = 5
SQLITE_OK: int = 0
SQLITE_OPEN_AUTOPROXY: int = 0x00000020
SQLITE_OPEN_CREATE: int = 0x00000004
SQLITE_OPEN_DELETEONCLOSE: int = 0x00000008
SQLITE_OPEN_EXCLUSIVE: int = 0x00000010
SQLITE_OPEN_EXRESCODE: int = 0x02000000
SQLITE_OPEN_FULLMUTEX: int = 0x00010000
SQLITE_OPEN_MAIN_DB: int = 0x00000100
SQLITE_OPEN_MAIN_JOURNAL: int = 0x00000800
SQLITE_OPEN_MASTER_JOURNAL: int = 0x00004000
SQLITE_OPEN_MEMORY: int = 0x00000080
SQLITE_OPEN_NOFOLLOW: int = 0x01000000
SQLITE_OPEN_NOMUTEX: int = 0x00008000
SQLITE_OPEN_PRIVATECACHE: int = 0x00040000
SQLITE_OPEN_READONLY: int = 0x00000001
SQLITE_OPEN_READWRITE: int = 0x00000002
SQLITE_OPEN_SHAREDCACHE: int = 0x00020000
SQLITE_OPEN_SUBJOURNAL: int = 0x00002000
SQLITE_OPEN_SUPER_JOURNAL: int = 0x00004000
SQLITE_OPEN_TEMP_DB: int = 0x00000200
SQLITE_OPEN_TEMP_JOURNAL: int = 0x00001000
SQLITE_OPEN_TRANSIENT_DB: int = 0x00000400
SQLITE_OPEN_URI: int = 0x00000040
SQLITE_OPEN_WAL: int = 0x00080000
SQLITE_PERM: int = 3
SQLITE_PRAGMA: int = 19
SQLITE_PREPARE_DONT_LOG: int = 0x10
SQLITE_PREPARE_FROM_DDL: int = 0x20
SQLITE_PREPARE_NORMALIZE: int = 0x02
SQLITE_PREPARE_NO_VTAB: int = 0x04
SQLITE_PREPARE_PERSISTENT: int = 0x01
SQLITE_PROTOCOL: int = 15
SQLITE_RANGE: int = 25
SQLITE_READ: int = 20
SQLITE_READONLY: int = 8
SQLITE_RECURSIVE: int = 33
SQLITE_REINDEX: int = 27
SQLITE_REPLACE: int = 5
SQLITE_RESULT_SUBTYPE: int = 0x001000000
SQLITE_ROLLBACK: int = 1
SQLITE_ROW: int = 100
SQLITE_SAVEPOINT: int = 32
SQLITE_SCANSTAT_COMPLEX: int = 0x0001
SQLITE_SCANSTAT_EST: int = 2
SQLITE_SCANSTAT_EXPLAIN: int = 4
SQLITE_SCANSTAT_NAME: int = 3
SQLITE_SCANSTAT_NCYCLE: int = 7
SQLITE_SCANSTAT_NLOOP: int = 0
SQLITE_SCANSTAT_NVISIT: int = 1
SQLITE_SCANSTAT_PARENTID: int = 6
SQLITE_SCANSTAT_SELECTID: int = 5
SQLITE_SCHEMA: int = 17
SQLITE_SCM_BRANCH: str = "branch-3.53"
SQLITE_SCM_DATETIME: str = "2026-06-03T19:12:13.350Z"
SQLITE_SCM_TAGS: str = "release version-3.53.2"
SQLITE_SELECT: int = 21
SQLITE_SELFORDER1: int = 0x002000000
SQLITE_SERIALIZE_NOCOPY: int = 0x001
SQLITE_SETLK_BLOCK_ON_CONNECT: int = 0x01
SQLITE_SHM_EXCLUSIVE: int = 8
SQLITE_SHM_LOCK: int = 2
SQLITE_SHM_NLOCK: int = 8
SQLITE_SHM_SHARED: int = 4
SQLITE_SHM_UNLOCK: int = 1
SQLITE_SOURCE_ID: str = "2026-06-03 19:12:13 d6e03d8c777cfa2d35e3b60d8ec3e0187f3e9f99d8e2ee9cac695fd6fcdf1a24"
SQLITE_STATUS_MALLOC_COUNT: int = 9
SQLITE_STATUS_MALLOC_SIZE: int = 5
SQLITE_STATUS_MEMORY_USED: int = 0
SQLITE_STATUS_PAGECACHE_OVERFLOW: int = 2
SQLITE_STATUS_PAGECACHE_SIZE: int = 7
SQLITE_STATUS_PAGECACHE_USED: int = 1
SQLITE_STATUS_PARSER_STACK: int = 6
SQLITE_STATUS_SCRATCH_OVERFLOW: int = 4
SQLITE_STATUS_SCRATCH_SIZE: int = 8
SQLITE_STATUS_SCRATCH_USED: int = 3
SQLITE_STMTSTATUS_AUTOINDEX: int = 3
SQLITE_STMTSTATUS_FILTER_HIT: int = 8
SQLITE_STMTSTATUS_FILTER_MISS: int = 7
SQLITE_STMTSTATUS_FULLSCAN_STEP: int = 1
SQLITE_STMTSTATUS_MEMUSED: int = 99
SQLITE_STMTSTATUS_REPREPARE: int = 5
SQLITE_STMTSTATUS_RUN: int = 6
SQLITE_STMTSTATUS_SORT: int = 2
SQLITE_STMTSTATUS_VM_STEP: int = 4
SQLITE_SUBTYPE: int = 0x000100000
SQLITE_SYNC_DATAONLY: int = 0x00010
SQLITE_SYNC_FULL: int = 0x00003
SQLITE_SYNC_NORMAL: int = 0x00002
SQLITE_TESTCTRL_ALWAYS: int = 13
SQLITE_TESTCTRL_ASSERT: int = 12
SQLITE_TESTCTRL_ATOF: int = 34
SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS: int = 10
SQLITE_TESTCTRL_BITVEC_TEST: int = 8
SQLITE_TESTCTRL_BYTEORDER: int = 22
SQLITE_TESTCTRL_EXPLAIN_STMT: int = 19
SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS: int = 29
SQLITE_TESTCTRL_FAULT_INSTALL: int = 9
SQLITE_TESTCTRL_FIRST: int = 5
SQLITE_TESTCTRL_FK_NO_ACTION: int = 7
SQLITE_TESTCTRL_GETOPT: int = 16
SQLITE_TESTCTRL_IMPOSTER: int = 25
SQLITE_TESTCTRL_INTERNAL_FUNCTIONS: int = 17
SQLITE_TESTCTRL_ISINIT: int = 23
SQLITE_TESTCTRL_ISKEYWORD: int = 16
SQLITE_TESTCTRL_JSON_SELFCHECK: int = 14
SQLITE_TESTCTRL_LAST: int = 34
SQLITE_TESTCTRL_LOCALTIME_FAULT: int = 18
SQLITE_TESTCTRL_LOGEST: int = 33
SQLITE_TESTCTRL_NEVER_CORRUPT: int = 20
SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD: int = 19
SQLITE_TESTCTRL_OPTIMIZATIONS: int = 15
SQLITE_TESTCTRL_PARSER_COVERAGE: int = 26
SQLITE_TESTCTRL_PENDING_BYTE: int = 11
SQLITE_TESTCTRL_PRNG_RESET: int = 7
SQLITE_TESTCTRL_PRNG_RESTORE: int = 6
SQLITE_TESTCTRL_PRNG_SAVE: int = 5
SQLITE_TESTCTRL_PRNG_SEED: int = 28
SQLITE_TESTCTRL_RESERVE: int = 14
SQLITE_TESTCTRL_RESULT_INTREAL: int = 27
SQLITE_TESTCTRL_SCRATCHMALLOC: int = 17
SQLITE_TESTCTRL_SEEK_COUNT: int = 30
SQLITE_TESTCTRL_SORTER_MMAP: int = 24
SQLITE_TESTCTRL_TRACEFLAGS: int = 31
SQLITE_TESTCTRL_TUNE: int = 32
SQLITE_TESTCTRL_USELONGDOUBLE: int = 34
SQLITE_TESTCTRL_VDBE_COVERAGE: int = 21
SQLITE_TEXT: int = 3
SQLITE_TOOBIG: int = 18
SQLITE_TRACE_CLOSE: int = 0x08
SQLITE_TRACE_PROFILE: int = 0x02
SQLITE_TRACE_ROW: int = 0x04
SQLITE_TRACE_STMT: int = 0x01
SQLITE_TRANSACTION: int = 22
SQLITE_TXN_NONE: int = 0
SQLITE_TXN_READ: int = 1
SQLITE_TXN_WRITE: int = 2
SQLITE_UPDATE: int = 23
SQLITE_UTF16: int = 4
SQLITE_UTF16BE: int = 3
SQLITE_UTF16LE: int = 2
SQLITE_UTF16_ALIGNED: int = 8
SQLITE_UTF8: int = 1
SQLITE_UTF8_ZT: int = 16
SQLITE_VERSION: str = "3.53.2"
SQLITE_VERSION_NUMBER: int = 3053002
SQLITE_VTAB_CONSTRAINT_SUPPORT: int = 1
SQLITE_VTAB_DIRECTONLY: int = 3
SQLITE_VTAB_INNOCUOUS: int = 2
SQLITE_VTAB_USES_ALL_SCHEMAS: int = 4
SQLITE_WARNING: int = 28
SQLITE_WIN32_DATA_DIRECTORY_TYPE: int = 1
SQLITE_WIN32_TEMP_DIRECTORY_TYPE: int = 2

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("sqlite3_aggregate_context")
def sqlite3_aggregate_context(arg0: sqlite3_context_h, nBytes: int) -> uintptr:
  ...

@native
@native_name("sqlite3_aggregate_count")
def sqlite3_aggregate_count(arg0: sqlite3_context_h) -> int:
  ...

@native
@native_name("sqlite3_auto_extension")
def sqlite3_auto_extension(xEntryPoint: uintptr) -> int:
  ...

@native
@native_name("sqlite3_autovacuum_pages")
def sqlite3_autovacuum_pages(db: sqlite3_h, arg1: uintptr, arg2: uintptr, arg3: uintptr) -> int:
  ...

@native
@native_name("sqlite3_backup_finish")
def sqlite3_backup_finish(p: sqlite3_backup_h) -> int:
  ...

@native
@native_name("sqlite3_backup_init")
def sqlite3_backup_init(pDest: sqlite3_h, zDestName: c_str, pSource: sqlite3_h, zSourceName: c_str) -> sqlite3_backup_h:
  ...

@native
@native_name("sqlite3_backup_pagecount")
def sqlite3_backup_pagecount(p: sqlite3_backup_h) -> int:
  ...

@native
@native_name("sqlite3_backup_remaining")
def sqlite3_backup_remaining(p: sqlite3_backup_h) -> int:
  ...

@native
@native_name("sqlite3_backup_step")
def sqlite3_backup_step(p: sqlite3_backup_h, nPage: int) -> int:
  ...

@native
@native_name("sqlite3_bind_blob")
def sqlite3_bind_blob(arg0: sqlite3_stmt_h, arg1: int, arg2: uintptr, n: int, arg4: uintptr) -> int:
  ...

@native
@native_name("sqlite3_bind_blob64")
def sqlite3_bind_blob64(arg0: sqlite3_stmt_h, arg1: int, arg2: uintptr, arg3: uint64, arg4: uintptr) -> int:
  ...

@native
@native_name("sqlite3_bind_double")
def sqlite3_bind_double(arg0: sqlite3_stmt_h, arg1: int, arg2: float64) -> int:
  ...

@native
@native_name("sqlite3_bind_int")
def sqlite3_bind_int(arg0: sqlite3_stmt_h, arg1: int, arg2: int) -> int:
  ...

@native
@native_name("sqlite3_bind_int64")
def sqlite3_bind_int64(arg0: sqlite3_stmt_h, arg1: int, arg2: uint64) -> int:
  ...

@native
@native_name("sqlite3_bind_null")
def sqlite3_bind_null(arg0: sqlite3_stmt_h, arg1: int) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_count")
def sqlite3_bind_parameter_count(arg0: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_index")
def sqlite3_bind_parameter_index(arg0: sqlite3_stmt_h, zName: c_str) -> int:
  ...

@native
@native_name("sqlite3_bind_parameter_name")
def sqlite3_bind_parameter_name(arg0: sqlite3_stmt_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_bind_pointer")
def sqlite3_bind_pointer(arg0: sqlite3_stmt_h, arg1: int, arg2: uintptr, arg3: c_str, arg4: uintptr) -> int:
  ...

@native
@native_name("sqlite3_bind_text")
def sqlite3_bind_text(arg0: sqlite3_stmt_h, arg1: int, arg2: c_str, arg3: int, arg4: uintptr) -> int:
  ...

@native
@native_name("sqlite3_bind_text16")
def sqlite3_bind_text16(arg0: sqlite3_stmt_h, arg1: int, arg2: uintptr, arg3: int, arg4: uintptr) -> int:
  ...

@native
@native_name("sqlite3_bind_text64")
def sqlite3_bind_text64(arg0: sqlite3_stmt_h, arg1: int, arg2: c_str, arg3: uint64, arg4: uintptr, encoding: int) -> int:
  ...

@native
@native_name("sqlite3_bind_value")
def sqlite3_bind_value(arg0: sqlite3_stmt_h, arg1: int, arg2: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_bind_zeroblob")
def sqlite3_bind_zeroblob(arg0: sqlite3_stmt_h, arg1: int, n: int) -> int:
  ...

@native
@native_name("sqlite3_bind_zeroblob64")
def sqlite3_bind_zeroblob64(arg0: sqlite3_stmt_h, arg1: int, arg2: uint64) -> int:
  ...

@native
@native_name("sqlite3_blob_bytes")
def sqlite3_blob_bytes(arg0: sqlite3_blob_h) -> int:
  ...

@native
@native_name("sqlite3_blob_close")
def sqlite3_blob_close(arg0: sqlite3_blob_h) -> int:
  ...

@native
@native_name("sqlite3_blob_open")
def sqlite3_blob_open(arg0: sqlite3_h, zDb: c_str, zTable: c_str, zColumn: c_str, iRow: uint64, flags: int, ppBlob: Pointer[sqlite3_blob_h]) -> int:
  ...

@native
@native_name("sqlite3_blob_read")
def sqlite3_blob_read(arg0: sqlite3_blob_h, Z: uintptr, N: int, iOffset: int) -> int:
  ...

@native
@native_name("sqlite3_blob_reopen")
def sqlite3_blob_reopen(arg0: sqlite3_blob_h, arg1: uint64) -> int:
  ...

@native
@native_name("sqlite3_blob_write")
def sqlite3_blob_write(arg0: sqlite3_blob_h, z: uintptr, n: int, iOffset: int) -> int:
  ...

@native
@native_name("sqlite3_busy_handler")
def sqlite3_busy_handler(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> int:
  ...

@native
@native_name("sqlite3_busy_timeout")
def sqlite3_busy_timeout(arg0: sqlite3_h, ms: int) -> int:
  ...

@native
@native_name("sqlite3_cancel_auto_extension")
def sqlite3_cancel_auto_extension(xEntryPoint: uintptr) -> int:
  ...

@native
@native_name("sqlite3_carray_bind")
def sqlite3_carray_bind(pStmt: sqlite3_stmt_h, i: int, aData: uintptr, nData: int, mFlags: int, xDel: uintptr) -> int:
  ...

@native
@native_name("sqlite3_carray_bind_v2")
def sqlite3_carray_bind_v2(pStmt: sqlite3_stmt_h, i: int, aData: uintptr, nData: int, mFlags: int, xDel: uintptr, pDel: uintptr) -> int:
  ...

@native
@native_name("sqlite3_changes")
def sqlite3_changes(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_changes64")
def sqlite3_changes64(arg0: sqlite3_h) -> uint64:  # record
  ...

@native
@native_name("sqlite3_clear_bindings")
def sqlite3_clear_bindings(arg0: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_close")
def sqlite3_close(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_close_v2")
def sqlite3_close_v2(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_collation_needed")
def sqlite3_collation_needed(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> int:
  ...

@native
@native_name("sqlite3_collation_needed16")
def sqlite3_collation_needed16(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> int:
  ...

@native
@native_name("sqlite3_column_blob")
def sqlite3_column_blob(arg0: sqlite3_stmt_h, iCol: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_bytes")
def sqlite3_column_bytes(arg0: sqlite3_stmt_h, iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_bytes16")
def sqlite3_column_bytes16(arg0: sqlite3_stmt_h, iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_count")
def sqlite3_column_count(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_column_database_name")
def sqlite3_column_database_name(arg0: sqlite3_stmt_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_database_name16")
def sqlite3_column_database_name16(arg0: sqlite3_stmt_h, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_decltype")
def sqlite3_column_decltype(arg0: sqlite3_stmt_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_decltype16")
def sqlite3_column_decltype16(arg0: sqlite3_stmt_h, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_double")
def sqlite3_column_double(arg0: sqlite3_stmt_h, iCol: int) -> float64:
  ...

@native
@native_name("sqlite3_column_int")
def sqlite3_column_int(arg0: sqlite3_stmt_h, iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_int64")
def sqlite3_column_int64(arg0: sqlite3_stmt_h, iCol: int) -> uint64:  # record
  ...

@native
@native_name("sqlite3_column_name")
def sqlite3_column_name(arg0: sqlite3_stmt_h, N: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_name16")
def sqlite3_column_name16(arg0: sqlite3_stmt_h, N: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_origin_name")
def sqlite3_column_origin_name(arg0: sqlite3_stmt_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_origin_name16")
def sqlite3_column_origin_name16(arg0: sqlite3_stmt_h, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_table_name")
def sqlite3_column_table_name(arg0: sqlite3_stmt_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_table_name16")
def sqlite3_column_table_name16(arg0: sqlite3_stmt_h, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_text")
def sqlite3_column_text(arg0: sqlite3_stmt_h, iCol: int) -> c_str:
  ...

@native
@native_name("sqlite3_column_text16")
def sqlite3_column_text16(arg0: sqlite3_stmt_h, iCol: int) -> uintptr:
  ...

@native
@native_name("sqlite3_column_type")
def sqlite3_column_type(arg0: sqlite3_stmt_h, iCol: int) -> int:
  ...

@native
@native_name("sqlite3_column_value")
def sqlite3_column_value(arg0: sqlite3_stmt_h, iCol: int) -> sqlite3_value_h:
  ...

@native
@native_name("sqlite3_commit_hook")
def sqlite3_commit_hook(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_compileoption_get")
def sqlite3_compileoption_get(N: int) -> c_str:
  ...

@native
@native_name("sqlite3_compileoption_used")
def sqlite3_compileoption_used(zOptName: c_str) -> int:
  ...

@native
@native_name("sqlite3_complete")
def sqlite3_complete(sql: c_str) -> int:
  ...

@native
@native_name("sqlite3_complete16")
def sqlite3_complete16(sql: uintptr) -> int:
  ...

@native
@native_name("sqlite3_config")
def sqlite3_config(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_context_db_handle")
def sqlite3_context_db_handle(arg0: sqlite3_context_h) -> sqlite3_h:
  ...

@native
@native_name("sqlite3_create_collation")
def sqlite3_create_collation(arg0: sqlite3_h, zName: c_str, eTextRep: int, pArg: uintptr, xCompare: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_collation16")
def sqlite3_create_collation16(arg0: sqlite3_h, zName: uintptr, eTextRep: int, pArg: uintptr, xCompare: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_collation_v2")
def sqlite3_create_collation_v2(arg0: sqlite3_h, zName: c_str, eTextRep: int, pArg: uintptr, xCompare: uintptr, xDestroy: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_filename")
def sqlite3_create_filename(zDatabase: c_str, zJournal: c_str, zWal: c_str, nParam: int, azParam: Pointer[c_str]) -> uint64:  # record
  ...

@native
@native_name("sqlite3_create_function")
def sqlite3_create_function(db: sqlite3_h, zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xFunc: uintptr, xStep: uintptr, xFinal: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_function16")
def sqlite3_create_function16(db: sqlite3_h, zFunctionName: uintptr, nArg: int, eTextRep: int, pApp: uintptr, xFunc: uintptr, xStep: uintptr, xFinal: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_function_v2")
def sqlite3_create_function_v2(db: sqlite3_h, zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xFunc: uintptr, xStep: uintptr, xFinal: uintptr, xDestroy: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_module")
def sqlite3_create_module(db: sqlite3_h, zName: c_str, p: sqlite3_module_h, pClientData: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_module_v2")
def sqlite3_create_module_v2(db: sqlite3_h, zName: c_str, p: sqlite3_module_h, pClientData: uintptr, xDestroy: uintptr) -> int:
  ...

@native
@native_name("sqlite3_create_window_function")
def sqlite3_create_window_function(db: sqlite3_h, zFunctionName: c_str, nArg: int, eTextRep: int, pApp: uintptr, xStep: uintptr, xFinal: uintptr, xValue: uintptr, xInverse: uintptr, xDestroy: uintptr) -> int:
  ...

@native
@native_name("sqlite3_data_count")
def sqlite3_data_count(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_database_file_object")
def sqlite3_database_file_object(arg0: c_str) -> sqlite3_file_h:
  ...

@native
@native_name("sqlite3_db_cacheflush")
def sqlite3_db_cacheflush(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_db_config")
def sqlite3_db_config(arg0: sqlite3_h, op: int) -> int:
  ...

@native
@native_name("sqlite3_db_filename")
def sqlite3_db_filename(db: sqlite3_h, zDbName: c_str) -> uint64:  # record
  ...

@native
@native_name("sqlite3_db_handle")
def sqlite3_db_handle(arg0: sqlite3_stmt_h) -> sqlite3_h:
  ...

@native
@native_name("sqlite3_db_mutex")
def sqlite3_db_mutex(arg0: sqlite3_h) -> sqlite3_mutex_h:
  ...

@native
@native_name("sqlite3_db_name")
def sqlite3_db_name(db: sqlite3_h, N: int) -> c_str:
  ...

@native
@native_name("sqlite3_db_readonly")
def sqlite3_db_readonly(db: sqlite3_h, zDbName: c_str) -> int:
  ...

@native
@native_name("sqlite3_db_release_memory")
def sqlite3_db_release_memory(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_db_status")
def sqlite3_db_status(arg0: sqlite3_h, op: int, pCur: Pointer[int], pHiwtr: Pointer[int], resetFlg: int) -> int:
  ...

@native
@native_name("sqlite3_db_status64")
def sqlite3_db_status64(arg0: sqlite3_h, arg1: int, arg2: uint64, arg3: uint64, arg4: int) -> int:
  ...

@native
@native_name("sqlite3_declare_vtab")
def sqlite3_declare_vtab(arg0: sqlite3_h, zSQL: c_str) -> int:
  ...

@native
@native_name("sqlite3_deserialize")
def sqlite3_deserialize(db: sqlite3_h, zSchema: c_str, pData: c_str, szDb: uint64, szBuf: uint64, mFlags: uint) -> int:
  ...

@native
@native_name("sqlite3_drop_modules")
def sqlite3_drop_modules(db: sqlite3_h, azKeep: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_enable_load_extension")
def sqlite3_enable_load_extension(db: sqlite3_h, onoff: int) -> int:
  ...

@native
@native_name("sqlite3_enable_shared_cache")
def sqlite3_enable_shared_cache(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_errcode")
def sqlite3_errcode(db: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_errmsg")
def sqlite3_errmsg(arg0: sqlite3_h) -> c_str:
  ...

@native
@native_name("sqlite3_errmsg16")
def sqlite3_errmsg16(arg0: sqlite3_h) -> uintptr:
  ...

@native
@native_name("sqlite3_error_offset")
def sqlite3_error_offset(db: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_errstr")
def sqlite3_errstr(arg0: int) -> c_str:
  ...

@native
@native_name("sqlite3_exec")
def sqlite3_exec(arg0: sqlite3_h, sql: c_str, callback: uintptr, arg3: uintptr, errmsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_expanded_sql")
def sqlite3_expanded_sql(pStmt: sqlite3_stmt_h) -> c_str:
  ...

@native
@native_name("sqlite3_expired")
def sqlite3_expired(arg0: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_extended_errcode")
def sqlite3_extended_errcode(db: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_extended_result_codes")
def sqlite3_extended_result_codes(arg0: sqlite3_h, onoff: int) -> int:
  ...

@native
@native_name("sqlite3_file_control")
def sqlite3_file_control(arg0: sqlite3_h, zDbName: c_str, op: int, arg3: uintptr) -> int:
  ...

@native
@native_name("sqlite3_filename_database")
def sqlite3_filename_database(arg0: uint64) -> c_str:
  ...

@native
@native_name("sqlite3_filename_journal")
def sqlite3_filename_journal(arg0: uint64) -> c_str:
  ...

@native
@native_name("sqlite3_filename_wal")
def sqlite3_filename_wal(arg0: uint64) -> c_str:
  ...

@native
@native_name("sqlite3_finalize")
def sqlite3_finalize(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_free")
def sqlite3_free(arg0: uintptr) -> None:
  ...

@native
@native_name("sqlite3_free_filename")
def sqlite3_free_filename(arg0: uint64) -> None:
  ...

@native
@native_name("sqlite3_free_table")
def sqlite3_free_table(result: Pointer[c_str]) -> None:
  ...

@native
@native_name("sqlite3_get_autocommit")
def sqlite3_get_autocommit(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_get_auxdata")
def sqlite3_get_auxdata(arg0: sqlite3_context_h, N: int) -> uintptr:
  ...

@native
@native_name("sqlite3_get_clientdata")
def sqlite3_get_clientdata(arg0: sqlite3_h, arg1: c_str) -> uintptr:
  ...

@native
@native_name("sqlite3_get_table")
def sqlite3_get_table(db: sqlite3_h, zSql: c_str, pazResult: Pointer[Pointer[c_str]], pnRow: Pointer[int], pnColumn: Pointer[int], pzErrmsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_global_recover")
def sqlite3_global_recover() -> int:
  ...

@native
@native_name("sqlite3_hard_heap_limit64")
def sqlite3_hard_heap_limit64(N: uint64) -> uint64:  # record
  ...

@native
@native_name("sqlite3_initialize")
def sqlite3_initialize() -> int:
  ...

@native
@native_name("sqlite3_interrupt")
def sqlite3_interrupt(arg0: sqlite3_h) -> None:
  ...

@native
@native_name("sqlite3_is_interrupted")
def sqlite3_is_interrupted(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_keyword_check")
def sqlite3_keyword_check(arg0: c_str, arg1: int) -> int:
  ...

@native
@native_name("sqlite3_keyword_count")
def sqlite3_keyword_count() -> int:
  ...

@native
@native_name("sqlite3_keyword_name")
def sqlite3_keyword_name(arg0: int, arg1: Pointer[c_str], arg2: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_last_insert_rowid")
def sqlite3_last_insert_rowid(arg0: sqlite3_h) -> uint64:  # record
  ...

@native
@native_name("sqlite3_libversion")
def sqlite3_libversion() -> c_str:
  ...

@native
@native_name("sqlite3_libversion_number")
def sqlite3_libversion_number() -> int:
  ...

@native
@native_name("sqlite3_limit")
def sqlite3_limit(arg0: sqlite3_h, id: int, newVal: int) -> int:
  ...

@native
@native_name("sqlite3_load_extension")
def sqlite3_load_extension(db: sqlite3_h, zFile: c_str, zProc: c_str, pzErrMsg: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_log")
def sqlite3_log(iErrCode: int, zFormat: c_str) -> None:
  ...

@native
@native_name("sqlite3_malloc")
def sqlite3_malloc(arg0: int) -> uintptr:
  ...

@native
@native_name("sqlite3_malloc64")
def sqlite3_malloc64(arg0: uint64) -> uintptr:
  ...

@native
@native_name("sqlite3_memory_alarm")
def sqlite3_memory_alarm(arg0: uintptr, arg1: uintptr, arg2: uint64) -> int:
  ...

@native
@native_name("sqlite3_memory_highwater")
def sqlite3_memory_highwater(resetFlag: int) -> uint64:  # record
  ...

@native
@native_name("sqlite3_memory_used")
def sqlite3_memory_used() -> uint64:  # record
  ...

@native
@native_name("sqlite3_mprintf")
def sqlite3_mprintf(arg0: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_msize")
def sqlite3_msize(arg0: uintptr) -> uint64:  # record
  ...

@native
@native_name("sqlite3_mutex_alloc")
def sqlite3_mutex_alloc(arg0: int) -> sqlite3_mutex_h:
  ...

@native
@native_name("sqlite3_mutex_enter")
def sqlite3_mutex_enter(arg0: sqlite3_mutex_h) -> None:
  ...

@native
@native_name("sqlite3_mutex_free")
def sqlite3_mutex_free(arg0: sqlite3_mutex_h) -> None:
  ...

@native
@native_name("sqlite3_mutex_held")
def sqlite3_mutex_held(arg0: sqlite3_mutex_h) -> int:
  ...

@native
@native_name("sqlite3_mutex_leave")
def sqlite3_mutex_leave(arg0: sqlite3_mutex_h) -> None:
  ...

@native
@native_name("sqlite3_mutex_notheld")
def sqlite3_mutex_notheld(arg0: sqlite3_mutex_h) -> int:
  ...

@native
@native_name("sqlite3_mutex_try")
def sqlite3_mutex_try(arg0: sqlite3_mutex_h) -> int:
  ...

@native
@native_name("sqlite3_next_stmt")
def sqlite3_next_stmt(pDb: sqlite3_h, pStmt: sqlite3_stmt_h) -> sqlite3_stmt_h:
  ...

@native
@native_name("sqlite3_open")
def sqlite3_open(filename: c_str, ppDb: Pointer[sqlite3_h]) -> int:
  ...

@native
@native_name("sqlite3_open16")
def sqlite3_open16(filename: uintptr, ppDb: Pointer[sqlite3_h]) -> int:
  ...

@native
@native_name("sqlite3_open_v2")
def sqlite3_open_v2(filename: c_str, ppDb: Pointer[sqlite3_h], flags: int, zVfs: c_str) -> int:
  ...

@native
@native_name("sqlite3_os_end")
def sqlite3_os_end() -> int:
  ...

@native
@native_name("sqlite3_os_init")
def sqlite3_os_init() -> int:
  ...

@native
@native_name("sqlite3_overload_function")
def sqlite3_overload_function(arg0: sqlite3_h, zFuncName: c_str, nArg: int) -> int:
  ...

@native
@native_name("sqlite3_prepare")
def sqlite3_prepare(db: sqlite3_h, zSql: c_str, nByte: int, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_prepare16")
def sqlite3_prepare16(db: sqlite3_h, zSql: uintptr, nByte: int, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare16_v2")
def sqlite3_prepare16_v2(db: sqlite3_h, zSql: uintptr, nByte: int, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare16_v3")
def sqlite3_prepare16_v3(db: sqlite3_h, zSql: uintptr, nByte: int, prepFlags: uint, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[uintptr]) -> int:
  ...

@native
@native_name("sqlite3_prepare_v2")
def sqlite3_prepare_v2(db: sqlite3_h, zSql: c_str, nByte: int, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_prepare_v3")
def sqlite3_prepare_v3(db: sqlite3_h, zSql: c_str, nByte: int, prepFlags: uint, ppStmt: Pointer[sqlite3_stmt_h], pzTail: Pointer[c_str]) -> int:
  ...

@native
@native_name("sqlite3_profile")
def sqlite3_profile(arg0: sqlite3_h, xProfile: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_progress_handler")
def sqlite3_progress_handler(arg0: sqlite3_h, arg1: int, arg2: uintptr, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_randomness")
def sqlite3_randomness(N: int, P: uintptr) -> None:
  ...

@native
@native_name("sqlite3_realloc")
def sqlite3_realloc(arg0: uintptr, arg1: int) -> uintptr:
  ...

@native
@native_name("sqlite3_realloc64")
def sqlite3_realloc64(arg0: uintptr, arg1: uint64) -> uintptr:
  ...

@native
@native_name("sqlite3_release_memory")
def sqlite3_release_memory(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_reset")
def sqlite3_reset(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_reset_auto_extension")
def sqlite3_reset_auto_extension() -> None:
  ...

@native
@native_name("sqlite3_result_blob")
def sqlite3_result_blob(arg0: sqlite3_context_h, arg1: uintptr, arg2: int, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_blob64")
def sqlite3_result_blob64(arg0: sqlite3_context_h, arg1: uintptr, arg2: uint64, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_double")
def sqlite3_result_double(arg0: sqlite3_context_h, arg1: float64) -> None:
  ...

@native
@native_name("sqlite3_result_error")
def sqlite3_result_error(arg0: sqlite3_context_h, arg1: c_str, arg2: int) -> None:
  ...

@native
@native_name("sqlite3_result_error16")
def sqlite3_result_error16(arg0: sqlite3_context_h, arg1: uintptr, arg2: int) -> None:
  ...

@native
@native_name("sqlite3_result_error_code")
def sqlite3_result_error_code(arg0: sqlite3_context_h, arg1: int) -> None:
  ...

@native
@native_name("sqlite3_result_error_nomem")
def sqlite3_result_error_nomem(arg0: sqlite3_context_h) -> None:
  ...

@native
@native_name("sqlite3_result_error_toobig")
def sqlite3_result_error_toobig(arg0: sqlite3_context_h) -> None:
  ...

@native
@native_name("sqlite3_result_int")
def sqlite3_result_int(arg0: sqlite3_context_h, arg1: int) -> None:
  ...

@native
@native_name("sqlite3_result_int64")
def sqlite3_result_int64(arg0: sqlite3_context_h, arg1: uint64) -> None:
  ...

@native
@native_name("sqlite3_result_null")
def sqlite3_result_null(arg0: sqlite3_context_h) -> None:
  ...

@native
@native_name("sqlite3_result_pointer")
def sqlite3_result_pointer(arg0: sqlite3_context_h, arg1: uintptr, arg2: c_str, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_subtype")
def sqlite3_result_subtype(arg0: sqlite3_context_h, arg1: uint) -> None:
  ...

@native
@native_name("sqlite3_result_text")
def sqlite3_result_text(arg0: sqlite3_context_h, arg1: c_str, arg2: int, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_text16")
def sqlite3_result_text16(arg0: sqlite3_context_h, arg1: uintptr, arg2: int, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_text16be")
def sqlite3_result_text16be(arg0: sqlite3_context_h, arg1: uintptr, arg2: int, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_text16le")
def sqlite3_result_text16le(arg0: sqlite3_context_h, arg1: uintptr, arg2: int, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_result_text64")
def sqlite3_result_text64(arg0: sqlite3_context_h, z: c_str, n: uint64, arg3: uintptr, encoding: int) -> None:
  ...

@native
@native_name("sqlite3_result_value")
def sqlite3_result_value(arg0: sqlite3_context_h, arg1: sqlite3_value_h) -> None:
  ...

@native
@native_name("sqlite3_result_zeroblob")
def sqlite3_result_zeroblob(arg0: sqlite3_context_h, n: int) -> None:
  ...

@native
@native_name("sqlite3_result_zeroblob64")
def sqlite3_result_zeroblob64(arg0: sqlite3_context_h, n: uint64) -> int:
  ...

@native
@native_name("sqlite3_rollback_hook")
def sqlite3_rollback_hook(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_rtree_geometry_callback")
def sqlite3_rtree_geometry_callback(db: sqlite3_h, zGeom: c_str, xGeom: uintptr, pContext: uintptr) -> int:
  ...

@native
@native_name("sqlite3_rtree_query_callback")
def sqlite3_rtree_query_callback(db: sqlite3_h, zQueryFunc: c_str, xQueryFunc: uintptr, pContext: uintptr, xDestructor: uintptr) -> int:
  ...

@native
@native_name("sqlite3_serialize")
def sqlite3_serialize(db: sqlite3_h, zSchema: c_str, piSize: uint64, mFlags: uint) -> c_str:
  ...

@native
@native_name("sqlite3_set_authorizer")
def sqlite3_set_authorizer(arg0: sqlite3_h, xAuth: uintptr, pUserData: uintptr) -> int:
  ...

@native
@native_name("sqlite3_set_auxdata")
def sqlite3_set_auxdata(arg0: sqlite3_context_h, N: int, arg2: uintptr, arg3: uintptr) -> None:
  ...

@native
@native_name("sqlite3_set_clientdata")
def sqlite3_set_clientdata(arg0: sqlite3_h, arg1: c_str, arg2: uintptr, arg3: uintptr) -> int:
  ...

@native
@native_name("sqlite3_set_errmsg")
def sqlite3_set_errmsg(db: sqlite3_h, errcode: int, zErrMsg: c_str) -> int:
  ...

@native
@native_name("sqlite3_set_last_insert_rowid")
def sqlite3_set_last_insert_rowid(arg0: sqlite3_h, arg1: uint64) -> None:
  ...

@native
@native_name("sqlite3_setlk_timeout")
def sqlite3_setlk_timeout(arg0: sqlite3_h, ms: int, flags: int) -> int:
  ...

@native
@native_name("sqlite3_shutdown")
def sqlite3_shutdown() -> int:
  ...

@native
@native_name("sqlite3_sleep")
def sqlite3_sleep(arg0: int) -> int:
  ...

@native
@native_name("sqlite3_snapshot_cmp")
def sqlite3_snapshot_cmp(p1: sqlite3_snapshot_h, p2: sqlite3_snapshot_h) -> int:
  ...

@native
@native_name("sqlite3_snapshot_free")
def sqlite3_snapshot_free(arg0: sqlite3_snapshot_h) -> None:
  ...

@native
@native_name("sqlite3_snapshot_get")
def sqlite3_snapshot_get(db: sqlite3_h, zSchema: c_str, ppSnapshot: Pointer[sqlite3_snapshot_h]) -> int:
  ...

@native
@native_name("sqlite3_snapshot_open")
def sqlite3_snapshot_open(db: sqlite3_h, zSchema: c_str, pSnapshot: sqlite3_snapshot_h) -> int:
  ...

@native
@native_name("sqlite3_snapshot_recover")
def sqlite3_snapshot_recover(db: sqlite3_h, zDb: c_str) -> int:
  ...

@native
@native_name("sqlite3_snprintf")
def sqlite3_snprintf(arg0: int, arg1: c_str, arg2: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_soft_heap_limit")
def sqlite3_soft_heap_limit(N: int) -> None:
  ...

@native
@native_name("sqlite3_soft_heap_limit64")
def sqlite3_soft_heap_limit64(N: uint64) -> uint64:  # record
  ...

@native
@native_name("sqlite3_sourceid")
def sqlite3_sourceid() -> c_str:
  ...

@native
@native_name("sqlite3_sql")
def sqlite3_sql(pStmt: sqlite3_stmt_h) -> c_str:
  ...

@native
@native_name("sqlite3_status")
def sqlite3_status(op: int, pCurrent: Pointer[int], pHighwater: Pointer[int], resetFlag: int) -> int:
  ...

@native
@native_name("sqlite3_status64")
def sqlite3_status64(op: int, pCurrent: uint64, pHighwater: uint64, resetFlag: int) -> int:
  ...

@native
@native_name("sqlite3_step")
def sqlite3_step(arg0: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_stmt_busy")
def sqlite3_stmt_busy(arg0: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_stmt_explain")
def sqlite3_stmt_explain(pStmt: sqlite3_stmt_h, eMode: int) -> int:
  ...

@native
@native_name("sqlite3_stmt_isexplain")
def sqlite3_stmt_isexplain(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_stmt_readonly")
def sqlite3_stmt_readonly(pStmt: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_stmt_scanstatus")
def sqlite3_stmt_scanstatus(pStmt: sqlite3_stmt_h, idx: int, iScanStatusOp: int, pOut: uintptr) -> int:
  ...

@native
@native_name("sqlite3_stmt_scanstatus_reset")
def sqlite3_stmt_scanstatus_reset(arg0: sqlite3_stmt_h) -> None:
  ...

@native
@native_name("sqlite3_stmt_scanstatus_v2")
def sqlite3_stmt_scanstatus_v2(pStmt: sqlite3_stmt_h, idx: int, iScanStatusOp: int, flags: int, pOut: uintptr) -> int:
  ...

@native
@native_name("sqlite3_stmt_status")
def sqlite3_stmt_status(arg0: sqlite3_stmt_h, op: int, resetFlg: int) -> int:
  ...

@native
@native_name("sqlite3_str_append")
def sqlite3_str_append(arg0: sqlite3_str_h, zIn: c_str, N: int) -> None:
  ...

@native
@native_name("sqlite3_str_appendall")
def sqlite3_str_appendall(arg0: sqlite3_str_h, zIn: c_str) -> None:
  ...

@native
@native_name("sqlite3_str_appendchar")
def sqlite3_str_appendchar(arg0: sqlite3_str_h, N: int, C: int) -> None:
  ...

@native
@native_name("sqlite3_str_appendf")
def sqlite3_str_appendf(arg0: sqlite3_str_h, zFormat: c_str) -> None:
  ...

@native
@native_name("sqlite3_str_errcode")
def sqlite3_str_errcode(arg0: sqlite3_str_h) -> int:
  ...

@native
@native_name("sqlite3_str_finish")
def sqlite3_str_finish(arg0: sqlite3_str_h) -> c_str:
  ...

@native
@native_name("sqlite3_str_free")
def sqlite3_str_free(arg0: sqlite3_str_h) -> None:
  ...

@native
@native_name("sqlite3_str_length")
def sqlite3_str_length(arg0: sqlite3_str_h) -> int:
  ...

@native
@native_name("sqlite3_str_new")
def sqlite3_str_new(arg0: sqlite3_h) -> sqlite3_str_h:
  ...

@native
@native_name("sqlite3_str_reset")
def sqlite3_str_reset(arg0: sqlite3_str_h) -> None:
  ...

@native
@native_name("sqlite3_str_truncate")
def sqlite3_str_truncate(arg0: sqlite3_str_h, N: int) -> None:
  ...

@native
@native_name("sqlite3_str_value")
def sqlite3_str_value(arg0: sqlite3_str_h) -> c_str:
  ...

@native
@native_name("sqlite3_str_vappendf")
def sqlite3_str_vappendf(arg0: sqlite3_str_h, zFormat: c_str, arg2: uint64) -> None:
  ...

@native
@native_name("sqlite3_strglob")
def sqlite3_strglob(zGlob: c_str, zStr: c_str) -> int:
  ...

@native
@native_name("sqlite3_stricmp")
def sqlite3_stricmp(arg0: c_str, arg1: c_str) -> int:
  ...

@native
@native_name("sqlite3_strlike")
def sqlite3_strlike(zGlob: c_str, zStr: c_str, cEsc: uint) -> int:
  ...

@native
@native_name("sqlite3_strnicmp")
def sqlite3_strnicmp(arg0: c_str, arg1: c_str, arg2: int) -> int:
  ...

@native
@native_name("sqlite3_system_errno")
def sqlite3_system_errno(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_table_column_metadata")
def sqlite3_table_column_metadata(db: sqlite3_h, zDbName: c_str, zTableName: c_str, zColumnName: c_str, pzDataType: Pointer[c_str], pzCollSeq: Pointer[c_str], pNotNull: Pointer[int], pPrimaryKey: Pointer[int], pAutoinc: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_test_control")
def sqlite3_test_control(op: int) -> int:
  ...

@native
@native_name("sqlite3_thread_cleanup")
def sqlite3_thread_cleanup() -> None:
  ...

@native
@native_name("sqlite3_threadsafe")
def sqlite3_threadsafe() -> int:
  ...

@native
@native_name("sqlite3_total_changes")
def sqlite3_total_changes(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_total_changes64")
def sqlite3_total_changes64(arg0: sqlite3_h) -> uint64:  # record
  ...

@native
@native_name("sqlite3_trace")
def sqlite3_trace(arg0: sqlite3_h, xTrace: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_trace_v2")
def sqlite3_trace_v2(arg0: sqlite3_h, uMask: uint, xCallback: uintptr, pCtx: uintptr) -> int:
  ...

@native
@native_name("sqlite3_transfer_bindings")
def sqlite3_transfer_bindings(arg0: sqlite3_stmt_h, arg1: sqlite3_stmt_h) -> int:
  ...

@native
@native_name("sqlite3_txn_state")
def sqlite3_txn_state(arg0: sqlite3_h, zSchema: c_str) -> int:
  ...

@native
@native_name("sqlite3_unlock_notify")
def sqlite3_unlock_notify(pBlocked: sqlite3_h, xNotify: uintptr, pNotifyArg: uintptr) -> int:
  ...

@native
@native_name("sqlite3_update_hook")
def sqlite3_update_hook(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_uri_boolean")
def sqlite3_uri_boolean(z: uint64, zParam: c_str, bDefault: int) -> int:
  ...

@native
@native_name("sqlite3_uri_int64")
def sqlite3_uri_int64(arg0: uint64, arg1: c_str, arg2: uint64) -> uint64:  # record
  ...

@native
@native_name("sqlite3_uri_key")
def sqlite3_uri_key(z: uint64, N: int) -> c_str:
  ...

@native
@native_name("sqlite3_uri_parameter")
def sqlite3_uri_parameter(z: uint64, zParam: c_str) -> c_str:
  ...

@native
@native_name("sqlite3_user_data")
def sqlite3_user_data(arg0: sqlite3_context_h) -> uintptr:
  ...

@native
@native_name("sqlite3_value_blob")
def sqlite3_value_blob(arg0: sqlite3_value_h) -> uintptr:
  ...

@native
@native_name("sqlite3_value_bytes")
def sqlite3_value_bytes(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_bytes16")
def sqlite3_value_bytes16(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_double")
def sqlite3_value_double(arg0: sqlite3_value_h) -> float64:
  ...

@native
@native_name("sqlite3_value_dup")
def sqlite3_value_dup(arg0: sqlite3_value_h) -> sqlite3_value_h:
  ...

@native
@native_name("sqlite3_value_encoding")
def sqlite3_value_encoding(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_free")
def sqlite3_value_free(arg0: sqlite3_value_h) -> None:
  ...

@native
@native_name("sqlite3_value_frombind")
def sqlite3_value_frombind(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_int")
def sqlite3_value_int(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_int64")
def sqlite3_value_int64(arg0: sqlite3_value_h) -> uint64:  # record
  ...

@native
@native_name("sqlite3_value_nochange")
def sqlite3_value_nochange(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_numeric_type")
def sqlite3_value_numeric_type(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_value_pointer")
def sqlite3_value_pointer(arg0: sqlite3_value_h, arg1: c_str) -> uintptr:
  ...

@native
@native_name("sqlite3_value_subtype")
def sqlite3_value_subtype(arg0: sqlite3_value_h) -> uint:
  ...

@native
@native_name("sqlite3_value_text")
def sqlite3_value_text(arg0: sqlite3_value_h) -> c_str:
  ...

@native
@native_name("sqlite3_value_text16")
def sqlite3_value_text16(arg0: sqlite3_value_h) -> uintptr:
  ...

@native
@native_name("sqlite3_value_text16be")
def sqlite3_value_text16be(arg0: sqlite3_value_h) -> uintptr:
  ...

@native
@native_name("sqlite3_value_text16le")
def sqlite3_value_text16le(arg0: sqlite3_value_h) -> uintptr:
  ...

@native
@native_name("sqlite3_value_type")
def sqlite3_value_type(arg0: sqlite3_value_h) -> int:
  ...

@native
@native_name("sqlite3_vfs_find")
def sqlite3_vfs_find(zVfsName: c_str) -> sqlite3_vfs_h:
  ...

@native
@native_name("sqlite3_vfs_register")
def sqlite3_vfs_register(arg0: sqlite3_vfs_h, makeDflt: int) -> int:
  ...

@native
@native_name("sqlite3_vfs_unregister")
def sqlite3_vfs_unregister(arg0: sqlite3_vfs_h) -> int:
  ...

@native
@native_name("sqlite3_vmprintf")
def sqlite3_vmprintf(arg0: c_str, arg1: uint64) -> c_str:
  ...

@native
@native_name("sqlite3_vsnprintf")
def sqlite3_vsnprintf(arg0: int, arg1: c_str, arg2: c_str, arg3: uint64) -> c_str:
  ...

@native
@native_name("sqlite3_vtab_collation")
def sqlite3_vtab_collation(arg0: sqlite3_index_info_h, arg1: int) -> c_str:
  ...

@native
@native_name("sqlite3_vtab_config")
def sqlite3_vtab_config(arg0: sqlite3_h, op: int) -> int:
  ...

@native
@native_name("sqlite3_vtab_distinct")
def sqlite3_vtab_distinct(arg0: sqlite3_index_info_h) -> int:
  ...

@native
@native_name("sqlite3_vtab_in")
def sqlite3_vtab_in(arg0: sqlite3_index_info_h, iCons: int, bHandle: int) -> int:
  ...

@native
@native_name("sqlite3_vtab_in_first")
def sqlite3_vtab_in_first(pVal: sqlite3_value_h, ppOut: Pointer[sqlite3_value_h]) -> int:
  ...

@native
@native_name("sqlite3_vtab_in_next")
def sqlite3_vtab_in_next(pVal: sqlite3_value_h, ppOut: Pointer[sqlite3_value_h]) -> int:
  ...

@native
@native_name("sqlite3_vtab_nochange")
def sqlite3_vtab_nochange(arg0: sqlite3_context_h) -> int:
  ...

@native
@native_name("sqlite3_vtab_on_conflict")
def sqlite3_vtab_on_conflict(arg0: sqlite3_h) -> int:
  ...

@native
@native_name("sqlite3_vtab_rhs_value")
def sqlite3_vtab_rhs_value(arg0: sqlite3_index_info_h, arg1: int, ppVal: Pointer[sqlite3_value_h]) -> int:
  ...

@native
@native_name("sqlite3_wal_autocheckpoint")
def sqlite3_wal_autocheckpoint(db: sqlite3_h, N: int) -> int:
  ...

@native
@native_name("sqlite3_wal_checkpoint")
def sqlite3_wal_checkpoint(db: sqlite3_h, zDb: c_str) -> int:
  ...

@native
@native_name("sqlite3_wal_checkpoint_v2")
def sqlite3_wal_checkpoint_v2(db: sqlite3_h, zDb: c_str, eMode: int, pnLog: Pointer[int], pnCkpt: Pointer[int]) -> int:
  ...

@native
@native_name("sqlite3_wal_hook")
def sqlite3_wal_hook(arg0: sqlite3_h, arg1: uintptr, arg2: uintptr) -> uintptr:
  ...

@native
@native_name("sqlite3_win32_set_directory")
def sqlite3_win32_set_directory(type: uint, zValue: uintptr) -> int:
  ...

@native
@native_name("sqlite3_win32_set_directory16")
def sqlite3_win32_set_directory16(type: uint, zValue: uintptr) -> int:
  ...

@native
@native_name("sqlite3_win32_set_directory8")
def sqlite3_win32_set_directory8(type: uint, zValue: c_str) -> int:
  ...

# stats: opaques=17 consts=410 funcs=298
