"""``__iter__`` / ``__reversed__`` 返回迭代器类名表（接收者 Python 类名 → 迭代器 C++ 基名 + 模板 arity）。"""

# (iterator_cpp_base, type_param_arity)：0=无模板实参，1=``T0``，2=``K,V``
ITER_RETURN: dict[str, tuple[str, int]] = {
  "str": ("StrIterator", 0),
  "StrIterator": ("StrIterator", 0),
  "StrReverseIterator": ("StrReverseIterator", 0),
  "range": ("RangeIterator", 0),
  "RangeIterator": ("RangeIterator", 0),
  "list": ("ListIterator", 1),
  "ListIterator": ("ListIterator", 1),
  "ListReverseIterator": ("ListReverseIterator", 1),
  "deque": ("DequeIterator", 1),
  "DequeIterator": ("DequeIterator", 1),
  "DequeReverseIterator": ("DequeReverseIterator", 1),
  "ChunkDeque": ("ChunkDequeIterator", 1),
  "ChunkDequeIterator": ("ChunkDequeIterator", 1),
  "ChunkDequeReverseIterator": ("ChunkDequeReverseIterator", 1),
  "TupleIterator": ("TupleIterator", 1),
  "frozenlist": ("FrozenListIterator", 1),
  "FrozenListIterator": ("FrozenListIterator", 1),
  "dict": ("DictKeyIterator", 2),
  "DictKeyIterator": ("DictKeyIterator", 2),
  "DictKeyReverseIterator": ("DictKeyReverseIterator", 2),
  "DictValuesIterator": ("DictValuesIterator", 2),
  "DictItemsIterator": ("DictItemsIterator", 2),
  "DictKeysView": ("DictKeyIterator", 2),
  "DictValuesView": ("DictValuesIterator", 2),
  "DictItemsView": ("DictItemsIterator", 2),
  "frozendict": ("FrozenDictKeyIterator", 2),
  "FrozenDictKeyIterator": ("FrozenDictKeyIterator", 2),
  "FrozenDictKeyReverseIterator": ("FrozenDictKeyReverseIterator", 2),
  "FrozenDictValuesIterator": ("FrozenDictValuesIterator", 2),
  "FrozenDictItemsIterator": ("FrozenDictItemsIterator", 2),
  "FrozenDictKeysView": ("FrozenDictKeyIterator", 2),
  "FrozenDictValuesView": ("FrozenDictValuesIterator", 2),
  "FrozenDictItemsView": ("FrozenDictItemsIterator", 2),
}

REVERSED_RETURN: dict[str, tuple[str, int]] = {
  "str": ("StrReverseIterator", 0),
  "range": ("RangeIterator", 0),
  "RangeIterator": ("RangeIterator", 0),
  "list": ("ListReverseIterator", 1),
  "deque": ("DequeReverseIterator", 1),
  "ChunkDeque": ("ChunkDequeReverseIterator", 1),
  "dict": ("DictKeyReverseIterator", 2),
  "DictKeysView": ("DictKeyReverseIterator", 2),
  "frozendict": ("FrozenDictKeyReverseIterator", 2),
  "FrozenDictKeysView": ("FrozenDictKeyReverseIterator", 2),
}
