"""``__iter__`` / ``__reversed__`` 返回迭代器类名表（接收者 Python 类名 → 迭代器 C++ 基名 + 模板 arity）。"""

# (iterator_cpp_base, type_param_arity)：0=无模板实参，1=``T0``，2=``K,V``
ITER_RETURN: dict[str, tuple[str, int]] = {
  "str": ("str_iterator", 0),
  "str_iterator": ("str_iterator", 0),
  "str_reverse_iterator": ("str_reverse_iterator", 0),
  "range": ("range_iterator", 0),
  "range_iterator": ("range_iterator", 0),
  "list": ("list_iterator", 1),
  "list_iterator": ("list_iterator", 1),
  "list_reverse_iterator": ("list_reverse_iterator", 1),
  "deque": ("deque_iterator", 1),
  "deque_iterator": ("deque_iterator", 1),
  "deque_reverse_iterator": ("deque_reverse_iterator", 1),
  "ChunkDeque": ("ChunkDequeIterator", 1),
  "ChunkDequeIterator": ("ChunkDequeIterator", 1),
  "ChunkDequeReverseIterator": ("ChunkDequeReverseIterator", 1),
  "tuple_iterator": ("tuple_iterator", 1),
  "frozenlist": ("frozenlist_iterator", 1),
  "frozenlist_iterator": ("frozenlist_iterator", 1),
  "dict": ("dict_key_iterator", 2),
  "dict_key_iterator": ("dict_key_iterator", 2),
  "dict_key_reverse_iterator": ("dict_key_reverse_iterator", 2),
  "dict_values_iterator": ("dict_values_iterator", 2),
  "dict_items_iterator": ("dict_items_iterator", 2),
  "dict_keys_view": ("dict_key_iterator", 2),
  "dict_values_view": ("dict_values_iterator", 2),
  "dict_items_view": ("dict_items_iterator", 2),
  "frozendict": ("frozendict_key_iterator", 2),
  "frozendict_key_iterator": ("frozendict_key_iterator", 2),
  "frozendict_key_reverse_iterator": ("frozendict_key_reverse_iterator", 2),
  "frozendict_values_iterator": ("frozendict_values_iterator", 2),
  "frozendict_items_iterator": ("frozendict_items_iterator", 2),
  "frozendict_keys_view": ("frozendict_key_iterator", 2),
  "frozendict_values_view": ("frozendict_values_iterator", 2),
  "frozendict_items_view": ("frozendict_items_iterator", 2),
}

REVERSED_RETURN: dict[str, tuple[str, int]] = {
  "str": ("str_reverse_iterator", 0),
  "range": ("range_iterator", 0),
  "range_iterator": ("range_iterator", 0),
  "list": ("list_reverse_iterator", 1),
  "deque": ("deque_reverse_iterator", 1),
  "ChunkDeque": ("ChunkDequeReverseIterator", 1),
  "dict": ("dict_key_reverse_iterator", 2),
  "dict_keys_view": ("dict_key_reverse_iterator", 2),
  "frozendict": ("frozendict_key_reverse_iterator", 2),
  "frozendict_keys_view": ("frozendict_key_reverse_iterator", 2),
}
