# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\direct.h
# Generated: 2026-08-20 20:18:07
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint16 @native_name("_Byte")
  state: uint16 @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint16] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

@native
@native_name("_diskfree_t")
class PyiDiskfreeT:
  totalClusters: uint @native_name("total_clusters")
  availClusters: uint @native_name("avail_clusters")
  sectorsPerCluster: uint @native_name("sectors_per_cluster")
  bytesPerSector: uint @native_name("bytes_per_sector")

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@overload
@native
@native_name("_chdir")
def pyiChdir(_Path: utf8ptr) -> int:
  ...

@native
@native_name("_chdrive")
def pyiChdrive(_Drive: int) -> int:
  ...

@overload
@native
@native_name("_getcwd")
def pyiGetcwd(_DstBuf: utf8ptr, _SizeInBytes: int) -> utf8ptr:
  ...

@native
@native_name("_getdcwd")
def pyiGetdcwd(_Drive: int, _DstBuf: utf8ptr, _SizeInBytes: int) -> utf8ptr:
  ...

@native
@native_name("_getdiskfree")
def pyiGetdiskfree(_Drive: uint, _DiskFree: Pointer[PyiDiskfreeT]) -> uint:
  ...

@native
@native_name("_getdrive")
def pyiGetdrive() -> int:
  ...

@native
@native_name("_getdrives")
def pyiGetdrives() -> uint:
  ...

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: utf16ptr, _FunctionName: utf16ptr, _FileName: utf16ptr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

@overload
@native
@native_name("_mkdir")
def pyiMkdir(_Path: utf8ptr) -> int:
  ...

@overload
@native
@native_name("_rmdir")
def pyiRmdir(_Path: utf8ptr) -> int:
  ...

@native
@native_name("_wchdir")
def pyiWchdir(_Path: utf16ptr) -> int:
  ...

@native
@native_name("_wgetcwd")
def pyiWgetcwd(_DstBuf: Pointer[uint16], _SizeInWords: int) -> Pointer[uint16]:
  ...

@native
@native_name("_wgetdcwd")
def pyiWgetdcwd(_Drive: int, _DstBuf: Pointer[uint16], _SizeInWords: int) -> Pointer[uint16]:
  ...

@native
@native_name("_wmkdir")
def pyiWmkdir(_Path: utf16ptr) -> int:
  ...

@native
@native_name("_wrmdir")
def pyiWrmdir(_Path: utf16ptr) -> int:
  ...

@overload
@native
@native_name("chdir")
def pyiChdir(_Path: utf8ptr) -> int:
  ...

@overload
@native
@native_name("getcwd")
def pyiGetcwd(_DstBuf: utf8ptr, _SizeInBytes: int) -> utf8ptr:
  ...

@overload
@native
@native_name("mkdir")
def pyiMkdir(_Path: utf8ptr) -> int:
  ...

@overload
@native
@native_name("rmdir")
def pyiRmdir(_Path: utf8ptr) -> int:
  ...

# stats: structs=6 enums=0 aliases=1 consts=15 funcs=21
