# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\fcntl.h
# Generated: 2026-08-20 20:18:10
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint16 @native_name("_Byte")
  state: uint16 @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint16] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiOAppend: int @native_name("O_APPEND") = 0x0008
PyiOBinary: int @native_name("O_BINARY") = 0x8000
PyiOCreat: int @native_name("O_CREAT") = 0x0100
PyiOExcl: int @native_name("O_EXCL") = 0x0400
PyiONoinherit: int @native_name("O_NOINHERIT") = 0x0080
PyiORandom: int @native_name("O_RANDOM") = 0x0010
PyiORaw: int @native_name("O_RAW") = 0x8000
PyiORdonly: int @native_name("O_RDONLY") = 0x0000
PyiORdwr: int @native_name("O_RDWR") = 0x0002
PyiOSequential: int @native_name("O_SEQUENTIAL") = 0x0020
PyiOTemporary: int @native_name("O_TEMPORARY") = 0x0040
PyiOText: int @native_name("O_TEXT") = 0x4000
PyiOTrunc: int @native_name("O_TRUNC") = 0x0200
PyiOWronly: int @native_name("O_WRONLY") = 0x0001
PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiOObtainDir: int @native_name("_O_OBTAIN_DIR") = 0x2000
PyiOShortLived: int @native_name("_O_SHORT_LIVED") = 0x1000
PyiOU16Text: int @native_name("_O_U16TEXT") = 0x20000
PyiOU8Text: int @native_name("_O_U8TEXT") = 0x40000
PyiOWtext: int @native_name("_O_WTEXT") = 0x10000
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: utf16ptr, _FunctionName: utf16ptr, _FileName: utf16ptr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

# stats: structs=5 enums=0 aliases=1 consts=34 funcs=3
