# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\io.h
# Generated: 2026-08-17 16:07:12
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint @native_name("_Byte")
  state: uint @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

@native
@native_name("__finddata64_t")
class PyiFinddata64T:
  attrib: uint
  timeCreate: int64 @native_name("time_create")
  timeAccess: int64 @native_name("time_access")
  timeWrite: int64 @native_name("time_write")
  size: int64
  name: Pointer[int]  # array

@native
@native_name("_finddata32_t")
class PyiFinddata32T:
  attrib: uint
  timeCreate: int @native_name("time_create")
  timeAccess: int @native_name("time_access")
  timeWrite: int @native_name("time_write")
  size: uint
  name: Pointer[int]  # array

@native
@native_name("_finddata32i64_t")
class PyiFinddata32i64T:
  attrib: uint
  timeCreate: int @native_name("time_create")
  timeAccess: int @native_name("time_access")
  timeWrite: int @native_name("time_write")
  size: int64
  name: Pointer[int]  # array

@native
@native_name("_finddata64i32_t")
class PyiFinddata64i32T:
  attrib: uint
  timeCreate: int64 @native_name("time_create")
  timeAccess: int64 @native_name("time_access")
  timeWrite: int64 @native_name("time_write")
  size: uint
  name: Pointer[int]  # array

@native
@native_name("_wfinddata32_t")
class PyiWfinddata32T:
  attrib: uint
  timeCreate: int @native_name("time_create")
  timeAccess: int @native_name("time_access")
  timeWrite: int @native_name("time_write")
  size: uint
  name: Pointer[uint]  # array

@native
@native_name("_wfinddata32i64_t")
class PyiWfinddata32i64T:
  attrib: uint
  timeCreate: int @native_name("time_create")
  timeAccess: int @native_name("time_access")
  timeWrite: int @native_name("time_write")
  size: int64
  name: Pointer[uint]  # array

@native
@native_name("_wfinddata64_t")
class PyiWfinddata64T:
  attrib: uint
  timeCreate: int64 @native_name("time_create")
  timeAccess: int64 @native_name("time_access")
  timeWrite: int64 @native_name("time_write")
  size: int64
  name: Pointer[uint]  # array

@native
@native_name("_wfinddata64i32_t")
class PyiWfinddata64i32T:
  attrib: uint
  timeCreate: int64 @native_name("time_create")
  timeAccess: int64 @native_name("time_access")
  timeWrite: int64 @native_name("time_write")
  size: uint
  name: Pointer[uint]  # array

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiShDenyno: int @native_name("SH_DENYNO") = 0x40
PyiShDenyrd: int @native_name("SH_DENYRD") = 0x30
PyiShDenyrw: int @native_name("SH_DENYRW") = 0x10
PyiShDenywr: int @native_name("SH_DENYWR") = 0x20
PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiAArch: int @native_name("_A_ARCH") = 0x20
PyiAHidden: int @native_name("_A_HIDDEN") = 0x02
PyiANormal: int @native_name("_A_NORMAL") = 0x00
PyiARdonly: int @native_name("_A_RDONLY") = 0x01
PyiASubdir: int @native_name("_A_SUBDIR") = 0x10
PyiASystem: int @native_name("_A_SYSTEM") = 0x04
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiShDenyno: int @native_name("_SH_DENYNO") = 0x40
PyiShDenyrd: int @native_name("_SH_DENYRD") = 0x30
PyiShDenyrw: int @native_name("_SH_DENYRW") = 0x10
PyiShDenywr: int @native_name("_SH_DENYWR") = 0x20
PyiShSecure: int @native_name("_SH_SECURE") = 0x80
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@overload
@native
@native_name("_access")
def pyiAccess(_FileName: CStr, _AccessMode: int) -> int:
  ...

@native
@native_name("_access_s")
def pyiAccessS(_FileName: CStr, _AccessMode: int) -> int:
  ...

@overload
@native
@native_name("_chmod")
def pyiChmod(_FileName: CStr, _Mode: int) -> int:
  ...

@overload
@native
@native_name("_chsize")
def pyiChsize(_FileHandle: int, _Size: int) -> int:
  ...

@native
@native_name("_chsize_s")
def pyiChsizeS(_FileHandle: int, _Size: int64) -> int:
  ...

@overload
@native
@native_name("_close")
def pyiClose(_FileHandle: int) -> int:
  ...

@native
@native_name("_commit")
def pyiCommit(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("_creat")
def pyiCreat(_FileName: CStr, _PermissionMode: int) -> int:
  ...

@overload
@native
@native_name("_dup")
def pyiDup(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("_dup2")
def pyiDup2(_FileHandleSrc: int, _FileHandleDst: int) -> int:
  ...

@overload
@native
@native_name("_eof")
def pyiEof(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("_filelength")
def pyiFilelength(_FileHandle: int) -> int:
  ...

@native
@native_name("_filelengthi64")
def pyiFilelengthi64(_FileHandle: int) -> int64:
  ...

@native
@native_name("_findclose")
def pyiFindclose(_FindHandle: int64) -> int:
  ...

@native
@native_name("_findfirst32")
def pyiFindfirst32(_FileName: CStr, _FindData: Pointer[PyiFinddata32T]) -> int64:
  ...

@native
@native_name("_findfirst32i64")
def pyiFindfirst32I64(_FileName: CStr, _FindData: Pointer[PyiFinddata32i64T]) -> int64:
  ...

@native
@native_name("_findfirst64")
def pyiFindfirst64(_FileName: CStr, _FindData: Pointer[PyiFinddata64T]) -> int64:
  ...

@native
@native_name("_findfirst64i32")
def pyiFindfirst64I32(_FileName: CStr, _FindData: Pointer[PyiFinddata64i32T]) -> int64:
  ...

@native
@native_name("_findnext32")
def pyiFindnext32(_FindHandle: int64, _FindData: Pointer[PyiFinddata32T]) -> int:
  ...

@native
@native_name("_findnext32i64")
def pyiFindnext32I64(_FindHandle: int64, _FindData: Pointer[PyiFinddata32i64T]) -> int:
  ...

@native
@native_name("_findnext64")
def pyiFindnext64(_FindHandle: int64, _FindData: Pointer[PyiFinddata64T]) -> int:
  ...

@native
@native_name("_findnext64i32")
def pyiFindnext64I32(_FindHandle: int64, _FindData: Pointer[PyiFinddata64i32T]) -> int:
  ...

@native
@native_name("_get_osfhandle")
def pyiGetOsfhandle(_FileHandle: int) -> int64:
  ...

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: CStr, _FunctionName: CStr, _FileName: CStr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

@overload
@native
@native_name("_isatty")
def pyiIsatty(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("_locking")
def pyiLocking(_FileHandle: int, _LockMode: int, _NumOfBytes: int) -> int:
  ...

@overload
@native
@native_name("_lseek")
def pyiLseek(_FileHandle: int, _Offset: int, _Origin: int) -> int:
  ...

@native
@native_name("_lseeki64")
def pyiLseeki64(_FileHandle: int, _Offset: int64, _Origin: int) -> int64:
  ...

@overload
@native
@native_name("_mktemp")
def pyiMktemp(_TemplateName: CStr) -> CStr:
  ...

@native
@native_name("_mktemp_s")
def pyiMktempS(_TemplateName: CStr, _Size: uint64) -> int:
  ...

@overload
@native
@native_name("_open")
def pyiOpen(_FileName: CStr, _OpenFlag: int, *_) -> int:
  ...

@native
@native_name("_open_osfhandle")
def pyiOpenOsfhandle(_OSFileHandle: int64, _Flags: int) -> int:
  ...

@native
@native_name("_pipe")
def pyiPipe(_PtHandles: Pointer[int], _PipeSize: uint, _TextMode: int) -> int:
  ...

@overload
@native
@native_name("_read")
def pyiRead(_FileHandle: int, _DstBuf: uintptr, _MaxCharCount: uint) -> int:
  ...

@overload
@native
@native_name("_setmode")
def pyiSetmode(_FileHandle: int, _Mode: int) -> int:
  ...

@overload
@native
@native_name("_sopen")
def pyiSopen(_FileName: CStr, _OpenFlag: int, _ShareFlag: int, *_) -> int:
  ...

@native
@native_name("_sopen_dispatch")
def pyiSopenDispatch(_FileName: CStr, _OFlag: int, _ShFlag: int, _PMode: int, _PFileHandle: Pointer[int], _BSecure: int) -> int:
  ...

@native
@native_name("_sopen_s")
def pyiSopenS(_FileHandle: Pointer[int], _FileName: CStr, _OpenFlag: int, _ShareFlag: int, _PermissionMode: int) -> int:
  ...

@native
@native_name("_sopen_s_nolock")
def pyiSopenSNolock(_FileHandle: Pointer[int], _FileName: CStr, _OpenFlag: int, _ShareFlag: int, _PermissionMode: int) -> int:
  ...

@overload
@native
@native_name("_tell")
def pyiTell(_FileHandle: int) -> int:
  ...

@native
@native_name("_telli64")
def pyiTelli64(_FileHandle: int) -> int64:
  ...

@overload
@native
@native_name("_umask")
def pyiUmask(_Mode: int) -> int:
  ...

@native
@native_name("_umask_s")
def pyiUmaskS(_NewMode: int, _OldMode: Pointer[int]) -> int:
  ...

@overload
@native
@native_name("_unlink")
def pyiUnlink(_FileName: CStr) -> int:
  ...

@native
@native_name("_waccess")
def pyiWaccess(_FileName: CStr, _AccessMode: int) -> int:
  ...

@native
@native_name("_waccess_s")
def pyiWaccessS(_FileName: CStr, _AccessMode: int) -> int:
  ...

@native
@native_name("_wchmod")
def pyiWchmod(_FileName: CStr, _Mode: int) -> int:
  ...

@native
@native_name("_wcreat")
def pyiWcreat(_FileName: CStr, _PermissionMode: int) -> int:
  ...

@native
@native_name("_wfindfirst32")
def pyiWfindfirst32(_FileName: CStr, _FindData: Pointer[PyiWfinddata32T]) -> int64:
  ...

@native
@native_name("_wfindfirst32i64")
def pyiWfindfirst32I64(_FileName: CStr, _FindData: Pointer[PyiWfinddata32i64T]) -> int64:
  ...

@native
@native_name("_wfindfirst64")
def pyiWfindfirst64(_FileName: CStr, _FindData: Pointer[PyiWfinddata64T]) -> int64:
  ...

@native
@native_name("_wfindfirst64i32")
def pyiWfindfirst64I32(_FileName: CStr, _FindData: Pointer[PyiWfinddata64i32T]) -> int64:
  ...

@native
@native_name("_wfindnext32")
def pyiWfindnext32(_FindHandle: int64, _FindData: Pointer[PyiWfinddata32T]) -> int:
  ...

@native
@native_name("_wfindnext32i64")
def pyiWfindnext32I64(_FindHandle: int64, _FindData: Pointer[PyiWfinddata32i64T]) -> int:
  ...

@native
@native_name("_wfindnext64")
def pyiWfindnext64(_FindHandle: int64, _FindData: Pointer[PyiWfinddata64T]) -> int:
  ...

@native
@native_name("_wfindnext64i32")
def pyiWfindnext64I32(_FindHandle: int64, _FindData: Pointer[PyiWfinddata64i32T]) -> int:
  ...

@native
@native_name("_wmktemp")
def pyiWmktemp(_TemplateName: CStr) -> CStr:
  ...

@native
@native_name("_wmktemp_s")
def pyiWmktempS(_TemplateName: CStr, _SizeInWords: uint64) -> int:
  ...

@native
@native_name("_wopen")
def pyiWopen(_FileName: CStr, _OpenFlag: int, *_) -> int:
  ...

@native
@native_name("_wrename")
def pyiWrename(_OldFileName: CStr, _NewFileName: CStr) -> int:
  ...

@overload
@native
@native_name("_write")
def pyiWrite(_FileHandle: int, _Buf: uintptr, _MaxCharCount: uint) -> int:
  ...

@native
@native_name("_wsopen")
def pyiWsopen(_FileName: CStr, _OpenFlag: int, _ShareFlag: int, *_) -> int:
  ...

@native
@native_name("_wsopen_dispatch")
def pyiWsopenDispatch(_FileName: CStr, _OFlag: int, _ShFlag: int, _PMode: int, _PFileHandle: Pointer[int], _BSecure: int) -> int:
  ...

@native
@native_name("_wsopen_s")
def pyiWsopenS(_FileHandle: Pointer[int], _FileName: CStr, _OpenFlag: int, _ShareFlag: int, _PermissionFlag: int) -> int:
  ...

@native
@native_name("_wunlink")
def pyiWunlink(_FileName: CStr) -> int:
  ...

@overload
@native
@native_name("access")
def pyiAccess(_FileName: CStr, _AccessMode: int) -> int:
  ...

@overload
@native
@native_name("chmod")
def pyiChmod(_FileName: CStr, _AccessMode: int) -> int:
  ...

@overload
@native
@native_name("chsize")
def pyiChsize(_FileHandle: int, _Size: int) -> int:
  ...

@overload
@native
@native_name("close")
def pyiClose(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("creat")
def pyiCreat(_FileName: CStr, _PermissionMode: int) -> int:
  ...

@overload
@native
@native_name("dup")
def pyiDup(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("dup2")
def pyiDup2(_FileHandleSrc: int, _FileHandleDst: int) -> int:
  ...

@overload
@native
@native_name("eof")
def pyiEof(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("filelength")
def pyiFilelength(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("isatty")
def pyiIsatty(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("locking")
def pyiLocking(_FileHandle: int, _LockMode: int, _NumOfBytes: int) -> int:
  ...

@overload
@native
@native_name("lseek")
def pyiLseek(_FileHandle: int, _Offset: int, _Origin: int) -> int:
  ...

@overload
@native
@native_name("mktemp")
def pyiMktemp(_TemplateName: CStr) -> CStr:
  ...

@overload
@native
@native_name("open")
def pyiOpen(_FileName: CStr, _OpenFlag: int, *_) -> int:
  ...

@overload
@native
@native_name("read")
def pyiRead(_FileHandle: int, _DstBuf: uintptr, _MaxCharCount: uint) -> int:
  ...

@native
@native_name("remove")
def pyiRemove(_FileName: CStr) -> int:
  ...

@native
@native_name("rename")
def pyiRename(_OldFilename: CStr, _NewFilename: CStr) -> int:
  ...

@overload
@native
@native_name("setmode")
def pyiSetmode(_FileHandle: int, _Mode: int) -> int:
  ...

@overload
@native
@native_name("sopen")
def pyiSopen(_FileName: CStr, _OpenFlag: int, _ShareFlag: int, *_) -> int:
  ...

@overload
@native
@native_name("tell")
def pyiTell(_FileHandle: int) -> int:
  ...

@overload
@native
@native_name("umask")
def pyiUmask(_Mode: int) -> int:
  ...

@overload
@native
@native_name("unlink")
def pyiUnlink(_FileName: CStr) -> int:
  ...

@overload
@native
@native_name("write")
def pyiWrite(_FileHandle: int, _Buf: uintptr, _MaxCharCount: uint) -> int:
  ...

# stats: structs=13 enums=0 aliases=1 consts=30 funcs=90
