# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\math.h
# Generated: 2026-08-17 18:07:10
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint @native_name("_Byte")
  state: uint @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

@native
@native_name("_complex")
class PyiComplex:
  x: float64
  y: float64

@native
@native_name("_double_val")
class PyiDoubleVal:
  ...  # C union

@native
@native_name("_exception")
class PyiExceptionRec:
  type: int
  name: CStr
  arg1: float64
  arg2: float64
  retval: float64

@native
@native_name("_float_const")
class PyiFloatConst:
  ...  # C union

@native
@native_name("_float_val")
class PyiFloatVal:
  ...  # C union

@native
@native_name("_ldouble_val")
class PyiLdoubleVal:
  ...  # C union

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiDomain: int @native_name("DOMAIN") = 1
PyiFpIlogbnan: int @native_name("FP_ILOGBNAN") = 0x7fffffff
PyiFpInfinite: int @native_name("FP_INFINITE") = 1
PyiFpNan: int @native_name("FP_NAN") = 2
PyiFpZero: int @native_name("FP_ZERO") = 0
PyiMathErrexcept: int @native_name("MATH_ERREXCEPT") = 2
PyiMathErrno: int @native_name("MATH_ERRNO") = 1
PyiOverflow: int @native_name("OVERFLOW") = 3
PyiPloss: int @native_name("PLOSS") = 6
PyiSing: int @native_name("SING") = 2
PyiTloss: int @native_name("TLOSS") = 5
PyiUnderflow: int @native_name("UNDERFLOW") = 4
PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiC2: int @native_name("_C2") = 1
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiD0C: int @native_name("_D0_C") = 3
PyiD1C: int @native_name("_D1_C") = 2
PyiD2C: int @native_name("_D2_C") = 1
PyiD3C: int @native_name("_D3_C") = 0
PyiDbias: int @native_name("_DBIAS") = 0x3fe
PyiDoff: int @native_name("_DOFF") = 4
PyiF0C: int @native_name("_F0_C") = 1
PyiF1C: int @native_name("_F1_C") = 0
PyiFbias: int @native_name("_FBIAS") = 0x7e
PyiFeDivbyzero: int @native_name("_FE_DIVBYZERO") = 0x04
PyiFeInexact: int @native_name("_FE_INEXACT") = 0x20
PyiFeInvalid: int @native_name("_FE_INVALID") = 0x01
PyiFeOverflow: int @native_name("_FE_OVERFLOW") = 0x08
PyiFeUnderflow: int @native_name("_FE_UNDERFLOW") = 0x10
PyiFoff: int @native_name("_FOFF") = 7
PyiFpEq: int @native_name("_FP_EQ") = 2
PyiFpGt: int @native_name("_FP_GT") = 4
PyiFpLt: int @native_name("_FP_LT") = 1
PyiFrnd: int @native_name("_FRND") = 1
PyiInfcode: int @native_name("_INFCODE") = 1
PyiL0C: int @native_name("_L0_C") = 3
PyiL1C: int @native_name("_L1_C") = 2
PyiL2C: int @native_name("_L2_C") = 1
PyiL3C: int @native_name("_L3_C") = 0
PyiLbias: int @native_name("_LBIAS") = 0x3fe
PyiLoff: int @native_name("_LOFF") = 4
PyiNancode: int @native_name("_NANCODE") = 2
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("_atof_l")
def pyiAtofL(_String: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> float64:
  ...

@native
@native_name("_cabs")
def pyiCabs(_Complex_value: PyiComplex) -> float64:
  ...

@native
@native_name("_chgsign")
def pyiChgsign(_X: float64) -> float64:
  ...

@native
@native_name("_chgsignf")
def pyiChgsignf(_X: float) -> float:
  ...

@native
@native_name("_chgsignl")
def pyiChgsignl(_X: float64) -> float64:
  ...

@overload
@native
@native_name("_copysign")
def pyiCopysign(_Number: float64, _Sign: float64) -> float64:
  ...

@overload
@native
@native_name("_copysignf")
def pyiCopysignf(_Number: float, _Sign: float) -> float:
  ...

@overload
@native
@native_name("_copysignl")
def pyiCopysignl(_Number: float64, _Sign: float64) -> float64:
  ...

@native
@native_name("_d_int")
def pyiDInt(_Px: Pointer[float64], _Xexp: int) -> int:
  ...

@native
@native_name("_dclass")
def pyiDclass(_X: float64) -> int:
  ...

@native
@native_name("_dexp")
def pyiDexp(_Px: Pointer[float64], _Y: float64, _Eoff: int) -> int:
  ...

@native
@native_name("_dlog")
def pyiDlog(_X: float64, _Baseflag: int) -> float64:
  ...

@native
@native_name("_dnorm")
def pyiDnorm(_Ps: Pointer[uint]) -> int:
  ...

@native
@native_name("_dpcomp")
def pyiDpcomp(_X: float64, _Y: float64) -> int:
  ...

@native
@native_name("_dpoly")
def pyiDpoly(_X: float64, _Tab: Pointer[float64], _N: int) -> float64:
  ...

@native
@native_name("_dscale")
def pyiDscale(_Px: Pointer[float64], _Lexp: int) -> int:
  ...

@native
@native_name("_dsign")
def pyiDsign(_X: float64) -> int:
  ...

@native
@native_name("_dsin")
def pyiDsin(_X: float64, _Qoff: uint) -> float64:
  ...

@native
@native_name("_dtest")
def pyiDtest(_Px: Pointer[float64]) -> int:
  ...

@native
@native_name("_dunscale")
def pyiDunscale(_Pex: Pointer[int], _Px: Pointer[float64]) -> int:
  ...

@native
@native_name("_fd_int")
def pyiFdInt(_Px: Pointer[float], _Xexp: int) -> int:
  ...

@native
@native_name("_fdclass")
def pyiFdclass(_X: float) -> int:
  ...

@native
@native_name("_fdexp")
def pyiFdexp(_Px: Pointer[float], _Y: float, _Eoff: int) -> int:
  ...

@native
@native_name("_fdlog")
def pyiFdlog(_X: float, _Baseflag: int) -> float:
  ...

@native
@native_name("_fdnorm")
def pyiFdnorm(_Ps: Pointer[uint]) -> int:
  ...

@native
@native_name("_fdpcomp")
def pyiFdpcomp(_X: float, _Y: float) -> int:
  ...

@native
@native_name("_fdpoly")
def pyiFdpoly(_X: float, _Tab: Pointer[float], _N: int) -> float:
  ...

@native
@native_name("_fdscale")
def pyiFdscale(_Px: Pointer[float], _Lexp: int) -> int:
  ...

@native
@native_name("_fdsign")
def pyiFdsign(_X: float) -> int:
  ...

@native
@native_name("_fdsin")
def pyiFdsin(_X: float, _Qoff: uint) -> float:
  ...

@native
@native_name("_fdtest")
def pyiFdtest(_Px: Pointer[float]) -> int:
  ...

@native
@native_name("_fdunscale")
def pyiFdunscale(_Pex: Pointer[int], _Px: Pointer[float]) -> int:
  ...

@native
@native_name("_finitef")
def pyiFinitef(_X: float) -> int:
  ...

@native
@native_name("_fpclassf")
def pyiFpclassf(_X: float) -> int:
  ...

@native
@native_name("_fperrraise")
def pyiFperrraise(_Except: int) -> None:
  ...

@native
@native_name("_get_FMA3_enable")
def pyiGetFma3Enable() -> int:
  ...

@overload
@native
@native_name("_hypot")
def pyiHypot(_X: float64, _Y: float64) -> float64:
  ...

@overload
@native
@native_name("_hypotf")
def pyiHypotf(_X: float, _Y: float) -> float:
  ...

@overload
@native
@native_name("_hypotl")
def pyiHypotl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: CStr, _FunctionName: CStr, _FileName: CStr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

@native
@native_name("_isnanf")
def pyiIsnanf(_X: float) -> int:
  ...

@overload
@native
@native_name("_j0")
def pyiJ0(_X: float64) -> float64:
  ...

@overload
@native
@native_name("_j1")
def pyiJ1(_X: float64) -> float64:
  ...

@overload
@native
@native_name("_jn")
def pyiJn(_X: int, _Y: float64) -> float64:
  ...

@native
@native_name("_ld_int")
def pyiLdInt(_Px: Pointer[float64], _Xexp: int) -> int:
  ...

@native
@native_name("_ldclass")
def pyiLdclass(_X: float64) -> int:
  ...

@overload
@native
@native_name("_ldexp")
def pyiLdexp(_Px: Pointer[float64], _Y: float64, _Eoff: int) -> int:
  ...

@native
@native_name("_ldlog")
def pyiLdlog(_X: float64, _Baseflag: int) -> float64:
  ...

@native
@native_name("_ldpcomp")
def pyiLdpcomp(_X: float64, _Y: float64) -> int:
  ...

@native
@native_name("_ldpoly")
def pyiLdpoly(_X: float64, _Tab: Pointer[float64], _N: int) -> float64:
  ...

@native
@native_name("_ldscale")
def pyiLdscale(_Px: Pointer[float64], _Lexp: int) -> int:
  ...

@native
@native_name("_ldsign")
def pyiLdsign(_X: float64) -> int:
  ...

@native
@native_name("_ldsin")
def pyiLdsin(_X: float64, _Qoff: uint) -> float64:
  ...

@native
@native_name("_ldtest")
def pyiLdtest(_Px: Pointer[float64]) -> int:
  ...

@native
@native_name("_ldunscale")
def pyiLdunscale(_Pex: Pointer[int], _Px: Pointer[float64]) -> int:
  ...

@overload
@native
@native_name("_logbf")
def pyiLogbf(_X: float) -> float:
  ...

@native
@native_name("_matherr")
def pyiMatherr(_Except: Pointer[PyiExceptionRec]) -> int:
  ...

@overload
@native
@native_name("_nextafterf")
def pyiNextafterf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("_set_FMA3_enable")
def pyiSetFma3Enable(_Flag: int) -> int:
  ...

@overload
@native
@native_name("_y0")
def pyiY0(_X: float64) -> float64:
  ...

@overload
@native
@native_name("_y1")
def pyiY1(_X: float64) -> float64:
  ...

@overload
@native
@native_name("_yn")
def pyiYn(_X: int, _Y: float64) -> float64:
  ...

@native
@native_name("abs")
def pyiAbs(_X: int) -> int:
  ...

@native
@native_name("acos")
def pyiAcos(_X: float64) -> float64:
  ...

@native
@native_name("acosf")
def pyiAcosf(_X: float) -> float:
  ...

@native
@native_name("acosh")
def pyiAcosh(_X: float64) -> float64:
  ...

@native
@native_name("acoshf")
def pyiAcoshf(_X: float) -> float:
  ...

@native
@native_name("acoshl")
def pyiAcoshl(_X: float64) -> float64:
  ...

@native
@native_name("acosl")
def pyiAcosl(_X: float64) -> float64:
  ...

@native
@native_name("asin")
def pyiAsin(_X: float64) -> float64:
  ...

@native
@native_name("asinf")
def pyiAsinf(_X: float) -> float:
  ...

@native
@native_name("asinh")
def pyiAsinh(_X: float64) -> float64:
  ...

@native
@native_name("asinhf")
def pyiAsinhf(_X: float) -> float:
  ...

@native
@native_name("asinhl")
def pyiAsinhl(_X: float64) -> float64:
  ...

@native
@native_name("asinl")
def pyiAsinl(_X: float64) -> float64:
  ...

@native
@native_name("atan")
def pyiAtan(_X: float64) -> float64:
  ...

@native
@native_name("atan2")
def pyiAtan2(_Y: float64, _X: float64) -> float64:
  ...

@native
@native_name("atan2f")
def pyiAtan2F(_Y: float, _X: float) -> float:
  ...

@native
@native_name("atan2l")
def pyiAtan2L(_Y: float64, _X: float64) -> float64:
  ...

@native
@native_name("atanf")
def pyiAtanf(_X: float) -> float:
  ...

@native
@native_name("atanh")
def pyiAtanh(_X: float64) -> float64:
  ...

@native
@native_name("atanhf")
def pyiAtanhf(_X: float) -> float:
  ...

@native
@native_name("atanhl")
def pyiAtanhl(_X: float64) -> float64:
  ...

@native
@native_name("atanl")
def pyiAtanl(_X: float64) -> float64:
  ...

@native
@native_name("atof")
def pyiAtof(_String: CStr) -> float64:
  ...

@native
@native_name("cbrt")
def pyiCbrt(_X: float64) -> float64:
  ...

@native
@native_name("cbrtf")
def pyiCbrtf(_X: float) -> float:
  ...

@native
@native_name("cbrtl")
def pyiCbrtl(_X: float64) -> float64:
  ...

@native
@native_name("ceil")
def pyiCeil(_X: float64) -> float64:
  ...

@native
@native_name("ceilf")
def pyiCeilf(_X: float) -> float:
  ...

@native
@native_name("ceill")
def pyiCeill(_X: float64) -> float64:
  ...

@overload
@native
@native_name("copysign")
def pyiCopysign(_Number: float64, _Sign: float64) -> float64:
  ...

@overload
@native
@native_name("copysignf")
def pyiCopysignf(_Number: float, _Sign: float) -> float:
  ...

@overload
@native
@native_name("copysignl")
def pyiCopysignl(_Number: float64, _Sign: float64) -> float64:
  ...

@native
@native_name("cos")
def pyiCos(_X: float64) -> float64:
  ...

@native
@native_name("cosf")
def pyiCosf(_X: float) -> float:
  ...

@native
@native_name("cosh")
def pyiCosh(_X: float64) -> float64:
  ...

@native
@native_name("coshf")
def pyiCoshf(_X: float) -> float:
  ...

@native
@native_name("coshl")
def pyiCoshl(_X: float64) -> float64:
  ...

@native
@native_name("cosl")
def pyiCosl(_X: float64) -> float64:
  ...

@native
@native_name("erf")
def pyiErf(_X: float64) -> float64:
  ...

@native
@native_name("erfc")
def pyiErfc(_X: float64) -> float64:
  ...

@native
@native_name("erfcf")
def pyiErfcf(_X: float) -> float:
  ...

@native
@native_name("erfcl")
def pyiErfcl(_X: float64) -> float64:
  ...

@native
@native_name("erff")
def pyiErff(_X: float) -> float:
  ...

@native
@native_name("erfl")
def pyiErfl(_X: float64) -> float64:
  ...

@native
@native_name("exp")
def pyiExp(_X: float64) -> float64:
  ...

@native
@native_name("exp2")
def pyiExp2(_X: float64) -> float64:
  ...

@native
@native_name("exp2f")
def pyiExp2F(_X: float) -> float:
  ...

@native
@native_name("exp2l")
def pyiExp2L(_X: float64) -> float64:
  ...

@native
@native_name("expf")
def pyiExpf(_X: float) -> float:
  ...

@native
@native_name("expl")
def pyiExpl(_X: float64) -> float64:
  ...

@native
@native_name("expm1")
def pyiExpm1(_X: float64) -> float64:
  ...

@native
@native_name("expm1f")
def pyiExpm1F(_X: float) -> float:
  ...

@native
@native_name("expm1l")
def pyiExpm1L(_X: float64) -> float64:
  ...

@native
@native_name("fabs")
def pyiFabs(_X: float64) -> float64:
  ...

@native
@native_name("fabsf")
def pyiFabsf(_X: float) -> float:
  ...

@native
@native_name("fabsl")
def pyiFabsl(_X: float64) -> float64:
  ...

@native
@native_name("fdim")
def pyiFdim(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fdimf")
def pyiFdimf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("fdiml")
def pyiFdiml(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("floor")
def pyiFloor(_X: float64) -> float64:
  ...

@native
@native_name("floorf")
def pyiFloorf(_X: float) -> float:
  ...

@native
@native_name("floorl")
def pyiFloorl(_X: float64) -> float64:
  ...

@native
@native_name("fma")
def pyiFma(_X: float64, _Y: float64, _Z: float64) -> float64:
  ...

@native
@native_name("fmaf")
def pyiFmaf(_X: float, _Y: float, _Z: float) -> float:
  ...

@native
@native_name("fmal")
def pyiFmal(_X: float64, _Y: float64, _Z: float64) -> float64:
  ...

@native
@native_name("fmax")
def pyiFmax(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fmaxf")
def pyiFmaxf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("fmaxl")
def pyiFmaxl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fmin")
def pyiFmin(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fminf")
def pyiFminf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("fminl")
def pyiFminl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fmod")
def pyiFmod(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("fmodf")
def pyiFmodf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("fmodl")
def pyiFmodl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("frexp")
def pyiFrexp(_X: float64, _Y: Pointer[int]) -> float64:
  ...

@native
@native_name("frexpf")
def pyiFrexpf(_X: float, _Y: Pointer[int]) -> float:
  ...

@native
@native_name("frexpl")
def pyiFrexpl(_X: float64, _Y: Pointer[int]) -> float64:
  ...

@overload
@native
@native_name("hypot")
def pyiHypot(_X: float64, _Y: float64) -> float64:
  ...

@overload
@native
@native_name("hypotf")
def pyiHypotf(_X: float, _Y: float) -> float:
  ...

@overload
@native
@native_name("hypotl")
def pyiHypotl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("ilogb")
def pyiIlogb(_X: float64) -> int:
  ...

@native
@native_name("ilogbf")
def pyiIlogbf(_X: float) -> int:
  ...

@native
@native_name("ilogbl")
def pyiIlogbl(_X: float64) -> int:
  ...

@overload
@native
@native_name("j0")
def pyiJ0(_X: float64) -> float64:
  ...

@overload
@native
@native_name("j1")
def pyiJ1(_X: float64) -> float64:
  ...

@overload
@native
@native_name("jn")
def pyiJn(_X: int, _Y: float64) -> float64:
  ...

@native
@native_name("labs")
def pyiLabs(_X: int) -> int:
  ...

@overload
@native
@native_name("ldexp")
def pyiLdexp(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("ldexpf")
def pyiLdexpf(_X: float, _Y: int) -> float:
  ...

@native
@native_name("ldexpl")
def pyiLdexpl(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("lgamma")
def pyiLgamma(_X: float64) -> float64:
  ...

@native
@native_name("lgammaf")
def pyiLgammaf(_X: float) -> float:
  ...

@native
@native_name("lgammal")
def pyiLgammal(_X: float64) -> float64:
  ...

@native
@native_name("llabs")
def pyiLlabs(_X: int64) -> int64:
  ...

@native
@native_name("llrint")
def pyiLlrint(_X: float64) -> int64:
  ...

@native
@native_name("llrintf")
def pyiLlrintf(_X: float) -> int64:
  ...

@native
@native_name("llrintl")
def pyiLlrintl(_X: float64) -> int64:
  ...

@native
@native_name("llround")
def pyiLlround(_X: float64) -> int64:
  ...

@native
@native_name("llroundf")
def pyiLlroundf(_X: float) -> int64:
  ...

@native
@native_name("llroundl")
def pyiLlroundl(_X: float64) -> int64:
  ...

@native
@native_name("log")
def pyiLog(_X: float64) -> float64:
  ...

@native
@native_name("log10")
def pyiLog10(_X: float64) -> float64:
  ...

@native
@native_name("log10f")
def pyiLog10F(_X: float) -> float:
  ...

@native
@native_name("log10l")
def pyiLog10L(_X: float64) -> float64:
  ...

@native
@native_name("log1p")
def pyiLog1P(_X: float64) -> float64:
  ...

@native
@native_name("log1pf")
def pyiLog1Pf(_X: float) -> float:
  ...

@native
@native_name("log1pl")
def pyiLog1Pl(_X: float64) -> float64:
  ...

@native
@native_name("log2")
def pyiLog2(_X: float64) -> float64:
  ...

@native
@native_name("log2f")
def pyiLog2F(_X: float) -> float:
  ...

@native
@native_name("log2l")
def pyiLog2L(_X: float64) -> float64:
  ...

@native
@native_name("logb")
def pyiLogb(_X: float64) -> float64:
  ...

@overload
@native
@native_name("logbf")
def pyiLogbf(_X: float) -> float:
  ...

@native
@native_name("logbl")
def pyiLogbl(_X: float64) -> float64:
  ...

@native
@native_name("logf")
def pyiLogf(_X: float) -> float:
  ...

@native
@native_name("logl")
def pyiLogl(_X: float64) -> float64:
  ...

@native
@native_name("lrint")
def pyiLrint(_X: float64) -> int:
  ...

@native
@native_name("lrintf")
def pyiLrintf(_X: float) -> int:
  ...

@native
@native_name("lrintl")
def pyiLrintl(_X: float64) -> int:
  ...

@native
@native_name("lround")
def pyiLround(_X: float64) -> int:
  ...

@native
@native_name("lroundf")
def pyiLroundf(_X: float) -> int:
  ...

@native
@native_name("lroundl")
def pyiLroundl(_X: float64) -> int:
  ...

@native
@native_name("modf")
def pyiModf(_X: float64, _Y: Pointer[float64]) -> float64:
  ...

@native
@native_name("modff")
def pyiModff(_X: float, _Y: Pointer[float]) -> float:
  ...

@native
@native_name("modfl")
def pyiModfl(_X: float64, _Y: Pointer[float64]) -> float64:
  ...

@native
@native_name("nan")
def pyiNan(_X: CStr) -> float64:
  ...

@native
@native_name("nanf")
def pyiNanf(_X: CStr) -> float:
  ...

@native
@native_name("nanl")
def pyiNanl(_X: CStr) -> float64:
  ...

@native
@native_name("nearbyint")
def pyiNearbyint(_X: float64) -> float64:
  ...

@native
@native_name("nearbyintf")
def pyiNearbyintf(_X: float) -> float:
  ...

@native
@native_name("nearbyintl")
def pyiNearbyintl(_X: float64) -> float64:
  ...

@native
@native_name("nextafter")
def pyiNextafter(_X: float64, _Y: float64) -> float64:
  ...

@overload
@native
@native_name("nextafterf")
def pyiNextafterf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("nextafterl")
def pyiNextafterl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("nexttoward")
def pyiNexttoward(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("nexttowardf")
def pyiNexttowardf(_X: float, _Y: float64) -> float:
  ...

@native
@native_name("nexttowardl")
def pyiNexttowardl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("pow")
def pyiPow(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("powf")
def pyiPowf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("powl")
def pyiPowl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("remainder")
def pyiRemainder(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("remainderf")
def pyiRemainderf(_X: float, _Y: float) -> float:
  ...

@native
@native_name("remainderl")
def pyiRemainderl(_X: float64, _Y: float64) -> float64:
  ...

@native
@native_name("remquo")
def pyiRemquo(_X: float64, _Y: float64, _Z: Pointer[int]) -> float64:
  ...

@native
@native_name("remquof")
def pyiRemquof(_X: float, _Y: float, _Z: Pointer[int]) -> float:
  ...

@native
@native_name("remquol")
def pyiRemquol(_X: float64, _Y: float64, _Z: Pointer[int]) -> float64:
  ...

@native
@native_name("rint")
def pyiRint(_X: float64) -> float64:
  ...

@native
@native_name("rintf")
def pyiRintf(_X: float) -> float:
  ...

@native
@native_name("rintl")
def pyiRintl(_X: float64) -> float64:
  ...

@native
@native_name("round")
def pyiRound(_X: float64) -> float64:
  ...

@native
@native_name("roundf")
def pyiRoundf(_X: float) -> float:
  ...

@native
@native_name("roundl")
def pyiRoundl(_X: float64) -> float64:
  ...

@native
@native_name("scalbln")
def pyiScalbln(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("scalblnf")
def pyiScalblnf(_X: float, _Y: int) -> float:
  ...

@native
@native_name("scalblnl")
def pyiScalblnl(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("scalbn")
def pyiScalbn(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("scalbnf")
def pyiScalbnf(_X: float, _Y: int) -> float:
  ...

@native
@native_name("scalbnl")
def pyiScalbnl(_X: float64, _Y: int) -> float64:
  ...

@native
@native_name("sin")
def pyiSin(_X: float64) -> float64:
  ...

@native
@native_name("sinf")
def pyiSinf(_X: float) -> float:
  ...

@native
@native_name("sinh")
def pyiSinh(_X: float64) -> float64:
  ...

@native
@native_name("sinhf")
def pyiSinhf(_X: float) -> float:
  ...

@native
@native_name("sinhl")
def pyiSinhl(_X: float64) -> float64:
  ...

@native
@native_name("sinl")
def pyiSinl(_X: float64) -> float64:
  ...

@native
@native_name("sqrt")
def pyiSqrt(_X: float64) -> float64:
  ...

@native
@native_name("sqrtf")
def pyiSqrtf(_X: float) -> float:
  ...

@native
@native_name("sqrtl")
def pyiSqrtl(_X: float64) -> float64:
  ...

@native
@native_name("tan")
def pyiTan(_X: float64) -> float64:
  ...

@native
@native_name("tanf")
def pyiTanf(_X: float) -> float:
  ...

@native
@native_name("tanh")
def pyiTanh(_X: float64) -> float64:
  ...

@native
@native_name("tanhf")
def pyiTanhf(_X: float) -> float:
  ...

@native
@native_name("tanhl")
def pyiTanhl(_X: float64) -> float64:
  ...

@native
@native_name("tanl")
def pyiTanl(_X: float64) -> float64:
  ...

@native
@native_name("tgamma")
def pyiTgamma(_X: float64) -> float64:
  ...

@native
@native_name("tgammaf")
def pyiTgammaf(_X: float) -> float:
  ...

@native
@native_name("tgammal")
def pyiTgammal(_X: float64) -> float64:
  ...

@native
@native_name("trunc")
def pyiTrunc(_X: float64) -> float64:
  ...

@native
@native_name("truncf")
def pyiTruncf(_X: float) -> float:
  ...

@native
@native_name("truncl")
def pyiTruncl(_X: float64) -> float64:
  ...

@overload
@native
@native_name("y0")
def pyiY0(_X: float64) -> float64:
  ...

@overload
@native
@native_name("y1")
def pyiY1(_X: float64) -> float64:
  ...

@overload
@native
@native_name("yn")
def pyiYn(_X: int, _Y: float64) -> float64:
  ...

# stats: structs=11 enums=0 aliases=1 consts=55 funcs=245
