# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\sys\stat.h
# Generated: 2026-08-20 20:18:17
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint16 @native_name("_Byte")
  state: uint16 @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint16] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

@native
@native_name("_stat32")
class PyiStat32:
  stDev: uint @native_name("st_dev")
  stIno: uint16 @native_name("st_ino")
  stMode: uint16 @native_name("st_mode")
  stNlink: int16 @native_name("st_nlink")
  stUid: int16 @native_name("st_uid")
  stGid: int16 @native_name("st_gid")
  stRdev: uint @native_name("st_rdev")
  stSize: int @native_name("st_size")
  stAtime: int @native_name("st_atime")
  stMtime: int @native_name("st_mtime")
  stCtime: int @native_name("st_ctime")

@native
@native_name("_stat32i64")
class PyiStat32I64:
  stDev: uint @native_name("st_dev")
  stIno: uint16 @native_name("st_ino")
  stMode: uint16 @native_name("st_mode")
  stNlink: int16 @native_name("st_nlink")
  stUid: int16 @native_name("st_uid")
  stGid: int16 @native_name("st_gid")
  stRdev: uint @native_name("st_rdev")
  stSize: int64 @native_name("st_size")
  stAtime: int @native_name("st_atime")
  stMtime: int @native_name("st_mtime")
  stCtime: int @native_name("st_ctime")

@native
@native_name("_stat64")
class PyiStat64:
  stDev: uint @native_name("st_dev")
  stIno: uint16 @native_name("st_ino")
  stMode: uint16 @native_name("st_mode")
  stNlink: int16 @native_name("st_nlink")
  stUid: int16 @native_name("st_uid")
  stGid: int16 @native_name("st_gid")
  stRdev: uint @native_name("st_rdev")
  stSize: int64 @native_name("st_size")
  stAtime: int64 @native_name("st_atime")
  stMtime: int64 @native_name("st_mtime")
  stCtime: int64 @native_name("st_ctime")

@native
@native_name("_stat64i32")
class PyiStat64I32:
  stDev: uint @native_name("st_dev")
  stIno: uint16 @native_name("st_ino")
  stMode: uint16 @native_name("st_mode")
  stNlink: int16 @native_name("st_nlink")
  stUid: int16 @native_name("st_uid")
  stGid: int16 @native_name("st_gid")
  stRdev: uint @native_name("st_rdev")
  stSize: int @native_name("st_size")
  stAtime: int64 @native_name("st_atime")
  stMtime: int64 @native_name("st_mtime")
  stCtime: int64 @native_name("st_ctime")

@native
@native_name("stat")
class PyiStat:
  stDev: uint @native_name("st_dev")
  stIno: uint16 @native_name("st_ino")
  stMode: uint16 @native_name("st_mode")
  stNlink: int16 @native_name("st_nlink")
  stUid: int16 @native_name("st_uid")
  stGid: int16 @native_name("st_gid")
  stRdev: uint @native_name("st_rdev")
  stSize: int @native_name("st_size")
  stAtime: int64 @native_name("st_atime")
  stMtime: int64 @native_name("st_mtime")
  stCtime: int64 @native_name("st_ctime")

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiSIexec: int @native_name("S_IEXEC") = 0x0040
PyiSIfchr: int @native_name("S_IFCHR") = 0x2000
PyiSIfdir: int @native_name("S_IFDIR") = 0x4000
PyiSIfmt: int @native_name("S_IFMT") = 0xF000
PyiSIfreg: int @native_name("S_IFREG") = 0x8000
PyiSIread: int @native_name("S_IREAD") = 0x0100
PyiSIwrite: int @native_name("S_IWRITE") = 0x0080
PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1
PyiSIfifo: int @native_name("_S_IFIFO") = 0x1000

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("_fstat32")
def pyiFstat32(_FileHandle: int, _Stat: Pointer[PyiStat32]) -> int:
  ...

@native
@native_name("_fstat32i64")
def pyiFstat32I64(_FileHandle: int, _Stat: Pointer[PyiStat32I64]) -> int:
  ...

@native
@native_name("_fstat64")
def pyiFstat64(_FileHandle: int, _Stat: Pointer[PyiStat64]) -> int:
  ...

@native
@native_name("_fstat64i32")
def pyiFstat64I32(_FileHandle: int, _Stat: Pointer[PyiStat64I32]) -> int:
  ...

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: utf16ptr, _FunctionName: utf16ptr, _FileName: utf16ptr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

@native
@native_name("_stat32")
def pyiStat32(_FileName: utf8ptr, _Stat: Pointer[PyiStat32]) -> int:
  ...

@native
@native_name("_stat32i64")
def pyiStat32I64(_FileName: utf8ptr, _Stat: Pointer[PyiStat32I64]) -> int:
  ...

@native
@native_name("_stat64")
def pyiStat64(_FileName: utf8ptr, _Stat: Pointer[PyiStat64]) -> int:
  ...

@native
@native_name("_stat64i32")
def pyiStat64I32(_FileName: utf8ptr, _Stat: Pointer[PyiStat64I32]) -> int:
  ...

@native
@native_name("_wstat32")
def pyiWstat32(_FileName: utf16ptr, _Stat: Pointer[PyiStat32]) -> int:
  ...

@native
@native_name("_wstat32i64")
def pyiWstat32I64(_FileName: utf16ptr, _Stat: Pointer[PyiStat32I64]) -> int:
  ...

@native
@native_name("_wstat64")
def pyiWstat64(_FileName: utf16ptr, _Stat: Pointer[PyiStat64]) -> int:
  ...

@native
@native_name("_wstat64i32")
def pyiWstat64I32(_FileName: utf16ptr, _Stat: Pointer[PyiStat64I32]) -> int:
  ...

# stats: structs=10 enums=0 aliases=1 consts=23 funcs=15
