# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\string.h
# Generated: 2026-08-17 16:07:02
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_Mbstatet")
class PyiMbstatet:
  wchar: uint @native_name("_Wchar")
  byte: uint @native_name("_Byte")
  state: uint @native_name("_State")

@native
@native_name("__crt_locale_pointers::__crt_locale_data")
class PyiCrtLocaleData:
  ...  # C incomplete struct

@native
@native_name("__crt_locale_data_public")
class PyiCrtLocaleDataPublic:
  localePctype: Pointer[uint] @native_name("_locale_pctype")
  localeMbCurMax: int @native_name("_locale_mb_cur_max")
  localeLcCodepage: uint @native_name("_locale_lc_codepage")

@native
@native_name("__crt_locale_pointers")
class PyiCrtLocalePointers:
  locinfo: Pointer[PyiCrtLocaleData]
  mbcinfo: Pointer[PyiCrtMultibyteData]

@native
@native_name("__crt_locale_pointers::__crt_multibyte_data")
class PyiCrtMultibyteData:
  ...  # C incomplete struct

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiMbstateT = PyiMbstatet

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiE2Big: int @native_name("E2BIG") = 7
PyiEacces: int @native_name("EACCES") = 13
PyiEaddrinuse: int @native_name("EADDRINUSE") = 100
PyiEaddrnotavail: int @native_name("EADDRNOTAVAIL") = 101
PyiEafnosupport: int @native_name("EAFNOSUPPORT") = 102
PyiEagain: int @native_name("EAGAIN") = 11
PyiEalready: int @native_name("EALREADY") = 103
PyiEbadf: int @native_name("EBADF") = 9
PyiEbadmsg: int @native_name("EBADMSG") = 104
PyiEbusy: int @native_name("EBUSY") = 16
PyiEcanceled: int @native_name("ECANCELED") = 105
PyiEchild: int @native_name("ECHILD") = 10
PyiEconnaborted: int @native_name("ECONNABORTED") = 106
PyiEconnrefused: int @native_name("ECONNREFUSED") = 107
PyiEconnreset: int @native_name("ECONNRESET") = 108
PyiEdeadlk: int @native_name("EDEADLK") = 36
PyiEdeadlock: int @native_name("EDEADLOCK") = 36
PyiEdestaddrreq: int @native_name("EDESTADDRREQ") = 109
PyiEdom: int @native_name("EDOM") = 33
PyiEexist: int @native_name("EEXIST") = 17
PyiEfault: int @native_name("EFAULT") = 14
PyiEfbig: int @native_name("EFBIG") = 27
PyiEhostunreach: int @native_name("EHOSTUNREACH") = 110
PyiEidrm: int @native_name("EIDRM") = 111
PyiEilseq: int @native_name("EILSEQ") = 42
PyiEinprogress: int @native_name("EINPROGRESS") = 112
PyiEintr: int @native_name("EINTR") = 4
PyiEinval: int @native_name("EINVAL") = 22
PyiEio: int @native_name("EIO") = 5
PyiEisconn: int @native_name("EISCONN") = 113
PyiEisdir: int @native_name("EISDIR") = 21
PyiEloop: int @native_name("ELOOP") = 114
PyiEmfile: int @native_name("EMFILE") = 24
PyiEmlink: int @native_name("EMLINK") = 31
PyiEmsgsize: int @native_name("EMSGSIZE") = 115
PyiEnametoolong: int @native_name("ENAMETOOLONG") = 38
PyiEnetdown: int @native_name("ENETDOWN") = 116
PyiEnetreset: int @native_name("ENETRESET") = 117
PyiEnetunreach: int @native_name("ENETUNREACH") = 118
PyiEnfile: int @native_name("ENFILE") = 23
PyiEnobufs: int @native_name("ENOBUFS") = 119
PyiEnodatA: int @native_name("ENODATA") = 120
PyiEnodev: int @native_name("ENODEV") = 19
PyiEnoent: int @native_name("ENOENT") = 2
PyiEnoexec: int @native_name("ENOEXEC") = 8
PyiEnolck: int @native_name("ENOLCK") = 39
PyiEnolink: int @native_name("ENOLINK") = 121
PyiEnomem: int @native_name("ENOMEM") = 12
PyiEnomsg: int @native_name("ENOMSG") = 122
PyiEnoprotoopt: int @native_name("ENOPROTOOPT") = 123
PyiEnospc: int @native_name("ENOSPC") = 28
PyiEnosr: int @native_name("ENOSR") = 124
PyiEnostr: int @native_name("ENOSTR") = 125
PyiEnosys: int @native_name("ENOSYS") = 40
PyiEnotconn: int @native_name("ENOTCONN") = 126
PyiEnotdir: int @native_name("ENOTDIR") = 20
PyiEnotempty: int @native_name("ENOTEMPTY") = 41
PyiEnotrecoverable: int @native_name("ENOTRECOVERABLE") = 127
PyiEnotsock: int @native_name("ENOTSOCK") = 128
PyiEnotsup: int @native_name("ENOTSUP") = 129
PyiEnotty: int @native_name("ENOTTY") = 25
PyiEnxio: int @native_name("ENXIO") = 6
PyiEopnotsupp: int @native_name("EOPNOTSUPP") = 130
PyiEother: int @native_name("EOTHER") = 131
PyiEoverfloW: int @native_name("EOVERFLOW") = 132
PyiEownerdead: int @native_name("EOWNERDEAD") = 133
PyiEperm: int @native_name("EPERM") = 1
PyiEpipe: int @native_name("EPIPE") = 32
PyiEproto: int @native_name("EPROTO") = 134
PyiEprotonosupport: int @native_name("EPROTONOSUPPORT") = 135
PyiEprototype: int @native_name("EPROTOTYPE") = 136
PyiErange: int @native_name("ERANGE") = 34
PyiErofs: int @native_name("EROFS") = 30
PyiEspipe: int @native_name("ESPIPE") = 29
PyiEsrch: int @native_name("ESRCH") = 3
PyiEtime: int @native_name("ETIME") = 137
PyiEtimedout: int @native_name("ETIMEDOUT") = 138
PyiEtxtbsy: int @native_name("ETXTBSY") = 139
PyiEwouldblock: int @native_name("EWOULDBLOCK") = 140
PyiExdev: int @native_name("EXDEV") = 18
PyiStruncate: int @native_name("STRUNCATE") = 80
PyiArgmax: int @native_name("_ARGMAX") = 100
PyiArmWinapiPartitionDesktopSdkAvailable: int @native_name("_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE") = 1
PyiCrtBuildDesktopApp: int @native_name("_CRT_BUILD_DESKTOP_APP") = 1
PyiCrtFunctionsRequired: int @native_name("_CRT_FUNCTIONS_REQUIRED") = 1
PyiCrtHasC11: int @native_name("_CRT_HAS_C11") = 1
PyiCrtHasCxx17: int @native_name("_CRT_HAS_CXX17") = 0
PyiCrtInternalNonstdcNames: int @native_name("_CRT_INTERNAL_NONSTDC_NAMES") = 1
PyiCrtIntMax: int @native_name("_CRT_INT_MAX") = 2147483647
PyiCrtSecureCppOverloadSecureNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES") = 1
PyiCrtSecureCppOverloadSecureNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY") = 0
PyiCrtSecureCppOverloadStandardNames: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES") = 0
PyiCrtSecureCppOverloadStandardNamesCount: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT") = 0
PyiCrtSecureCppOverloadStandardNamesMemory: int @native_name("_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY") = 0
PyiNlscmperror: int @native_name("_NLSCMPERROR") = 2147483647
PyiSecurecrtFillBufferPattern: int @native_name("_SECURECRT_FILL_BUFFER_PATTERN") = 0xFE
PyiStaticInlineUcrtFunctions: int @native_name("_STATIC_INLINE_UCRT_FUNCTIONS") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("__doserrno")
def pyiDoserrno() -> Pointer[uint]:
  ...

@native
@native_name("__strncnt")
def pyiStrncnt(_String: CStr, _Count: uint64) -> uint64:
  ...

@overload
@native
@native_name("__wcserror")
def pyiWcserror(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("__wcserror_s")
def pyiWcserrorS(_Buffer: CStr, _SizeInWords: uint64, _ErrorMessage: CStr) -> int:
  ...

@native
@native_name("_errno")
def pyiErrno() -> Pointer[int]:
  ...

@native
@native_name("_get_doserrno")
def pyiGetDoserrno(_Value: Pointer[uint]) -> int:
  ...

@native
@native_name("_get_errno")
def pyiGetErrno(_Value: Pointer[int]) -> int:
  ...

@native
@native_name("_invalid_parameter_noinfo")
def pyiInvalidParameterNoinfo() -> None:
  ...

@native
@native_name("_invalid_parameter_noinfo_noreturn")
def pyiInvalidParameterNoinfoNoreturn() -> None:
  ...

@native
@native_name("_invoke_watson")
def pyiInvokeWatson(_Expression: CStr, _FunctionName: CStr, _FileName: CStr, _LineNo: uint, _Reserved: uint64) -> None:
  ...

@overload
@native
@native_name("_memccpy")
def pyiMemccpy(_Dst: uintptr, _Src: uintptr, _Val: int, _MaxCount: uint64) -> uintptr:
  ...

@overload
@native
@native_name("_memicmp")
def pyiMemicmp(_Buf1: uintptr, _Buf2: uintptr, _Size: uint64) -> int:
  ...

@native
@native_name("_memicmp_l")
def pyiMemicmpL(_Buf1: uintptr, _Buf2: uintptr, _Size: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_set_doserrno")
def pyiSetDoserrno(_Value: uint) -> int:
  ...

@native
@native_name("_set_errno")
def pyiSetErrno(_Value: int) -> int:
  ...

@overload
@native
@native_name("_strcmpi")
def pyiStrcmpi(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("_strcoll_l")
def pyiStrcollL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_strdup")
def pyiStrdup(_Source: CStr) -> CStr:
  ...

@overload
@native
@native_name("_strerror")
def pyiStrerror(_ErrorMessage: CStr) -> CStr:
  ...

@overload
@native
@native_name("_strerror_s")
def pyiStrerrorS(_Buffer: CStr, _SizeInBytes: uint64, _ErrorMessage: CStr) -> int:
  ...

@overload
@native
@native_name("_stricmp")
def pyiStricmp(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("_stricmp_l")
def pyiStricmpL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_stricoll")
def pyiStricoll(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("_stricoll_l")
def pyiStricollL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_strlwr")
def pyiStrlwr(_String: CStr) -> CStr:
  ...

@native
@native_name("_strlwr_l")
def pyiStrlwrL(_String: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> CStr:
  ...

@native
@native_name("_strlwr_s")
def pyiStrlwrS(_String: CStr, _Size: uint64) -> int:
  ...

@native
@native_name("_strlwr_s_l")
def pyiStrlwrSL(_String: CStr, _Size: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_strncoll")
def pyiStrncoll(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_strncoll_l")
def pyiStrncollL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_strnicmp")
def pyiStrnicmp(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_strnicmp_l")
def pyiStrnicmpL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_strnicoll")
def pyiStrnicoll(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_strnicoll_l")
def pyiStrnicollL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_strnset")
def pyiStrnset(_Destination: CStr, _Value: int, _Count: uint64) -> CStr:
  ...

@native
@native_name("_strnset_s")
def pyiStrnsetS(_String: CStr, _SizeInBytes: uint64, _Value: int, _MaxCount: uint64) -> int:
  ...

@overload
@native
@native_name("_strrev")
def pyiStrrev(_Str: CStr) -> CStr:
  ...

@overload
@native
@native_name("_strset")
def pyiStrset(_Destination: CStr, _Value: int) -> CStr:
  ...

@native
@native_name("_strset_s")
def pyiStrsetS(_Destination: CStr, _DestinationSize: uint64, _Value: int) -> int:
  ...

@overload
@native
@native_name("_strupr")
def pyiStrupr(_String: CStr) -> CStr:
  ...

@native
@native_name("_strupr_l")
def pyiStruprL(_String: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> CStr:
  ...

@native
@native_name("_strupr_s")
def pyiStruprS(_String: CStr, _Size: uint64) -> int:
  ...

@native
@native_name("_strupr_s_l")
def pyiStruprSL(_String: CStr, _Size: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_strxfrm_l")
def pyiStrxfrmL(_Destination: CStr, _Source: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> uint64:
  ...

@native
@native_name("_wcscoll_l")
def pyiWcscollL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_wcsdup")
def pyiWcsdup(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("_wcserror")
def pyiWcserror(_ErrorNumber: int) -> CStr:
  ...

@overload
@native
@native_name("_wcserror_s")
def pyiWcserrorS(_Buffer: CStr, _SizeInWords: uint64, _ErrorNumber: int) -> int:
  ...

@overload
@native
@native_name("_wcsicmp")
def pyiWcsicmp(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("_wcsicmp_l")
def pyiWcsicmpL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_wcsicoll")
def pyiWcsicoll(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("_wcsicoll_l")
def pyiWcsicollL(_String1: CStr, _String2: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_wcslwr")
def pyiWcslwr(_String: CStr) -> CStr:
  ...

@native
@native_name("_wcslwr_l")
def pyiWcslwrL(_String: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> CStr:
  ...

@native
@native_name("_wcslwr_s")
def pyiWcslwrS(_String: CStr, _SizeInWords: uint64) -> int:
  ...

@native
@native_name("_wcslwr_s_l")
def pyiWcslwrSL(_String: CStr, _SizeInWords: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_wcsncoll")
def pyiWcsncoll(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_wcsncoll_l")
def pyiWcsncollL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_wcsnicmp")
def pyiWcsnicmp(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_wcsnicmp_l")
def pyiWcsnicmpL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_wcsnicoll")
def pyiWcsnicoll(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("_wcsnicoll_l")
def pyiWcsnicollL(_String1: CStr, _String2: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@overload
@native
@native_name("_wcsnset")
def pyiWcsnset(_String: CStr, _Value: uint, _MaxCount: uint64) -> CStr:
  ...

@native
@native_name("_wcsnset_s")
def pyiWcsnsetS(_Destination: CStr, _SizeInWords: uint64, _Value: uint, _MaxCount: uint64) -> int:
  ...

@overload
@native
@native_name("_wcsrev")
def pyiWcsrev(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("_wcsset")
def pyiWcsset(_String: CStr, _Value: uint) -> CStr:
  ...

@native
@native_name("_wcsset_s")
def pyiWcssetS(_Destination: CStr, _SizeInWords: uint64, _Value: uint) -> int:
  ...

@overload
@native
@native_name("_wcsupr")
def pyiWcsupr(_String: CStr) -> CStr:
  ...

@native
@native_name("_wcsupr_l")
def pyiWcsuprL(_String: CStr, _Locale: Pointer[PyiCrtLocalePointers]) -> CStr:
  ...

@native
@native_name("_wcsupr_s")
def pyiWcsuprS(_String: CStr, _Size: uint64) -> int:
  ...

@native
@native_name("_wcsupr_s_l")
def pyiWcsuprSL(_String: CStr, _Size: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> int:
  ...

@native
@native_name("_wcsxfrm_l")
def pyiWcsxfrmL(_Destination: CStr, _Source: CStr, _MaxCount: uint64, _Locale: Pointer[PyiCrtLocalePointers]) -> uint64:
  ...

@overload
@native
@native_name("memccpy")
def pyiMemccpy(_Dst: uintptr, _Src: uintptr, _Val: int, _Size: uint64) -> uintptr:
  ...

@overload
@native
@native_name("memicmp")
def pyiMemicmp(_Buf1: uintptr, _Buf2: uintptr, _Size: uint64) -> int:
  ...

@native
@native_name("strcat")
def pyiStrcat(_Destination: CStr, _Source: CStr) -> CStr:
  ...

@native
@native_name("strcat_s")
def pyiStrcatS(_Destination: CStr, _SizeInBytes: uint64, _Source: CStr) -> int:
  ...

@native
@native_name("strcmp")
def pyiStrcmp(_Str1: CStr, _Str2: CStr) -> int:
  ...

@overload
@native
@native_name("strcmpi")
def pyiStrcmpi(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("strcoll")
def pyiStrcoll(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("strcpy")
def pyiStrcpy(_Destination: CStr, _Source: CStr) -> CStr:
  ...

@native
@native_name("strcpy_s")
def pyiStrcpyS(_Destination: CStr, _SizeInBytes: uint64, _Source: CStr) -> int:
  ...

@native
@native_name("strcspn")
def pyiStrcspn(_Str: CStr, _Control: CStr) -> uint64:
  ...

@overload
@native
@native_name("strdup")
def pyiStrdup(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("strerror")
def pyiStrerror(_ErrorMessage: int) -> CStr:
  ...

@overload
@native
@native_name("strerror_s")
def pyiStrerrorS(_Buffer: CStr, _SizeInBytes: uint64, _ErrorNumber: int) -> int:
  ...

@overload
@native
@native_name("stricmp")
def pyiStricmp(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("strlen")
def pyiStrlen(_Str: CStr) -> uint64:
  ...

@overload
@native
@native_name("strlwr")
def pyiStrlwr(_String: CStr) -> CStr:
  ...

@native
@native_name("strncat")
def pyiStrncat(_Destination: CStr, _Source: CStr, _Count: uint64) -> CStr:
  ...

@native
@native_name("strncat_s")
def pyiStrncatS(_Destination: CStr, _SizeInBytes: uint64, _Source: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("strncmp")
def pyiStrncmp(_Str1: CStr, _Str2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("strncpy")
def pyiStrncpy(_Destination: CStr, _Source: CStr, _Count: uint64) -> CStr:
  ...

@native
@native_name("strncpy_s")
def pyiStrncpyS(_Destination: CStr, _SizeInBytes: uint64, _Source: CStr, _MaxCount: uint64) -> int:
  ...

@overload
@native
@native_name("strnicmp")
def pyiStrnicmp(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("strnlen")
def pyiStrnlen(_String: CStr, _MaxCount: uint64) -> uint64:
  ...

@overload
@native
@native_name("strnset")
def pyiStrnset(_String: CStr, _Value: int, _MaxCount: uint64) -> CStr:
  ...

@native
@native_name("strpbrk")
def pyiStrpbrk(_Str: CStr, _Control: CStr) -> CStr:
  ...

@overload
@native
@native_name("strrev")
def pyiStrrev(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("strset")
def pyiStrset(_String: CStr, _Value: int) -> CStr:
  ...

@native
@native_name("strspn")
def pyiStrspn(_Str: CStr, _Control: CStr) -> uint64:
  ...

@native
@native_name("strtok")
def pyiStrtok(_String: CStr, _Delimiter: CStr) -> CStr:
  ...

@native
@native_name("strtok_s")
def pyiStrtokS(_String: CStr, _Delimiter: CStr, _Context: Pointer[CStr]) -> CStr:
  ...

@overload
@native
@native_name("strupr")
def pyiStrupr(_String: CStr) -> CStr:
  ...

@native
@native_name("strxfrm")
def pyiStrxfrm(_Destination: CStr, _Source: CStr, _MaxCount: uint64) -> uint64:
  ...

@native
@native_name("wcscat")
def pyiWcscat(_Destination: CStr, _Source: CStr) -> CStr:
  ...

@native
@native_name("wcscat_s")
def pyiWcscatS(_Destination: CStr, _SizeInWords: uint64, _Source: CStr) -> int:
  ...

@native
@native_name("wcscmp")
def pyiWcscmp(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("wcscoll")
def pyiWcscoll(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("wcscpy")
def pyiWcscpy(_Destination: CStr, _Source: CStr) -> CStr:
  ...

@native
@native_name("wcscpy_s")
def pyiWcscpyS(_Destination: CStr, _SizeInWords: uint64, _Source: CStr) -> int:
  ...

@native
@native_name("wcscspn")
def pyiWcscspn(_String: CStr, _Control: CStr) -> uint64:
  ...

@overload
@native
@native_name("wcsdup")
def pyiWcsdup(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("wcsicmp")
def pyiWcsicmp(_String1: CStr, _String2: CStr) -> int:
  ...

@overload
@native
@native_name("wcsicoll")
def pyiWcsicoll(_String1: CStr, _String2: CStr) -> int:
  ...

@native
@native_name("wcslen")
def pyiWcslen(_String: CStr) -> uint64:
  ...

@overload
@native
@native_name("wcslwr")
def pyiWcslwr(_String: CStr) -> CStr:
  ...

@native
@native_name("wcsncat")
def pyiWcsncat(_Destination: CStr, _Source: CStr, _Count: uint64) -> CStr:
  ...

@native
@native_name("wcsncat_s")
def pyiWcsncatS(_Destination: CStr, _SizeInWords: uint64, _Source: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("wcsncmp")
def pyiWcsncmp(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("wcsncpy")
def pyiWcsncpy(_Destination: CStr, _Source: CStr, _Count: uint64) -> CStr:
  ...

@native
@native_name("wcsncpy_s")
def pyiWcsncpyS(_Destination: CStr, _SizeInWords: uint64, _Source: CStr, _MaxCount: uint64) -> int:
  ...

@overload
@native
@native_name("wcsnicmp")
def pyiWcsnicmp(_String1: CStr, _String2: CStr, _MaxCount: uint64) -> int:
  ...

@native
@native_name("wcsnlen")
def pyiWcsnlen(_Source: CStr, _MaxCount: uint64) -> uint64:
  ...

@overload
@native
@native_name("wcsnset")
def pyiWcsnset(_String: CStr, _Value: uint, _MaxCount: uint64) -> CStr:
  ...

@native
@native_name("wcspbrk")
def pyiWcspbrk(_String: CStr, _Control: CStr) -> CStr:
  ...

@overload
@native
@native_name("wcsrev")
def pyiWcsrev(_String: CStr) -> CStr:
  ...

@overload
@native
@native_name("wcsset")
def pyiWcsset(_String: CStr, _Value: uint) -> CStr:
  ...

@native
@native_name("wcsspn")
def pyiWcsspn(_String: CStr, _Control: CStr) -> uint64:
  ...

@native
@native_name("wcstok")
def pyiWcstok(_String: CStr, _Delimiter: CStr, _Context: Pointer[CStr]) -> CStr:
  ...

@native
@native_name("wcstok_s")
def pyiWcstokS(_String: CStr, _Delimiter: CStr, _Context: Pointer[CStr]) -> CStr:
  ...

@overload
@native
@native_name("wcsupr")
def pyiWcsupr(_String: CStr) -> CStr:
  ...

@native
@native_name("wcsxfrm")
def pyiWcsxfrm(_Destination: CStr, _Source: CStr, _MaxCount: uint64) -> uint64:
  ...

# stats: structs=5 enums=0 aliases=1 consts=97 funcs=132
