# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/netinet/in.h
# Generated: 2026-08-17 15:28:51
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("in_addr")
class PyiInAddr:
  sAddr: uint @native_name("s_addr")

@native
@native_name("sockaddr_in")
class PyiSockaddrIn:
  sinFamily: uint @native_name("sin_family")
  sinPort: uint @native_name("sin_port")
  sinAddr: PyiInAddr @native_name("sin_addr")

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("htonl")
def pyiHtonl(hostlong: uint) -> uint:
  ...

@native
@native_name("htons")
def pyiHtons(hostshort: uint) -> uint:
  ...

@native
@native_name("ntohl")
def pyiNtohl(netlong: uint) -> uint:
  ...

@native
@native_name("ntohs")
def pyiNtohs(netshort: uint) -> uint:
  ...

# stats: structs=2 enums=0 aliases=0 consts=0 funcs=4
