# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\commdlg.h
# Generated: 2026-08-17 15:22:53
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("HDC__")
class PyiHdc:
  unused: int

@native
@native_name("HINSTANCE__")
class PyiHinstance:
  unused: int

@native
@native_name("HWND__")
class PyiHwnd:
  unused: int

@native
@native_name("_OFNOTIFYA")
class PyiOfnotifyA:
  hdr: PyiTagNmhdr
  lpOfn: Pointer[PyiTagOfna] @native_name("lpOFN")
  pszFile: CStr

@native
@native_name("_OFNOTIFYEXA")
class PyiOfnotifyexA:
  hdr: PyiTagNmhdr
  lpOfn: Pointer[PyiTagOfna] @native_name("lpOFN")
  psf: uintptr
  pidl: uintptr

@native
@native_name("_OFNOTIFYEXW")
class PyiOfnotifyexW:
  hdr: PyiTagNmhdr
  lpOfn: Pointer[PyiTagOfnw] @native_name("lpOFN")
  psf: uintptr
  pidl: uintptr

@native
@native_name("_OFNOTIFYW")
class PyiOfnotifyW:
  hdr: PyiTagNmhdr
  lpOfn: Pointer[PyiTagOfnw] @native_name("lpOFN")
  pszFile: Pointer[uint]

@native
@native_name("tagCHOOSECOLORA")
class PyiTagChoosecolorA:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHwnd]
  rgbResult: uint
  lpCustColors: Pointer[uint]
  flags: uint @native_name("Flags")
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: CStr

@native
@native_name("tagCHOOSECOLORW")
class PyiTagChoosecolorW:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHwnd]
  rgbResult: uint
  lpCustColors: Pointer[uint]
  flags: uint @native_name("Flags")
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: Pointer[uint]

@native
@native_name("tagCHOOSEFONTA")
class PyiTagChoosefontA:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDc: Pointer[PyiHdc] @native_name("hDC")
  lpLogFont: Pointer[PyiTagLogfontA]
  iPointSize: int
  flags: uint @native_name("Flags")
  rgbColors: uint
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: CStr
  hInstance: Pointer[PyiHinstance]
  lpszStyle: CStr
  nFontType: uint
  missingAlignment: uint @native_name("___MISSING_ALIGNMENT__")
  nSizeMin: int
  nSizeMax: int

@native
@native_name("tagCHOOSEFONTW")
class PyiTagChoosefontW:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDc: Pointer[PyiHdc] @native_name("hDC")
  lpLogFont: Pointer[PyiTagLogfontW]
  iPointSize: int
  flags: uint @native_name("Flags")
  rgbColors: uint
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: Pointer[uint]
  hInstance: Pointer[PyiHinstance]
  lpszStyle: Pointer[uint]
  nFontType: uint
  missingAlignment: uint @native_name("___MISSING_ALIGNMENT__")
  nSizeMin: int
  nSizeMax: int

@native
@native_name("tagDEVNAMES")
class PyiTagDevnames:
  wDriverOffset: uint
  wDeviceOffset: uint
  wOutputOffset: uint
  wDefault: uint

@native
@native_name("tagFINDREPLACEA")
class PyiTagFindreplaceA:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  flags: uint @native_name("Flags")
  lpstrFindWhat: CStr
  lpstrReplaceWith: CStr
  wFindWhatLen: uint
  wReplaceWithLen: uint
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: CStr

@native
@native_name("tagFINDREPLACEW")
class PyiTagFindreplaceW:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  flags: uint @native_name("Flags")
  lpstrFindWhat: Pointer[uint]
  lpstrReplaceWith: Pointer[uint]
  wFindWhatLen: uint
  wReplaceWithLen: uint
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: Pointer[uint]

@native
@native_name("tagLOGFONTA")
class PyiTagLogfontA:
  lfHeight: int
  lfWidth: int
  lfEscapement: int
  lfOrientation: int
  lfWeight: int
  lfItalic: int
  lfUnderline: int
  lfStrikeOut: int
  lfCharSet: int
  lfOutPrecision: int
  lfClipPrecision: int
  lfQuality: int
  lfPitchAndFamily: int
  lfFaceName: Pointer[int]  # array

@native
@native_name("tagLOGFONTW")
class PyiTagLogfontW:
  lfHeight: int
  lfWidth: int
  lfEscapement: int
  lfOrientation: int
  lfWeight: int
  lfItalic: int
  lfUnderline: int
  lfStrikeOut: int
  lfCharSet: int
  lfOutPrecision: int
  lfClipPrecision: int
  lfQuality: int
  lfPitchAndFamily: int
  lfFaceName: Pointer[uint]  # array

@native
@native_name("tagNMHDR")
class PyiTagNmhdr:
  hwndFrom: Pointer[PyiHwnd]
  idFrom: uint64
  code: uint

@native
@native_name("tagOFNA")
class PyiTagOfna:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  lpstrFilter: CStr
  lpstrCustomFilter: CStr
  nMaxCustFilter: uint
  nFilterIndex: uint
  lpstrFile: CStr
  nMaxFile: uint
  lpstrFileTitle: CStr
  nMaxFileTitle: uint
  lpstrInitialDir: CStr
  lpstrTitle: CStr
  flags: uint @native_name("Flags")
  nFileOffset: uint
  nFileExtension: uint
  lpstrDefExt: CStr
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: CStr
  pvReserved: uintptr
  dwReserved: uint
  flagsEx: uint @native_name("FlagsEx")

@native
@native_name("tagOFNW")
class PyiTagOfnw:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  lpstrFilter: Pointer[uint]
  lpstrCustomFilter: Pointer[uint]
  nMaxCustFilter: uint
  nFilterIndex: uint
  lpstrFile: Pointer[uint]
  nMaxFile: uint
  lpstrFileTitle: Pointer[uint]
  nMaxFileTitle: uint
  lpstrInitialDir: Pointer[uint]
  lpstrTitle: Pointer[uint]
  flags: uint @native_name("Flags")
  nFileOffset: uint
  nFileExtension: uint
  lpstrDefExt: Pointer[uint]
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: Pointer[uint]
  pvReserved: uintptr
  dwReserved: uint
  flagsEx: uint @native_name("FlagsEx")

@native
@native_name("tagOFN_NT4A")
class PyiTagOFNNt4A:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  lpstrFilter: CStr
  lpstrCustomFilter: CStr
  nMaxCustFilter: uint
  nFilterIndex: uint
  lpstrFile: CStr
  nMaxFile: uint
  lpstrFileTitle: CStr
  nMaxFileTitle: uint
  lpstrInitialDir: CStr
  lpstrTitle: CStr
  flags: uint @native_name("Flags")
  nFileOffset: uint
  nFileExtension: uint
  lpstrDefExt: CStr
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: CStr

@native
@native_name("tagOFN_NT4W")
class PyiTagOFNNt4W:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hInstance: Pointer[PyiHinstance]
  lpstrFilter: Pointer[uint]
  lpstrCustomFilter: Pointer[uint]
  nMaxCustFilter: uint
  nFilterIndex: uint
  lpstrFile: Pointer[uint]
  nMaxFile: uint
  lpstrFileTitle: Pointer[uint]
  nMaxFileTitle: uint
  lpstrInitialDir: Pointer[uint]
  lpstrTitle: Pointer[uint]
  flags: uint @native_name("Flags")
  nFileOffset: uint
  nFileExtension: uint
  lpstrDefExt: Pointer[uint]
  lCustData: int64
  lpfnHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpTemplateName: Pointer[uint]

@native
@native_name("tagPDA")
class PyiTagPda:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDevMode: uintptr
  hDevNames: uintptr
  hDc: Pointer[PyiHdc] @native_name("hDC")
  flags: uint @native_name("Flags")
  nFromPage: uint
  nToPage: uint
  nMinPage: uint
  nMaxPage: uint
  nCopies: uint
  hInstance: Pointer[PyiHinstance]
  lCustData: int64
  lpfnPrintHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpfnSetupHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpPrintTemplateName: CStr
  lpSetupTemplateName: CStr
  hPrintTemplate: uintptr
  hSetupTemplate: uintptr

@native
@native_name("tagPDW")
class PyiTagPdw:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDevMode: uintptr
  hDevNames: uintptr
  hDc: Pointer[PyiHdc] @native_name("hDC")
  flags: uint @native_name("Flags")
  nFromPage: uint
  nToPage: uint
  nMinPage: uint
  nMaxPage: uint
  nCopies: uint
  hInstance: Pointer[PyiHinstance]
  lCustData: int64
  lpfnPrintHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpfnSetupHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpPrintTemplateName: Pointer[uint]
  lpSetupTemplateName: Pointer[uint]
  hPrintTemplate: uintptr
  hSetupTemplate: uintptr

@native
@native_name("tagPOINT")
class PyiTagPoint:
  x: int
  y: int

@native
@native_name("tagPSDA")
class PyiTagPsda:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDevMode: uintptr
  hDevNames: uintptr
  flags: uint @native_name("Flags")
  ptPaperSize: PyiTagPoint
  rtMinMargin: PyiTagRect
  rtMargin: PyiTagRect
  hInstance: Pointer[PyiHinstance]
  lCustData: int64
  lpfnPageSetupHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpfnPagePaintHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpPageSetupTemplateName: CStr
  hPageSetupTemplate: uintptr

@native
@native_name("tagPSDW")
class PyiTagPsdw:
  lStructSize: uint
  hwndOwner: Pointer[PyiHwnd]
  hDevMode: uintptr
  hDevNames: uintptr
  flags: uint @native_name("Flags")
  ptPaperSize: PyiTagPoint
  rtMinMargin: PyiTagRect
  rtMargin: PyiTagRect
  hInstance: Pointer[PyiHinstance]
  lCustData: int64
  lpfnPageSetupHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpfnPagePaintHook: Function[[Pointer[PyiHwnd], uint, uint64, int64], uint64]  # fn ptr
  lpPageSetupTemplateName: Pointer[uint]
  hPageSetupTemplate: uintptr

@native
@native_name("tagRECT")
class PyiTagRect:
  left: int
  top: int
  right: int
  bottom: int

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiChoosecolor = PyiTagChoosecolorW
type PyiChoosecolorA = PyiTagChoosecolorA
type PyiChoosecolorW = PyiTagChoosecolorW
type PyiChoosefont = PyiTagChoosefontW
type PyiChoosefontA = PyiTagChoosefontA
type PyiChoosefontW = PyiTagChoosefontW
type PyiDevnames = PyiTagDevnames
type PyiFindreplace = PyiTagFindreplaceW
type PyiFindreplaceA = PyiTagFindreplaceA
type PyiFindreplaceW = PyiTagFindreplaceW
type PyiOfnotify = PyiOfnotifyW
type PyiOfnotifyA = PyiOfnotifyA
type PyiOfnotifyex = PyiOfnotifyexW
type PyiOfnotifyexA = PyiOfnotifyexA
type PyiOfnotifyexW = PyiOfnotifyexW
type PyiOfnotifyW = PyiOfnotifyW
type PyiOpenfilename = PyiTagOfnw
type PyiOpenfilenameA = PyiTagOfna
type PyiOpenfilenameW = PyiTagOfnw
type PyiOpenfilenameNt4 = PyiTagOFNNt4W
type PyiOpenfilenameNt4A = PyiTagOFNNt4A
type PyiOpenfilenameNt4W = PyiTagOFNNt4W
type PyiPagesetupdlg = PyiTagPsdw
type PyiPagesetupdlgA = PyiTagPsda
type PyiPagesetupdlgW = PyiTagPsdw
type PyiPrintdlg = PyiTagPdw
type PyiPrintdlgA = PyiTagPda
type PyiPrintdlgW = PyiTagPdw

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiBoldFonttype: int @native_name("BOLD_FONTTYPE") = 0x0100
PyiCcAnycolor: int @native_name("CC_ANYCOLOR") = 0x00000100
PyiCcEnablehook: int @native_name("CC_ENABLEHOOK") = 0x00000010
PyiCcEnabletemplate: int @native_name("CC_ENABLETEMPLATE") = 0x00000020
PyiCcEnabletemplatehandle: int @native_name("CC_ENABLETEMPLATEHANDLE") = 0x00000040
PyiCcFullopen: int @native_name("CC_FULLOPEN") = 0x00000002
PyiCcPreventfullopen: int @native_name("CC_PREVENTFULLOPEN") = 0x00000004
PyiCcRgbinit: int @native_name("CC_RGBINIT") = 0x00000001
PyiCcShowhelp: int @native_name("CC_SHOWHELP") = 0x00000008
PyiCcSolidcolor: int @native_name("CC_SOLIDCOLOR") = 0x00000080
PyiCdLbseladd: int @native_name("CD_LBSELADD") = 2
PyiCdLbselchange: int @native_name("CD_LBSELCHANGE") = 0
PyiCdLbselnoitems: int @native_name("CD_LBSELNOITEMS") = -1
PyiCdLbselsub: int @native_name("CD_LBSELSUB") = 1
PyiCfAnsionly: int @native_name("CF_ANSIONLY") = 0x00000400
PyiCfApply: int @native_name("CF_APPLY") = 0x00000200
PyiCfEffects: int @native_name("CF_EFFECTS") = 0x00000100
PyiCfEnablehook: int @native_name("CF_ENABLEHOOK") = 0x00000008
PyiCfEnabletemplate: int @native_name("CF_ENABLETEMPLATE") = 0x00000010
PyiCfEnabletemplatehandle: int @native_name("CF_ENABLETEMPLATEHANDLE") = 0x00000020
PyiCfFixedpitchonly: int @native_name("CF_FIXEDPITCHONLY") = 0x00004000
PyiCfForcefontexist: int @native_name("CF_FORCEFONTEXIST") = 0x00010000
PyiCfInactivefonts: int @native_name("CF_INACTIVEFONTS") = 0x02000000
PyiCfInittologfontstruct: int @native_name("CF_INITTOLOGFONTSTRUCT") = 0x00000040
PyiCfLimitsize: int @native_name("CF_LIMITSIZE") = 0x00002000
PyiCfNofacesel: int @native_name("CF_NOFACESEL") = 0x00080000
PyiCfNooemfonts: int @native_name("CF_NOOEMFONTS") = 0x00000800
PyiCfNoscriptsel: int @native_name("CF_NOSCRIPTSEL") = 0x00800000
PyiCfNosimulations: int @native_name("CF_NOSIMULATIONS") = 0x00001000
PyiCfNosizesel: int @native_name("CF_NOSIZESEL") = 0x00200000
PyiCfNostylesel: int @native_name("CF_NOSTYLESEL") = 0x00100000
PyiCfNovectorfonts: int @native_name("CF_NOVECTORFONTS") = 0x00000800
PyiCfNovertfonts: int @native_name("CF_NOVERTFONTS") = 0x01000000
PyiCfPrinterfonts: int @native_name("CF_PRINTERFONTS") = 0x00000002
PyiCfScalableonly: int @native_name("CF_SCALABLEONLY") = 0x00020000
PyiCfScreenfonts: int @native_name("CF_SCREENFONTS") = 0x00000001
PyiCfScriptsonly: int @native_name("CF_SCRIPTSONLY") = 0x00000400
PyiCfSelectscript: int @native_name("CF_SELECTSCRIPT") = 0x00400000
PyiCfShowhelp: int @native_name("CF_SHOWHELP") = 0x00000004
PyiCfTtonly: int @native_name("CF_TTONLY") = 0x00040000
PyiCfUsestyle: int @native_name("CF_USESTYLE") = 0x00000080
PyiCfWysiwyg: int @native_name("CF_WYSIWYG") = 0x00008000
PyiColorokstring: str @native_name("COLOROKSTRING") = "commdlg_ColorOK"
PyiColorokstringA: str @native_name("COLOROKSTRINGA") = "commdlg_ColorOK"
PyiColorokstringW: str @native_name("COLOROKSTRINGW") = "commdlg_ColorOK"
PyiDnDefaultprn: int @native_name("DN_DEFAULTPRN") = 0x0001
PyiFileokstring: str @native_name("FILEOKSTRING") = "commdlg_FileNameOK"
PyiFileokstringA: str @native_name("FILEOKSTRINGA") = "commdlg_FileNameOK"
PyiFileokstringW: str @native_name("FILEOKSTRINGW") = "commdlg_FileNameOK"
PyiFindmsgstring: str @native_name("FINDMSGSTRING") = "commdlg_FindReplace"
PyiFindmsgstringA: str @native_name("FINDMSGSTRINGA") = "commdlg_FindReplace"
PyiFindmsgstringW: str @native_name("FINDMSGSTRINGW") = "commdlg_FindReplace"
PyiFrDialogterm: int @native_name("FR_DIALOGTERM") = 0x00000040
PyiFrDown: int @native_name("FR_DOWN") = 0x00000001
PyiFrEnablehook: int @native_name("FR_ENABLEHOOK") = 0x00000100
PyiFrEnabletemplate: int @native_name("FR_ENABLETEMPLATE") = 0x00000200
PyiFrEnabletemplatehandle: int @native_name("FR_ENABLETEMPLATEHANDLE") = 0x00002000
PyiFrFindnext: int @native_name("FR_FINDNEXT") = 0x00000008
PyiFrHidematchcase: int @native_name("FR_HIDEMATCHCASE") = 0x00008000
PyiFrHideupdown: int @native_name("FR_HIDEUPDOWN") = 0x00004000
PyiFrHidewholeword: int @native_name("FR_HIDEWHOLEWORD") = 0x00010000
PyiFrMatchalefhamzA: int @native_name("FR_MATCHALEFHAMZA") = 0x80000000
PyiFrMatchcase: int @native_name("FR_MATCHCASE") = 0x00000004
PyiFrMatchdiac: int @native_name("FR_MATCHDIAC") = 0x20000000
PyiFrMatchkashidA: int @native_name("FR_MATCHKASHIDA") = 0x40000000
PyiFrNomatchcase: int @native_name("FR_NOMATCHCASE") = 0x00000800
PyiFrNoupdown: int @native_name("FR_NOUPDOWN") = 0x00000400
PyiFrNowholeword: int @native_name("FR_NOWHOLEWORD") = 0x00001000
PyiFrNowraparound: int @native_name("FR_NOWRAPAROUND") = 0x00080000
PyiFrRaw: int @native_name("FR_RAW") = 0x00020000
PyiFrReplace: int @native_name("FR_REPLACE") = 0x00000010
PyiFrReplaceall: int @native_name("FR_REPLACEALL") = 0x00000020
PyiFrShowhelp: int @native_name("FR_SHOWHELP") = 0x00000080
PyiFrShowwraparound: int @native_name("FR_SHOWWRAPAROUND") = 0x00040000
PyiFrWholeword: int @native_name("FR_WHOLEWORD") = 0x00000002
PyiFrWraparound: int @native_name("FR_WRAPAROUND") = 0x00100000
PyiHelpmsgstring: str @native_name("HELPMSGSTRING") = "commdlg_help"
PyiHelpmsgstringA: str @native_name("HELPMSGSTRINGA") = "commdlg_help"
PyiHelpmsgstringW: str @native_name("HELPMSGSTRINGW") = "commdlg_help"
PyiItalicFonttype: int @native_name("ITALIC_FONTTYPE") = 0x0200
PyiLbselchstring: str @native_name("LBSELCHSTRING") = "commdlg_LBSelChangedNotify"
PyiLbselchstringA: str @native_name("LBSELCHSTRINGA") = "commdlg_LBSelChangedNotify"
PyiLbselchstringW: str @native_name("LBSELCHSTRINGW") = "commdlg_LBSelChangedNotify"
PyiOfnAllowmultiselect: int @native_name("OFN_ALLOWMULTISELECT") = 0x00000200
PyiOfnCreateprompt: int @native_name("OFN_CREATEPROMPT") = 0x00002000
PyiOfnDontaddtorecent: int @native_name("OFN_DONTADDTORECENT") = 0x02000000
PyiOfnEnablehook: int @native_name("OFN_ENABLEHOOK") = 0x00000020
PyiOfnEnableincludenotify: int @native_name("OFN_ENABLEINCLUDENOTIFY") = 0x00400000
PyiOfnEnablesizing: int @native_name("OFN_ENABLESIZING") = 0x00800000
PyiOfnEnabletemplate: int @native_name("OFN_ENABLETEMPLATE") = 0x00000040
PyiOfnEnabletemplatehandle: int @native_name("OFN_ENABLETEMPLATEHANDLE") = 0x00000080
PyiOfnExplorer: int @native_name("OFN_EXPLORER") = 0x00080000
PyiOfnExtensiondifferent: int @native_name("OFN_EXTENSIONDIFFERENT") = 0x00000400
PyiOfnExNoplacesbar: int @native_name("OFN_EX_NOPLACESBAR") = 0x00000001
PyiOfnFilemustexist: int @native_name("OFN_FILEMUSTEXIST") = 0x00001000
PyiOfnForceshowhidden: int @native_name("OFN_FORCESHOWHIDDEN") = 0x10000000
PyiOfnHidereadonly: int @native_name("OFN_HIDEREADONLY") = 0x00000004
PyiOfnLongnames: int @native_name("OFN_LONGNAMES") = 0x00200000
PyiOfnNochangedir: int @native_name("OFN_NOCHANGEDIR") = 0x00000008
PyiOfnNodereferencelinks: int @native_name("OFN_NODEREFERENCELINKS") = 0x00100000
PyiOfnNolongnames: int @native_name("OFN_NOLONGNAMES") = 0x00040000
PyiOfnNonetworkbutton: int @native_name("OFN_NONETWORKBUTTON") = 0x00020000
PyiOfnNoreadonlyreturn: int @native_name("OFN_NOREADONLYRETURN") = 0x00008000
PyiOfnNotestfilecreate: int @native_name("OFN_NOTESTFILECREATE") = 0x00010000
PyiOfnNovalidate: int @native_name("OFN_NOVALIDATE") = 0x00000100
PyiOfnOverwriteprompt: int @native_name("OFN_OVERWRITEPROMPT") = 0x00000002
PyiOfnPathmustexist: int @native_name("OFN_PATHMUSTEXIST") = 0x00000800
PyiOfnReadonly: int @native_name("OFN_READONLY") = 0x00000001
PyiOfnShareaware: int @native_name("OFN_SHAREAWARE") = 0x00004000
PyiOfnSharefallthrough: int @native_name("OFN_SHAREFALLTHROUGH") = 2
PyiOfnSharenowarn: int @native_name("OFN_SHARENOWARN") = 1
PyiOfnSharewarn: int @native_name("OFN_SHAREWARN") = 0
PyiOfnShowhelp: int @native_name("OFN_SHOWHELP") = 0x00000010
PyiPdAllpages: int @native_name("PD_ALLPAGES") = 0x00000000
PyiPdCollate: int @native_name("PD_COLLATE") = 0x00000010
PyiPdCurrentpage: int @native_name("PD_CURRENTPAGE") = 0x00400000
PyiPdDisableprinttofile: int @native_name("PD_DISABLEPRINTTOFILE") = 0x00080000
PyiPdEnableprinthook: int @native_name("PD_ENABLEPRINTHOOK") = 0x00001000
PyiPdEnableprinttemplate: int @native_name("PD_ENABLEPRINTTEMPLATE") = 0x00004000
PyiPdEnableprinttemplatehandle: int @native_name("PD_ENABLEPRINTTEMPLATEHANDLE") = 0x00010000
PyiPdEnablesetuphook: int @native_name("PD_ENABLESETUPHOOK") = 0x00002000
PyiPdEnablesetuptemplate: int @native_name("PD_ENABLESETUPTEMPLATE") = 0x00008000
PyiPdEnablesetuptemplatehandle: int @native_name("PD_ENABLESETUPTEMPLATEHANDLE") = 0x00020000
PyiPdExclusionflags: int @native_name("PD_EXCLUSIONFLAGS") = 0x01000000
PyiPdHideprinttofile: int @native_name("PD_HIDEPRINTTOFILE") = 0x00100000
PyiPdNocurrentpage: int @native_name("PD_NOCURRENTPAGE") = 0x00800000
PyiPdNonetworkbutton: int @native_name("PD_NONETWORKBUTTON") = 0x00200000
PyiPdNopagenums: int @native_name("PD_NOPAGENUMS") = 0x00000008
PyiPdNoselection: int @native_name("PD_NOSELECTION") = 0x00000004
PyiPdNowarning: int @native_name("PD_NOWARNING") = 0x00000080
PyiPdPagenums: int @native_name("PD_PAGENUMS") = 0x00000002
PyiPdPrintsetup: int @native_name("PD_PRINTSETUP") = 0x00000040
PyiPdPrinttofile: int @native_name("PD_PRINTTOFILE") = 0x00000020
PyiPdResultApply: int @native_name("PD_RESULT_APPLY") = 2
PyiPdResultCancel: int @native_name("PD_RESULT_CANCEL") = 0
PyiPdResultPrint: int @native_name("PD_RESULT_PRINT") = 1
PyiPdReturndc: int @native_name("PD_RETURNDC") = 0x00000100
PyiPdReturndefault: int @native_name("PD_RETURNDEFAULT") = 0x00000400
PyiPdReturnic: int @native_name("PD_RETURNIC") = 0x00000200
PyiPdSelection: int @native_name("PD_SELECTION") = 0x00000001
PyiPdShowhelp: int @native_name("PD_SHOWHELP") = 0x00000800
PyiPdUsedevmodecopies: int @native_name("PD_USEDEVMODECOPIES") = 0x00040000
PyiPdUsedevmodecopiesandcollate: int @native_name("PD_USEDEVMODECOPIESANDCOLLATE") = 0x00040000
PyiPdUselargetemplate: int @native_name("PD_USELARGETEMPLATE") = 0x10000000
PyiPrinterFonttype: int @native_name("PRINTER_FONTTYPE") = 0x4000
PyiPsdDefaultminmargins: int @native_name("PSD_DEFAULTMINMARGINS") = 0x00000000
PyiPsdDisablemargins: int @native_name("PSD_DISABLEMARGINS") = 0x00000010
PyiPsdDisableorientation: int @native_name("PSD_DISABLEORIENTATION") = 0x00000100
PyiPsdDisablepagepainting: int @native_name("PSD_DISABLEPAGEPAINTING") = 0x00080000
PyiPsdDisablepaper: int @native_name("PSD_DISABLEPAPER") = 0x00000200
PyiPsdDisableprinter: int @native_name("PSD_DISABLEPRINTER") = 0x00000020
PyiPsdEnablepagepainthook: int @native_name("PSD_ENABLEPAGEPAINTHOOK") = 0x00040000
PyiPsdEnablepagesetuphook: int @native_name("PSD_ENABLEPAGESETUPHOOK") = 0x00002000
PyiPsdEnablepagesetuptemplate: int @native_name("PSD_ENABLEPAGESETUPTEMPLATE") = 0x00008000
PyiPsdEnablepagesetuptemplatehandle: int @native_name("PSD_ENABLEPAGESETUPTEMPLATEHANDLE") = 0x00020000
PyiPsdInhundredthsofmillimeters: int @native_name("PSD_INHUNDREDTHSOFMILLIMETERS") = 0x00000008
PyiPsdInthousandthsofinches: int @native_name("PSD_INTHOUSANDTHSOFINCHES") = 0x00000004
PyiPsdInwininiintlmeasure: int @native_name("PSD_INWININIINTLMEASURE") = 0x00000000
PyiPsdMargins: int @native_name("PSD_MARGINS") = 0x00000002
PyiPsdMinmargins: int @native_name("PSD_MINMARGINS") = 0x00000001
PyiPsdNonetworkbutton: int @native_name("PSD_NONETWORKBUTTON") = 0x00200000
PyiPsdNowarning: int @native_name("PSD_NOWARNING") = 0x00000080
PyiPsdReturndefault: int @native_name("PSD_RETURNDEFAULT") = 0x00000400
PyiPsdShowhelp: int @native_name("PSD_SHOWHELP") = 0x00000800
PyiPsOpentypeFonttype: int @native_name("PS_OPENTYPE_FONTTYPE") = 0x10000
PyiRegularFonttype: int @native_name("REGULAR_FONTTYPE") = 0x0400
PyiScreenFonttype: int @native_name("SCREEN_FONTTYPE") = 0x2000
PyiSetrgbstring: str @native_name("SETRGBSTRING") = "commdlg_SetRGBColor"
PyiSetrgbstringA: str @native_name("SETRGBSTRINGA") = "commdlg_SetRGBColor"
PyiSetrgbstringW: str @native_name("SETRGBSTRINGW") = "commdlg_SetRGBColor"
PyiSharevistring: str @native_name("SHAREVISTRING") = "commdlg_ShareViolation"
PyiSharevistringA: str @native_name("SHAREVISTRINGA") = "commdlg_ShareViolation"
PyiSharevistringW: str @native_name("SHAREVISTRINGW") = "commdlg_ShareViolation"
PyiSimulatedFonttype: int @native_name("SIMULATED_FONTTYPE") = 0x8000
PyiStartPageGeneral: int @native_name("START_PAGE_GENERAL") = 0xffffffff
PyiSymbolFonttype: int @native_name("SYMBOL_FONTTYPE") = 0x80000
PyiTtOpentypeFonttype: int @native_name("TT_OPENTYPE_FONTTYPE") = 0x20000
PyiType1Fonttype: int @native_name("TYPE1_FONTTYPE") = 0x40000

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("ChooseColorA")
def pyiChooseColorA(arg0: Pointer[PyiTagChoosecolorA]) -> int:
  ...

@native
@native_name("ChooseColorW")
def pyiChooseColorW(arg0: Pointer[PyiTagChoosecolorW]) -> int:
  ...

@native
@native_name("ChooseFontA")
def pyiChooseFontA(arg0: Pointer[PyiTagChoosefontA]) -> int:
  ...

@native
@native_name("ChooseFontW")
def pyiChooseFontW(arg0: Pointer[PyiTagChoosefontW]) -> int:
  ...

@native
@native_name("CommDlgExtendedError")
def pyiCommDlgExtendedError() -> uint:
  ...

@native
@native_name("FindTextA")
def pyiFindTextA(arg0: Pointer[PyiTagFindreplaceA]) -> Pointer[PyiHwnd]:
  ...

@native
@native_name("FindTextW")
def pyiFindTextW(arg0: Pointer[PyiTagFindreplaceW]) -> Pointer[PyiHwnd]:
  ...

@native
@native_name("GetFileTitleA")
def pyiGetFileTitleA(arg0: CStr, Buf: CStr, cchSize: uint) -> int:
  ...

@native
@native_name("GetFileTitleW")
def pyiGetFileTitleW(arg0: Pointer[uint], Buf: Pointer[uint], cchSize: uint) -> int:
  ...

@native
@native_name("GetOpenFileNameA")
def pyiGetOpenFileNameA(arg0: Pointer[PyiTagOfna]) -> int:
  ...

@native
@native_name("GetOpenFileNameW")
def pyiGetOpenFileNameW(arg0: Pointer[PyiTagOfnw]) -> int:
  ...

@native
@native_name("GetSaveFileNameA")
def pyiGetSaveFileNameA(arg0: Pointer[PyiTagOfna]) -> int:
  ...

@native
@native_name("GetSaveFileNameW")
def pyiGetSaveFileNameW(arg0: Pointer[PyiTagOfnw]) -> int:
  ...

@native
@native_name("PageSetupDlgA")
def pyiPageSetupDlgA(arg0: Pointer[PyiTagPsda]) -> int:
  ...

@native
@native_name("PageSetupDlgW")
def pyiPageSetupDlgW(arg0: Pointer[PyiTagPsdw]) -> int:
  ...

@native
@native_name("PrintDlgA")
def pyiPrintDlgA(pPD: Pointer[PyiTagPda]) -> int:
  ...

@native
@native_name("PrintDlgW")
def pyiPrintDlgW(pPD: Pointer[PyiTagPdw]) -> int:
  ...

@native
@native_name("ReplaceTextA")
def pyiReplaceTextA(arg0: Pointer[PyiTagFindreplaceA]) -> Pointer[PyiHwnd]:
  ...

@native
@native_name("ReplaceTextW")
def pyiReplaceTextW(arg0: Pointer[PyiTagFindreplaceW]) -> Pointer[PyiHwnd]:
  ...

# stats: structs=27 enums=0 aliases=28 consts=178 funcs=19
