# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\WinSock2.h
# Generated: 2026-08-17 15:19:50
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("HWND__")
class PyiHwnd:
  unused: int

@native
@native_name("SOCK_NOTIFY_REGISTRATION")
class PyiSockNotifyRegistration:
  socket: uint64
  completionKey: uintptr
  eventFilter: uint
  operation: int
  triggerFlags: int
  registrationResult: uint

@native
@native_name("WSAData")
class PyiWsadAta:
  wVersion: uint
  wHighVersion: uint
  iMaxSockets: uint
  iMaxUdpDg: uint
  lpVendorInfo: CStr
  szDescription: Pointer[int]  # array
  szSystemStatus: Pointer[int]  # array

@native
@native_name("_AFPROTOCOLS")
class PyiAfprotocols:
  iAddressFamily: int
  iProtocol: int

@native
@native_name("_BLOB")
class PyiBlob:
  cbSize: uint
  pBlobData: Pointer[int]

@native
@native_name("_CSADDR_INFO")
class PyiCsaddrInfo:
  localAddr: PyiSocketAddress @native_name("LocalAddr")
  remoteAddr: PyiSocketAddress @native_name("RemoteAddr")
  iSocketType: int
  iProtocol: int

@native
@native_name("_GUID")
class PyiGuid:
  data1: uint @native_name("Data1")
  data2: uint @native_name("Data2")
  data3: uint @native_name("Data3")
  data4: Pointer[int] @native_name("Data4")  # array

@native
@native_name("_OVERLAPPED")
class PyiOverlapped:
  internal: uint64 @native_name("Internal")
  internalHigh: uint64 @native_name("InternalHigh")
  hEvent: uintptr

@native
@native_name("_OVERLAPPED_ENTRY")
class PyiOverlappedEntry:
  lpCompletionKey: uint64
  lpOverlapped: Pointer[PyiOverlapped]
  internal: uint64 @native_name("Internal")
  dwNumberOfBytesTransferred: uint

@native
@native_name("_QualityOfService")
class PyiQualityOfService:
  sendingFlowspec: PyiFlowspec @native_name("SendingFlowspec")
  receivingFlowspec: PyiFlowspec @native_name("ReceivingFlowspec")
  providerSpecific: PyiWsabuf @native_name("ProviderSpecific")

@native
@native_name("_SOCKET_ADDRESS")
class PyiSocketAddress:
  lpSockaddr: Pointer[PyiSockaddr]
  iSockaddrLength: int

@native
@native_name("_SOCKET_ADDRESS_LIST")
class PyiSocketAddressList:
  iAddressCount: int
  address: Pointer[PyiSocketAddress] @native_name("Address")  # array

@native
@native_name("_WSABUF")
class PyiWsabuf:
  len: uint
  buf: Pointer[int]

@native
@native_name("_WSACOMPLETION")
class PyiWsacompletion:
  type: PyiWsacompletiontype @native_name("Type")
  parameters: None @native_name("Parameters")  # C: unnamed union

@native
@native_name("_WSAMSG")
class PyiWsamsg:
  name: Pointer[PyiSockaddr]
  namelen: int
  lpBuffers: Pointer[PyiWsabuf]
  dwBufferCount: uint
  control: PyiWsabuf @native_name("Control")
  dwFlags: uint

@native
@native_name("_WSANAMESPACE_INFOA")
class PyiWsanamespaceInfoa:
  nsProviderId: PyiGuid @native_name("NSProviderId")
  dwNameSpace: uint
  fActive: int
  dwVersion: uint
  lpszIdentifier: CStr

@native
@native_name("_WSANAMESPACE_INFOEXA")
class PyiWsanamespaceInfoexA:
  nsProviderId: PyiGuid @native_name("NSProviderId")
  dwNameSpace: uint
  fActive: int
  dwVersion: uint
  lpszIdentifier: CStr
  providerSpecific: PyiBlob @native_name("ProviderSpecific")

@native
@native_name("_WSANAMESPACE_INFOEXW")
class PyiWsanamespaceInfoexW:
  nsProviderId: PyiGuid @native_name("NSProviderId")
  dwNameSpace: uint
  fActive: int
  dwVersion: uint
  lpszIdentifier: Pointer[uint]
  providerSpecific: PyiBlob @native_name("ProviderSpecific")

@native
@native_name("_WSANAMESPACE_INFOW")
class PyiWsanamespaceInfow:
  nsProviderId: PyiGuid @native_name("NSProviderId")
  dwNameSpace: uint
  fActive: int
  dwVersion: uint
  lpszIdentifier: Pointer[uint]

@native
@native_name("_WSANETWORKEVENTS")
class PyiWsanetworkevents:
  lNetworkEvents: int
  iErrorCode: Pointer[int]  # array

@native
@native_name("_WSANSClassInfoA")
class PyiWsansClassInfoA:
  lpszName: CStr
  dwNameSpace: uint
  dwValueType: uint
  dwValueSize: uint
  lpValue: uintptr

@native
@native_name("_WSANSClassInfoW")
class PyiWsansClassInfoW:
  lpszName: Pointer[uint]
  dwNameSpace: uint
  dwValueType: uint
  dwValueSize: uint
  lpValue: uintptr

@native
@native_name("_WSAPROTOCOLCHAIN")
class PyiWsaprotocolchain:
  chainLen: int @native_name("ChainLen")
  chainEntries: Pointer[uint] @native_name("ChainEntries")  # array

@native
@native_name("_WSAPROTOCOL_INFOA")
class PyiWsaprotocolInfoa:
  dwServiceFlags1: uint
  dwServiceFlags2: uint
  dwServiceFlags3: uint
  dwServiceFlags4: uint
  dwProviderFlags: uint
  providerId: PyiGuid @native_name("ProviderId")
  dwCatalogEntryId: uint
  protocolChain: PyiWsaprotocolchain @native_name("ProtocolChain")
  iVersion: int
  iAddressFamily: int
  iMaxSockAddr: int
  iMinSockAddr: int
  iSocketType: int
  iProtocol: int
  iProtocolMaxOffset: int
  iNetworkByteOrder: int
  iSecurityScheme: int
  dwMessageSize: uint
  dwProviderReserved: uint
  szProtocol: Pointer[int]  # array

@native
@native_name("_WSAPROTOCOL_INFOW")
class PyiWsaprotocolInfow:
  dwServiceFlags1: uint
  dwServiceFlags2: uint
  dwServiceFlags3: uint
  dwServiceFlags4: uint
  dwProviderFlags: uint
  providerId: PyiGuid @native_name("ProviderId")
  dwCatalogEntryId: uint
  protocolChain: PyiWsaprotocolchain @native_name("ProtocolChain")
  iVersion: int
  iAddressFamily: int
  iMaxSockAddr: int
  iMinSockAddr: int
  iSocketType: int
  iProtocol: int
  iProtocolMaxOffset: int
  iNetworkByteOrder: int
  iSecurityScheme: int
  dwMessageSize: uint
  dwProviderReserved: uint
  szProtocol: Pointer[uint]  # array

@native
@native_name("_WSAQuerySet2A")
class PyiWsaQuerySet2A:
  dwSize: uint
  lpszServiceInstanceName: CStr
  lpVersion: Pointer[PyiWsavErsion]
  lpszComment: CStr
  dwNameSpace: uint
  lpNsProviderId: Pointer[PyiGuid] @native_name("lpNSProviderId")
  lpszContext: CStr
  dwNumberOfProtocols: uint
  lpafpProtocols: Pointer[PyiAfprotocols]
  lpszQueryString: CStr
  dwNumberOfCsAddrs: uint
  lpcsaBuffer: Pointer[PyiCsaddrInfo]
  dwOutputFlags: uint
  lpBlob: Pointer[PyiBlob]

@native
@native_name("_WSAQuerySet2W")
class PyiWsaQuerySet2W:
  dwSize: uint
  lpszServiceInstanceName: Pointer[uint]
  lpVersion: Pointer[PyiWsavErsion]
  lpszComment: Pointer[uint]
  dwNameSpace: uint
  lpNsProviderId: Pointer[PyiGuid] @native_name("lpNSProviderId")
  lpszContext: Pointer[uint]
  dwNumberOfProtocols: uint
  lpafpProtocols: Pointer[PyiAfprotocols]
  lpszQueryString: Pointer[uint]
  dwNumberOfCsAddrs: uint
  lpcsaBuffer: Pointer[PyiCsaddrInfo]
  dwOutputFlags: uint
  lpBlob: Pointer[PyiBlob]

@native
@native_name("_WSAQuerySetA")
class PyiWsaQuerySetA:
  dwSize: uint
  lpszServiceInstanceName: CStr
  lpServiceClassId: Pointer[PyiGuid]
  lpVersion: Pointer[PyiWsavErsion]
  lpszComment: CStr
  dwNameSpace: uint
  lpNsProviderId: Pointer[PyiGuid] @native_name("lpNSProviderId")
  lpszContext: CStr
  dwNumberOfProtocols: uint
  lpafpProtocols: Pointer[PyiAfprotocols]
  lpszQueryString: CStr
  dwNumberOfCsAddrs: uint
  lpcsaBuffer: Pointer[PyiCsaddrInfo]
  dwOutputFlags: uint
  lpBlob: Pointer[PyiBlob]

@native
@native_name("_WSAQuerySetW")
class PyiWsaQuerySetW:
  dwSize: uint
  lpszServiceInstanceName: Pointer[uint]
  lpServiceClassId: Pointer[PyiGuid]
  lpVersion: Pointer[PyiWsavErsion]
  lpszComment: Pointer[uint]
  dwNameSpace: uint
  lpNsProviderId: Pointer[PyiGuid] @native_name("lpNSProviderId")
  lpszContext: Pointer[uint]
  dwNumberOfProtocols: uint
  lpafpProtocols: Pointer[PyiAfprotocols]
  lpszQueryString: Pointer[uint]
  dwNumberOfCsAddrs: uint
  lpcsaBuffer: Pointer[PyiCsaddrInfo]
  dwOutputFlags: uint
  lpBlob: Pointer[PyiBlob]

@native
@native_name("_WSAServiceClassInfoA")
class PyiWsaServiceClassInfoA:
  lpServiceClassId: Pointer[PyiGuid]
  lpszServiceClassName: CStr
  dwCount: uint
  lpClassInfos: Pointer[PyiWsansClassInfoA]

@native
@native_name("_WSAServiceClassInfoW")
class PyiWsaServiceClassInfoW:
  lpServiceClassId: Pointer[PyiGuid]
  lpszServiceClassName: Pointer[uint]
  dwCount: uint
  lpClassInfos: Pointer[PyiWsansClassInfoW]

@native
@native_name("_WSAVersion")
class PyiWsavErsion:
  dwVersion: uint
  ecHow: PyiWsaecomparator

@native
@native_name("_flowspec")
class PyiFlowspec:
  tokenRate: uint @native_name("TokenRate")
  tokenBucketSize: uint @native_name("TokenBucketSize")
  peakBandwidth: uint @native_name("PeakBandwidth")
  latency: uint @native_name("Latency")
  delayVariation: uint @native_name("DelayVariation")
  serviceType: uint @native_name("ServiceType")
  maxSduSize: uint @native_name("MaxSduSize")
  minimumPolicedSize: uint @native_name("MinimumPolicedSize")

@native
@native_name("fd_set")
class PyiFdSet:
  fdCount: uint @native_name("fd_count")
  fdArray: Pointer[uint64] @native_name("fd_array")  # array

@native
@native_name("hostent")
class PyiHostent:
  hName: CStr @native_name("h_name")
  hAliases: Pointer[CStr] @native_name("h_aliases")
  hAddrtype: int @native_name("h_addrtype")
  hLength: int @native_name("h_length")
  hAddrList: Pointer[CStr] @native_name("h_addr_list")

@native
@native_name("in_addr")
class PyiInAddr:
  sUn: None @native_name("S_un")  # C: unnamed union

@native
@native_name("linger")
class PyiLinger:
  lOnoff: uint @native_name("l_onoff")
  lLinger: uint @native_name("l_linger")

@native
@native_name("netent")
class PyiNetent:
  nName: CStr @native_name("n_name")
  nAliases: Pointer[CStr] @native_name("n_aliases")
  nAddrtype: int @native_name("n_addrtype")
  nNet: uint @native_name("n_net")

@native
@native_name("pollfd")
class PyiPollfd:
  fd: uint64
  events: int
  revents: int

@native
@native_name("protoent")
class PyiProtoent:
  pName: CStr @native_name("p_name")
  pAliases: Pointer[CStr] @native_name("p_aliases")
  pProto: int @native_name("p_proto")

@native
@native_name("servent")
class PyiServent:
  sName: CStr @native_name("s_name")
  sAliases: Pointer[CStr] @native_name("s_aliases")
  sProto: CStr @native_name("s_proto")
  sPort: int @native_name("s_port")

@native
@native_name("sockaddr")
class PyiSockaddr:
  saFamily: uint @native_name("sa_family")
  saData: Pointer[int] @native_name("sa_data")  # array

@native
@native_name("sockproto")
class PyiSockproto:
  spFamily: uint @native_name("sp_family")
  spProtocol: uint @native_name("sp_protocol")

@native
@native_name("timeval")
class PyiTimeval:
  tvSec: int @native_name("tv_sec")
  tvUsec: int @native_name("tv_usec")

# ---------------------------------------------------------------------------
# Enums（空 @native 类；C++ using PyiE = ::E；成员见 Constants；类名带 Enum 后缀）
# ---------------------------------------------------------------------------

@native
@native_name("_WSACOMPLETIONTYPE")
class PyiWsacompletiontypeEnum:
  ...  # C enum

@native
@native_name("_WSAESETSERVICEOP")
class PyiWsaesetserviceopEnum:
  ...  # C enum

@native
@native_name("_WSAEcomparator")
class PyiWsaeComparatorEnum:
  ...  # C enum

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiAfprotocols = PyiAfprotocols
type PyiBlob = PyiBlob
type PyiFdSet = PyiFdSet
type PyiHostent = PyiHostent
type PyiLinger = PyiLinger
type PyiProtoent = PyiProtoent
type PyiQos = PyiQualityOfService
type PyiServent = PyiServent
type PyiTimeval = PyiTimeval
type PyiWsacompletion = PyiWsacompletion
type PyiWsacompletiontype = PyiWsacompletiontype
type PyiWsadatA = PyiWsadAta
type PyiWsaecomparator = PyiWsaeComparator
type PyiWsaesetserviceop = PyiWsaesetserviceop
type PyiWsanamespaceInfo = PyiWsanamespaceInfow
type PyiWsanamespaceInfoa = PyiWsanamespaceInfoa
type PyiWsanamespaceInfoex = PyiWsanamespaceInfoexW
type PyiWsanamespaceInfoexA = PyiWsanamespaceInfoexA
type PyiWsanamespaceInfoexW = PyiWsanamespaceInfoexW
type PyiWsanamespaceInfow = PyiWsanamespaceInfow
type PyiWsanetworkevents = PyiWsanetworkevents
type PyiWsansclassinfo = PyiWsansClassInfoW
type PyiWsansclassinfoA = PyiWsansClassInfoA
type PyiWsansclassinfoW = PyiWsansClassInfoW
type PyiWsapollfd = PyiPollfd
type PyiWsaprotocolchain = PyiWsaprotocolchain
type PyiWsaprotocolInfo = PyiWsaprotocolInfow
type PyiWsaprotocolInfoa = PyiWsaprotocolInfoa
type PyiWsaprotocolInfow = PyiWsaprotocolInfow
type PyiWsaqueryset = PyiWsaQuerySetW
type PyiWsaqueryset2 = PyiWsaQuerySet2W
type PyiWsaqueryset2A = PyiWsaQuerySet2A
type PyiWsaqueryset2W = PyiWsaQuerySet2W
type PyiWsaquerysetA = PyiWsaQuerySetA
type PyiWsaquerysetW = PyiWsaQuerySetW
type PyiWsaserviceclassinfo = PyiWsaServiceClassInfoW
type PyiWsaserviceclassinfoA = PyiWsaServiceClassInfoA
type PyiWsaserviceclassinfoW = PyiWsaServiceClassInfoW
type PyiWsaversion = PyiWsavErsion

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiBaseProtocol: int @native_name("BASE_PROTOCOL") = 1
PyiBigendian: int @native_name("BIGENDIAN") = 0x0000
PyiCfAccept: int @native_name("CF_ACCEPT") = 0x0000
PyiCfDefer: int @native_name("CF_DEFER") = 0x0002
PyiCfReject: int @native_name("CF_REJECT") = 0x0001
PyiCompEqual: PyiWsaeComparatorEnum @native_name("COMP_EQUAL") = 0
PyiCompNotless: PyiWsaeComparatorEnum @native_name("COMP_NOTLESS") = 1
PyiFdAcceptBit: int @native_name("FD_ACCEPT_BIT") = 3
PyiFdAddressListChangeBit: int @native_name("FD_ADDRESS_LIST_CHANGE_BIT") = 9
PyiFdCloseBit: int @native_name("FD_CLOSE_BIT") = 5
PyiFdConnectBit: int @native_name("FD_CONNECT_BIT") = 4
PyiFdGroupQosBit: int @native_name("FD_GROUP_QOS_BIT") = 7
PyiFdMaxEvents: int @native_name("FD_MAX_EVENTS") = 10
PyiFdOobBit: int @native_name("FD_OOB_BIT") = 2
PyiFdQosBit: int @native_name("FD_QOS_BIT") = 6
PyiFdReadBit: int @native_name("FD_READ_BIT") = 0
PyiFdRoutingInterfaceChangeBit: int @native_name("FD_ROUTING_INTERFACE_CHANGE_BIT") = 8
PyiFdSetsize: int @native_name("FD_SETSIZE") = 64
PyiFdWriteBit: int @native_name("FD_WRITE_BIT") = 1
PyiImplinkHighexper: int @native_name("IMPLINK_HIGHEXPER") = 158
PyiImplinkIp: int @native_name("IMPLINK_IP") = 155
PyiImplinkLowexper: int @native_name("IMPLINK_LOWEXPER") = 156
PyiInclWinsockApiPrototypes: int @native_name("INCL_WINSOCK_API_PROTOTYPES") = 1
PyiInclWinsockApiTypedefs: int @native_name("INCL_WINSOCK_API_TYPEDEFS") = 0
PyiIocparmMask: int @native_name("IOCPARM_MASK") = 0x7f
PyiIocIn: int @native_name("IOC_IN") = 0x80000000
PyiIocOut: int @native_name("IOC_OUT") = 0x40000000
PyiIocVoid: int @native_name("IOC_VOID") = 0x20000000
PyiIpportBiffudp: int @native_name("IPPORT_BIFFUDP") = 512
PyiIpportCmdserver: int @native_name("IPPORT_CMDSERVER") = 514
PyiIpportDaytime: int @native_name("IPPORT_DAYTIME") = 13
PyiIpportDiscard: int @native_name("IPPORT_DISCARD") = 9
PyiIpportEcho: int @native_name("IPPORT_ECHO") = 7
PyiIpportEfsserver: int @native_name("IPPORT_EFSSERVER") = 520
PyiIpportExecserver: int @native_name("IPPORT_EXECSERVER") = 512
PyiIpportFinger: int @native_name("IPPORT_FINGER") = 79
PyiIpportFtp: int @native_name("IPPORT_FTP") = 21
PyiIpportLoginserver: int @native_name("IPPORT_LOGINSERVER") = 513
PyiIpportMtp: int @native_name("IPPORT_MTP") = 57
PyiIpportNameserver: int @native_name("IPPORT_NAMESERVER") = 42
PyiIpportNetstat: int @native_name("IPPORT_NETSTAT") = 15
PyiIpportReserved: int @native_name("IPPORT_RESERVED") = 1024
PyiIpportRje: int @native_name("IPPORT_RJE") = 77
PyiIpportRouteserver: int @native_name("IPPORT_ROUTESERVER") = 520
PyiIpportSmtp: int @native_name("IPPORT_SMTP") = 25
PyiIpportSupdup: int @native_name("IPPORT_SUPDUP") = 95
PyiIpportSystat: int @native_name("IPPORT_SYSTAT") = 11
PyiIpportTelnet: int @native_name("IPPORT_TELNET") = 23
PyiIpportTftp: int @native_name("IPPORT_TFTP") = 69
PyiIpportTimeserver: int @native_name("IPPORT_TIMESERVER") = 37
PyiIpportTtylink: int @native_name("IPPORT_TTYLINK") = 87
PyiIpportWhois: int @native_name("IPPORT_WHOIS") = 43
PyiIpportWhoserver: int @native_name("IPPORT_WHOSERVER") = 513
PyiJlBoth: int @native_name("JL_BOTH") = 0x04
PyiJlReceiverOnly: int @native_name("JL_RECEIVER_ONLY") = 0x02
PyiJlSenderOnly: int @native_name("JL_SENDER_ONLY") = 0x01
PyiLayeredProtocol: int @native_name("LAYERED_PROTOCOL") = 0
PyiLittleendian: int @native_name("LITTLEENDIAN") = 0x0001
PyiLupAddrconfig: int @native_name("LUP_ADDRCONFIG") = 0x00100000
PyiLupApiAnsi: int @native_name("LUP_API_ANSI") = 0x01000000
PyiLupContainers: int @native_name("LUP_CONTAINERS") = 0x00000002
PyiLupDeep: int @native_name("LUP_DEEP") = 0x00000001
PyiLupDisableIdnEncoding: int @native_name("LUP_DISABLE_IDN_ENCODING") = 0x00800000
PyiLupDnsOnly: int @native_name("LUP_DNS_ONLY") = 0x00020000
PyiLupDualAddr: int @native_name("LUP_DUAL_ADDR") = 0x00200000
PyiLupExclusiveCustomServers: int @native_name("LUP_EXCLUSIVE_CUSTOM_SERVERS") = 0x08000000
PyiLupExtendedQueryset: int @native_name("LUP_EXTENDED_QUERYSET") = 0x02000000
PyiLupFileserver: int @native_name("LUP_FILESERVER") = 0x00400000
PyiLupFlushcache: int @native_name("LUP_FLUSHCACHE") = 0x00001000
PyiLupFlushprevious: int @native_name("LUP_FLUSHPREVIOUS") = 0x00002000
PyiLupForceClearText: int @native_name("LUP_FORCE_CLEAR_TEXT") = 0x40000000
PyiLupNearest: int @native_name("LUP_NEAREST") = 0x00000008
PyiLupNocontainers: int @native_name("LUP_NOCONTAINERS") = 0x00000004
PyiLupNonAuthoritative: int @native_name("LUP_NON_AUTHORITATIVE") = 0x00004000
PyiLupRequireSecure: int @native_name("LUP_REQUIRE_SECURE") = 0x10000000
PyiLupReservedUnused: int @native_name("LUP_RESERVED_UNUSED") = 0x00080000
PyiLupResolutionHandle: int @native_name("LUP_RESOLUTION_HANDLE") = 0x80000000
PyiLupResService: int @native_name("LUP_RES_SERVICE") = 0x00008000
PyiLupReturnAddr: int @native_name("LUP_RETURN_ADDR") = 0x00000100
PyiLupReturnAliases: int @native_name("LUP_RETURN_ALIASES") = 0x00000400
PyiLupReturnAll: int @native_name("LUP_RETURN_ALL") = 0x00000FF0
PyiLupReturnBlob: int @native_name("LUP_RETURN_BLOB") = 0x00000200
PyiLupReturnComment: int @native_name("LUP_RETURN_COMMENT") = 0x00000080
PyiLupReturnName: int @native_name("LUP_RETURN_NAME") = 0x00000010
PyiLupReturnPreferredNames: int @native_name("LUP_RETURN_PREFERRED_NAMES") = 0x00010000
PyiLupReturnQueryString: int @native_name("LUP_RETURN_QUERY_STRING") = 0x00000800
PyiLupReturnResponseFlags: int @native_name("LUP_RETURN_RESPONSE_FLAGS") = 0x00040000
PyiLupReturnTtl: int @native_name("LUP_RETURN_TTL") = 0x20000000
PyiLupReturnType: int @native_name("LUP_RETURN_TYPE") = 0x00000020
PyiLupReturnVersion: int @native_name("LUP_RETURN_VERSION") = 0x00000040
PyiLupSecure: int @native_name("LUP_SECURE") = 0x00008000
PyiLupSecureWithFallback: int @native_name("LUP_SECURE_WITH_FALLBACK") = 0x04000000
PyiMaxgethoststruct: int @native_name("MAXGETHOSTSTRUCT") = 1024
PyiMaxProtocolChain: int @native_name("MAX_PROTOCOL_CHAIN") = 7
PyiMsgDontroute: int @native_name("MSG_DONTROUTE") = 0x4
PyiMsgInterrupt: int @native_name("MSG_INTERRUPT") = 0x10
PyiMsgMaxiovlen: int @native_name("MSG_MAXIOVLEN") = 16
PyiMsgOob: int @native_name("MSG_OOB") = 0x1
PyiMsgPartial: int @native_name("MSG_PARTIAL") = 0x8000
PyiMsgPeek: int @native_name("MSG_PEEK") = 0x2
PyiMsgPushImmediate: int @native_name("MSG_PUSH_IMMEDIATE") = 0x20
PyiMsgWaitall: int @native_name("MSG_WAITALL") = 0x8
PyiNspNotifyApc: PyiWsacompletiontypeEnum @native_name("NSP_NOTIFY_APC") = 4
PyiNspNotifyEvent: PyiWsacompletiontypeEnum @native_name("NSP_NOTIFY_EVENT") = 2
PyiNspNotifyHwnd: PyiWsacompletiontypeEnum @native_name("NSP_NOTIFY_HWND") = 1
PyiNspNotifyImmediately: PyiWsacompletiontypeEnum @native_name("NSP_NOTIFY_IMMEDIATELY") = 0
PyiNspNotifyPort: PyiWsacompletiontypeEnum @native_name("NSP_NOTIFY_PORT") = 3
PyiPflHidden: int @native_name("PFL_HIDDEN") = 0x00000004
PyiPflMatchesProtocolZero: int @native_name("PFL_MATCHES_PROTOCOL_ZERO") = 0x00000008
PyiPflMultipleProtoEntries: int @native_name("PFL_MULTIPLE_PROTO_ENTRIES") = 0x00000001
PyiPflNetworkdirectProvider: int @native_name("PFL_NETWORKDIRECT_PROVIDER") = 0x00000010
PyiPflRecommendedProtoEntry: int @native_name("PFL_RECOMMENDED_PROTO_ENTRY") = 0x00000002
PyiPollerr: int @native_name("POLLERR") = 0x0001
PyiPollhup: int @native_name("POLLHUP") = 0x0002
PyiPollnval: int @native_name("POLLNVAL") = 0x0004
PyiPollpri: int @native_name("POLLPRI") = 0x0400
PyiPollrdband: int @native_name("POLLRDBAND") = 0x0200
PyiPollrdnorm: int @native_name("POLLRDNORM") = 0x0100
PyiPollwrband: int @native_name("POLLWRBAND") = 0x0020
PyiPollwrnorm: int @native_name("POLLWRNORM") = 0x0010
PyiPvdConfig: int @native_name("PVD_CONFIG") = 0x3001
PyiResultIsAdded: int @native_name("RESULT_IS_ADDED") = 0x0010
PyiResultIsAlias: int @native_name("RESULT_IS_ALIAS") = 0x0001
PyiResultIsChanged: int @native_name("RESULT_IS_CHANGED") = 0x0020
PyiResultIsDeleted: int @native_name("RESULT_IS_DELETED") = 0x0040
PyiRnrserviceDelete: PyiWsaesetserviceopEnum @native_name("RNRSERVICE_DELETE") = 2
PyiRnrserviceDeregister: PyiWsaesetserviceopEnum @native_name("RNRSERVICE_DEREGISTER") = 1
PyiRnrserviceRegister: PyiWsaesetserviceopEnum @native_name("RNRSERVICE_REGISTER") = 0
PyiSdBoth: int @native_name("SD_BOTH") = 0x02
PyiSdReceive: int @native_name("SD_RECEIVE") = 0x00
PyiSdSend: int @native_name("SD_SEND") = 0x01
PyiSecurityProtocolNone: int @native_name("SECURITY_PROTOCOL_NONE") = 0x0000
PyiServiceTypeValueIpxportA: str @native_name("SERVICE_TYPE_VALUE_IPXPORTA") = "IpxSocket"
PyiServiceTypeValueIpxportW: str @native_name("SERVICE_TYPE_VALUE_IPXPORTW") = "IpxSocket"
PyiServiceTypeValueObjectid: str @native_name("SERVICE_TYPE_VALUE_OBJECTID") = "ObjectId"
PyiServiceTypeValueObjectidA: str @native_name("SERVICE_TYPE_VALUE_OBJECTIDA") = "ObjectId"
PyiServiceTypeValueObjectidW: str @native_name("SERVICE_TYPE_VALUE_OBJECTIDW") = "ObjectId"
PyiServiceTypeValueSapid: str @native_name("SERVICE_TYPE_VALUE_SAPID") = "SapId"
PyiServiceTypeValueSapida: str @native_name("SERVICE_TYPE_VALUE_SAPIDA") = "SapId"
PyiServiceTypeValueSapidw: str @native_name("SERVICE_TYPE_VALUE_SAPIDW") = "SapId"
PyiServiceTypeValueTcpport: str @native_name("SERVICE_TYPE_VALUE_TCPPORT") = "TcpPort"
PyiServiceTypeValueTcpportA: str @native_name("SERVICE_TYPE_VALUE_TCPPORTA") = "TcpPort"
PyiServiceTypeValueTcpportW: str @native_name("SERVICE_TYPE_VALUE_TCPPORTW") = "TcpPort"
PyiServiceTypeValueUdpport: str @native_name("SERVICE_TYPE_VALUE_UDPPORT") = "UdpPort"
PyiServiceTypeValueUdpportA: str @native_name("SERVICE_TYPE_VALUE_UDPPORTA") = "UdpPort"
PyiServiceTypeValueUdpportW: str @native_name("SERVICE_TYPE_VALUE_UDPPORTW") = "UdpPort"
PyiSgConstrainedGroup: int @native_name("SG_CONSTRAINED_GROUP") = 0x02
PyiSgUnconstrainedGroup: int @native_name("SG_UNCONSTRAINED_GROUP") = 0x01
PyiSockDgram: int @native_name("SOCK_DGRAM") = 2
PyiSockNotifyEventErr: int @native_name("SOCK_NOTIFY_EVENT_ERR") = 0x40
PyiSockNotifyEventHangup: int @native_name("SOCK_NOTIFY_EVENT_HANGUP") = 0x04
PyiSockNotifyEventIn: int @native_name("SOCK_NOTIFY_EVENT_IN") = 0x01
PyiSockNotifyEventOut: int @native_name("SOCK_NOTIFY_EVENT_OUT") = 0x02
PyiSockNotifyEventRemove: int @native_name("SOCK_NOTIFY_EVENT_REMOVE") = 0x80
PyiSockNotifyOpDisable: int @native_name("SOCK_NOTIFY_OP_DISABLE") = 0x02
PyiSockNotifyOpEnable: int @native_name("SOCK_NOTIFY_OP_ENABLE") = 0x01
PyiSockNotifyOpNone: int @native_name("SOCK_NOTIFY_OP_NONE") = 0x00
PyiSockNotifyOpRemove: int @native_name("SOCK_NOTIFY_OP_REMOVE") = 0x04
PyiSockNotifyRegisterEventHangup: int @native_name("SOCK_NOTIFY_REGISTER_EVENT_HANGUP") = 0x04
PyiSockNotifyRegisterEventIn: int @native_name("SOCK_NOTIFY_REGISTER_EVENT_IN") = 0x01
PyiSockNotifyRegisterEventNone: int @native_name("SOCK_NOTIFY_REGISTER_EVENT_NONE") = 0x00
PyiSockNotifyRegisterEventOut: int @native_name("SOCK_NOTIFY_REGISTER_EVENT_OUT") = 0x02
PyiSockNotifyTriggerEdge: int @native_name("SOCK_NOTIFY_TRIGGER_EDGE") = 0x08
PyiSockNotifyTriggerLevel: int @native_name("SOCK_NOTIFY_TRIGGER_LEVEL") = 0x04
PyiSockNotifyTriggerOneshot: int @native_name("SOCK_NOTIFY_TRIGGER_ONESHOT") = 0x01
PyiSockNotifyTriggerPersistent: int @native_name("SOCK_NOTIFY_TRIGGER_PERSISTENT") = 0x02
PyiSockRaw: int @native_name("SOCK_RAW") = 3
PyiSockRdm: int @native_name("SOCK_RDM") = 4
PyiSockSeqpacket: int @native_name("SOCK_SEQPACKET") = 5
PyiSockStream: int @native_name("SOCK_STREAM") = 1
PyiSolSocket: int @native_name("SOL_SOCKET") = 0xffff
PyiSomaxconn: int @native_name("SOMAXCONN") = 0x7fffffff
PyiSoAcceptconn: int @native_name("SO_ACCEPTCONN") = 0x0002
PyiSoBroadcast: int @native_name("SO_BROADCAST") = 0x0020
PyiSoConditionalAccept: int @native_name("SO_CONDITIONAL_ACCEPT") = 0x3002
PyiSoDebug: int @native_name("SO_DEBUG") = 0x0001
PyiSoDontroute: int @native_name("SO_DONTROUTE") = 0x0010
PyiSoError: int @native_name("SO_ERROR") = 0x1007
PyiSoGroupId: int @native_name("SO_GROUP_ID") = 0x2001
PyiSoGroupPriority: int @native_name("SO_GROUP_PRIORITY") = 0x2002
PyiSoKeepalive: int @native_name("SO_KEEPALIVE") = 0x0008
PyiSoLinger: int @native_name("SO_LINGER") = 0x0080
PyiSoMaxMsgSize: int @native_name("SO_MAX_MSG_SIZE") = 0x2003
PyiSoOobinline: int @native_name("SO_OOBINLINE") = 0x0100
PyiSoProtocolInfo: int @native_name("SO_PROTOCOL_INFO") = 0x2005
PyiSoProtocolInfoa: int @native_name("SO_PROTOCOL_INFOA") = 0x2004
PyiSoProtocolInfow: int @native_name("SO_PROTOCOL_INFOW") = 0x2005
PyiSoRcvbuf: int @native_name("SO_RCVBUF") = 0x1002
PyiSoRcvlowat: int @native_name("SO_RCVLOWAT") = 0x1004
PyiSoRcvtimeo: int @native_name("SO_RCVTIMEO") = 0x1006
PyiSoReuseaddr: int @native_name("SO_REUSEADDR") = 0x0004
PyiSoSndbuf: int @native_name("SO_SNDBUF") = 0x1001
PyiSoSndlowat: int @native_name("SO_SNDLOWAT") = 0x1003
PyiSoSndtimeo: int @native_name("SO_SNDTIMEO") = 0x1005
PyiSoType: int @native_name("SO_TYPE") = 0x1008
PyiSoUseloopback: int @native_name("SO_USELOOPBACK") = 0x0040
PyiThNetdev: int @native_name("TH_NETDEV") = 0x00000001
PyiThTapi: int @native_name("TH_TAPI") = 0x00000002
PyiWsadescriptionLen: int @native_name("WSADESCRIPTION_LEN") = 256
PyiWsaprotocolLen: int @native_name("WSAPROTOCOL_LEN") = 255
PyiWsasysStatusLen: int @native_name("WSASYS_STATUS_LEN") = 128
PyiWsaFlagAccessSystemSecurity: int @native_name("WSA_FLAG_ACCESS_SYSTEM_SECURITY") = 0x40
PyiWsaFlagMultipointCLeaf: int @native_name("WSA_FLAG_MULTIPOINT_C_LEAF") = 0x04
PyiWsaFlagMultipointCRoot: int @native_name("WSA_FLAG_MULTIPOINT_C_ROOT") = 0x02
PyiWsaFlagMultipointDLeaf: int @native_name("WSA_FLAG_MULTIPOINT_D_LEAF") = 0x10
PyiWsaFlagMultipointDRoot: int @native_name("WSA_FLAG_MULTIPOINT_D_ROOT") = 0x08
PyiWsaFlagNoHandleInherit: int @native_name("WSA_FLAG_NO_HANDLE_INHERIT") = 0x80
PyiWsaFlagOverlapped: int @native_name("WSA_FLAG_OVERLAPPED") = 0x01
PyiWsaFlagRegisteredIo: int @native_name("WSA_FLAG_REGISTERED_IO") = 0x100
PyiXp1Connectionless: int @native_name("XP1_CONNECTIONLESS") = 0x00000001
PyiXp1ConnectData: int @native_name("XP1_CONNECT_DATA") = 0x00000080
PyiXp1DisconnectData: int @native_name("XP1_DISCONNECT_DATA") = 0x00000100
PyiXp1ExpeditedData: int @native_name("XP1_EXPEDITED_DATA") = 0x00000040
PyiXp1GracefulClose: int @native_name("XP1_GRACEFUL_CLOSE") = 0x00000020
PyiXp1GuaranteedDelivery: int @native_name("XP1_GUARANTEED_DELIVERY") = 0x00000002
PyiXp1GuaranteedOrder: int @native_name("XP1_GUARANTEED_ORDER") = 0x00000004
PyiXp1IfsHandles: int @native_name("XP1_IFS_HANDLES") = 0x00020000
PyiXp1Interrupt: int @native_name("XP1_INTERRUPT") = 0x00004000
PyiXp1MessageOriented: int @native_name("XP1_MESSAGE_ORIENTED") = 0x00000008
PyiXp1MultipointControlPlane: int @native_name("XP1_MULTIPOINT_CONTROL_PLANE") = 0x00000800
PyiXp1MultipointDataPlane: int @native_name("XP1_MULTIPOINT_DATA_PLANE") = 0x00001000
PyiXp1PartialMessage: int @native_name("XP1_PARTIAL_MESSAGE") = 0x00040000
PyiXp1PseudoStream: int @native_name("XP1_PSEUDO_STREAM") = 0x00000010
PyiXp1QosSupported: int @native_name("XP1_QOS_SUPPORTED") = 0x00002000
PyiXp1SanSupportSdp: int @native_name("XP1_SAN_SUPPORT_SDP") = 0x00080000
PyiXp1SupportBroadcast: int @native_name("XP1_SUPPORT_BROADCAST") = 0x00000200
PyiXp1SupportMultipoint: int @native_name("XP1_SUPPORT_MULTIPOINT") = 0x00000400
PyiXp1UniRecv: int @native_name("XP1_UNI_RECV") = 0x00010000
PyiXp1UniSend: int @native_name("XP1_UNI_SEND") = 0x00008000

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("GetHostNameW")
def pyiGetHostNameW(name: Pointer[uint], namelen: int) -> int:
  ...

@native
@native_name("ProcessSocketNotifications")
def pyiProcessSocketNotifications(completionPort: uintptr, registrationCount: uint, registrationInfos: Pointer[PyiSockNotifyRegistration], timeoutMs: uint, completionCount: uint, completionPortEntries: Pointer[PyiOverlappedEntry], receivedEntryCount: Pointer[uint]) -> uint:
  ...

@native
@native_name("SocketNotificationRetrieveEvents")
def pyiSocketNotificationRetrieveEvents(notification: Pointer[PyiOverlappedEntry]) -> uint:
  ...

@native
@native_name("WSAAccept")
def pyiWsaaCcept(s: uint64, addr: Pointer[PyiSockaddr], addrlen: Pointer[int], lpfnCondition: Function[[Pointer[PyiWsabuf], Pointer[PyiWsabuf], Pointer[PyiQualityOfService], Pointer[PyiQualityOfService], Pointer[PyiWsabuf], Pointer[PyiWsabuf], Pointer[uint], uint64], int], dwCallbackData: uint64) -> uint64:
  ...

@native
@native_name("WSAAddressToStringA")
def pyiWsaAddressToStringA(lpsaAddress: Pointer[PyiSockaddr], dwAddressLength: uint, lpProtocolInfo: Pointer[PyiWsaprotocolInfoa], lpszAddressString: CStr, lpdwAddressStringLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAAddressToStringW")
def pyiWsaAddressToStringW(lpsaAddress: Pointer[PyiSockaddr], dwAddressLength: uint, lpProtocolInfo: Pointer[PyiWsaprotocolInfow], lpszAddressString: Pointer[uint], lpdwAddressStringLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAAsyncGetHostByAddr")
def pyiWsaAsyncGetHostByAddr(hWnd: Pointer[PyiHwnd], wMsg: uint, addr: CStr, len: int, type: int, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncGetHostByName")
def pyiWsaAsyncGetHostByName(hWnd: Pointer[PyiHwnd], wMsg: uint, name: CStr, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncGetProtoByName")
def pyiWsaAsyncGetProtoByName(hWnd: Pointer[PyiHwnd], wMsg: uint, name: CStr, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncGetProtoByNumber")
def pyiWsaAsyncGetProtoByNumber(hWnd: Pointer[PyiHwnd], wMsg: uint, number: int, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncGetServByName")
def pyiWsaAsyncGetServByName(hWnd: Pointer[PyiHwnd], wMsg: uint, name: CStr, proto: CStr, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncGetServByPort")
def pyiWsaAsyncGetServByPort(hWnd: Pointer[PyiHwnd], wMsg: uint, port: int, proto: CStr, buf: CStr, buflen: int) -> uintptr:
  ...

@native
@native_name("WSAAsyncSelect")
def pyiWsaAsyncSelect(s: uint64, hWnd: Pointer[PyiHwnd], wMsg: uint, lEvent: int) -> int:
  ...

@native
@native_name("WSACancelAsyncRequest")
def pyiWsaCancelAsyncRequest(hAsyncTaskHandle: uintptr) -> int:
  ...

@native
@native_name("WSACancelBlockingCall")
def pyiWsaCancelBlockingCall() -> int:
  ...

@native
@native_name("WSACleanup")
def pyiWsacLeanup() -> int:
  ...

@native
@native_name("WSACloseEvent")
def pyiWsaCloseEvent(hEvent: uintptr) -> int:
  ...

@native
@native_name("WSAConnect")
def pyiWsacOnnect(s: uint64, name: Pointer[PyiSockaddr], namelen: int, lpCallerData: Pointer[PyiWsabuf], lpCalleeData: Pointer[PyiWsabuf], lpSQOS: Pointer[PyiQualityOfService], lpGQOS: Pointer[PyiQualityOfService]) -> int:
  ...

@native
@native_name("WSAConnectByList")
def pyiWsaConnectByList(s: uint64, SocketAddress: Pointer[PyiSocketAddressList], LocalAddressLength: Pointer[uint], LocalAddress: Pointer[PyiSockaddr], RemoteAddressLength: Pointer[uint], RemoteAddress: Pointer[PyiSockaddr], timeout: Pointer[PyiTimeval], Reserved: Pointer[PyiOverlapped]) -> int:
  ...

@native
@native_name("WSAConnectByNameA")
def pyiWsaConnectByNameA(s: uint64, nodename: CStr, servicename: CStr, LocalAddressLength: Pointer[uint], LocalAddress: Pointer[PyiSockaddr], RemoteAddressLength: Pointer[uint], RemoteAddress: Pointer[PyiSockaddr], timeout: Pointer[PyiTimeval], Reserved: Pointer[PyiOverlapped]) -> int:
  ...

@native
@native_name("WSAConnectByNameW")
def pyiWsaConnectByNameW(s: uint64, nodename: Pointer[uint], servicename: Pointer[uint], LocalAddressLength: Pointer[uint], LocalAddress: Pointer[PyiSockaddr], RemoteAddressLength: Pointer[uint], RemoteAddress: Pointer[PyiSockaddr], timeout: Pointer[PyiTimeval], Reserved: Pointer[PyiOverlapped]) -> int:
  ...

@native
@native_name("WSACreateEvent")
def pyiWsaCreateEvent() -> uintptr:
  ...

@native
@native_name("WSADuplicateSocketA")
def pyiWsaDuplicateSocketA(s: uint64, dwProcessId: uint, lpProtocolInfo: Pointer[PyiWsaprotocolInfoa]) -> int:
  ...

@native
@native_name("WSADuplicateSocketW")
def pyiWsaDuplicateSocketW(s: uint64, dwProcessId: uint, lpProtocolInfo: Pointer[PyiWsaprotocolInfow]) -> int:
  ...

@native
@native_name("WSAEnumNameSpaceProvidersA")
def pyiWsaEnumNameSpaceProvidersA(lpdwBufferLength: Pointer[uint], lpnspBuffer: Pointer[PyiWsanamespaceInfoa]) -> int:
  ...

@native
@native_name("WSAEnumNameSpaceProvidersExA")
def pyiWsaEnumNameSpaceProvidersExA(lpdwBufferLength: Pointer[uint], lpnspBuffer: Pointer[PyiWsanamespaceInfoexA]) -> int:
  ...

@native
@native_name("WSAEnumNameSpaceProvidersExW")
def pyiWsaEnumNameSpaceProvidersExW(lpdwBufferLength: Pointer[uint], lpnspBuffer: Pointer[PyiWsanamespaceInfoexW]) -> int:
  ...

@native
@native_name("WSAEnumNameSpaceProvidersW")
def pyiWsaEnumNameSpaceProvidersW(lpdwBufferLength: Pointer[uint], lpnspBuffer: Pointer[PyiWsanamespaceInfow]) -> int:
  ...

@native
@native_name("WSAEnumNetworkEvents")
def pyiWsaEnumNetworkEvents(s: uint64, hEventObject: uintptr, lpNetworkEvents: Pointer[PyiWsanetworkevents]) -> int:
  ...

@native
@native_name("WSAEnumProtocolsA")
def pyiWsaEnumProtocolsA(lpiProtocols: Pointer[int], lpProtocolBuffer: Pointer[PyiWsaprotocolInfoa], lpdwBufferLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAEnumProtocolsW")
def pyiWsaEnumProtocolsW(lpiProtocols: Pointer[int], lpProtocolBuffer: Pointer[PyiWsaprotocolInfow], lpdwBufferLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAEventSelect")
def pyiWsaEventSelect(s: uint64, hEventObject: uintptr, lNetworkEvents: int) -> int:
  ...

@native
@native_name("WSAGetLastError")
def pyiWsaGetLastError() -> int:
  ...

@native
@native_name("WSAGetOverlappedResult")
def pyiWsaGetOverlappedResult(s: uint64, lpOverlapped: Pointer[PyiOverlapped], lpcbTransfer: Pointer[uint], fWait: int, lpdwFlags: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetQOSByName")
def pyiWsaGetQosByName(s: uint64, lpQOSName: Pointer[PyiWsabuf], lpQOS: Pointer[PyiQualityOfService]) -> int:
  ...

@native
@native_name("WSAGetServiceClassInfoA")
def pyiWsaGetServiceClassInfoA(lpProviderId: Pointer[PyiGuid], lpServiceClassId: Pointer[PyiGuid], lpdwBufSize: Pointer[uint], lpServiceClassInfo: Pointer[PyiWsaServiceClassInfoA]) -> int:
  ...

@native
@native_name("WSAGetServiceClassInfoW")
def pyiWsaGetServiceClassInfoW(lpProviderId: Pointer[PyiGuid], lpServiceClassId: Pointer[PyiGuid], lpdwBufSize: Pointer[uint], lpServiceClassInfo: Pointer[PyiWsaServiceClassInfoW]) -> int:
  ...

@native
@native_name("WSAGetServiceClassNameByClassIdA")
def pyiWsaGetServiceClassNameByClassIdA(lpServiceClassId: Pointer[PyiGuid], lpszServiceClassName: CStr, lpdwBufferLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetServiceClassNameByClassIdW")
def pyiWsaGetServiceClassNameByClassIdW(lpServiceClassId: Pointer[PyiGuid], lpszServiceClassName: Pointer[uint], lpdwBufferLength: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAHtonl")
def pyiWsahTonl(s: uint64, hostlong: uint, lpnetlong: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAHtons")
def pyiWsahTons(s: uint64, hostshort: uint, lpnetshort: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAInstallServiceClassA")
def pyiWsaInstallServiceClassA(lpServiceClassInfo: Pointer[PyiWsaServiceClassInfoA]) -> int:
  ...

@native
@native_name("WSAInstallServiceClassW")
def pyiWsaInstallServiceClassW(lpServiceClassInfo: Pointer[PyiWsaServiceClassInfoW]) -> int:
  ...

@native
@native_name("WSAIoctl")
def pyiWsaiOctl(s: uint64, dwIoControlCode: uint, lpvInBuffer: uintptr, cbInBuffer: uint, lpvOutBuffer: uintptr, cbOutBuffer: uint, lpcbBytesReturned: Pointer[uint], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSAIsBlocking")
def pyiWsaIsBlocking() -> int:
  ...

@native
@native_name("WSAJoinLeaf")
def pyiWsaJoinLeaf(s: uint64, name: Pointer[PyiSockaddr], namelen: int, lpCallerData: Pointer[PyiWsabuf], lpCalleeData: Pointer[PyiWsabuf], lpSQOS: Pointer[PyiQualityOfService], lpGQOS: Pointer[PyiQualityOfService], dwFlags: uint) -> uint64:
  ...

@native
@native_name("WSALookupServiceBeginA")
def pyiWsaLookupServiceBeginA(lpqsRestrictions: Pointer[PyiWsaQuerySetA], dwControlFlags: uint, lphLookup: Pointer[uintptr]) -> int:
  ...

@native
@native_name("WSALookupServiceBeginW")
def pyiWsaLookupServiceBeginW(lpqsRestrictions: Pointer[PyiWsaQuerySetW], dwControlFlags: uint, lphLookup: Pointer[uintptr]) -> int:
  ...

@native
@native_name("WSALookupServiceEnd")
def pyiWsaLookupServiceEnd(hLookup: uintptr) -> int:
  ...

@native
@native_name("WSALookupServiceNextA")
def pyiWsaLookupServiceNextA(hLookup: uintptr, dwControlFlags: uint, lpdwBufferLength: Pointer[uint], lpqsResults: Pointer[PyiWsaQuerySetA]) -> int:
  ...

@native
@native_name("WSALookupServiceNextW")
def pyiWsaLookupServiceNextW(hLookup: uintptr, dwControlFlags: uint, lpdwBufferLength: Pointer[uint], lpqsResults: Pointer[PyiWsaQuerySetW]) -> int:
  ...

@native
@native_name("WSANSPIoctl")
def pyiWsanspiOctl(hLookup: uintptr, dwControlCode: uint, lpvInBuffer: uintptr, cbInBuffer: uint, lpvOutBuffer: uintptr, cbOutBuffer: uint, lpcbBytesReturned: Pointer[uint], lpCompletion: Pointer[PyiWsacompletion]) -> int:
  ...

@native
@native_name("WSANtohl")
def pyiWsanTohl(s: uint64, netlong: uint, lphostlong: Pointer[uint]) -> int:
  ...

@native
@native_name("WSANtohs")
def pyiWsanTohs(s: uint64, netshort: uint, lphostshort: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAPoll")
def pyiWsapOll(fdArray: Pointer[PyiPollfd], fds: uint, timeout: int) -> int:
  ...

@native
@native_name("WSAProviderConfigChange")
def pyiWsaProviderConfigChange(lpNotificationHandle: Pointer[uintptr], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSARecv")
def pyiWsarEcv(s: uint64, lpBuffers: Pointer[PyiWsabuf], dwBufferCount: uint, lpNumberOfBytesRecvd: Pointer[uint], lpFlags: Pointer[uint], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSARecvDisconnect")
def pyiWsaRecvDisconnect(s: uint64, lpInboundDisconnectData: Pointer[PyiWsabuf]) -> int:
  ...

@native
@native_name("WSARecvFrom")
def pyiWsaRecvFrom(s: uint64, lpBuffers: Pointer[PyiWsabuf], dwBufferCount: uint, lpNumberOfBytesRecvd: Pointer[uint], lpFlags: Pointer[uint], lpFrom: Pointer[PyiSockaddr], lpFromlen: Pointer[int], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSARemoveServiceClass")
def pyiWsaRemoveServiceClass(lpServiceClassId: Pointer[PyiGuid]) -> int:
  ...

@native
@native_name("WSAResetEvent")
def pyiWsaResetEvent(hEvent: uintptr) -> int:
  ...

@native
@native_name("WSASend")
def pyiWsasEnd(s: uint64, lpBuffers: Pointer[PyiWsabuf], dwBufferCount: uint, lpNumberOfBytesSent: Pointer[uint], dwFlags: uint, lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSASendDisconnect")
def pyiWsaSendDisconnect(s: uint64, lpOutboundDisconnectData: Pointer[PyiWsabuf]) -> int:
  ...

@native
@native_name("WSASendMsg")
def pyiWsaSendMsg(Handle: uint64, lpMsg: Pointer[PyiWsamsg], dwFlags: uint, lpNumberOfBytesSent: Pointer[uint], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSASendTo")
def pyiWsaSendTo(s: uint64, lpBuffers: Pointer[PyiWsabuf], dwBufferCount: uint, lpNumberOfBytesSent: Pointer[uint], dwFlags: uint, lpTo: Pointer[PyiSockaddr], iTolen: int, lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("WSASetBlockingHook")
def pyiWsaSetBlockingHook(lpBlockFunc: uintptr) -> uintptr:  # C: long long ()
  ...

@native
@native_name("WSASetEvent")
def pyiWsaSetEvent(hEvent: uintptr) -> int:
  ...

@native
@native_name("WSASetLastError")
def pyiWsaSetLastError(iError: int) -> None:
  ...

@native
@native_name("WSASetServiceA")
def pyiWsaSetServiceA(lpqsRegInfo: Pointer[PyiWsaQuerySetA], essoperation: PyiWsaesetserviceop, dwControlFlags: uint) -> int:
  ...

@native
@native_name("WSASetServiceW")
def pyiWsaSetServiceW(lpqsRegInfo: Pointer[PyiWsaQuerySetW], essoperation: PyiWsaesetserviceop, dwControlFlags: uint) -> int:
  ...

@native
@native_name("WSASocketA")
def pyiWsaSocketA(af: int, type: int, protocol: int, lpProtocolInfo: Pointer[PyiWsaprotocolInfoa], g: uint, dwFlags: uint) -> uint64:
  ...

@native
@native_name("WSASocketW")
def pyiWsaSocketW(af: int, type: int, protocol: int, lpProtocolInfo: Pointer[PyiWsaprotocolInfow], g: uint, dwFlags: uint) -> uint64:
  ...

@native
@native_name("WSAStartup")
def pyiWsasTartup(wVersionRequested: uint, lpWSAData: Pointer[PyiWsadAta]) -> int:
  ...

@native
@native_name("WSAStringToAddressA")
def pyiWsaStringToAddressA(AddressString: CStr, AddressFamily: int, lpProtocolInfo: Pointer[PyiWsaprotocolInfoa], lpAddress: Pointer[PyiSockaddr], lpAddressLength: Pointer[int]) -> int:
  ...

@native
@native_name("WSAStringToAddressW")
def pyiWsaStringToAddressW(AddressString: Pointer[uint], AddressFamily: int, lpProtocolInfo: Pointer[PyiWsaprotocolInfow], lpAddress: Pointer[PyiSockaddr], lpAddressLength: Pointer[int]) -> int:
  ...

@native
@native_name("WSAUnhookBlockingHook")
def pyiWsaUnhookBlockingHook() -> int:
  ...

@native
@native_name("WSAWaitForMultipleEvents")
def pyiWsaWaitForMultipleEvents(cEvents: uint, lphEvents: Pointer[uintptr], fWaitAll: int, dwTimeout: uint, fAlertable: int) -> uint:
  ...

@native
@native_name("__WSAFDIsSet")
def pyiWsafdIsSet(fd: uint64, arg1: Pointer[PyiFdSet]) -> int:
  ...

@native
@native_name("accept")
def pyiAccept(s: uint64, addr: Pointer[PyiSockaddr], addrlen: Pointer[int]) -> uint64:
  ...

@native
@native_name("bind")
def pyiBind(s: uint64, name: Pointer[PyiSockaddr], namelen: int) -> int:
  ...

@native
@native_name("closesocket")
def pyiClosesocket(s: uint64) -> int:
  ...

@native
@native_name("connect")
def pyiConnect(s: uint64, name: Pointer[PyiSockaddr], namelen: int) -> int:
  ...

@native
@native_name("gethostbyaddr")
def pyiGethostbyaddr(addr: CStr, len: int, type: int) -> Pointer[PyiHostent]:
  ...

@native
@native_name("gethostbyname")
def pyiGethostbyname(name: CStr) -> Pointer[PyiHostent]:
  ...

@native
@native_name("gethostname")
def pyiGethostname(name: CStr, namelen: int) -> int:
  ...

@native
@native_name("getpeername")
def pyiGetpeername(s: uint64, name: Pointer[PyiSockaddr], namelen: Pointer[int]) -> int:
  ...

@native
@native_name("getprotobyname")
def pyiGetprotobyname(name: CStr) -> Pointer[PyiProtoent]:
  ...

@native
@native_name("getprotobynumber")
def pyiGetprotobynumber(number: int) -> Pointer[PyiProtoent]:
  ...

@native
@native_name("getservbyname")
def pyiGetservbyname(name: CStr, proto: CStr) -> Pointer[PyiServent]:
  ...

@native
@native_name("getservbyport")
def pyiGetservbyport(port: int, proto: CStr) -> Pointer[PyiServent]:
  ...

@native
@native_name("getsockname")
def pyiGetsockname(s: uint64, name: Pointer[PyiSockaddr], namelen: Pointer[int]) -> int:
  ...

@native
@native_name("getsockopt")
def pyiGetsockopt(s: uint64, level: int, optname: int, optval: CStr, optlen: Pointer[int]) -> int:
  ...

@native
@native_name("htond")
def pyiHtond(Value: float64) -> uint64:
  ...

@native
@native_name("htonf")
def pyiHtonf(Value: float) -> uint:
  ...

@native
@native_name("htonl")
def pyiHtonl(hostlong: uint) -> uint:
  ...

@native
@native_name("htonll")
def pyiHtonll(Value: uint64) -> uint64:
  ...

@native
@native_name("htons")
def pyiHtons(hostshort: uint) -> uint:
  ...

@native
@native_name("inet_addr")
def pyiInetAddr(cp: CStr) -> uint:
  ...

@native
@native_name("inet_ntoa")
def pyiInetNtoa(in_: PyiInAddr) -> CStr:
  ...

@native
@native_name("ioctlsocket")
def pyiIoctlsocket(s: uint64, cmd: int, argp: Pointer[uint]) -> int:
  ...

@native
@native_name("listen")
def pyiListen(s: uint64, backlog: int) -> int:
  ...

@native
@native_name("ntohd")
def pyiNtohd(Value: uint64) -> float64:
  ...

@native
@native_name("ntohf")
def pyiNtohf(Value: uint) -> float:
  ...

@native
@native_name("ntohl")
def pyiNtohl(netlong: uint) -> uint:
  ...

@native
@native_name("ntohll")
def pyiNtohll(Value: uint64) -> uint64:
  ...

@native
@native_name("ntohs")
def pyiNtohs(netshort: uint) -> uint:
  ...

@native
@native_name("recv")
def pyiRecv(s: uint64, buf: CStr, len: int, flags: int) -> int:
  ...

@native
@native_name("recvfrom")
def pyiRecvfrom(s: uint64, buf: CStr, len: int, flags: int, from_: Pointer[PyiSockaddr], fromlen: Pointer[int]) -> int:
  ...

@native
@native_name("select")
def pyiSelect(nfds: int, readfds: Pointer[PyiFdSet], writefds: Pointer[PyiFdSet], exceptfds: Pointer[PyiFdSet], timeout: Pointer[PyiTimeval]) -> int:
  ...

@native
@native_name("send")
def pyiSend(s: uint64, buf: CStr, len: int, flags: int) -> int:
  ...

@native
@native_name("sendto")
def pyiSendto(s: uint64, buf: CStr, len: int, flags: int, to: Pointer[PyiSockaddr], tolen: int) -> int:
  ...

@native
@native_name("setsockopt")
def pyiSetsockopt(s: uint64, level: int, optname: int, optval: CStr, optlen: int) -> int:
  ...

@native
@native_name("shutdown")
def pyiShutdown(s: uint64, how: int) -> int:
  ...

@native
@native_name("socket")
def pyiSocket(af: int, type: int, protocol: int) -> uint64:
  ...

# stats: structs=44 enums=3 aliases=39 consts=229 funcs=114
