# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\WS2tcpip.h
# Generated: 2026-08-17 15:20:53
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("_BLOB")
class PyiBlob:
  cbSize: uint
  pBlobData: Pointer[int]

@native
@native_name("_GUID")
class PyiGuid:
  data1: uint @native_name("Data1")
  data2: uint @native_name("Data2")
  data3: uint @native_name("Data3")
  data4: Pointer[int] @native_name("Data4")  # array

@native
@native_name("_OVERLAPPED")
class PyiOverlapped:
  internal: uint64 @native_name("Internal")
  internalHigh: uint64 @native_name("InternalHigh")
  hEvent: uintptr

@native
@native_name("_SOCKADDR_INET")
class PyiSockaddrInet:
  ...  # C union

@native
@native_name("_SOCKET_ADDRESS")
class PyiSocketAddress:
  lpSockaddr: Pointer[PyiSockaddr]
  iSockaddrLength: int

@native
@native_name("addrinfo")
class PyiAddrinfo:
  aiFlags: int @native_name("ai_flags")
  aiFamily: int @native_name("ai_family")
  aiSocktype: int @native_name("ai_socktype")
  aiProtocol: int @native_name("ai_protocol")
  aiAddrlen: uint64 @native_name("ai_addrlen")
  aiCanonname: CStr @native_name("ai_canonname")
  aiAddr: Pointer[PyiSockaddr] @native_name("ai_addr")
  aiNext: Pointer[Self] @native_name("ai_next")

@native
@native_name("addrinfoW")
class PyiAddrinfoW:
  aiFlags: int @native_name("ai_flags")
  aiFamily: int @native_name("ai_family")
  aiSocktype: int @native_name("ai_socktype")
  aiProtocol: int @native_name("ai_protocol")
  aiAddrlen: uint64 @native_name("ai_addrlen")
  aiCanonname: Pointer[uint] @native_name("ai_canonname")
  aiAddr: Pointer[PyiSockaddr] @native_name("ai_addr")
  aiNext: Pointer[Self] @native_name("ai_next")

@native
@native_name("addrinfoexA")
class PyiAddrinfoexA:
  aiFlags: int @native_name("ai_flags")
  aiFamily: int @native_name("ai_family")
  aiSocktype: int @native_name("ai_socktype")
  aiProtocol: int @native_name("ai_protocol")
  aiAddrlen: uint64 @native_name("ai_addrlen")
  aiCanonname: CStr @native_name("ai_canonname")
  aiAddr: Pointer[PyiSockaddr] @native_name("ai_addr")
  aiBlob: uintptr @native_name("ai_blob")
  aiBloblen: uint64 @native_name("ai_bloblen")
  aiProvider: Pointer[PyiGuid] @native_name("ai_provider")
  aiNext: Pointer[Self] @native_name("ai_next")

@native
@native_name("addrinfoexW")
class PyiAddrinfoexW:
  aiFlags: int @native_name("ai_flags")
  aiFamily: int @native_name("ai_family")
  aiSocktype: int @native_name("ai_socktype")
  aiProtocol: int @native_name("ai_protocol")
  aiAddrlen: uint64 @native_name("ai_addrlen")
  aiCanonname: Pointer[uint] @native_name("ai_canonname")
  aiAddr: Pointer[PyiSockaddr] @native_name("ai_addr")
  aiBlob: uintptr @native_name("ai_blob")
  aiBloblen: uint64 @native_name("ai_bloblen")
  aiProvider: Pointer[PyiGuid] @native_name("ai_provider")
  aiNext: Pointer[Self] @native_name("ai_next")

@native
@native_name("icmp_error_info")
class PyiIcmpErrorInfo:
  srcaddress: PyiSockaddrInet
  protocol: PyiIpproto
  type: int
  code: int

@native
@native_name("in6_addr")
class PyiIn6Addr:
  u: None  # C: unnamed union

@native
@native_name("in_addr")
class PyiInAddr:
  sUn: None @native_name("S_un")  # C: unnamed union

@native
@native_name("sockaddr")
class PyiSockaddr:
  saFamily: uint @native_name("sa_family")
  saData: Pointer[int] @native_name("sa_data")  # array

@native
@native_name("sockaddr_in")
class PyiSockaddrIn:
  sinFamily: uint @native_name("sin_family")
  sinPort: uint @native_name("sin_port")
  sinAddr: PyiInAddr @native_name("sin_addr")
  sinZero: Pointer[int] @native_name("sin_zero")  # array

@native
@native_name("sockaddr_in6")
class PyiSockaddrIn6:
  sin6Family: uint @native_name("sin6_family")
  sin6Port: uint @native_name("sin6_port")
  sin6Flowinfo: uint @native_name("sin6_flowinfo")
  sin6Addr: PyiIn6Addr @native_name("sin6_addr")

@native
@native_name("sockaddr_storage")
class PyiSockaddrStorage:
  ssFamily: uint @native_name("ss_family")
  ssPad1: Pointer[int] @native_name("__ss_pad1")  # array
  ssAlign: int64 @native_name("__ss_align")
  ssPad2: Pointer[int] @native_name("__ss_pad2")  # array

@native
@native_name("timeval")
class PyiTimeval:
  tvSec: int @native_name("tv_sec")
  tvUsec: int @native_name("tv_usec")

# ---------------------------------------------------------------------------
# Enums（空 @native 类；C++ using PyiE = ::E；成员见 Constants；类名带 Enum 后缀）
# ---------------------------------------------------------------------------

@native
@native_name("IPPROTO")
class PyiIpprotoEnum:
  ...  # C enum

@native
@native_name("MULTICAST_MODE_TYPE")
class PyiMulticastModeTypeEnum:
  ...  # C enum

# ---------------------------------------------------------------------------
# Typedef aliases（type PyiAlias = PyiStructTag / PyiEnumTag）
# ---------------------------------------------------------------------------

type PyiAddrinfo = PyiAddrinfo
type PyiAddrinfoex = PyiAddrinfoexW
type PyiAddrinfot = PyiAddrinfoW

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiGaiStrerrorBufferSize: int @native_name("GAI_STRERROR_BUFFER_SIZE") = 1024
PyiUdpChecksumCoverage: int @native_name("UDP_CHECKSUM_COVERAGE") = 20
PyiUdpNochecksum: int @native_name("UDP_NOCHECKSUM") = 1

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("FreeAddrInfoEx")
def pyiFreeAddrInfoEx(pAddrInfoEx: Pointer[PyiAddrinfoexA]) -> None:
  ...

@native
@native_name("FreeAddrInfoExW")
def pyiFreeAddrInfoExW(pAddrInfoEx: Pointer[PyiAddrinfoexW]) -> None:
  ...

@native
@native_name("FreeAddrInfoW")
def pyiFreeAddrInfoW(pAddrInfo: Pointer[PyiAddrinfoW]) -> None:
  ...

@native
@native_name("GetAddrInfoExA")
def pyiGetAddrInfoExA(pName: CStr, pServiceName: CStr, dwNameSpace: uint, lpNspId: Pointer[PyiGuid], hints: Pointer[PyiAddrinfoexA], ppResult: Pointer[Pointer[PyiAddrinfoexA]], timeout: Pointer[PyiTimeval], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped]], None], lpNameHandle: Pointer[uintptr]) -> int:
  ...

@native
@native_name("GetAddrInfoExCancel")
def pyiGetAddrInfoExCancel(lpHandle: Pointer[uintptr]) -> int:
  ...

@native
@native_name("GetAddrInfoExOverlappedResult")
def pyiGetAddrInfoExOverlappedResult(lpOverlapped: Pointer[PyiOverlapped]) -> int:
  ...

@native
@native_name("GetAddrInfoExW")
def pyiGetAddrInfoExW(pName: Pointer[uint], pServiceName: Pointer[uint], dwNameSpace: uint, lpNspId: Pointer[PyiGuid], hints: Pointer[PyiAddrinfoexW], ppResult: Pointer[Pointer[PyiAddrinfoexW]], timeout: Pointer[PyiTimeval], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped]], None], lpHandle: Pointer[uintptr]) -> int:
  ...

@native
@native_name("GetAddrInfoW")
def pyiGetAddrInfoW(pNodeName: Pointer[uint], pServiceName: Pointer[uint], pHints: Pointer[PyiAddrinfoW], ppResult: Pointer[Pointer[PyiAddrinfoW]]) -> int:
  ...

@native
@native_name("GetNameInfoW")
def pyiGetNameInfoW(pSockaddr: Pointer[PyiSockaddr], SockaddrLength: int, pNodeBuffer: Pointer[uint], NodeBufferSize: uint, pServiceBuffer: Pointer[uint], ServiceBufferSize: uint, Flags: int) -> int:
  ...

@native
@native_name("InetNtopW")
def pyiInetNtopW(Family: int, pAddr: uintptr, pStringBuf: Pointer[uint], StringBufSize: uint64) -> Pointer[uint]:
  ...

@native
@native_name("InetPtonW")
def pyiInetPtonW(Family: int, pszAddrString: Pointer[uint], pAddrBuf: uintptr) -> int:
  ...

@native
@native_name("SetAddrInfoExA")
def pyiSetAddrInfoExA(pName: CStr, pServiceName: CStr, pAddresses: Pointer[PyiSocketAddress], dwAddressCount: uint, lpBlob: Pointer[PyiBlob], dwFlags: uint, dwNameSpace: uint, lpNspId: Pointer[PyiGuid], timeout: Pointer[PyiTimeval], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped]], None], lpNameHandle: Pointer[uintptr]) -> int:
  ...

@native
@native_name("SetAddrInfoExW")
def pyiSetAddrInfoExW(pName: Pointer[uint], pServiceName: Pointer[uint], pAddresses: Pointer[PyiSocketAddress], dwAddressCount: uint, lpBlob: Pointer[PyiBlob], dwFlags: uint, dwNameSpace: uint, lpNspId: Pointer[PyiGuid], timeout: Pointer[PyiTimeval], lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped]], None], lpNameHandle: Pointer[uintptr]) -> int:
  ...

@native
@native_name("WSAGetFailConnectOnIcmpError")
def pyiWsaGetFailConnectOnIcmpError(Socket: uint64, Enabled: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetIPUserMtu")
def pyiWsaGetIpUserMtu(Socket: uint64, Mtu: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetIcmpErrorInfo")
def pyiWsaGetIcmpErrorInfo(Socket: uint64, Info: Pointer[PyiIcmpErrorInfo]) -> int:
  ...

@native
@native_name("WSAGetReceivedProcessorOption")
def pyiWsaGetReceivedProcessorOption(Socket: uint64, Enabled: Pointer[int]) -> int:
  ...

@native
@native_name("WSAGetRecvIPEcn")
def pyiWsaGetRecvIpEcn(Socket: uint64, Enabled: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetUdpRecvMaxCoalescedSize")
def pyiWsaGetUdpRecvMaxCoalescedSize(Socket: uint64, MaxCoalescedMsgSize: Pointer[uint]) -> int:
  ...

@native
@native_name("WSAGetUdpSendMessageSize")
def pyiWsaGetUdpSendMessageSize(Socket: uint64, MsgSize: Pointer[uint]) -> int:
  ...

@native
@native_name("WSASetFailConnectOnIcmpError")
def pyiWsaSetFailConnectOnIcmpError(Socket: uint64, Enabled: uint) -> int:
  ...

@native
@native_name("WSASetIPUserMtu")
def pyiWsaSetIpUserMtu(Socket: uint64, Mtu: uint) -> int:
  ...

@native
@native_name("WSASetReceivedProcessorOption")
def pyiWsaSetReceivedProcessorOption(Socket: uint64, Enabled: int) -> int:
  ...

@native
@native_name("WSASetRecvIPEcn")
def pyiWsaSetRecvIpEcn(Socket: uint64, Enabled: uint) -> int:
  ...

@native
@native_name("WSASetUdpRecvMaxCoalescedSize")
def pyiWsaSetUdpRecvMaxCoalescedSize(Socket: uint64, MaxCoalescedMsgSize: uint) -> int:
  ...

@native
@native_name("WSASetUdpSendMessageSize")
def pyiWsaSetUdpSendMessageSize(Socket: uint64, MsgSize: uint) -> int:
  ...

@native
@native_name("freeaddrinfo")
def pyiFreeaddrinfo(pAddrInfo: Pointer[PyiAddrinfo]) -> None:
  ...

@native
@native_name("gai_strerrorA")
def pyiGaiStrerrorA(ecode: int) -> CStr:
  ...

@native
@native_name("gai_strerrorW")
def pyiGaiStrerrorW(ecode: int) -> CStr:
  ...

@native
@native_name("getaddrinfo")
def pyiGetaddrinfo(pNodeName: CStr, pServiceName: CStr, pHints: Pointer[PyiAddrinfo], ppResult: Pointer[Pointer[PyiAddrinfo]]) -> int:
  ...

@native
@native_name("getipv4sourcefilter")
def pyiGetipv4Sourcefilter(Socket: uint64, Interface: PyiInAddr, Group: PyiInAddr, FilterMode: Pointer[PyiMulticastModeType], SourceCount: Pointer[uint], SourceList: Pointer[PyiInAddr]) -> int:
  ...

@native
@native_name("getnameinfo")
def pyiGetnameinfo(pSockaddr: Pointer[PyiSockaddr], SockaddrLength: int, pNodeBuffer: CStr, NodeBufferSize: uint, pServiceBuffer: CStr, ServiceBufferSize: uint, Flags: int) -> int:
  ...

@native
@native_name("getsourcefilter")
def pyiGetsourcefilter(Socket: uint64, Interface: uint, Group: Pointer[PyiSockaddr], GroupLength: int, FilterMode: Pointer[PyiMulticastModeType], SourceCount: Pointer[uint], SourceList: Pointer[PyiSockaddrStorage]) -> int:
  ...

@native
@native_name("idealsendbacklognotify")
def pyiIdealsendbacklognotify(s: uint64, lpOverlapped: Pointer[PyiOverlapped], lpCompletionRoutine: Function[[uint, uint, Pointer[PyiOverlapped], uint], None]) -> int:
  ...

@native
@native_name("idealsendbacklogquery")
def pyiIdealsendbacklogquery(s: uint64, pISB: Pointer[uint]) -> int:
  ...

@native
@native_name("inet_ntop")
def pyiInetNtop(Family: int, pAddr: uintptr, pStringBuf: CStr, StringBufSize: uint64) -> CStr:
  ...

@native
@native_name("inet_pton")
def pyiInetPton(Family: int, pszAddrString: CStr, pAddrBuf: uintptr) -> int:
  ...

@native
@native_name("setipv4sourcefilter")
def pyiSetipv4Sourcefilter(Socket: uint64, Interface: PyiInAddr, Group: PyiInAddr, FilterMode: PyiMulticastModeType, SourceCount: uint, SourceList: Pointer[PyiInAddr]) -> int:
  ...

@native
@native_name("setsourcefilter")
def pyiSetsourcefilter(Socket: uint64, Interface: uint, Group: Pointer[PyiSockaddr], GroupLength: int, FilterMode: PyiMulticastModeType, SourceCount: uint, SourceList: Pointer[PyiSockaddrStorage]) -> int:
  ...

# stats: structs=17 enums=2 aliases=3 consts=3 funcs=39
