"""I/O 协议：``TextWriterType`` / ``TextReaderType`` / ``TextIOType``（``@protocol``，供 ``Json`` 等）。"""
from ..builtins import *
from __future__ import annotations

from ..core.protocols import Self, protocol


@protocol
class TextWriterType:
  """文本写出端；``TextIO`` / ``StringIO`` 均实现。"""

  @overload
  def write(self, s: str) -> int: ...

  @overload
  def write(self, src: char[:], end: int = int.Max) -> int: ...

  def flush(self) -> None: ...


@protocol
class TextReaderType:
  """文本读入端；``TextIO`` / ``StringIO`` 均实现。"""

  def read(self, size: int = int.Max) -> str: ...


@protocol
class TextIOType:
  """文本双向流（``io.TextIOBase`` 子集）；``StringIO`` / ``TextIO`` 均实现。"""

  def __bool__(self) -> bool: ...

  def __enter__(self) -> Self: ...

  def __exit__(self): ...

  def read(self, size: int = int.Max) -> str: ...

  def readLine(self, size: int = int.Max) -> str: ...

  def readLines(self, hint: int = int.Max) -> list[str]: ...

  @overload
  def write(self, s: str) -> int: ...

  @overload
  def write(self, src: char[:], end: int = int.Max) -> int: ...

  def writeLines(self, lines: list[str]) -> None: ...

  def flush(self) -> None: ...

  def __iter__(self) -> Self: ...

  def __next__(self) -> str: ...

  def close(self) -> None: ...

  def seek(self, pos: int, whence: int = 0) -> int: ...

  def tell(self) -> int: ...

  @property
  def isAtty(self) -> bool: ...
