# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\gl\GL.h
# Generated: 2026-08-20 21:45:33
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

PyiGl2D: int @native_name("GL_2D") = 0x0600
PyiGl2Bytes: int @native_name("GL_2_BYTES") = 0x1407
PyiGl3D: int @native_name("GL_3D") = 0x0601
PyiGl3DColor: int @native_name("GL_3D_COLOR") = 0x0602
PyiGl3DColorTexture: int @native_name("GL_3D_COLOR_TEXTURE") = 0x0603
PyiGl3Bytes: int @native_name("GL_3_BYTES") = 0x1408
PyiGl4DColorTexture: int @native_name("GL_4D_COLOR_TEXTURE") = 0x0604
PyiGl4Bytes: int @native_name("GL_4_BYTES") = 0x1409
PyiGlAccum: int @native_name("GL_ACCUM") = 0x0100
PyiGlAccumAlphaBits: int @native_name("GL_ACCUM_ALPHA_BITS") = 0x0D5B
PyiGlAccumBlueBits: int @native_name("GL_ACCUM_BLUE_BITS") = 0x0D5A
PyiGlAccumBufferBit: int @native_name("GL_ACCUM_BUFFER_BIT") = 0x00000200
PyiGlAccumClearValue: int @native_name("GL_ACCUM_CLEAR_VALUE") = 0x0B80
PyiGlAccumGreenBits: int @native_name("GL_ACCUM_GREEN_BITS") = 0x0D59
PyiGlAccumRedBits: int @native_name("GL_ACCUM_RED_BITS") = 0x0D58
PyiGlAdd: int @native_name("GL_ADD") = 0x0104
PyiGlAllAttribBits: int @native_name("GL_ALL_ATTRIB_BITS") = 0x000fffff
PyiGlAlpha: int @native_name("GL_ALPHA") = 0x1906
PyiGlAlpha12: int @native_name("GL_ALPHA12") = 0x803D
PyiGlAlpha16: int @native_name("GL_ALPHA16") = 0x803E
PyiGlAlpha4: int @native_name("GL_ALPHA4") = 0x803B
PyiGlAlpha8: int @native_name("GL_ALPHA8") = 0x803C
PyiGlAlphaBias: int @native_name("GL_ALPHA_BIAS") = 0x0D1D
PyiGlAlphaBits: int @native_name("GL_ALPHA_BITS") = 0x0D55
PyiGlAlphaScale: int @native_name("GL_ALPHA_SCALE") = 0x0D1C
PyiGlAlphaTest: int @native_name("GL_ALPHA_TEST") = 0x0BC0
PyiGlAlphaTestFunc: int @native_name("GL_ALPHA_TEST_FUNC") = 0x0BC1
PyiGlAlphaTestRef: int @native_name("GL_ALPHA_TEST_REF") = 0x0BC2
PyiGlAlways: int @native_name("GL_ALWAYS") = 0x0207
PyiGlAmbient: int @native_name("GL_AMBIENT") = 0x1200
PyiGlAmbientAndDiffuse: int @native_name("GL_AMBIENT_AND_DIFFUSE") = 0x1602
PyiGlAnd: int @native_name("GL_AND") = 0x1501
PyiGlAndInverted: int @native_name("GL_AND_INVERTED") = 0x1504
PyiGlAndReverse: int @native_name("GL_AND_REVERSE") = 0x1502
PyiGlAttribStackDepth: int @native_name("GL_ATTRIB_STACK_DEPTH") = 0x0BB0
PyiGlAutoNormal: int @native_name("GL_AUTO_NORMAL") = 0x0D80
PyiGlAux0: int @native_name("GL_AUX0") = 0x0409
PyiGlAux1: int @native_name("GL_AUX1") = 0x040A
PyiGlAux2: int @native_name("GL_AUX2") = 0x040B
PyiGlAux3: int @native_name("GL_AUX3") = 0x040C
PyiGlAuxBuffers: int @native_name("GL_AUX_BUFFERS") = 0x0C00
PyiGlBack: int @native_name("GL_BACK") = 0x0405
PyiGlBackLeft: int @native_name("GL_BACK_LEFT") = 0x0402
PyiGlBackRight: int @native_name("GL_BACK_RIGHT") = 0x0403
PyiGlBgraExt: int @native_name("GL_BGRA_EXT") = 0x80E1
PyiGlBgrExt: int @native_name("GL_BGR_EXT") = 0x80E0
PyiGlBitmap: int @native_name("GL_BITMAP") = 0x1A00
PyiGlBitmapToken: int @native_name("GL_BITMAP_TOKEN") = 0x0704
PyiGlBlend: int @native_name("GL_BLEND") = 0x0BE2
PyiGlBlendDst: int @native_name("GL_BLEND_DST") = 0x0BE0
PyiGlBlendSrc: int @native_name("GL_BLEND_SRC") = 0x0BE1
PyiGlBlue: int @native_name("GL_BLUE") = 0x1905
PyiGlBlueBias: int @native_name("GL_BLUE_BIAS") = 0x0D1B
PyiGlBlueBits: int @native_name("GL_BLUE_BITS") = 0x0D54
PyiGlBlueScale: int @native_name("GL_BLUE_SCALE") = 0x0D1A
PyiGlByte: int @native_name("GL_BYTE") = 0x1400
PyiGlC3FV3F: int @native_name("GL_C3F_V3F") = 0x2A24
PyiGlC4FN3FV3F: int @native_name("GL_C4F_N3F_V3F") = 0x2A26
PyiGlC4UbV2F: int @native_name("GL_C4UB_V2F") = 0x2A22
PyiGlC4UbV3F: int @native_name("GL_C4UB_V3F") = 0x2A23
PyiGlCcw: int @native_name("GL_CCW") = 0x0901
PyiGlClamp: int @native_name("GL_CLAMP") = 0x2900
PyiGlClear: int @native_name("GL_CLEAR") = 0x1500
PyiGlClientAllAttribBits: int @native_name("GL_CLIENT_ALL_ATTRIB_BITS") = 0xffffffff
PyiGlClientAttribStackDepth: int @native_name("GL_CLIENT_ATTRIB_STACK_DEPTH") = 0x0BB1
PyiGlClientPixelStoreBit: int @native_name("GL_CLIENT_PIXEL_STORE_BIT") = 0x00000001
PyiGlClientVertexArrayBit: int @native_name("GL_CLIENT_VERTEX_ARRAY_BIT") = 0x00000002
PyiGlClipPlane0: int @native_name("GL_CLIP_PLANE0") = 0x3000
PyiGlClipPlane1: int @native_name("GL_CLIP_PLANE1") = 0x3001
PyiGlClipPlane2: int @native_name("GL_CLIP_PLANE2") = 0x3002
PyiGlClipPlane3: int @native_name("GL_CLIP_PLANE3") = 0x3003
PyiGlClipPlane4: int @native_name("GL_CLIP_PLANE4") = 0x3004
PyiGlClipPlane5: int @native_name("GL_CLIP_PLANE5") = 0x3005
PyiGlCoeff: int @native_name("GL_COEFF") = 0x0A00
PyiGlColor: int @native_name("GL_COLOR") = 0x1800
PyiGlColorArray: int @native_name("GL_COLOR_ARRAY") = 0x8076
PyiGlColorArrayCountExt: int @native_name("GL_COLOR_ARRAY_COUNT_EXT") = 0x8084
PyiGlColorArrayExt: int @native_name("GL_COLOR_ARRAY_EXT") = 0x8076
PyiGlColorArrayPointer: int @native_name("GL_COLOR_ARRAY_POINTER") = 0x8090
PyiGlColorArrayPointerExt: int @native_name("GL_COLOR_ARRAY_POINTER_EXT") = 0x8090
PyiGlColorArraySize: int @native_name("GL_COLOR_ARRAY_SIZE") = 0x8081
PyiGlColorArraySizeExt: int @native_name("GL_COLOR_ARRAY_SIZE_EXT") = 0x8081
PyiGlColorArrayStride: int @native_name("GL_COLOR_ARRAY_STRIDE") = 0x8083
PyiGlColorArrayStrideExt: int @native_name("GL_COLOR_ARRAY_STRIDE_EXT") = 0x8083
PyiGlColorArrayType: int @native_name("GL_COLOR_ARRAY_TYPE") = 0x8082
PyiGlColorArrayTypeExt: int @native_name("GL_COLOR_ARRAY_TYPE_EXT") = 0x8082
PyiGlColorBufferBit: int @native_name("GL_COLOR_BUFFER_BIT") = 0x00004000
PyiGlColorClearValue: int @native_name("GL_COLOR_CLEAR_VALUE") = 0x0C22
PyiGlColorIndex: int @native_name("GL_COLOR_INDEX") = 0x1900
PyiGlColorIndex12Ext: int @native_name("GL_COLOR_INDEX12_EXT") = 0x80E6
PyiGlColorIndex16Ext: int @native_name("GL_COLOR_INDEX16_EXT") = 0x80E7
PyiGlColorIndex1Ext: int @native_name("GL_COLOR_INDEX1_EXT") = 0x80E2
PyiGlColorIndex2Ext: int @native_name("GL_COLOR_INDEX2_EXT") = 0x80E3
PyiGlColorIndex4Ext: int @native_name("GL_COLOR_INDEX4_EXT") = 0x80E4
PyiGlColorIndex8Ext: int @native_name("GL_COLOR_INDEX8_EXT") = 0x80E5
PyiGlColorIndexes: int @native_name("GL_COLOR_INDEXES") = 0x1603
PyiGlColorLogicOp: int @native_name("GL_COLOR_LOGIC_OP") = 0x0BF2
PyiGlColorMaterial: int @native_name("GL_COLOR_MATERIAL") = 0x0B57
PyiGlColorMaterialFace: int @native_name("GL_COLOR_MATERIAL_FACE") = 0x0B55
PyiGlColorMaterialParameter: int @native_name("GL_COLOR_MATERIAL_PARAMETER") = 0x0B56
PyiGlColorTableAlphaSizeExt: int @native_name("GL_COLOR_TABLE_ALPHA_SIZE_EXT") = 0x80DD
PyiGlColorTableBlueSizeExt: int @native_name("GL_COLOR_TABLE_BLUE_SIZE_EXT") = 0x80DC
PyiGlColorTableFormatExt: int @native_name("GL_COLOR_TABLE_FORMAT_EXT") = 0x80D8
PyiGlColorTableGreenSizeExt: int @native_name("GL_COLOR_TABLE_GREEN_SIZE_EXT") = 0x80DB
PyiGlColorTableIntensitySizeExt: int @native_name("GL_COLOR_TABLE_INTENSITY_SIZE_EXT") = 0x80DF
PyiGlColorTableLuminanceSizeExt: int @native_name("GL_COLOR_TABLE_LUMINANCE_SIZE_EXT") = 0x80DE
PyiGlColorTableRedSizeExt: int @native_name("GL_COLOR_TABLE_RED_SIZE_EXT") = 0x80DA
PyiGlColorTableWidthExt: int @native_name("GL_COLOR_TABLE_WIDTH_EXT") = 0x80D9
PyiGlColorWritemask: int @native_name("GL_COLOR_WRITEMASK") = 0x0C23
PyiGlCompile: int @native_name("GL_COMPILE") = 0x1300
PyiGlCompileAndExecute: int @native_name("GL_COMPILE_AND_EXECUTE") = 0x1301
PyiGlConstantAttenuation: int @native_name("GL_CONSTANT_ATTENUATION") = 0x1207
PyiGlCopy: int @native_name("GL_COPY") = 0x1503
PyiGlCopyInverted: int @native_name("GL_COPY_INVERTED") = 0x150C
PyiGlCopyPixelToken: int @native_name("GL_COPY_PIXEL_TOKEN") = 0x0706
PyiGlCullFace: int @native_name("GL_CULL_FACE") = 0x0B44
PyiGlCullFaceMode: int @native_name("GL_CULL_FACE_MODE") = 0x0B45
PyiGlCurrentBit: int @native_name("GL_CURRENT_BIT") = 0x00000001
PyiGlCurrentColor: int @native_name("GL_CURRENT_COLOR") = 0x0B00
PyiGlCurrentIndex: int @native_name("GL_CURRENT_INDEX") = 0x0B01
PyiGlCurrentNormal: int @native_name("GL_CURRENT_NORMAL") = 0x0B02
PyiGlCurrentRasterColor: int @native_name("GL_CURRENT_RASTER_COLOR") = 0x0B04
PyiGlCurrentRasterDistance: int @native_name("GL_CURRENT_RASTER_DISTANCE") = 0x0B09
PyiGlCurrentRasterIndex: int @native_name("GL_CURRENT_RASTER_INDEX") = 0x0B05
PyiGlCurrentRasterPosition: int @native_name("GL_CURRENT_RASTER_POSITION") = 0x0B07
PyiGlCurrentRasterPositionValid: int @native_name("GL_CURRENT_RASTER_POSITION_VALID") = 0x0B08
PyiGlCurrentRasterTextureCoords: int @native_name("GL_CURRENT_RASTER_TEXTURE_COORDS") = 0x0B06
PyiGlCurrentTextureCoords: int @native_name("GL_CURRENT_TEXTURE_COORDS") = 0x0B03
PyiGlCw: int @native_name("GL_CW") = 0x0900
PyiGlDecal: int @native_name("GL_DECAL") = 0x2101
PyiGlDecr: int @native_name("GL_DECR") = 0x1E03
PyiGlDepth: int @native_name("GL_DEPTH") = 0x1801
PyiGlDepthBias: int @native_name("GL_DEPTH_BIAS") = 0x0D1F
PyiGlDepthBits: int @native_name("GL_DEPTH_BITS") = 0x0D56
PyiGlDepthBufferBit: int @native_name("GL_DEPTH_BUFFER_BIT") = 0x00000100
PyiGlDepthClearValue: int @native_name("GL_DEPTH_CLEAR_VALUE") = 0x0B73
PyiGlDepthComponent: int @native_name("GL_DEPTH_COMPONENT") = 0x1902
PyiGlDepthFunc: int @native_name("GL_DEPTH_FUNC") = 0x0B74
PyiGlDepthRange: int @native_name("GL_DEPTH_RANGE") = 0x0B70
PyiGlDepthScale: int @native_name("GL_DEPTH_SCALE") = 0x0D1E
PyiGlDepthTest: int @native_name("GL_DEPTH_TEST") = 0x0B71
PyiGlDepthWritemask: int @native_name("GL_DEPTH_WRITEMASK") = 0x0B72
PyiGlDiffuse: int @native_name("GL_DIFFUSE") = 0x1201
PyiGlDither: int @native_name("GL_DITHER") = 0x0BD0
PyiGlDomain: int @native_name("GL_DOMAIN") = 0x0A02
PyiGlDontCare: int @native_name("GL_DONT_CARE") = 0x1100
PyiGlDouble: int @native_name("GL_DOUBLE") = 0x140A
PyiGlDoublebuffer: int @native_name("GL_DOUBLEBUFFER") = 0x0C32
PyiGlDoubleExt: int @native_name("GL_DOUBLE_EXT") = 0x140A
PyiGlDrawBuffer: int @native_name("GL_DRAW_BUFFER") = 0x0C01
PyiGlDrawPixelToken: int @native_name("GL_DRAW_PIXEL_TOKEN") = 0x0705
PyiGlDstAlpha: int @native_name("GL_DST_ALPHA") = 0x0304
PyiGlDstColor: int @native_name("GL_DST_COLOR") = 0x0306
PyiGlEdgeFlag: int @native_name("GL_EDGE_FLAG") = 0x0B43
PyiGlEdgeFlagArray: int @native_name("GL_EDGE_FLAG_ARRAY") = 0x8079
PyiGlEdgeFlagArrayCountExt: int @native_name("GL_EDGE_FLAG_ARRAY_COUNT_EXT") = 0x808D
PyiGlEdgeFlagArrayExt: int @native_name("GL_EDGE_FLAG_ARRAY_EXT") = 0x8079
PyiGlEdgeFlagArrayPointer: int @native_name("GL_EDGE_FLAG_ARRAY_POINTER") = 0x8093
PyiGlEdgeFlagArrayPointerExt: int @native_name("GL_EDGE_FLAG_ARRAY_POINTER_EXT") = 0x8093
PyiGlEdgeFlagArrayStride: int @native_name("GL_EDGE_FLAG_ARRAY_STRIDE") = 0x808C
PyiGlEdgeFlagArrayStrideExt: int @native_name("GL_EDGE_FLAG_ARRAY_STRIDE_EXT") = 0x808C
PyiGlEmission: int @native_name("GL_EMISSION") = 0x1600
PyiGlEnableBit: int @native_name("GL_ENABLE_BIT") = 0x00002000
PyiGlEqual: int @native_name("GL_EQUAL") = 0x0202
PyiGlEquiv: int @native_name("GL_EQUIV") = 0x1509
PyiGlEvalBit: int @native_name("GL_EVAL_BIT") = 0x00010000
PyiGlExp: int @native_name("GL_EXP") = 0x0800
PyiGlExp2: int @native_name("GL_EXP2") = 0x0801
PyiGlExtensions: int @native_name("GL_EXTENSIONS") = 0x1F03
PyiGlExtBgra: int @native_name("GL_EXT_bgra") = 1
PyiGlExtPalettedTexture: int @native_name("GL_EXT_paletted_texture") = 1
PyiGlExtVertexArray: int @native_name("GL_EXT_vertex_array") = 1
PyiGlEyeLinear: int @native_name("GL_EYE_LINEAR") = 0x2400
PyiGlEyePlane: int @native_name("GL_EYE_PLANE") = 0x2502
PyiGlFalse: int @native_name("GL_FALSE") = 0
PyiGlFastest: int @native_name("GL_FASTEST") = 0x1101
PyiGlFeedback: int @native_name("GL_FEEDBACK") = 0x1C01
PyiGlFeedbackBufferPointer: int @native_name("GL_FEEDBACK_BUFFER_POINTER") = 0x0DF0
PyiGlFeedbackBufferSize: int @native_name("GL_FEEDBACK_BUFFER_SIZE") = 0x0DF1
PyiGlFeedbackBufferType: int @native_name("GL_FEEDBACK_BUFFER_TYPE") = 0x0DF2
PyiGlFill: int @native_name("GL_FILL") = 0x1B02
PyiGlFlat: int @native_name("GL_FLAT") = 0x1D00
PyiGlFloat: int @native_name("GL_FLOAT") = 0x1406
PyiGlFog: int @native_name("GL_FOG") = 0x0B60
PyiGlFogBit: int @native_name("GL_FOG_BIT") = 0x00000080
PyiGlFogColor: int @native_name("GL_FOG_COLOR") = 0x0B66
PyiGlFogDensity: int @native_name("GL_FOG_DENSITY") = 0x0B62
PyiGlFogEnd: int @native_name("GL_FOG_END") = 0x0B64
PyiGlFogHint: int @native_name("GL_FOG_HINT") = 0x0C54
PyiGlFogIndex: int @native_name("GL_FOG_INDEX") = 0x0B61
PyiGlFogMode: int @native_name("GL_FOG_MODE") = 0x0B65
PyiGlFogSpecularTextureWin: int @native_name("GL_FOG_SPECULAR_TEXTURE_WIN") = 0x80EC
PyiGlFogStart: int @native_name("GL_FOG_START") = 0x0B63
PyiGlFront: int @native_name("GL_FRONT") = 0x0404
PyiGlFrontAndBack: int @native_name("GL_FRONT_AND_BACK") = 0x0408
PyiGlFrontFace: int @native_name("GL_FRONT_FACE") = 0x0B46
PyiGlFrontLeft: int @native_name("GL_FRONT_LEFT") = 0x0400
PyiGlFrontRight: int @native_name("GL_FRONT_RIGHT") = 0x0401
PyiGlGequal: int @native_name("GL_GEQUAL") = 0x0206
PyiGlGreater: int @native_name("GL_GREATER") = 0x0204
PyiGlGreen: int @native_name("GL_GREEN") = 0x1904
PyiGlGreenBias: int @native_name("GL_GREEN_BIAS") = 0x0D19
PyiGlGreenBits: int @native_name("GL_GREEN_BITS") = 0x0D53
PyiGlGreenScale: int @native_name("GL_GREEN_SCALE") = 0x0D18
PyiGlHintBit: int @native_name("GL_HINT_BIT") = 0x00008000
PyiGlIncr: int @native_name("GL_INCR") = 0x1E02
PyiGlIndexArray: int @native_name("GL_INDEX_ARRAY") = 0x8077
PyiGlIndexArrayCountExt: int @native_name("GL_INDEX_ARRAY_COUNT_EXT") = 0x8087
PyiGlIndexArrayExt: int @native_name("GL_INDEX_ARRAY_EXT") = 0x8077
PyiGlIndexArrayPointer: int @native_name("GL_INDEX_ARRAY_POINTER") = 0x8091
PyiGlIndexArrayPointerExt: int @native_name("GL_INDEX_ARRAY_POINTER_EXT") = 0x8091
PyiGlIndexArrayStride: int @native_name("GL_INDEX_ARRAY_STRIDE") = 0x8086
PyiGlIndexArrayStrideExt: int @native_name("GL_INDEX_ARRAY_STRIDE_EXT") = 0x8086
PyiGlIndexArrayType: int @native_name("GL_INDEX_ARRAY_TYPE") = 0x8085
PyiGlIndexArrayTypeExt: int @native_name("GL_INDEX_ARRAY_TYPE_EXT") = 0x8085
PyiGlIndexBits: int @native_name("GL_INDEX_BITS") = 0x0D51
PyiGlIndexClearValue: int @native_name("GL_INDEX_CLEAR_VALUE") = 0x0C20
PyiGlIndexLogicOp: int @native_name("GL_INDEX_LOGIC_OP") = 0x0BF1
PyiGlIndexMode: int @native_name("GL_INDEX_MODE") = 0x0C30
PyiGlIndexOffset: int @native_name("GL_INDEX_OFFSET") = 0x0D13
PyiGlIndexShift: int @native_name("GL_INDEX_SHIFT") = 0x0D12
PyiGlIndexWritemask: int @native_name("GL_INDEX_WRITEMASK") = 0x0C21
PyiGlInt: int @native_name("GL_INT") = 0x1404
PyiGlIntensity: int @native_name("GL_INTENSITY") = 0x8049
PyiGlIntensity12: int @native_name("GL_INTENSITY12") = 0x804C
PyiGlIntensity16: int @native_name("GL_INTENSITY16") = 0x804D
PyiGlIntensity4: int @native_name("GL_INTENSITY4") = 0x804A
PyiGlIntensity8: int @native_name("GL_INTENSITY8") = 0x804B
PyiGlInvalidEnum: int @native_name("GL_INVALID_ENUM") = 0x0500
PyiGlInvalidOperation: int @native_name("GL_INVALID_OPERATION") = 0x0502
PyiGlInvalidValue: int @native_name("GL_INVALID_VALUE") = 0x0501
PyiGlInvert: int @native_name("GL_INVERT") = 0x150A
PyiGlKeep: int @native_name("GL_KEEP") = 0x1E00
PyiGlLeft: int @native_name("GL_LEFT") = 0x0406
PyiGlLequal: int @native_name("GL_LEQUAL") = 0x0203
PyiGlLess: int @native_name("GL_LESS") = 0x0201
PyiGlLight0: int @native_name("GL_LIGHT0") = 0x4000
PyiGlLight1: int @native_name("GL_LIGHT1") = 0x4001
PyiGlLight2: int @native_name("GL_LIGHT2") = 0x4002
PyiGlLight3: int @native_name("GL_LIGHT3") = 0x4003
PyiGlLight4: int @native_name("GL_LIGHT4") = 0x4004
PyiGlLight5: int @native_name("GL_LIGHT5") = 0x4005
PyiGlLight6: int @native_name("GL_LIGHT6") = 0x4006
PyiGlLight7: int @native_name("GL_LIGHT7") = 0x4007
PyiGlLighting: int @native_name("GL_LIGHTING") = 0x0B50
PyiGlLightingBit: int @native_name("GL_LIGHTING_BIT") = 0x00000040
PyiGlLightModelAmbient: int @native_name("GL_LIGHT_MODEL_AMBIENT") = 0x0B53
PyiGlLightModelLocalViewer: int @native_name("GL_LIGHT_MODEL_LOCAL_VIEWER") = 0x0B51
PyiGlLightModelTwoSide: int @native_name("GL_LIGHT_MODEL_TWO_SIDE") = 0x0B52
PyiGlLine: int @native_name("GL_LINE") = 0x1B01
PyiGlLinear: int @native_name("GL_LINEAR") = 0x2601
PyiGlLinearAttenuation: int @native_name("GL_LINEAR_ATTENUATION") = 0x1208
PyiGlLinearMipmapLinear: int @native_name("GL_LINEAR_MIPMAP_LINEAR") = 0x2703
PyiGlLinearMipmapNearest: int @native_name("GL_LINEAR_MIPMAP_NEAREST") = 0x2701
PyiGlLines: int @native_name("GL_LINES") = 0x0001
PyiGlLineBit: int @native_name("GL_LINE_BIT") = 0x00000004
PyiGlLineLoop: int @native_name("GL_LINE_LOOP") = 0x0002
PyiGlLineResetToken: int @native_name("GL_LINE_RESET_TOKEN") = 0x0707
PyiGlLineSmooth: int @native_name("GL_LINE_SMOOTH") = 0x0B20
PyiGlLineSmoothHint: int @native_name("GL_LINE_SMOOTH_HINT") = 0x0C52
PyiGlLineStipple: int @native_name("GL_LINE_STIPPLE") = 0x0B24
PyiGlLineStipplePattern: int @native_name("GL_LINE_STIPPLE_PATTERN") = 0x0B25
PyiGlLineStippleRepeat: int @native_name("GL_LINE_STIPPLE_REPEAT") = 0x0B26
PyiGlLineStrip: int @native_name("GL_LINE_STRIP") = 0x0003
PyiGlLineToken: int @native_name("GL_LINE_TOKEN") = 0x0702
PyiGlLineWidth: int @native_name("GL_LINE_WIDTH") = 0x0B21
PyiGlLineWidthGranularity: int @native_name("GL_LINE_WIDTH_GRANULARITY") = 0x0B23
PyiGlLineWidthRange: int @native_name("GL_LINE_WIDTH_RANGE") = 0x0B22
PyiGlListBase: int @native_name("GL_LIST_BASE") = 0x0B32
PyiGlListBit: int @native_name("GL_LIST_BIT") = 0x00020000
PyiGlListIndex: int @native_name("GL_LIST_INDEX") = 0x0B33
PyiGlListMode: int @native_name("GL_LIST_MODE") = 0x0B30
PyiGlLoad: int @native_name("GL_LOAD") = 0x0101
PyiGlLogicOp: int @native_name("GL_LOGIC_OP") = 0x0BF1
PyiGlLogicOpMode: int @native_name("GL_LOGIC_OP_MODE") = 0x0BF0
PyiGlLuminance: int @native_name("GL_LUMINANCE") = 0x1909
PyiGlLuminance12: int @native_name("GL_LUMINANCE12") = 0x8041
PyiGlLuminance12Alpha12: int @native_name("GL_LUMINANCE12_ALPHA12") = 0x8047
PyiGlLuminance12Alpha4: int @native_name("GL_LUMINANCE12_ALPHA4") = 0x8046
PyiGlLuminance16: int @native_name("GL_LUMINANCE16") = 0x8042
PyiGlLuminance16Alpha16: int @native_name("GL_LUMINANCE16_ALPHA16") = 0x8048
PyiGlLuminance4: int @native_name("GL_LUMINANCE4") = 0x803F
PyiGlLuminance4Alpha4: int @native_name("GL_LUMINANCE4_ALPHA4") = 0x8043
PyiGlLuminance6Alpha2: int @native_name("GL_LUMINANCE6_ALPHA2") = 0x8044
PyiGlLuminance8: int @native_name("GL_LUMINANCE8") = 0x8040
PyiGlLuminance8Alpha8: int @native_name("GL_LUMINANCE8_ALPHA8") = 0x8045
PyiGlLuminanceAlpha: int @native_name("GL_LUMINANCE_ALPHA") = 0x190A
PyiGlMap1Color4: int @native_name("GL_MAP1_COLOR_4") = 0x0D90
PyiGlMap1GridDomain: int @native_name("GL_MAP1_GRID_DOMAIN") = 0x0DD0
PyiGlMap1GridSegments: int @native_name("GL_MAP1_GRID_SEGMENTS") = 0x0DD1
PyiGlMap1Index: int @native_name("GL_MAP1_INDEX") = 0x0D91
PyiGlMap1Normal: int @native_name("GL_MAP1_NORMAL") = 0x0D92
PyiGlMap1TextureCoord1: int @native_name("GL_MAP1_TEXTURE_COORD_1") = 0x0D93
PyiGlMap1TextureCoord2: int @native_name("GL_MAP1_TEXTURE_COORD_2") = 0x0D94
PyiGlMap1TextureCoord3: int @native_name("GL_MAP1_TEXTURE_COORD_3") = 0x0D95
PyiGlMap1TextureCoord4: int @native_name("GL_MAP1_TEXTURE_COORD_4") = 0x0D96
PyiGlMap1Vertex3: int @native_name("GL_MAP1_VERTEX_3") = 0x0D97
PyiGlMap1Vertex4: int @native_name("GL_MAP1_VERTEX_4") = 0x0D98
PyiGlMap2Color4: int @native_name("GL_MAP2_COLOR_4") = 0x0DB0
PyiGlMap2GridDomain: int @native_name("GL_MAP2_GRID_DOMAIN") = 0x0DD2
PyiGlMap2GridSegments: int @native_name("GL_MAP2_GRID_SEGMENTS") = 0x0DD3
PyiGlMap2Index: int @native_name("GL_MAP2_INDEX") = 0x0DB1
PyiGlMap2Normal: int @native_name("GL_MAP2_NORMAL") = 0x0DB2
PyiGlMap2TextureCoord1: int @native_name("GL_MAP2_TEXTURE_COORD_1") = 0x0DB3
PyiGlMap2TextureCoord2: int @native_name("GL_MAP2_TEXTURE_COORD_2") = 0x0DB4
PyiGlMap2TextureCoord3: int @native_name("GL_MAP2_TEXTURE_COORD_3") = 0x0DB5
PyiGlMap2TextureCoord4: int @native_name("GL_MAP2_TEXTURE_COORD_4") = 0x0DB6
PyiGlMap2Vertex3: int @native_name("GL_MAP2_VERTEX_3") = 0x0DB7
PyiGlMap2Vertex4: int @native_name("GL_MAP2_VERTEX_4") = 0x0DB8
PyiGlMapColor: int @native_name("GL_MAP_COLOR") = 0x0D10
PyiGlMapStencil: int @native_name("GL_MAP_STENCIL") = 0x0D11
PyiGlMatrixMode: int @native_name("GL_MATRIX_MODE") = 0x0BA0
PyiGlMaxAttribStackDepth: int @native_name("GL_MAX_ATTRIB_STACK_DEPTH") = 0x0D35
PyiGlMaxClientAttribStackDepth: int @native_name("GL_MAX_CLIENT_ATTRIB_STACK_DEPTH") = 0x0D3B
PyiGlMaxClipPlanes: int @native_name("GL_MAX_CLIP_PLANES") = 0x0D32
PyiGlMaxElementsIndicesWin: int @native_name("GL_MAX_ELEMENTS_INDICES_WIN") = 0x80E9
PyiGlMaxElementsVerticesWin: int @native_name("GL_MAX_ELEMENTS_VERTICES_WIN") = 0x80E8
PyiGlMaxEvalOrder: int @native_name("GL_MAX_EVAL_ORDER") = 0x0D30
PyiGlMaxLights: int @native_name("GL_MAX_LIGHTS") = 0x0D31
PyiGlMaxListNesting: int @native_name("GL_MAX_LIST_NESTING") = 0x0B31
PyiGlMaxModelviewStackDepth: int @native_name("GL_MAX_MODELVIEW_STACK_DEPTH") = 0x0D36
PyiGlMaxNameStackDepth: int @native_name("GL_MAX_NAME_STACK_DEPTH") = 0x0D37
PyiGlMaxPixelMapTable: int @native_name("GL_MAX_PIXEL_MAP_TABLE") = 0x0D34
PyiGlMaxProjectionStackDepth: int @native_name("GL_MAX_PROJECTION_STACK_DEPTH") = 0x0D38
PyiGlMaxTextureSize: int @native_name("GL_MAX_TEXTURE_SIZE") = 0x0D33
PyiGlMaxTextureStackDepth: int @native_name("GL_MAX_TEXTURE_STACK_DEPTH") = 0x0D39
PyiGlMaxViewportDims: int @native_name("GL_MAX_VIEWPORT_DIMS") = 0x0D3A
PyiGlModelview: int @native_name("GL_MODELVIEW") = 0x1700
PyiGlModelviewMatrix: int @native_name("GL_MODELVIEW_MATRIX") = 0x0BA6
PyiGlModelviewStackDepth: int @native_name("GL_MODELVIEW_STACK_DEPTH") = 0x0BA3
PyiGlModulate: int @native_name("GL_MODULATE") = 0x2100
PyiGlMult: int @native_name("GL_MULT") = 0x0103
PyiGlN3FV3F: int @native_name("GL_N3F_V3F") = 0x2A25
PyiGlNameStackDepth: int @native_name("GL_NAME_STACK_DEPTH") = 0x0D70
PyiGlNand: int @native_name("GL_NAND") = 0x150E
PyiGlNearest: int @native_name("GL_NEAREST") = 0x2600
PyiGlNearestMipmapLinear: int @native_name("GL_NEAREST_MIPMAP_LINEAR") = 0x2702
PyiGlNearestMipmapNearest: int @native_name("GL_NEAREST_MIPMAP_NEAREST") = 0x2700
PyiGlNever: int @native_name("GL_NEVER") = 0x0200
PyiGlNicest: int @native_name("GL_NICEST") = 0x1102
PyiGlNone: int @native_name("GL_NONE") = 0
PyiGlNoop: int @native_name("GL_NOOP") = 0x1505
PyiGlNor: int @native_name("GL_NOR") = 0x1508
PyiGlNormalize: int @native_name("GL_NORMALIZE") = 0x0BA1
PyiGlNormalArray: int @native_name("GL_NORMAL_ARRAY") = 0x8075
PyiGlNormalArrayCountExt: int @native_name("GL_NORMAL_ARRAY_COUNT_EXT") = 0x8080
PyiGlNormalArrayExt: int @native_name("GL_NORMAL_ARRAY_EXT") = 0x8075
PyiGlNormalArrayPointer: int @native_name("GL_NORMAL_ARRAY_POINTER") = 0x808F
PyiGlNormalArrayPointerExt: int @native_name("GL_NORMAL_ARRAY_POINTER_EXT") = 0x808F
PyiGlNormalArrayStride: int @native_name("GL_NORMAL_ARRAY_STRIDE") = 0x807F
PyiGlNormalArrayStrideExt: int @native_name("GL_NORMAL_ARRAY_STRIDE_EXT") = 0x807F
PyiGlNormalArrayType: int @native_name("GL_NORMAL_ARRAY_TYPE") = 0x807E
PyiGlNormalArrayTypeExt: int @native_name("GL_NORMAL_ARRAY_TYPE_EXT") = 0x807E
PyiGlNotequal: int @native_name("GL_NOTEQUAL") = 0x0205
PyiGlNoError: int @native_name("GL_NO_ERROR") = 0
PyiGlObjectLinear: int @native_name("GL_OBJECT_LINEAR") = 0x2401
PyiGlObjectPlane: int @native_name("GL_OBJECT_PLANE") = 0x2501
PyiGlOne: int @native_name("GL_ONE") = 1
PyiGlOneMinusDstAlpha: int @native_name("GL_ONE_MINUS_DST_ALPHA") = 0x0305
PyiGlOneMinusDstColor: int @native_name("GL_ONE_MINUS_DST_COLOR") = 0x0307
PyiGlOneMinusSrcAlpha: int @native_name("GL_ONE_MINUS_SRC_ALPHA") = 0x0303
PyiGlOneMinusSrcColor: int @native_name("GL_ONE_MINUS_SRC_COLOR") = 0x0301
PyiGlOr: int @native_name("GL_OR") = 0x1507
PyiGlOrder: int @native_name("GL_ORDER") = 0x0A01
PyiGlOrInverted: int @native_name("GL_OR_INVERTED") = 0x150D
PyiGlOrReverse: int @native_name("GL_OR_REVERSE") = 0x150B
PyiGlOutOfMemory: int @native_name("GL_OUT_OF_MEMORY") = 0x0505
PyiGlPackAlignment: int @native_name("GL_PACK_ALIGNMENT") = 0x0D05
PyiGlPackLsbFirst: int @native_name("GL_PACK_LSB_FIRST") = 0x0D01
PyiGlPackRowLength: int @native_name("GL_PACK_ROW_LENGTH") = 0x0D02
PyiGlPackSkipPixels: int @native_name("GL_PACK_SKIP_PIXELS") = 0x0D04
PyiGlPackSkipRows: int @native_name("GL_PACK_SKIP_ROWS") = 0x0D03
PyiGlPackSwapBytes: int @native_name("GL_PACK_SWAP_BYTES") = 0x0D00
PyiGlPassThroughToken: int @native_name("GL_PASS_THROUGH_TOKEN") = 0x0700
PyiGlPerspectiveCorrectionHint: int @native_name("GL_PERSPECTIVE_CORRECTION_HINT") = 0x0C50
PyiGlPhongHintWin: int @native_name("GL_PHONG_HINT_WIN") = 0x80EB
PyiGlPhongWin: int @native_name("GL_PHONG_WIN") = 0x80EA
PyiGlPixelMapAToA: int @native_name("GL_PIXEL_MAP_A_TO_A") = 0x0C79
PyiGlPixelMapAToASize: int @native_name("GL_PIXEL_MAP_A_TO_A_SIZE") = 0x0CB9
PyiGlPixelMapBToB: int @native_name("GL_PIXEL_MAP_B_TO_B") = 0x0C78
PyiGlPixelMapBToBSize: int @native_name("GL_PIXEL_MAP_B_TO_B_SIZE") = 0x0CB8
PyiGlPixelMapGToG: int @native_name("GL_PIXEL_MAP_G_TO_G") = 0x0C77
PyiGlPixelMapGToGSize: int @native_name("GL_PIXEL_MAP_G_TO_G_SIZE") = 0x0CB7
PyiGlPixelMapIToA: int @native_name("GL_PIXEL_MAP_I_TO_A") = 0x0C75
PyiGlPixelMapIToASize: int @native_name("GL_PIXEL_MAP_I_TO_A_SIZE") = 0x0CB5
PyiGlPixelMapIToB: int @native_name("GL_PIXEL_MAP_I_TO_B") = 0x0C74
PyiGlPixelMapIToBSize: int @native_name("GL_PIXEL_MAP_I_TO_B_SIZE") = 0x0CB4
PyiGlPixelMapIToG: int @native_name("GL_PIXEL_MAP_I_TO_G") = 0x0C73
PyiGlPixelMapIToGSize: int @native_name("GL_PIXEL_MAP_I_TO_G_SIZE") = 0x0CB3
PyiGlPixelMapIToI: int @native_name("GL_PIXEL_MAP_I_TO_I") = 0x0C70
PyiGlPixelMapIToISize: int @native_name("GL_PIXEL_MAP_I_TO_I_SIZE") = 0x0CB0
PyiGlPixelMapIToR: int @native_name("GL_PIXEL_MAP_I_TO_R") = 0x0C72
PyiGlPixelMapIToRSize: int @native_name("GL_PIXEL_MAP_I_TO_R_SIZE") = 0x0CB2
PyiGlPixelMapRToR: int @native_name("GL_PIXEL_MAP_R_TO_R") = 0x0C76
PyiGlPixelMapRToRSize: int @native_name("GL_PIXEL_MAP_R_TO_R_SIZE") = 0x0CB6
PyiGlPixelMapSToS: int @native_name("GL_PIXEL_MAP_S_TO_S") = 0x0C71
PyiGlPixelMapSToSSize: int @native_name("GL_PIXEL_MAP_S_TO_S_SIZE") = 0x0CB1
PyiGlPixelModeBit: int @native_name("GL_PIXEL_MODE_BIT") = 0x00000020
PyiGlPoint: int @native_name("GL_POINT") = 0x1B00
PyiGlPoints: int @native_name("GL_POINTS") = 0x0000
PyiGlPointBit: int @native_name("GL_POINT_BIT") = 0x00000002
PyiGlPointSize: int @native_name("GL_POINT_SIZE") = 0x0B11
PyiGlPointSizeGranularity: int @native_name("GL_POINT_SIZE_GRANULARITY") = 0x0B13
PyiGlPointSizeRange: int @native_name("GL_POINT_SIZE_RANGE") = 0x0B12
PyiGlPointSmooth: int @native_name("GL_POINT_SMOOTH") = 0x0B10
PyiGlPointSmoothHint: int @native_name("GL_POINT_SMOOTH_HINT") = 0x0C51
PyiGlPointToken: int @native_name("GL_POINT_TOKEN") = 0x0701
PyiGlPolygon: int @native_name("GL_POLYGON") = 0x0009
PyiGlPolygonBit: int @native_name("GL_POLYGON_BIT") = 0x00000008
PyiGlPolygonMode: int @native_name("GL_POLYGON_MODE") = 0x0B40
PyiGlPolygonOffsetFactor: int @native_name("GL_POLYGON_OFFSET_FACTOR") = 0x8038
PyiGlPolygonOffsetFill: int @native_name("GL_POLYGON_OFFSET_FILL") = 0x8037
PyiGlPolygonOffsetLine: int @native_name("GL_POLYGON_OFFSET_LINE") = 0x2A02
PyiGlPolygonOffsetPoint: int @native_name("GL_POLYGON_OFFSET_POINT") = 0x2A01
PyiGlPolygonOffsetUnits: int @native_name("GL_POLYGON_OFFSET_UNITS") = 0x2A00
PyiGlPolygonSmooth: int @native_name("GL_POLYGON_SMOOTH") = 0x0B41
PyiGlPolygonSmoothHint: int @native_name("GL_POLYGON_SMOOTH_HINT") = 0x0C53
PyiGlPolygonStipple: int @native_name("GL_POLYGON_STIPPLE") = 0x0B42
PyiGlPolygonStippleBit: int @native_name("GL_POLYGON_STIPPLE_BIT") = 0x00000010
PyiGlPolygonToken: int @native_name("GL_POLYGON_TOKEN") = 0x0703
PyiGlPosition: int @native_name("GL_POSITION") = 0x1203
PyiGlProjection: int @native_name("GL_PROJECTION") = 0x1701
PyiGlProjectionMatrix: int @native_name("GL_PROJECTION_MATRIX") = 0x0BA7
PyiGlProjectionStackDepth: int @native_name("GL_PROJECTION_STACK_DEPTH") = 0x0BA4
PyiGlProxyTexture1D: int @native_name("GL_PROXY_TEXTURE_1D") = 0x8063
PyiGlProxyTexture2D: int @native_name("GL_PROXY_TEXTURE_2D") = 0x8064
PyiGlQ: int @native_name("GL_Q") = 0x2003
PyiGlQuadraticAttenuation: int @native_name("GL_QUADRATIC_ATTENUATION") = 0x1209
PyiGlQuads: int @native_name("GL_QUADS") = 0x0007
PyiGlQuadStrip: int @native_name("GL_QUAD_STRIP") = 0x0008
PyiGlR: int @native_name("GL_R") = 0x2002
PyiGlR3G3B2: int @native_name("GL_R3_G3_B2") = 0x2A10
PyiGlReadBuffer: int @native_name("GL_READ_BUFFER") = 0x0C02
PyiGlRed: int @native_name("GL_RED") = 0x1903
PyiGlRedBias: int @native_name("GL_RED_BIAS") = 0x0D15
PyiGlRedBits: int @native_name("GL_RED_BITS") = 0x0D52
PyiGlRedScale: int @native_name("GL_RED_SCALE") = 0x0D14
PyiGlRender: int @native_name("GL_RENDER") = 0x1C00
PyiGlRenderer: int @native_name("GL_RENDERER") = 0x1F01
PyiGlRenderMode: int @native_name("GL_RENDER_MODE") = 0x0C40
PyiGlRepeat: int @native_name("GL_REPEAT") = 0x2901
PyiGlReplace: int @native_name("GL_REPLACE") = 0x1E01
PyiGlReturn: int @native_name("GL_RETURN") = 0x0102
PyiGlRgb: int @native_name("GL_RGB") = 0x1907
PyiGlRgb10: int @native_name("GL_RGB10") = 0x8052
PyiGlRgb10A2: int @native_name("GL_RGB10_A2") = 0x8059
PyiGlRgb12: int @native_name("GL_RGB12") = 0x8053
PyiGlRgb16: int @native_name("GL_RGB16") = 0x8054
PyiGlRgb4: int @native_name("GL_RGB4") = 0x804F
PyiGlRgb5: int @native_name("GL_RGB5") = 0x8050
PyiGlRgb5A1: int @native_name("GL_RGB5_A1") = 0x8057
PyiGlRgb8: int @native_name("GL_RGB8") = 0x8051
PyiGlRgba: int @native_name("GL_RGBA") = 0x1908
PyiGlRgba12: int @native_name("GL_RGBA12") = 0x805A
PyiGlRgba16: int @native_name("GL_RGBA16") = 0x805B
PyiGlRgba2: int @native_name("GL_RGBA2") = 0x8055
PyiGlRgba4: int @native_name("GL_RGBA4") = 0x8056
PyiGlRgba8: int @native_name("GL_RGBA8") = 0x8058
PyiGlRgbaMode: int @native_name("GL_RGBA_MODE") = 0x0C31
PyiGlRight: int @native_name("GL_RIGHT") = 0x0407
PyiGlS: int @native_name("GL_S") = 0x2000
PyiGlScissorBit: int @native_name("GL_SCISSOR_BIT") = 0x00080000
PyiGlScissorBox: int @native_name("GL_SCISSOR_BOX") = 0x0C10
PyiGlScissorTest: int @native_name("GL_SCISSOR_TEST") = 0x0C11
PyiGlSelect: int @native_name("GL_SELECT") = 0x1C02
PyiGlSelectionBufferPointer: int @native_name("GL_SELECTION_BUFFER_POINTER") = 0x0DF3
PyiGlSelectionBufferSize: int @native_name("GL_SELECTION_BUFFER_SIZE") = 0x0DF4
PyiGlSet: int @native_name("GL_SET") = 0x150F
PyiGlShadeModel: int @native_name("GL_SHADE_MODEL") = 0x0B54
PyiGlShininess: int @native_name("GL_SHININESS") = 0x1601
PyiGlShort: int @native_name("GL_SHORT") = 0x1402
PyiGlSmooth: int @native_name("GL_SMOOTH") = 0x1D01
PyiGlSpecular: int @native_name("GL_SPECULAR") = 0x1202
PyiGlSphereMap: int @native_name("GL_SPHERE_MAP") = 0x2402
PyiGlSpotCutoff: int @native_name("GL_SPOT_CUTOFF") = 0x1206
PyiGlSpotDirection: int @native_name("GL_SPOT_DIRECTION") = 0x1204
PyiGlSpotExponent: int @native_name("GL_SPOT_EXPONENT") = 0x1205
PyiGlSrcAlpha: int @native_name("GL_SRC_ALPHA") = 0x0302
PyiGlSrcAlphaSaturate: int @native_name("GL_SRC_ALPHA_SATURATE") = 0x0308
PyiGlSrcColor: int @native_name("GL_SRC_COLOR") = 0x0300
PyiGlStackOverflow: int @native_name("GL_STACK_OVERFLOW") = 0x0503
PyiGlStackUnderflow: int @native_name("GL_STACK_UNDERFLOW") = 0x0504
PyiGlStencil: int @native_name("GL_STENCIL") = 0x1802
PyiGlStencilBits: int @native_name("GL_STENCIL_BITS") = 0x0D57
PyiGlStencilBufferBit: int @native_name("GL_STENCIL_BUFFER_BIT") = 0x00000400
PyiGlStencilClearValue: int @native_name("GL_STENCIL_CLEAR_VALUE") = 0x0B91
PyiGlStencilFail: int @native_name("GL_STENCIL_FAIL") = 0x0B94
PyiGlStencilFunc: int @native_name("GL_STENCIL_FUNC") = 0x0B92
PyiGlStencilIndex: int @native_name("GL_STENCIL_INDEX") = 0x1901
PyiGlStencilPassDepthFail: int @native_name("GL_STENCIL_PASS_DEPTH_FAIL") = 0x0B95
PyiGlStencilPassDepthPass: int @native_name("GL_STENCIL_PASS_DEPTH_PASS") = 0x0B96
PyiGlStencilRef: int @native_name("GL_STENCIL_REF") = 0x0B97
PyiGlStencilTest: int @native_name("GL_STENCIL_TEST") = 0x0B90
PyiGlStencilValueMask: int @native_name("GL_STENCIL_VALUE_MASK") = 0x0B93
PyiGlStencilWritemask: int @native_name("GL_STENCIL_WRITEMASK") = 0x0B98
PyiGlStereo: int @native_name("GL_STEREO") = 0x0C33
PyiGlSubpixelBits: int @native_name("GL_SUBPIXEL_BITS") = 0x0D50
PyiGlT: int @native_name("GL_T") = 0x2001
PyiGlT2FC3FV3F: int @native_name("GL_T2F_C3F_V3F") = 0x2A2A
PyiGlT2FC4FN3FV3F: int @native_name("GL_T2F_C4F_N3F_V3F") = 0x2A2C
PyiGlT2FC4UbV3F: int @native_name("GL_T2F_C4UB_V3F") = 0x2A29
PyiGlT2FN3FV3F: int @native_name("GL_T2F_N3F_V3F") = 0x2A2B
PyiGlT2FV3F: int @native_name("GL_T2F_V3F") = 0x2A27
PyiGlT4FC4FN3FV4F: int @native_name("GL_T4F_C4F_N3F_V4F") = 0x2A2D
PyiGlT4FV4F: int @native_name("GL_T4F_V4F") = 0x2A28
PyiGlTexture: int @native_name("GL_TEXTURE") = 0x1702
PyiGlTexture1D: int @native_name("GL_TEXTURE_1D") = 0x0DE0
PyiGlTexture2D: int @native_name("GL_TEXTURE_2D") = 0x0DE1
PyiGlTextureAlphaSize: int @native_name("GL_TEXTURE_ALPHA_SIZE") = 0x805F
PyiGlTextureBinding1D: int @native_name("GL_TEXTURE_BINDING_1D") = 0x8068
PyiGlTextureBinding2D: int @native_name("GL_TEXTURE_BINDING_2D") = 0x8069
PyiGlTextureBit: int @native_name("GL_TEXTURE_BIT") = 0x00040000
PyiGlTextureBlueSize: int @native_name("GL_TEXTURE_BLUE_SIZE") = 0x805E
PyiGlTextureBorder: int @native_name("GL_TEXTURE_BORDER") = 0x1005
PyiGlTextureBorderColor: int @native_name("GL_TEXTURE_BORDER_COLOR") = 0x1004
PyiGlTextureComponents: int @native_name("GL_TEXTURE_COMPONENTS") = 0x1003
PyiGlTextureCoordArray: int @native_name("GL_TEXTURE_COORD_ARRAY") = 0x8078
PyiGlTextureCoordArrayCountExt: int @native_name("GL_TEXTURE_COORD_ARRAY_COUNT_EXT") = 0x808B
PyiGlTextureCoordArrayExt: int @native_name("GL_TEXTURE_COORD_ARRAY_EXT") = 0x8078
PyiGlTextureCoordArrayPointer: int @native_name("GL_TEXTURE_COORD_ARRAY_POINTER") = 0x8092
PyiGlTextureCoordArrayPointerExt: int @native_name("GL_TEXTURE_COORD_ARRAY_POINTER_EXT") = 0x8092
PyiGlTextureCoordArraySize: int @native_name("GL_TEXTURE_COORD_ARRAY_SIZE") = 0x8088
PyiGlTextureCoordArraySizeExt: int @native_name("GL_TEXTURE_COORD_ARRAY_SIZE_EXT") = 0x8088
PyiGlTextureCoordArrayStride: int @native_name("GL_TEXTURE_COORD_ARRAY_STRIDE") = 0x808A
PyiGlTextureCoordArrayStrideExt: int @native_name("GL_TEXTURE_COORD_ARRAY_STRIDE_EXT") = 0x808A
PyiGlTextureCoordArrayType: int @native_name("GL_TEXTURE_COORD_ARRAY_TYPE") = 0x8089
PyiGlTextureCoordArrayTypeExt: int @native_name("GL_TEXTURE_COORD_ARRAY_TYPE_EXT") = 0x8089
PyiGlTextureEnv: int @native_name("GL_TEXTURE_ENV") = 0x2300
PyiGlTextureEnvColor: int @native_name("GL_TEXTURE_ENV_COLOR") = 0x2201
PyiGlTextureEnvMode: int @native_name("GL_TEXTURE_ENV_MODE") = 0x2200
PyiGlTextureGenMode: int @native_name("GL_TEXTURE_GEN_MODE") = 0x2500
PyiGlTextureGenQ: int @native_name("GL_TEXTURE_GEN_Q") = 0x0C63
PyiGlTextureGenR: int @native_name("GL_TEXTURE_GEN_R") = 0x0C62
PyiGlTextureGenS: int @native_name("GL_TEXTURE_GEN_S") = 0x0C60
PyiGlTextureGenT: int @native_name("GL_TEXTURE_GEN_T") = 0x0C61
PyiGlTextureGreenSize: int @native_name("GL_TEXTURE_GREEN_SIZE") = 0x805D
PyiGlTextureHeight: int @native_name("GL_TEXTURE_HEIGHT") = 0x1001
PyiGlTextureIntensitySize: int @native_name("GL_TEXTURE_INTENSITY_SIZE") = 0x8061
PyiGlTextureInternalFormat: int @native_name("GL_TEXTURE_INTERNAL_FORMAT") = 0x1003
PyiGlTextureLuminanceSize: int @native_name("GL_TEXTURE_LUMINANCE_SIZE") = 0x8060
PyiGlTextureMagFilter: int @native_name("GL_TEXTURE_MAG_FILTER") = 0x2800
PyiGlTextureMatrix: int @native_name("GL_TEXTURE_MATRIX") = 0x0BA8
PyiGlTextureMinFilter: int @native_name("GL_TEXTURE_MIN_FILTER") = 0x2801
PyiGlTexturePriority: int @native_name("GL_TEXTURE_PRIORITY") = 0x8066
PyiGlTextureRedSize: int @native_name("GL_TEXTURE_RED_SIZE") = 0x805C
PyiGlTextureResident: int @native_name("GL_TEXTURE_RESIDENT") = 0x8067
PyiGlTextureStackDepth: int @native_name("GL_TEXTURE_STACK_DEPTH") = 0x0BA5
PyiGlTextureWidth: int @native_name("GL_TEXTURE_WIDTH") = 0x1000
PyiGlTextureWrapS: int @native_name("GL_TEXTURE_WRAP_S") = 0x2802
PyiGlTextureWrapT: int @native_name("GL_TEXTURE_WRAP_T") = 0x2803
PyiGlTransformBit: int @native_name("GL_TRANSFORM_BIT") = 0x00001000
PyiGlTriangles: int @native_name("GL_TRIANGLES") = 0x0004
PyiGlTriangleFan: int @native_name("GL_TRIANGLE_FAN") = 0x0006
PyiGlTriangleStrip: int @native_name("GL_TRIANGLE_STRIP") = 0x0005
PyiGlTrue: int @native_name("GL_TRUE") = 1
PyiGlUnpackAlignment: int @native_name("GL_UNPACK_ALIGNMENT") = 0x0CF5
PyiGlUnpackLsbFirst: int @native_name("GL_UNPACK_LSB_FIRST") = 0x0CF1
PyiGlUnpackRowLength: int @native_name("GL_UNPACK_ROW_LENGTH") = 0x0CF2
PyiGlUnpackSkipPixels: int @native_name("GL_UNPACK_SKIP_PIXELS") = 0x0CF4
PyiGlUnpackSkipRows: int @native_name("GL_UNPACK_SKIP_ROWS") = 0x0CF3
PyiGlUnpackSwapBytes: int @native_name("GL_UNPACK_SWAP_BYTES") = 0x0CF0
PyiGlUnsignedByte: int @native_name("GL_UNSIGNED_BYTE") = 0x1401
PyiGlUnsignedInt: int @native_name("GL_UNSIGNED_INT") = 0x1405
PyiGlUnsignedShort: int @native_name("GL_UNSIGNED_SHORT") = 0x1403
PyiGlV2F: int @native_name("GL_V2F") = 0x2A20
PyiGlV3F: int @native_name("GL_V3F") = 0x2A21
PyiGlVendor: int @native_name("GL_VENDOR") = 0x1F00
PyiGlVersion: int @native_name("GL_VERSION") = 0x1F02
PyiGlVersion11: int @native_name("GL_VERSION_1_1") = 1
PyiGlVertexArray: int @native_name("GL_VERTEX_ARRAY") = 0x8074
PyiGlVertexArrayCountExt: int @native_name("GL_VERTEX_ARRAY_COUNT_EXT") = 0x807D
PyiGlVertexArrayExt: int @native_name("GL_VERTEX_ARRAY_EXT") = 0x8074
PyiGlVertexArrayPointer: int @native_name("GL_VERTEX_ARRAY_POINTER") = 0x808E
PyiGlVertexArrayPointerExt: int @native_name("GL_VERTEX_ARRAY_POINTER_EXT") = 0x808E
PyiGlVertexArraySize: int @native_name("GL_VERTEX_ARRAY_SIZE") = 0x807A
PyiGlVertexArraySizeExt: int @native_name("GL_VERTEX_ARRAY_SIZE_EXT") = 0x807A
PyiGlVertexArrayStride: int @native_name("GL_VERTEX_ARRAY_STRIDE") = 0x807C
PyiGlVertexArrayStrideExt: int @native_name("GL_VERTEX_ARRAY_STRIDE_EXT") = 0x807C
PyiGlVertexArrayType: int @native_name("GL_VERTEX_ARRAY_TYPE") = 0x807B
PyiGlVertexArrayTypeExt: int @native_name("GL_VERTEX_ARRAY_TYPE_EXT") = 0x807B
PyiGlViewport: int @native_name("GL_VIEWPORT") = 0x0BA2
PyiGlViewportBit: int @native_name("GL_VIEWPORT_BIT") = 0x00000800
PyiGlWinDrawRangeElements: int @native_name("GL_WIN_draw_range_elements") = 1
PyiGlWinSwapHint: int @native_name("GL_WIN_swap_hint") = 1
PyiGlXor: int @native_name("GL_XOR") = 0x1506
PyiGlZero: int @native_name("GL_ZERO") = 0
PyiGlZoomX: int @native_name("GL_ZOOM_X") = 0x0D16
PyiGlZoomY: int @native_name("GL_ZOOM_Y") = 0x0D17

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("glAccum")
def pyiGlAccum(op: uint, value: float) -> None:
  """
  **********************************************************

  /
  """
  ...

@native
@native_name("glAlphaFunc")
def pyiGlAlphaFunc(func: uint, ref: float) -> None:
  ...

@native
@native_name("glAreTexturesResident")
def pyiGlAreTexturesResident(n: int, textures: Pointer[uint], residences: Pointer[int]) -> int:
  ...

@native
@native_name("glArrayElement")
def pyiGlArrayElement(i: int) -> None:
  ...

@native
@native_name("glBegin")
def pyiGlBegin(mode: uint) -> None:
  ...

@native
@native_name("glBindTexture")
def pyiGlBindTexture(target: uint, texture: uint) -> None:
  ...

@native
@native_name("glBitmap")
def pyiGlBitmap(width: int, height: int, xorig: float, yorig: float, xmove: float, ymove: float, bitmap: Pointer[int]) -> None:
  ...

@native
@native_name("glBlendFunc")
def pyiGlBlendFunc(sfactor: uint, dfactor: uint) -> None:
  ...

@native
@native_name("glCallList")
def pyiGlCallList(list: uint) -> None:
  ...

@native
@native_name("glCallLists")
def pyiGlCallLists(n: int, type: uint, lists: Pointer[None]) -> None:
  ...

@native
@native_name("glClear")
def pyiGlClear(mask: uint) -> None:
  ...

@native
@native_name("glClearAccum")
def pyiGlClearAccum(red: float, green: float, blue: float, alpha: float) -> None:
  ...

@native
@native_name("glClearColor")
def pyiGlClearColor(red: float, green: float, blue: float, alpha: float) -> None:
  ...

@native
@native_name("glClearDepth")
def pyiGlClearDepth(depth: float64) -> None:
  ...

@native
@native_name("glClearIndex")
def pyiGlClearIndex(c: float) -> None:
  ...

@native
@native_name("glClearStencil")
def pyiGlClearStencil(s: int) -> None:
  ...

@native
@native_name("glClipPlane")
def pyiGlClipPlane(plane: uint, equation: Pointer[float64]) -> None:
  ...

@native
@native_name("glColor3b")
def pyiGlColor3B(red: int, green: int, blue: int) -> None:
  ...

@native
@native_name("glColor3bv")
def pyiGlColor3Bv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor3d")
def pyiGlColor3D(red: float64, green: float64, blue: float64) -> None:
  ...

@native
@native_name("glColor3dv")
def pyiGlColor3Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glColor3f")
def pyiGlColor3F(red: float, green: float, blue: float) -> None:
  ...

@native
@native_name("glColor3fv")
def pyiGlColor3Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glColor3i")
def pyiGlColor3I(red: int, green: int, blue: int) -> None:
  ...

@native
@native_name("glColor3iv")
def pyiGlColor3Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor3s")
def pyiGlColor3S(red: int16, green: int16, blue: int16) -> None:
  ...

@native
@native_name("glColor3sv")
def pyiGlColor3Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glColor3ub")
def pyiGlColor3Ub(red: int, green: int, blue: int) -> None:
  ...

@native
@native_name("glColor3ubv")
def pyiGlColor3Ubv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor3ui")
def pyiGlColor3Ui(red: uint, green: uint, blue: uint) -> None:
  ...

@native
@native_name("glColor3uiv")
def pyiGlColor3Uiv(v: Pointer[uint]) -> None:
  ...

@native
@native_name("glColor3us")
def pyiGlColor3Us(red: uint16, green: uint16, blue: uint16) -> None:
  ...

@native
@native_name("glColor3usv")
def pyiGlColor3Usv(v: Pointer[uint16]) -> None:
  ...

@native
@native_name("glColor4b")
def pyiGlColor4B(red: int, green: int, blue: int, alpha: int) -> None:
  ...

@native
@native_name("glColor4bv")
def pyiGlColor4Bv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor4d")
def pyiGlColor4D(red: float64, green: float64, blue: float64, alpha: float64) -> None:
  ...

@native
@native_name("glColor4dv")
def pyiGlColor4Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glColor4f")
def pyiGlColor4F(red: float, green: float, blue: float, alpha: float) -> None:
  ...

@native
@native_name("glColor4fv")
def pyiGlColor4Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glColor4i")
def pyiGlColor4I(red: int, green: int, blue: int, alpha: int) -> None:
  ...

@native
@native_name("glColor4iv")
def pyiGlColor4Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor4s")
def pyiGlColor4S(red: int16, green: int16, blue: int16, alpha: int16) -> None:
  ...

@native
@native_name("glColor4sv")
def pyiGlColor4Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glColor4ub")
def pyiGlColor4Ub(red: int, green: int, blue: int, alpha: int) -> None:
  ...

@native
@native_name("glColor4ubv")
def pyiGlColor4Ubv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glColor4ui")
def pyiGlColor4Ui(red: uint, green: uint, blue: uint, alpha: uint) -> None:
  ...

@native
@native_name("glColor4uiv")
def pyiGlColor4Uiv(v: Pointer[uint]) -> None:
  ...

@native
@native_name("glColor4us")
def pyiGlColor4Us(red: uint16, green: uint16, blue: uint16, alpha: uint16) -> None:
  ...

@native
@native_name("glColor4usv")
def pyiGlColor4Usv(v: Pointer[uint16]) -> None:
  ...

@native
@native_name("glColorMask")
def pyiGlColorMask(red: int, green: int, blue: int, alpha: int) -> None:
  ...

@native
@native_name("glColorMaterial")
def pyiGlColorMaterial(face: uint, mode: uint) -> None:
  ...

@native
@native_name("glColorPointer")
def pyiGlColorPointer(size: int, type: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glCopyPixels")
def pyiGlCopyPixels(x: int, y: int, width: int, height: int, type: uint) -> None:
  ...

@native
@native_name("glCopyTexImage1D")
def pyiGlCopyTexImage1D(target: uint, level: int, internalFormat: uint, x: int, y: int, width: int, border: int) -> None:
  ...

@native
@native_name("glCopyTexImage2D")
def pyiGlCopyTexImage2D(target: uint, level: int, internalFormat: uint, x: int, y: int, width: int, height: int, border: int) -> None:
  ...

@native
@native_name("glCopyTexSubImage1D")
def pyiGlCopyTexSubImage1D(target: uint, level: int, xoffset: int, x: int, y: int, width: int) -> None:
  ...

@native
@native_name("glCopyTexSubImage2D")
def pyiGlCopyTexSubImage2D(target: uint, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None:
  ...

@native
@native_name("glCullFace")
def pyiGlCullFace(mode: uint) -> None:
  ...

@native
@native_name("glDeleteLists")
def pyiGlDeleteLists(list: uint, range: int) -> None:
  ...

@native
@native_name("glDeleteTextures")
def pyiGlDeleteTextures(n: int, textures: Pointer[uint]) -> None:
  ...

@native
@native_name("glDepthFunc")
def pyiGlDepthFunc(func: uint) -> None:
  ...

@native
@native_name("glDepthMask")
def pyiGlDepthMask(flag: int) -> None:
  ...

@native
@native_name("glDepthRange")
def pyiGlDepthRange(zNear: float64, zFar: float64) -> None:
  ...

@native
@native_name("glDisable")
def pyiGlDisable(cap: uint) -> None:
  ...

@native
@native_name("glDisableClientState")
def pyiGlDisableClientState(array: uint) -> None:
  ...

@native
@native_name("glDrawArrays")
def pyiGlDrawArrays(mode: uint, first: int, count: int) -> None:
  ...

@native
@native_name("glDrawBuffer")
def pyiGlDrawBuffer(mode: uint) -> None:
  ...

@native
@native_name("glDrawElements")
def pyiGlDrawElements(mode: uint, count: int, type: uint, indices: Pointer[None]) -> None:
  ...

@native
@native_name("glDrawPixels")
def pyiGlDrawPixels(width: int, height: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glEdgeFlag")
def pyiGlEdgeFlag(flag: int) -> None:
  ...

@native
@native_name("glEdgeFlagPointer")
def pyiGlEdgeFlagPointer(stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glEdgeFlagv")
def pyiGlEdgeFlagv(flag: Pointer[int]) -> None:
  ...

@native
@native_name("glEnable")
def pyiGlEnable(cap: uint) -> None:
  ...

@native
@native_name("glEnableClientState")
def pyiGlEnableClientState(array: uint) -> None:
  ...

@native
@native_name("glEnd")
def pyiGlEnd() -> None:
  ...

@native
@native_name("glEndList")
def pyiGlEndList() -> None:
  ...

@native
@native_name("glEvalCoord1d")
def pyiGlEvalCoord1D(u: float64) -> None:
  ...

@native
@native_name("glEvalCoord1dv")
def pyiGlEvalCoord1Dv(u: Pointer[float64]) -> None:
  ...

@native
@native_name("glEvalCoord1f")
def pyiGlEvalCoord1F(u: float) -> None:
  ...

@native
@native_name("glEvalCoord1fv")
def pyiGlEvalCoord1Fv(u: Pointer[float]) -> None:
  ...

@native
@native_name("glEvalCoord2d")
def pyiGlEvalCoord2D(u: float64, v: float64) -> None:
  ...

@native
@native_name("glEvalCoord2dv")
def pyiGlEvalCoord2Dv(u: Pointer[float64]) -> None:
  ...

@native
@native_name("glEvalCoord2f")
def pyiGlEvalCoord2F(u: float, v: float) -> None:
  ...

@native
@native_name("glEvalCoord2fv")
def pyiGlEvalCoord2Fv(u: Pointer[float]) -> None:
  ...

@native
@native_name("glEvalMesh1")
def pyiGlEvalMesh1(mode: uint, i1: int, i2: int) -> None:
  ...

@native
@native_name("glEvalMesh2")
def pyiGlEvalMesh2(mode: uint, i1: int, i2: int, j1: int, j2: int) -> None:
  ...

@native
@native_name("glEvalPoint1")
def pyiGlEvalPoint1(i: int) -> None:
  ...

@native
@native_name("glEvalPoint2")
def pyiGlEvalPoint2(i: int, j: int) -> None:
  ...

@native
@native_name("glFeedbackBuffer")
def pyiGlFeedbackBuffer(size: int, type: uint, buffer: Pointer[float]) -> None:
  ...

@native
@native_name("glFinish")
def pyiGlFinish() -> None:
  ...

@native
@native_name("glFlush")
def pyiGlFlush() -> None:
  ...

@native
@native_name("glFogf")
def pyiGlFogf(pname: uint, param: float) -> None:
  ...

@native
@native_name("glFogfv")
def pyiGlFogfv(pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glFogi")
def pyiGlFogi(pname: uint, param: int) -> None:
  ...

@native
@native_name("glFogiv")
def pyiGlFogiv(pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glFrontFace")
def pyiGlFrontFace(mode: uint) -> None:
  ...

@native
@native_name("glFrustum")
def pyiGlFrustum(left: float64, right: float64, bottom: float64, top: float64, zNear: float64, zFar: float64) -> None:
  ...

@native
@native_name("glGenLists")
def pyiGlGenLists(range: int) -> uint:
  ...

@native
@native_name("glGenTextures")
def pyiGlGenTextures(n: int, textures: Pointer[uint]) -> None:
  ...

@native
@native_name("glGetBooleanv")
def pyiGlGetBooleanv(pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetClipPlane")
def pyiGlGetClipPlane(plane: uint, equation: Pointer[float64]) -> None:
  ...

@native
@native_name("glGetDoublev")
def pyiGlGetDoublev(pname: uint, params: Pointer[float64]) -> None:
  ...

@native
@native_name("glGetError")
def pyiGlGetError() -> uint:
  ...

@native
@native_name("glGetFloatv")
def pyiGlGetFloatv(pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetIntegerv")
def pyiGlGetIntegerv(pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetLightfv")
def pyiGlGetLightfv(light: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetLightiv")
def pyiGlGetLightiv(light: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetMapdv")
def pyiGlGetMapdv(target: uint, query: uint, v: Pointer[float64]) -> None:
  ...

@native
@native_name("glGetMapfv")
def pyiGlGetMapfv(target: uint, query: uint, v: Pointer[float]) -> None:
  ...

@native
@native_name("glGetMapiv")
def pyiGlGetMapiv(target: uint, query: uint, v: Pointer[int]) -> None:
  ...

@native
@native_name("glGetMaterialfv")
def pyiGlGetMaterialfv(face: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetMaterialiv")
def pyiGlGetMaterialiv(face: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetPixelMapfv")
def pyiGlGetPixelMapfv(map: uint, values: Pointer[float]) -> None:
  ...

@native
@native_name("glGetPixelMapuiv")
def pyiGlGetPixelMapuiv(map: uint, values: Pointer[uint]) -> None:
  ...

@native
@native_name("glGetPixelMapusv")
def pyiGlGetPixelMapusv(map: uint, values: Pointer[uint16]) -> None:
  ...

@native
@native_name("glGetPointerv")
def pyiGlGetPointerv(pname: uint, params: Pointer[Pointer[None]]) -> None:
  ...

@native
@native_name("glGetPolygonStipple")
def pyiGlGetPolygonStipple(mask: Pointer[int]) -> None:
  ...

@native
@native_name("glGetString")
def pyiGlGetString(name: uint) -> Pointer[int]:
  ...

@native
@native_name("glGetTexEnvfv")
def pyiGlGetTexEnvfv(target: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetTexEnviv")
def pyiGlGetTexEnviv(target: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetTexGendv")
def pyiGlGetTexGendv(coord: uint, pname: uint, params: Pointer[float64]) -> None:
  ...

@native
@native_name("glGetTexGenfv")
def pyiGlGetTexGenfv(coord: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetTexGeniv")
def pyiGlGetTexGeniv(coord: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetTexImage")
def pyiGlGetTexImage(target: uint, level: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glGetTexLevelParameterfv")
def pyiGlGetTexLevelParameterfv(target: uint, level: int, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetTexLevelParameteriv")
def pyiGlGetTexLevelParameteriv(target: uint, level: int, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glGetTexParameterfv")
def pyiGlGetTexParameterfv(target: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glGetTexParameteriv")
def pyiGlGetTexParameteriv(target: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glHint")
def pyiGlHint(target: uint, mode: uint) -> None:
  ...

@native
@native_name("glIndexMask")
def pyiGlIndexMask(mask: uint) -> None:
  ...

@native
@native_name("glIndexPointer")
def pyiGlIndexPointer(type: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glIndexd")
def pyiGlIndexd(c: float64) -> None:
  ...

@native
@native_name("glIndexdv")
def pyiGlIndexdv(c: Pointer[float64]) -> None:
  ...

@native
@native_name("glIndexf")
def pyiGlIndexf(c: float) -> None:
  ...

@native
@native_name("glIndexfv")
def pyiGlIndexfv(c: Pointer[float]) -> None:
  ...

@native
@native_name("glIndexi")
def pyiGlIndexi(c: int) -> None:
  ...

@native
@native_name("glIndexiv")
def pyiGlIndexiv(c: Pointer[int]) -> None:
  ...

@native
@native_name("glIndexs")
def pyiGlIndexs(c: int16) -> None:
  ...

@native
@native_name("glIndexsv")
def pyiGlIndexsv(c: Pointer[int16]) -> None:
  ...

@native
@native_name("glIndexub")
def pyiGlIndexub(c: int) -> None:
  ...

@native
@native_name("glIndexubv")
def pyiGlIndexubv(c: Pointer[int]) -> None:
  ...

@native
@native_name("glInitNames")
def pyiGlInitNames() -> None:
  ...

@native
@native_name("glInterleavedArrays")
def pyiGlInterleavedArrays(format: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glIsEnabled")
def pyiGlIsEnabled(cap: uint) -> int:
  ...

@native
@native_name("glIsList")
def pyiGlIsList(list: uint) -> int:
  ...

@native
@native_name("glIsTexture")
def pyiGlIsTexture(texture: uint) -> int:
  ...

@native
@native_name("glLightModelf")
def pyiGlLightModelf(pname: uint, param: float) -> None:
  ...

@native
@native_name("glLightModelfv")
def pyiGlLightModelfv(pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glLightModeli")
def pyiGlLightModeli(pname: uint, param: int) -> None:
  ...

@native
@native_name("glLightModeliv")
def pyiGlLightModeliv(pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glLightf")
def pyiGlLightf(light: uint, pname: uint, param: float) -> None:
  ...

@native
@native_name("glLightfv")
def pyiGlLightfv(light: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glLighti")
def pyiGlLighti(light: uint, pname: uint, param: int) -> None:
  ...

@native
@native_name("glLightiv")
def pyiGlLightiv(light: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glLineStipple")
def pyiGlLineStipple(factor: int, pattern: uint16) -> None:
  ...

@native
@native_name("glLineWidth")
def pyiGlLineWidth(width: float) -> None:
  ...

@native
@native_name("glListBase")
def pyiGlListBase(base: uint) -> None:
  ...

@native
@native_name("glLoadIdentity")
def pyiGlLoadIdentity() -> None:
  ...

@native
@native_name("glLoadMatrixd")
def pyiGlLoadMatrixd(m: Pointer[float64]) -> None:
  ...

@native
@native_name("glLoadMatrixf")
def pyiGlLoadMatrixf(m: Pointer[float]) -> None:
  ...

@native
@native_name("glLoadName")
def pyiGlLoadName(name: uint) -> None:
  ...

@native
@native_name("glLogicOp")
def pyiGlLogicOp(opcode: uint) -> None:
  ...

@native
@native_name("glMap1d")
def pyiGlMap1D(target: uint, u1: float64, u2: float64, stride: int, order: int, points: Pointer[float64]) -> None:
  ...

@native
@native_name("glMap1f")
def pyiGlMap1F(target: uint, u1: float, u2: float, stride: int, order: int, points: Pointer[float]) -> None:
  ...

@native
@native_name("glMap2d")
def pyiGlMap2D(target: uint, u1: float64, u2: float64, ustride: int, uorder: int, v1: float64, v2: float64, vstride: int, vorder: int, points: Pointer[float64]) -> None:
  ...

@native
@native_name("glMap2f")
def pyiGlMap2F(target: uint, u1: float, u2: float, ustride: int, uorder: int, v1: float, v2: float, vstride: int, vorder: int, points: Pointer[float]) -> None:
  ...

@native
@native_name("glMapGrid1d")
def pyiGlMapGrid1D(un: int, u1: float64, u2: float64) -> None:
  ...

@native
@native_name("glMapGrid1f")
def pyiGlMapGrid1F(un: int, u1: float, u2: float) -> None:
  ...

@native
@native_name("glMapGrid2d")
def pyiGlMapGrid2D(un: int, u1: float64, u2: float64, vn: int, v1: float64, v2: float64) -> None:
  ...

@native
@native_name("glMapGrid2f")
def pyiGlMapGrid2F(un: int, u1: float, u2: float, vn: int, v1: float, v2: float) -> None:
  ...

@native
@native_name("glMaterialf")
def pyiGlMaterialf(face: uint, pname: uint, param: float) -> None:
  ...

@native
@native_name("glMaterialfv")
def pyiGlMaterialfv(face: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glMateriali")
def pyiGlMateriali(face: uint, pname: uint, param: int) -> None:
  ...

@native
@native_name("glMaterialiv")
def pyiGlMaterialiv(face: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glMatrixMode")
def pyiGlMatrixMode(mode: uint) -> None:
  ...

@native
@native_name("glMultMatrixd")
def pyiGlMultMatrixd(m: Pointer[float64]) -> None:
  ...

@native
@native_name("glMultMatrixf")
def pyiGlMultMatrixf(m: Pointer[float]) -> None:
  ...

@native
@native_name("glNewList")
def pyiGlNewList(list: uint, mode: uint) -> None:
  ...

@native
@native_name("glNormal3b")
def pyiGlNormal3B(nx: int, ny: int, nz: int) -> None:
  ...

@native
@native_name("glNormal3bv")
def pyiGlNormal3Bv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glNormal3d")
def pyiGlNormal3D(nx: float64, ny: float64, nz: float64) -> None:
  ...

@native
@native_name("glNormal3dv")
def pyiGlNormal3Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glNormal3f")
def pyiGlNormal3F(nx: float, ny: float, nz: float) -> None:
  ...

@native
@native_name("glNormal3fv")
def pyiGlNormal3Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glNormal3i")
def pyiGlNormal3I(nx: int, ny: int, nz: int) -> None:
  ...

@native
@native_name("glNormal3iv")
def pyiGlNormal3Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glNormal3s")
def pyiGlNormal3S(nx: int16, ny: int16, nz: int16) -> None:
  ...

@native
@native_name("glNormal3sv")
def pyiGlNormal3Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glNormalPointer")
def pyiGlNormalPointer(type: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glOrtho")
def pyiGlOrtho(left: float64, right: float64, bottom: float64, top: float64, zNear: float64, zFar: float64) -> None:
  ...

@native
@native_name("glPassThrough")
def pyiGlPassThrough(token: float) -> None:
  ...

@native
@native_name("glPixelMapfv")
def pyiGlPixelMapfv(map: uint, mapsize: int, values: Pointer[float]) -> None:
  ...

@native
@native_name("glPixelMapuiv")
def pyiGlPixelMapuiv(map: uint, mapsize: int, values: Pointer[uint]) -> None:
  ...

@native
@native_name("glPixelMapusv")
def pyiGlPixelMapusv(map: uint, mapsize: int, values: Pointer[uint16]) -> None:
  ...

@native
@native_name("glPixelStoref")
def pyiGlPixelStoref(pname: uint, param: float) -> None:
  ...

@native
@native_name("glPixelStorei")
def pyiGlPixelStorei(pname: uint, param: int) -> None:
  ...

@native
@native_name("glPixelTransferf")
def pyiGlPixelTransferf(pname: uint, param: float) -> None:
  ...

@native
@native_name("glPixelTransferi")
def pyiGlPixelTransferi(pname: uint, param: int) -> None:
  ...

@native
@native_name("glPixelZoom")
def pyiGlPixelZoom(xfactor: float, yfactor: float) -> None:
  ...

@native
@native_name("glPointSize")
def pyiGlPointSize(size: float) -> None:
  ...

@native
@native_name("glPolygonMode")
def pyiGlPolygonMode(face: uint, mode: uint) -> None:
  ...

@native
@native_name("glPolygonOffset")
def pyiGlPolygonOffset(factor: float, units: float) -> None:
  ...

@native
@native_name("glPolygonStipple")
def pyiGlPolygonStipple(mask: Pointer[int]) -> None:
  ...

@native
@native_name("glPopAttrib")
def pyiGlPopAttrib() -> None:
  ...

@native
@native_name("glPopClientAttrib")
def pyiGlPopClientAttrib() -> None:
  ...

@native
@native_name("glPopMatrix")
def pyiGlPopMatrix() -> None:
  ...

@native
@native_name("glPopName")
def pyiGlPopName() -> None:
  ...

@native
@native_name("glPrioritizeTextures")
def pyiGlPrioritizeTextures(n: int, textures: Pointer[uint], priorities: Pointer[float]) -> None:
  ...

@native
@native_name("glPushAttrib")
def pyiGlPushAttrib(mask: uint) -> None:
  ...

@native
@native_name("glPushClientAttrib")
def pyiGlPushClientAttrib(mask: uint) -> None:
  ...

@native
@native_name("glPushMatrix")
def pyiGlPushMatrix() -> None:
  ...

@native
@native_name("glPushName")
def pyiGlPushName(name: uint) -> None:
  ...

@native
@native_name("glRasterPos2d")
def pyiGlRasterPos2D(x: float64, y: float64) -> None:
  ...

@native
@native_name("glRasterPos2dv")
def pyiGlRasterPos2Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glRasterPos2f")
def pyiGlRasterPos2F(x: float, y: float) -> None:
  ...

@native
@native_name("glRasterPos2fv")
def pyiGlRasterPos2Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glRasterPos2i")
def pyiGlRasterPos2I(x: int, y: int) -> None:
  ...

@native
@native_name("glRasterPos2iv")
def pyiGlRasterPos2Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glRasterPos2s")
def pyiGlRasterPos2S(x: int16, y: int16) -> None:
  ...

@native
@native_name("glRasterPos2sv")
def pyiGlRasterPos2Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glRasterPos3d")
def pyiGlRasterPos3D(x: float64, y: float64, z: float64) -> None:
  ...

@native
@native_name("glRasterPos3dv")
def pyiGlRasterPos3Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glRasterPos3f")
def pyiGlRasterPos3F(x: float, y: float, z: float) -> None:
  ...

@native
@native_name("glRasterPos3fv")
def pyiGlRasterPos3Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glRasterPos3i")
def pyiGlRasterPos3I(x: int, y: int, z: int) -> None:
  ...

@native
@native_name("glRasterPos3iv")
def pyiGlRasterPos3Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glRasterPos3s")
def pyiGlRasterPos3S(x: int16, y: int16, z: int16) -> None:
  ...

@native
@native_name("glRasterPos3sv")
def pyiGlRasterPos3Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glRasterPos4d")
def pyiGlRasterPos4D(x: float64, y: float64, z: float64, w: float64) -> None:
  ...

@native
@native_name("glRasterPos4dv")
def pyiGlRasterPos4Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glRasterPos4f")
def pyiGlRasterPos4F(x: float, y: float, z: float, w: float) -> None:
  ...

@native
@native_name("glRasterPos4fv")
def pyiGlRasterPos4Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glRasterPos4i")
def pyiGlRasterPos4I(x: int, y: int, z: int, w: int) -> None:
  ...

@native
@native_name("glRasterPos4iv")
def pyiGlRasterPos4Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glRasterPos4s")
def pyiGlRasterPos4S(x: int16, y: int16, z: int16, w: int16) -> None:
  ...

@native
@native_name("glRasterPos4sv")
def pyiGlRasterPos4Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glReadBuffer")
def pyiGlReadBuffer(mode: uint) -> None:
  ...

@native
@native_name("glReadPixels")
def pyiGlReadPixels(x: int, y: int, width: int, height: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glRectd")
def pyiGlRectd(x1: float64, y1: float64, x2: float64, y2: float64) -> None:
  ...

@native
@native_name("glRectdv")
def pyiGlRectdv(v1: Pointer[float64], v2: Pointer[float64]) -> None:
  ...

@native
@native_name("glRectf")
def pyiGlRectf(x1: float, y1: float, x2: float, y2: float) -> None:
  ...

@native
@native_name("glRectfv")
def pyiGlRectfv(v1: Pointer[float], v2: Pointer[float]) -> None:
  ...

@native
@native_name("glRecti")
def pyiGlRecti(x1: int, y1: int, x2: int, y2: int) -> None:
  ...

@native
@native_name("glRectiv")
def pyiGlRectiv(v1: Pointer[int], v2: Pointer[int]) -> None:
  ...

@native
@native_name("glRects")
def pyiGlRects(x1: int16, y1: int16, x2: int16, y2: int16) -> None:
  ...

@native
@native_name("glRectsv")
def pyiGlRectsv(v1: Pointer[int16], v2: Pointer[int16]) -> None:
  ...

@native
@native_name("glRenderMode")
def pyiGlRenderMode(mode: uint) -> int:
  ...

@native
@native_name("glRotated")
def pyiGlRotated(angle: float64, x: float64, y: float64, z: float64) -> None:
  ...

@native
@native_name("glRotatef")
def pyiGlRotatef(angle: float, x: float, y: float, z: float) -> None:
  ...

@native
@native_name("glScaled")
def pyiGlScaled(x: float64, y: float64, z: float64) -> None:
  ...

@native
@native_name("glScalef")
def pyiGlScalef(x: float, y: float, z: float) -> None:
  ...

@native
@native_name("glScissor")
def pyiGlScissor(x: int, y: int, width: int, height: int) -> None:
  ...

@native
@native_name("glSelectBuffer")
def pyiGlSelectBuffer(size: int, buffer: Pointer[uint]) -> None:
  ...

@native
@native_name("glShadeModel")
def pyiGlShadeModel(mode: uint) -> None:
  ...

@native
@native_name("glStencilFunc")
def pyiGlStencilFunc(func: uint, ref: int, mask: uint) -> None:
  ...

@native
@native_name("glStencilMask")
def pyiGlStencilMask(mask: uint) -> None:
  ...

@native
@native_name("glStencilOp")
def pyiGlStencilOp(fail: uint, zfail: uint, zpass: uint) -> None:
  ...

@native
@native_name("glTexCoord1d")
def pyiGlTexCoord1D(s: float64) -> None:
  ...

@native
@native_name("glTexCoord1dv")
def pyiGlTexCoord1Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glTexCoord1f")
def pyiGlTexCoord1F(s: float) -> None:
  ...

@native
@native_name("glTexCoord1fv")
def pyiGlTexCoord1Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glTexCoord1i")
def pyiGlTexCoord1I(s: int) -> None:
  ...

@native
@native_name("glTexCoord1iv")
def pyiGlTexCoord1Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glTexCoord1s")
def pyiGlTexCoord1S(s: int16) -> None:
  ...

@native
@native_name("glTexCoord1sv")
def pyiGlTexCoord1Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glTexCoord2d")
def pyiGlTexCoord2D(s: float64, t: float64) -> None:
  ...

@native
@native_name("glTexCoord2dv")
def pyiGlTexCoord2Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glTexCoord2f")
def pyiGlTexCoord2F(s: float, t: float) -> None:
  ...

@native
@native_name("glTexCoord2fv")
def pyiGlTexCoord2Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glTexCoord2i")
def pyiGlTexCoord2I(s: int, t: int) -> None:
  ...

@native
@native_name("glTexCoord2iv")
def pyiGlTexCoord2Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glTexCoord2s")
def pyiGlTexCoord2S(s: int16, t: int16) -> None:
  ...

@native
@native_name("glTexCoord2sv")
def pyiGlTexCoord2Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glTexCoord3d")
def pyiGlTexCoord3D(s: float64, t: float64, r: float64) -> None:
  ...

@native
@native_name("glTexCoord3dv")
def pyiGlTexCoord3Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glTexCoord3f")
def pyiGlTexCoord3F(s: float, t: float, r: float) -> None:
  ...

@native
@native_name("glTexCoord3fv")
def pyiGlTexCoord3Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glTexCoord3i")
def pyiGlTexCoord3I(s: int, t: int, r: int) -> None:
  ...

@native
@native_name("glTexCoord3iv")
def pyiGlTexCoord3Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glTexCoord3s")
def pyiGlTexCoord3S(s: int16, t: int16, r: int16) -> None:
  ...

@native
@native_name("glTexCoord3sv")
def pyiGlTexCoord3Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glTexCoord4d")
def pyiGlTexCoord4D(s: float64, t: float64, r: float64, q: float64) -> None:
  ...

@native
@native_name("glTexCoord4dv")
def pyiGlTexCoord4Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glTexCoord4f")
def pyiGlTexCoord4F(s: float, t: float, r: float, q: float) -> None:
  ...

@native
@native_name("glTexCoord4fv")
def pyiGlTexCoord4Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glTexCoord4i")
def pyiGlTexCoord4I(s: int, t: int, r: int, q: int) -> None:
  ...

@native
@native_name("glTexCoord4iv")
def pyiGlTexCoord4Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glTexCoord4s")
def pyiGlTexCoord4S(s: int16, t: int16, r: int16, q: int16) -> None:
  ...

@native
@native_name("glTexCoord4sv")
def pyiGlTexCoord4Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glTexCoordPointer")
def pyiGlTexCoordPointer(size: int, type: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glTexEnvf")
def pyiGlTexEnvf(target: uint, pname: uint, param: float) -> None:
  ...

@native
@native_name("glTexEnvfv")
def pyiGlTexEnvfv(target: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glTexEnvi")
def pyiGlTexEnvi(target: uint, pname: uint, param: int) -> None:
  ...

@native
@native_name("glTexEnviv")
def pyiGlTexEnviv(target: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glTexGend")
def pyiGlTexGend(coord: uint, pname: uint, param: float64) -> None:
  ...

@native
@native_name("glTexGendv")
def pyiGlTexGendv(coord: uint, pname: uint, params: Pointer[float64]) -> None:
  ...

@native
@native_name("glTexGenf")
def pyiGlTexGenf(coord: uint, pname: uint, param: float) -> None:
  ...

@native
@native_name("glTexGenfv")
def pyiGlTexGenfv(coord: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glTexGeni")
def pyiGlTexGeni(coord: uint, pname: uint, param: int) -> None:
  ...

@native
@native_name("glTexGeniv")
def pyiGlTexGeniv(coord: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glTexImage1D")
def pyiGlTexImage1D(target: uint, level: int, internalformat: int, width: int, border: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glTexImage2D")
def pyiGlTexImage2D(target: uint, level: int, internalformat: int, width: int, height: int, border: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glTexParameterf")
def pyiGlTexParameterf(target: uint, pname: uint, param: float) -> None:
  ...

@native
@native_name("glTexParameterfv")
def pyiGlTexParameterfv(target: uint, pname: uint, params: Pointer[float]) -> None:
  ...

@native
@native_name("glTexParameteri")
def pyiGlTexParameteri(target: uint, pname: uint, param: int) -> None:
  ...

@native
@native_name("glTexParameteriv")
def pyiGlTexParameteriv(target: uint, pname: uint, params: Pointer[int]) -> None:
  ...

@native
@native_name("glTexSubImage1D")
def pyiGlTexSubImage1D(target: uint, level: int, xoffset: int, width: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glTexSubImage2D")
def pyiGlTexSubImage2D(target: uint, level: int, xoffset: int, yoffset: int, width: int, height: int, format: uint, type: uint, pixels: Pointer[None]) -> None:
  ...

@native
@native_name("glTranslated")
def pyiGlTranslated(x: float64, y: float64, z: float64) -> None:
  ...

@native
@native_name("glTranslatef")
def pyiGlTranslatef(x: float, y: float, z: float) -> None:
  ...

@native
@native_name("glVertex2d")
def pyiGlVertex2D(x: float64, y: float64) -> None:
  ...

@native
@native_name("glVertex2dv")
def pyiGlVertex2Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glVertex2f")
def pyiGlVertex2F(x: float, y: float) -> None:
  ...

@native
@native_name("glVertex2fv")
def pyiGlVertex2Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glVertex2i")
def pyiGlVertex2I(x: int, y: int) -> None:
  ...

@native
@native_name("glVertex2iv")
def pyiGlVertex2Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glVertex2s")
def pyiGlVertex2S(x: int16, y: int16) -> None:
  ...

@native
@native_name("glVertex2sv")
def pyiGlVertex2Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glVertex3d")
def pyiGlVertex3D(x: float64, y: float64, z: float64) -> None:
  ...

@native
@native_name("glVertex3dv")
def pyiGlVertex3Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glVertex3f")
def pyiGlVertex3F(x: float, y: float, z: float) -> None:
  ...

@native
@native_name("glVertex3fv")
def pyiGlVertex3Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glVertex3i")
def pyiGlVertex3I(x: int, y: int, z: int) -> None:
  ...

@native
@native_name("glVertex3iv")
def pyiGlVertex3Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glVertex3s")
def pyiGlVertex3S(x: int16, y: int16, z: int16) -> None:
  ...

@native
@native_name("glVertex3sv")
def pyiGlVertex3Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glVertex4d")
def pyiGlVertex4D(x: float64, y: float64, z: float64, w: float64) -> None:
  ...

@native
@native_name("glVertex4dv")
def pyiGlVertex4Dv(v: Pointer[float64]) -> None:
  ...

@native
@native_name("glVertex4f")
def pyiGlVertex4F(x: float, y: float, z: float, w: float) -> None:
  ...

@native
@native_name("glVertex4fv")
def pyiGlVertex4Fv(v: Pointer[float]) -> None:
  ...

@native
@native_name("glVertex4i")
def pyiGlVertex4I(x: int, y: int, z: int, w: int) -> None:
  ...

@native
@native_name("glVertex4iv")
def pyiGlVertex4Iv(v: Pointer[int]) -> None:
  ...

@native
@native_name("glVertex4s")
def pyiGlVertex4S(x: int16, y: int16, z: int16, w: int16) -> None:
  ...

@native
@native_name("glVertex4sv")
def pyiGlVertex4Sv(v: Pointer[int16]) -> None:
  ...

@native
@native_name("glVertexPointer")
def pyiGlVertexPointer(size: int, type: uint, stride: int, pointer: Pointer[None]) -> None:
  ...

@native
@native_name("glViewport")
def pyiGlViewport(x: int, y: int, width: int, height: int) -> None:
  ...

# stats: structs=0 enums=0 aliases=0 consts=588 funcs=336
