# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/dirent.h
# Generated: 2026-08-20 20:18:32
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("DIR")
class PyiDir:
  ...  # C incomplete struct

@native
@native_name("dirent")
class PyiDirent:
  dName: Pointer[int] @native_name("d_name")  # array

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("closedir")
def pyiClosedir(dirp: Pointer[PyiDir]) -> int:
  ...

@native
@native_name("opendir")
def pyiOpendir(name: utf8ptr) -> Pointer[PyiDir]:
  ...

@native
@native_name("readdir")
def pyiReaddir(dirp: Pointer[PyiDir]) -> Pointer[PyiDirent]:
  ...

# stats: structs=2 enums=0 aliases=0 consts=0 funcs=3
