# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/pthread.h
# Generated: 2026-08-17 15:28:51
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

@native
@native_name("pthread_attr_t")
class PyiPthreadAttrT:
  x: int @native_name("_x")

@native
@native_name("pthread_mutex_t")
class PyiPthreadMutexT:
  x: int @native_name("_x")

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("pthread_create")
def pyiPthreadCreate(thread: Pointer[uint], attr: Pointer[PyiPthreadAttrT], start: Function[[uintptr], uintptr], arg: uintptr) -> int:
  ...

@native
@native_name("pthread_detach")
def pyiPthreadDetach(thread: uint) -> int:
  ...

@native
@native_name("pthread_join")
def pyiPthreadJoin(thread: uint, retval: Pointer[uintptr]) -> int:
  ...

@native
@native_name("pthread_mutex_destroy")
def pyiPthreadMutexDestroy(m: Pointer[PyiPthreadMutexT]) -> int:
  ...

@native
@native_name("pthread_mutex_init")
def pyiPthreadMutexInit(m: Pointer[PyiPthreadMutexT], attr: uintptr) -> int:
  ...

@native
@native_name("pthread_mutex_lock")
def pyiPthreadMutexLock(m: Pointer[PyiPthreadMutexT]) -> int:
  ...

@native
@native_name("pthread_mutex_unlock")
def pyiPthreadMutexUnlock(m: Pointer[PyiPthreadMutexT]) -> int:
  ...

# stats: structs=2 enums=0 aliases=0 consts=0 funcs=7
