# AUTO-GENERATED by src.tools.c_ffi_pyi — DO NOT EDIT
# Source: third_party/posix/unistd.h
# Generated: 2026-08-17 15:28:51
# Spec: docs/c-ffi-pyi.md

from py2cpp.builtins import *

# ---------------------------------------------------------------------------
# Structs / unions（模块名 Pyi…；@native_name 为 C 标签；C++ using 别名，不生成新 struct）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Constants（#define 与 enum 成员；@native_name 为 C 宏名）
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

@native
@native_name("access")
def pyiAccess(pathname: CStr, mode: int) -> int:
  ...

@native
@native_name("chdir")
def pyiChdir(path: CStr) -> int:
  ...

@native
@native_name("close")
def pyiClose(fd: int) -> int:
  ...

@native
@native_name("execvp")
def pyiExecvp(file: CStr, argv: Pointer[CStr]) -> int:
  ...

@native
@native_name("fork")
def pyiFork() -> int:
  ...

@native
@native_name("getcwd")
def pyiGetcwd(buf: CStr, size: uint) -> CStr:
  ...

@native
@native_name("pipe")
def pyiPipe(pipefd: Pointer[int]) -> int:
  ...

@native
@native_name("read")
def pyiRead(fd: int, buf: uintptr, count: uint) -> int:
  ...

@native
@native_name("rmdir")
def pyiRmdir(pathname: CStr) -> int:
  ...

@native
@native_name("sleep")
def pyiSleep(seconds: uint) -> uint:
  ...

@native
@native_name("sysconf")
def pyiSysconf(name: int) -> int:
  ...

@native
@native_name("unlink")
def pyiUnlink(pathname: CStr) -> int:
  ...

@native
@native_name("usleep")
def pyiUsleep(usec: uint) -> int:
  ...

@native
@native_name("write")
def pyiWrite(fd: int, buf: uintptr, count: uint) -> int:
  ...

# stats: structs=0 enums=0 aliases=0 consts=0 funcs=14
